>Geotrypetes_seraphini_XP_033777887.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDT-PIPPDFELRESSI-PGAG----LGIWAKKKIEA
--G-ERF--GPYISLQRT-T--LKDSNFGWEHILSDSVV-AAQESCIRKIAEELGNEKF-
---------NIEANQAGTG-NWLKYIRAVCS--CDE-QNLVVFPINDQ-IYYKVIKDIEP
GEELLVY--MKDGAYSVGNMPPNLE----------EEHAFRCEECDELFQSKLELRRHQK
YACGTVGP-LYE-SLSK-EIKQ
>Microcaecilia_unicolor_XP_030078445.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEVPVYIPDDT-PIPPDFELRESSI-PGAG----LGIWAKKKIEA
--G-ERF--GPYISLQRT-T--LKDTNFGWEQILSDSVV-TTQESCIRKIAEELGNEKF-
---------NIEANQAGTG-NWLKYIRAVCS--CDE-QNLVVFPINDQ-IYYKVIKDIEP
GEELLVY--MKDGAYSVGNMPPNLD----------EEHVFRCEDCDELFQSKLELRRHQK
YACGAVDP-LYE-SLSK-EIKQ
>Rhinatrema_bivittatum_XP_029433772.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDT-PIPADFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYITLQRT-T--LKERNFGWEQILSDSDV-TTQESCIRKIAEEFGNEKF-
---------SIEANQAGTG-NWLKYIRAACS--CDE-QNLIVFPIHDQ-IYYKVIKDIEP
GEELLVY--MKDGAYSVGNMPPNLD----------EEPTFRCEDCDELFQSKLELRRHQK
YACSTVGP-LYE-SLSK-EIKQ
>Bufo_bufo_XP_040285980.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSV-PGAG----LGIWAKKKIEI
--G-ERL--GPYIMMQKT-T--LKENNLGWEQILPDSEV-TSQDESLRKVSEELGEEKM-
---------CIETSQSGSG-SWLKFIRMAFS--CDE-QNLAICYQNEQ-LFYKVIKDIEP
GEELLVY--MKEGNFSLGSMPPNLE----------EEHTFRCEDCDELFQSKLDLRRHQK
YACNTVNH-IYE-SLNE-EIKQ
>Pseudophryne_corroboree_XP_063799414.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
---S-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKRIEI
--G-ERL--GPYIMIQKT-T--LKETNLGWEQILPDSEV-TSQDGCLRKVSEELVDEKL-
---------CIENNQSGSG-NWLKFIRIACS--CDE-QNLAICHLNDQ-LFYKVIKDIEP
GEELLVY--MKEGNFSLGSMPPNLE----------EEHTFRCEDCDELFQSKLDLRRHQK
YACNTVNH-IYE-SLSE-EIKQ
>Sturnira_hondurensis_XP_036918020.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKRMEI
--G-ERF--GPYMVAPRA-T--LKEADFGWEQMLTE-EV-PSQDSCVQKIAEDLGGEKF-
---------CVE---AGAG-SWLKYIRVACS--CDD-QNLTMCQIDEQ-IYYKVIKDIGP
GEELLVH--VKEGACSLGAVPPSLD----------EEPTFRCDMCDELFPSKLDLRRHKK
YACGPVGAALYA-GLAQ-ELKP
>Myotis_daubentonii_XP_059547499.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKRLEV
--G-ERV--GPCLAAPRA-A--LR-EDFGWEQMLTEAEV-SPQEGCVQKVSEDLGGEKF-
---------CVDAGQAGAG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIGP
GEELLLH--VKEGAYSLGTAPPGLE----------EEPTFRCDVCDELFQSKLDLRRHKK
YACGSVGAALYA-GLGD-ELKA
>Saccopteryx_leptura_XP_066230955.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKMEI
--G-ERF--GPYMVAPRA-T--LKEADFGWEQMLTEAEV-SSQEGSVQKVSEDLGGEKF-
---------CLDASQAGAG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIGP
GEELLVH--VKEGAYSLGTVPPSLD----------EEPTFRCDVCDELFQSKLDLRRHKK
YACGAVGAALYE-GLGQ-EPKP
>XP_025860937.1 (best hit for PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKRMEI
--G-ARF--GPYMGAPRA-T--WKEADFGWEQMLTDTEV-SSQEGCIQKISEDLSSEKL-
---------CMDAGQAGSG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGTVPPSLD----------EEPTFRCDACDELFQSKLDLRRHRK
YACSSVGATLYE-GLGE-ELKP
>Vulpes_vulpes_XP_025860937.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKRMEI
--G-ARF--GPYMGAPRA-T--WKEADFGWEQMLTDTEV-SSQEGCIQKISEDLSSEKL-
---------CMDAGQAGSG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGTVPPSLD----------EEPTFRCDACDELFQSKLDLRRHRK
YACSSVGATLYE-GLGE-ELKP
>Mirounga_leonina_XP_034874923.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKRMEI
--G-ARF--GPYMGAPRA-T--WKEADFGWEHMLTDTEV-SSQEGCIQKISEDLSTERL-
---------CMDAGQAGSG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGTVPPSLD----------EEPTFRCDACDELFQSKPDLRRHKK
YACGSVGAPLYE-GLGD-GLKP
>Lynx_pardinus_VFV44625.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGVWAKKRMEI
--G-ERF--GPYMVAPRA-T--LKEADFGWEQMLTDAEV-SSQEVCIQKISEDLSTEKL-
---------CMDAAPAGSG-SWLKYIRVACS--CND-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGPVPPGLD----------GEPTFRCDACDELFQSKLDLRRHKK
YACGSVGATLYE-GLGE-ELKP
>Muntiacus_reevesi_XP_065791979.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------FPTPKEGSPYEAPVYIPEDI-RIPPGFELRESSI-PGAG----LGIWAKKKMEV
--G-ERF--GPYMVAPRA-T--LNEADFGWEQMLTDAEV-SSQEGCIQKISEDLDSGKL-
---------CVDAQQAGAG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGAVPPSLD----------EEPTFRCDACDELFPSKLDLRRHKK
YACSSVGAALYE-GLAD-ELKP
>Bos_taurus_XP_024832553.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------FPTPKEGSPYEAPVYIPEDI-RIPPGFELRESSI-PGAG----LGIWAKKKMEV
--G-ERF--GPYMVAPRA-M--LNEADFGWEQMLTDAEV-SSQEGCIQKISEDLDSGKL-
---------CVDAQHAGAG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGAVPPSLD----------EEPTFRCDACDELFPSKLDLRRHKK
YACSSVGAALYE-GLAE-ELKP
>Balaenoptera_acutorostrata_XP_057389363.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKMEV
--G-ERF--GPYMVAPRA-A--LKEVDFGWEQMLTDAEV-SSQEGCIQKISEDLGSGKF-
---------CVDAHHAGAG-SWLKYVRVACS--CDH-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGSYSLGTVPPSLD----------EDPTFRCDACDELFPSKLDLRRHKK
YACSSVGAVLYE-GLAD-ELKP
>Equus_caballus_XP_023483282.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKMEI
--G-ERF--GPYMVAPQA-T--LKEAGFGWEQMLTDAEV-STQEGCIQKISEDLGSEKF-
---------CVDANQAGAG-SWLKYIRVACS--CDD-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGTVPPNLD----------EEPTFRCDMCDELFQSKLDLRRHKK
YACSSVGAALYQ-GLGE-ELKP
>Rattus_norvegicus_XP_038967291.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKRKMEI
--G-ERF--GPYMVAPRA-A--LKEADFGWE-MLTDTEV-SSQESCIKKISEGLGSEKF-
---------CVDANQAGAG-SWLKYIRVACS--CDD-QNLAMCQINEQ-IYYKVIKDIEP
GEELLVH--VKEGAYSLGVMAPSLD----------EDPTFRCDECDELFQCRLDLRRHKK
YACSSSGAPLYE-GLGE-ELKP
>Dasypus_novemcinctus_XP_058160581.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYVPDDI-PIPPDFELRESSI-PGAG----LGVWAKKRMEA
--G-LRF--GPCVVAART-A--LKDADFGWEQILTDTEM-SSQESCAKKVSEDLDSEKF-
---------CVDASQTAAG-SWLKYIRVACS--GDD-QNLSMCQINEQ-IYYKAVKDIEP
GEELLVR--VKEGVYGLGAEPPSLD----------EDRTFRCDECDELFLSKLDLRRHKK
YACGAVGAALYD-GLGG-ELKA
>Homo_sapiens_NP_071397.3_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPADFELRESSI-PGAG----LGVWAKRKMEA
--G-ERL--GPCVVVPRA-A--AKETDFGWEQILTDVEV-SPQEGCITKISEDLGSEKF-
---------CVDANQAGAG-SWLKYIRVACS--CDD-QNLTMCQISEQ-IYYKVIKDIEP
GEELLVH--VKEGVYPLGTVPPGLD----------EEPTFRCDECDELFQSKLDLRRHKK
YTCGSVGAALYE-GLAE-ELKP
>Erinaceus_europaeus_XP_016046514.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPPS-EDYTPKEGSPYEAPVYIPEDI-PVPPDFELRESSI-PGAG----LGIWAKKKMEV
--G-ERL--GPFILGSRATA--LKEANFSWEPVLTNVDV-SSQESCIKKISEDLSSEKF-
---------CVDASPAGAG-SWLKYIRVACS--CDD-QNLSMCQINEQ-IYYKVIKDIEP
GEELLVH--VKETAFTLGTVPSNLD----------EEPTFRCESCDELFQSKLDLRRHRK
YACSAVGTALYE-GLSQ-ELPT
>Loxodonta_africana_XP_064137199.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKMEV
--G-ERF--GPYVVAPRT-T--LKETDFGWEQILTDSEV-SSQEGCLKKISEDLGGEKF-
---------CVDANQTGAG-SWLKYIRVAYS--CDE-QNLTMCQINEQ-IYYKVIKDIEP
GEELLVH--MKEGAYSLGTMPPSLD----------EEHTFRCDECDELFQSKLDLRRHKK
YACSSVGATLYG-GLAD-GLQP
>Chelonoidis_abingdonii_XP_032619642.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEA
--G-ERF--GPYMTIPRT-T--LKETNFGWEQVLTDPEV-ASQEGCIKKIADDLGNEKI-
---------CADANQTGAG-NWLKYIRVACS--CDE-QNLAVCPINDQ-IYYKVIKEIEP
GEELLVY--MKEDAYSLGNIPPSLE----------EEHTFRCEDCDELFQSKLDLRRHKK
YACNSVNS-LYE-TLNE-EIKQ
>Chelonia_mydas_XP_037737204.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMTIPRT-T--LKETNFGWEQVLTDPEV-ASQEGCIKKIADDLGNEKF-
---------CADANQTGAG-NWLKYIRVACS--CDE-QNLAVCPVNDQ-IYYKVIKEIEP
GEELLVY--MKEGAYSLGNMPPSLE----------EEHTFRCEDCDELFQSKLDLRRHKK
YACNSVSS-LYE-TLNE-ELKQ
>Varanus_komodoensis_XP_044301414.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-------FPTKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWTKKKIET
--G-DKF--GPYLAFPRA-T--LKETNFGWEQMLADPET-ALQDGGIKKMGDDLGTDKF-
---------CVDANQAGNG-NWLKYIRVACS--SEE-QNLAVCSINDQ-IYYKVIKEIEP
GEELLMY--MKEGTYSAGNMAPSLE----------DAHTFRCEVCDELFQSKVDMRQHKR
YSCSAVSS-LYE-TLNE-EIKQ
>Taeniopygia_guttata_XP_030145034.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMAVQRS-T--LKETNFGWEQILTDPEV-TSQEGNIKKIPDALGTEKF-
---------CGDAGQGGAG-NWLKFIRVSCS--CAE-QNLAVCHVNEQ-VYYKVIKEIEP
GEELLVC--LKEGGYSLGNMAPSME----------EEPSFRCEDCDELFQSKLDLRRHKK
YGCGAVGA-LYD-SLSD-NIKQ
>Corvus_cornix_XP_039419977.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMAVQRS-T--LKETNFGWEQILTDPEV-TSQEGSIKKIPDALGTEKF-
---------CGDGGQSGAG-NWLKYIRVSCS--CDE-QNLAVCHINEQ-VYYKVIKEIEP
GEELLVC--LKEGGYSLGNMAPSME----------EEPSFRCEDCDELFQSKLDLRRHKK
YGCSAVGA-LYD-SLSD-EIKQ
>Apus_apus_XP_051493600.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMAVQRS-T--LKETNFGWEQILTDPEV-TSQEGNIKKIAEDLGTEKF-
---------CLDAGQSGAG-NWLKYIRVACS--CDE-QNLAVCHLNNQ-IYYKVIKEIEP
GEELLVY--LKEGGYSLGNMAPSME----------EEPTFRCEDCDELFQSKLELRRHKK
YTCSAVSS-LYE-TLSD-EIKQ
>Tyto_alba_XP_032863708.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMTVQRS-T--LKETNFGWEQILTDPEV-TSQEGNIKKIADDLGNEKF-
---------CIDASQSGAG-NWLKYIRVACS--CDE-QNLAVCHVNDQ-IYYKVIKEIEP
GEELLVY--LKEGGYSLGNMAPSME----------EEHTFRCEDCDELFQSKLDLRRHKK
YACNAVSS-LYE-TLND-EIKQ
>Apteryx_rowi_XP_025941455.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
FPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELRESSI-PGAG----LGIWAKKKIEV
--G-ERF--GPYMTVQRS-T--LKETNFGWEQMLTDPEV-TSQEGNIKKIADDLGNEKF-
---------CVDASQSGAG-NWLKYIRVACS--CDE-QNLAVCHXNDQ-IYYKVIKEIEP
GEELLAY--MKEGGYSLGNMAPSME----------EEPTFRCEDCDELFQSKLDLRRHKK
YACSSVGS-LYE-TLNE-EIKQ
>Protopterus_annectens_XP_043918907.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPTS-EDFTPKEGSPYEAPVYIPDDI-PIPPDFELKESSI-PGAG----LGIWAKKKIEM
--G-ERL--GPCILSHRM-T--IKGPDYGWEQMLNDSES-NSQDGSIRKIVDELGNETF-
---------CDDVSRSGTA-SWLKYIRTARS--FNE-QNLVICDINDQ-IYYKVIRDIEA
GEELLVY--MKDGGYSDGHLPPNLD----------EEQTFCCGVCGELFQTKVELRRHQK
YACSAVNT-IFE-TLNE-DIKQ
>Latimeria_chalumnae_XP_064424000.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LHTS-EDFTPKEGSPYEAPVYIPDDI-PIPSDFELRESSI-PGAG----LGIWAKKKVEV
--G-ERF--GPYTGVQRT-P--LKDSNFGWEQLLNDSEV-PSQEGCIRKIVDELGNEKF-
---------CIDASPAGTG-NWLKYIRVARC--YDE-QNLTACQVNDQVIYYKVIKDIEA
GEELLVY--VKDGSYPDGSMPPNLD----------EEQTFRCEDCEELFQSKLDLRRHQK
YACGNANT-IFE-TLNE-EINK
>Danio_rerio_XP_001922927.6_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
QPCN-EDFTPKEGSPYEVPVYIPDDI-PIPADLELRESSV-PGAG----LGIWAKVKIRM
--G-ERF--GPYNGLQS-AT--VKETTYGWEQMLNDHET-SSQDSCIKKVMDNMGNVKF-
---------CLDGALEASGSCWLKYVRTAPS--HLE-HNLAMCHISEDQIYYKAIRDIEI
GEELLVY--MKDGVFPEGSMAPNLE----------DEQMYRCEHCDELFTSKLELRRHQK
YSCSSGNS-IFD-SLSE-DFKQ
>Tachysurus_fulvidraco_XP_047656062.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
QPNN-EDFTPKEGSPYEVPVYIPDDI-PIPANLELRESSM-PGAG----LGIWAKTRIGM
--G-ERF--GPFH-----CT--VKETAFGWEQMLNDHEV-SSQDSCIKKVVDHMGNVKF-
---------CLDEALEASG-SWLKYVRAAPS--YEE-HNLAVCQISEDQIYYKTIRDIEV
GEELLVS--MKDGVFPEDSMAPNLE----------DEQMYRCEDCDELFSSKLELRRHQK
YSCNTGSS-IFD-SLSE-DLKQ
>Sebastes_umbrosus_XP_037628485.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SSNDQDFTTPKEGSPYEAPVYIPDDI-PIPSELELRESSV-PGAG----LGVWAKTCIGA
--G-ERF--GLHSTLHHEAT--GKDGSFGWEQMMNDDDE-ASPDSCIKKVVDDMGNVKF-
---------ALDTGPDATSNSWLKYVRSALS--FEE-QNLAACHLTGDQIYYKAVRDIEA
GEELLVY--MKDGIFPEGSMAPNLQ----------DEQMYRCEDCDELFSSTLELRRHQK
YSCSSTGS-IFD-TLRE-DFKQ
>Solea_solea_XP_058498839.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SSNDQDFTTPKEGSPYEAPVYIPDDI-PIPSDLELRESSV-PGAG----LGVWAKSCIHA
--G-ERF--GLHNSLHHGAT--GKDSSFGWEQMMNDDEE-ASPDSCVKKVVDDMGNVKF-
---------ALDTGPDAISNSWLKYVRCAPS--FEE-QNLSACHLTGDQIYYKAVRDIEA
GEELLVY--MKDGIFPEGSMAPNLQ----------DEQMYRCEDCDELFSSTLDLRRHQK
YSCTSAGS-IFD-SLRE-DFKQ
>Thunnus_albacares_XP_044207247.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SSNDQDFTTPKEGSPYEAPVYIPDDI-PIPSELELRESSV-PGAG----LGVWAKTRIGA
--G-ERF--GLHNTLHHGVT--GKDSSFGWEQMMNDHEE-ASPDSCIKKVVDDMGNVKF-
---------ALDTGPDATSNSWLKYVRSAPS--FEE-QNLAACHLTGDQIYYKAVRDIEA
GEELLVY--MKDGIFPEGSMAPNLQ----------DEQMYRCEDCDELFSSTLELRRHQK
YSCSSAGS-IFD-TLRE-DFKQ
>Takifugu_rubripes_XP_029689316.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SSNEQDFTTPKEGSPYEAPVYIPDDI-PIPSNLELRESSV-PGAG----LGVWAKTRIGA
--G-ERF--GLHSTLHHGS----KDNSFGWE-MMNDSEE-ASPDSCIKKVVDNMGNIKF-
---------ALDTGPDANSNSWLKYVRSAPS--FEE-QNLVACHLTGDQIYYKAVRDIEA
GEELLVY--MKDGIFPEGSMAPNLQ----------DEQMYRCEDCDELFSSTLELRRHQK
YSCSSTGS-IFD-TLRE-DFKQ
>Lucifuga_dentata_KAF7651522.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SSNDQDFTTPKEGSPYEAPVYIPDDI-PIPSELELRESSV-PGAG----LGVWAKTRIGA
--G-ERF--GLHNTLHHGAT--GKDNSFGWE-MMNDHEA-ASPDSCIKKVVDDMGNVKF-
---------ALDTGPDTTSNSWLKYVRSAPS--FKE-QNLAACHLTGDQIYYKAVRDIEA
GEELLVY--MKDGIFPEGSMAPNLQ----------DEQMYRCEDCDELFSSALELRRHQK
YSCSSAGS-IFD-TLKE-DFKQ
>Osmerus_eperlanus_XP_062315475.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
NSND-EDFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWVKSRITT
--G-ETF--GPHSGLQS-TT--DKDGSFGWAQMLSDHEA-TSPDSCIKKVVDDMGNVKF-
---------CVDPGSEAASGSWLKYVRTAPS--FDE-QNLAVCHLSGDQIYYKAIRDIEV
GEELLVY--MKDGIFPEGSMAPNLE----------DEQMYRCEDCDELFTSALELRRHQK
YSCSSAGS-IFD-TLSE-DFKQ
>Oncorhynchus_gorbuscha_XP_046199553.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-HNE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDHEAASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIEV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSGLELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Oncorhynchus_kisutch_XP_031649937.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
HHHE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDHEAASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIEV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSGLELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Oncorhynchus_keta_XP_052338880.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
HHNE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDHEAASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIEV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSGLELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Oncorhynchus_mykiss_XP_036843988.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
HHNE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGVG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDHEAASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIEV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSALELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Salmo_trutta_XP_029575639.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
HHNE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDRETASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIGV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSALELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Salmo_salar_XP_014001637.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
HHNE-DPFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKTRIGM
--G-ECF--GPHSALQS-AT--VKDGSFGWEQMLNDRETASSPESCIKKVVDEMGNVKF-
---------CLDEGSEA-GGSWLKYVRTAPS--FEE-QNLAACHLSGDQIYYKAIRDIGV
GEELLVY--MKDGLFPEGSMAPNLE----------DEQMYRCEDCDELFTSALELRRHQK
YSCASAGS-LFD-TLSNEDFKQ
>Esox_lucius_XP_028979953.2_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LHHQ-DPFTPKEGSPYEAPVYIPDDI-PIPCDLELRESSV-PGAG----LGIWAKTRIGM
--G-ERF--GPHSALQS-AT--VKDGSFRWEQMLNDCEAASSPESCIKKVVDEMGNVKF-
---------CLDAGSEA-GGSWLKYVRTAPT--FEE-QNLVACHLSGDQLYYKAIRDIEV
GEELLVY--MKDGIFPEGSMAPNLE----------DEQMYRCEDCDELFTSALELRRHQK
YSCSSAGS-LFD-TLSNEDFKQ
>Megalops_cyprinoides_XP_036389281.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPNN-QDFTPKEGSPYEVPVYIPDDI-PIPSDLELRESSI-PGAG----LGIWAKAKIRL
--G-ERF--GPYSGMQS-AA--VKETTFGWEQMLNDHEV-NTQDSCIKKVLDNMGNVKF-
---------CMDSSLEGSG-SWLKYVRTAPS--FEE-QNLAVCHLTGDQIYYKAIRDIEV
GEELLVY--MKDGVFPEGSMAPNLE----------DEQMYRCEDCDELFSSKLDLRRHQK
YSCSSAGS-LFD-TLGE-DFKQ
>Brienomyrus_brachyistius_XP_048873707.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPND-EGLTPKEGSPYEVPVYIPDDI-PIPSELELRESSV-PGTG----LGIWAKAKIGL
--G-ERF--GPYSGMQS-AS--IKETTFGWEQMLNDHDI-TSQDSCIKKVVDGMGNVKF-
---------CMATDLDGSG-SWLKYVRMAPS--FEE-QNLTVCYLNGDQIYYKAIRDIDA
GEELLVY--MKDGVFPEESMAPNLE----------DEQMYRCEDCDELFPSKPDLRRHQK
YSCSSAGS-IFD-TLNE-DLKQ
>Amia_calva_XP_066546864.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPNA-EDFTPKEGSPYEAPVYIPDDI-PIPSDLELRESSV-PGAG----LGIWAKKRIGP
--G-ERF--GPYTGMQN-AT--VKETTFGWEQMLNDHEV-ATQDGCIKKIVDDLGNVKF-
---------CVDATLGGSG-SWLKYVRVAPS--YEE-QNLTVCHLSEDQIYYKAIKDIEV
GEELLVY--MKDGAFPEGSMAPNLE----------DEQMYRCEDCEELFPSKLDLRRHQK
YSCSNANS-IFD-TLND-DFKQ
>Polyodon_spathula_XP_041128792.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPNS-EDFTPKEGSPYEAPVYITDDI-PIPADLELRESSI-PGAG----LGIWVKNRIEL
--G-ERF--GPYTGMQN-TA--VKDPSFGWEEMLNNHDM-ATQDGCIKKIAGDLGNMKF-
---------CVDANQAGTG-SWLKYVRVART--FEE-QNLTLCHIADDQVCYKAIKNIEA
GEELLVY--M-DGDFPEGSMAPNLG----------DEQMYRCDDCEELLPSKLDLHRHQK
YSCSNSTS-LFN-ALNQ-DFKQ
>Huso_huso_KAK6477557.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPNS-EDFTPKEGSPYEAPVYITDDI-PIPADLELRESTI-PGAG----LGIWVKNRIEL
--G-ERF--GPYTGMQN-TT--VKDPSFGWEEMLNDHDV-ATQDGCIKKIAGDLGNVKF-
---------CVDANQAGTG-SWLKYVRVARS--FEE-QNLTLCHITDNQICYKAIKDIEA
GEELLVY--M-DGDFPEGTMAPNLK----------DEQMYRCEDCEELLSSKLDLHRHQK
YSCSNGTS-IFN-ALNQ-DFKQ
>Mobula_hypostoma_XP_062889249.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPTS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKHEV
--G-EKF--GPYAGVQRV-T--LKDPNFGWEI------------------VDELGNIKF-
---------CIDANQAGSG-NWLKYIRSAHS--YNQ-QNLVACQINDQ-IYYKVIKEIKS
GDELLVF--MKDGVYPDGTMPPNLD----------EEQRYRCGDCDELFRSKVALRRHQA
YACNNVNA-IFT-TISE-DYKQ
>Hypanus_sabinus_XP_059808191.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPTS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSV-PGAG----LGIWAKKKHEV
--G-EKF--GPYAGVQRV-T--LKDPNFGWEI------------------VDELGNIKF-
---------CIDANQAGSG-NWLKYIRSAHS--YNQ-QNLVACQINDQ-IYYKVIKEIKS
GDELLVF--MKDGVYPDGTMPPNLD----------EEQRYRCGDCDELFRSKVALRRHQA
YACNNVNA-IFT-TINE-DYKQ
>Carcharodon_carcharias_XP_041062930.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPPS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSV-PGAG----LGIWSKKKSEV
--G-EKF--GPYAGIQRV-T--LKDPNFGWEVILTDVDV-T-PDLCLTKIVDELGNVKF-
---------CIDASQAGSG-NWLKYIRSAHS--YNQ-QNLVACQINDQ-IYYKVIKEVKS
GDELLVF--MKDGVYPDGTMPPNLD----------EEQRYRCGDCDELFRSKVALRRHQA
YACNNVNA-IFT-TINE-EFKQ
>Chiloscyllium_plagiosum_XP_043531999.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPPS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSV-PGAG----LGIWAKKKNEV
--G-ERF--GPYAGIQRV-T--LKDPNFGWEI------------------VDELGNVKF-
---------CIDASQAGSG-NWLKYIRSARS--YNQ-QNLIACQINDQ-IYYKVIKEVKS
GEELLVF--MKDGVYPDGTMPPNLD----------DEQRYRCGDCDELFRSKVALRRHQA
YACNNVNA-IFT-TINE-EFKQ
>Scyliorhinus_canicula_XP_038629573.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPPS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSV-PGAG----LGIWAKKKNEV
--G-EKF--GPYAGIQRV-T--LKDPNFGWEI------------------VDELGNVKF-
---------CIDASQAGSG-NWLKYIRSAHS--YNQ-QNLVACQINDQ-IYYKVIKEVKS
GDELLVF--MKDGVYPDGTMPPNLD----------EEQRYRCGDCDELFRSKVALRRHQA
YACNNVNA-IFT-TINE-EFKQ
>Amblyraja_radiata_XP_032903746.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
LPTS-NEFTPKEGSPYEAPVYIPEDI-PIPPDFELRESSI-PGAG----LGIWAKKKLEV
--G-EKF--GPFAGVQRG-T--LKDPNFGWEI------------------VDELGNLKF-
---------CIDANQAGSG-NWLKYICSAHT--YNH-QNLVACQINDQ-IYYKVIKEVKS
GDELLVF--MKDGVYPDGTMPPNLD----------EEQRYRCGDCDELFRSKVALRRHQA
YTCNNANA-IFT-TINE-EFKQ
>Antechinus_flavipes_XP_051839099.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-------FTPKEGSPYKAPIYIPDDI-PIPPEFELRESNV-PGAG----LGIWTKRKIEV
--G-EKF--GPYIGEQSA-D--LKDPSYGWE------------------ILDEFCNVKY-
---------YIDASQPDVG-SWLKYVKFAGC--YEQ-HNLVACQINDQ-IFYRVVTDIEP
GEELLLY--MKSEEYSHEAMAPDIH----------EERQYRCEDCDQLFESKAELVDHQK
FPCSTPHS-AFS-MVEE-DFQP
>Galemys_pyrenaicus_KAG8511482.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------FNPGRNAIYRPPVA-PART-QTLRSSC----KG----LGVSRSPAAYL
RCSDWRFPCSSCGTVRSG-R--LSRVGRSAS------------------ILDEFCNVKF-
---------CIDASQPDVG-SWLKYIRFAGC--YDQ-HNLVACQINDQ-IFYRVVTDIAP
GEELLLF--MKSEDYPHETMAP----------DIHEERQYRCEDCDQIFESKAELADHQK
FPCSTPHS-AFS-MVEE-DFQQ
>Dreissena_polymorpha_XP_052228621.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
--------------------MLNEQ---FNNVSIFM-RQV-Q-DR----SGVITPVDIQA
--G-QLV--GPIQEDF--------------------------------------------
-----------QADKEDKG-ALWKSLKKSDD--TES-CNLMAVHIQNE-LYYRALREIHA
GEEMLLY--AKERLYPDADFPMF------K-NKTEDADIISCRDCGEVFKDRTSYHKHQL
FSCNNTRS-EYG-HYQQ-GSDS
>Mya_arenaria_XP_052820856.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-------------------------------------------------MGVATVASLQA
--G-KMI--GPVPTNQN-------------------------------------------
-----------EVDVDDKR-DILRYIQKSDN--TES-SNLMAVHIQNQ-LYYQAIREIQA
GEEMLLY--TRDRLYPDTDL-MF------N-KKAEDVDTISCRDCGEVFQDRISLHKHQL
FSCNNSRS-EFA-AFQQ-AQRD
>Ruditapes_philippinarum_XP_060596562.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
--VVSAASTSFLCKNESSTATKEEC---AFEDFMLK-SLD-D-SH----PGVWTRVRLEA
--G-KLI--GPMTDKSQ-------------------------------------------
-----------NKESVKES-QLMKYIQKSNN--TET-SNLMAVHLQNQ-LYYRAIREIQA
GEEMLLY--AKDRLYQEPDFTGLF-----QKKISEGETTIPCGECGEIFKDPMSLHKHQL
FSCNNSRS-DYG-HGQD-LSGD
>Mercenaria_mercenaria_XP_045163259.2_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
--SPSAANTPLAVKNESSAATKEEG---FLEDYMLK-SLD-D-SH----PGVWTRVRLEA
--G-KLI--GPMSEADQ-------------------------------------------
-----------SIESGERN-QLMKFIQKSSN--TET-SNLMAVHLQNQ-LYYRTIREIQA
GEEMLLY--AKDRLYQEPDFTGLF-----PKKIEEGETTIPCGECGEIFKDPMSLHKHQL
FSCNNSRS-DFG-PNYN-LSGD
>Mytilus_californianus_XP_052082683.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------DLTSSKPELTLAMDKPEFPTDIEIKPVPG-S-GT----CSVFTKIVVSS
--G-RIY--GPKKFVKPE-S--LPGG-------------------------------SS-
---------MTMKEHDGEL-HWLNYIRRSTD--SEN-SNMMAKHINGK-VFYKVIKDIEA
GQEMLLY--STDPVYSEKQTEGFSA-------FENEIAKYPCGDCSAILTSREELKRHQA
FSCTRHMI-PTN-GQGS-----
>Saccostrea_cucullata_XP_062609405.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----SASASGEIKSEYLPVYIPEDI-HIPDQFELLESHV-Y-PG----LGVWTKQSIKK
--G-EKM--GPFVGTFKS-T--INNSPYSWK------------------VLNEKGEIKG-
---------WIDASETGTG-NWMKYIRSSTR--SEN-QNLMAVQIEEE-IYYKSMRDILP
GEEMLLY--PSDPVCRLDT-------PDFSKLDEQGETNYPC-DCGEVFRSKIALARHQT
YACTHSSH-VQN-IS-Q-KMSI
>Saccostrea_echinata_XP_061162415.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----PASASGEIKSEYLPVYIPEDI-HIPDQFELLESHV-F-PG----LGVWTKQSIQK
--G-EKM--GPFIGTFKS-T--LNNPLYSWK------------------VLNEKGEIKG-
---------WIDASETGTG-NWMKYIRSSTR--SES-QNLMAVQTEEE-IYYKSMRDILP
GEEMLLY--PSDPVCRLDT-------PDFSKLDEQGETNYPC-DCGEVFRSKIALARHQT
YACTHSSH-VQN-IS-Q-KMSI
>Ostrea_edulis_XP_055997510.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----TVSTSSEINSEHPPVYIPEDI-PIPEQFELRESHV-F-SG----LGVWTRRPLHK
--G-YKM--GPFVGTFKS-K--PGDPNCSWK------------------VLSEKGELKG-
---------WIDASETGTG-NWMKYIRSCTR--LEN-QNLMAVQIEED-IYYKSMRDILP
GEEMLLY--PSDPICRLDT-------PDFSKLDEQGNTNYPC-ECGEVFRSKIALARHQT
YACTHSSN-LRN-TH-Q-KMSI
>Crassostrea_virginica_XP_022340618.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
----PAASTSGGIKSDHPPVYIPEDI-PIPDRFELRESHM-F-PG----LGVWTKQLIQK
--G-EKF--GPFTGVLKS-T--FNNSNSSWK------------------VLTEKGEIKG-
---------WIDASEKGSG-NWMKYIRNCSR--SEN-QNLMAVQIEEE-IYYKSMRDLLP
GEEMLVY--PSDTVCRMDA-------PDFSKLDEQVETNYPC-DCGEVFRSKIALARHQT
YACTHSNN-VQS-TPHH-KMSL
>Haliotis_rubra_XP_046562500.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----ISHNPADMKSESLPVYIPEDI-PIPTDFELRESQV-Y-PG----LGVWSRIDLPA
--H-QKV--GPFAGVLKA-S--VSDPSCAWE------------------LVDDCGKVKG-
---------WVDASNPGSG-NWMKYIRGSED--RNQ-RNLMAVQVDDQ-VYYRAVRDIHP
GEEMLLY--AREALYPEMELDAMAM-----HKMEDEDRTYSCPECGEVFRSKVALRRHQT
YVCGRSAA-LYQ-AMTR-----
>Haliotis_rufescens_XP_046381086.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----ISHYPAEMKSESLPVYIPEDF-PIPTDFELRESQV-Y-PG----LGVWSRIDLPA
--H-QKV--GPFAGVLKA-S--VSDPSCAWE------------------LVDDCGKVKG-
---------WVDASDPGCG-NWMKYIRGSED--RNQ-RNLMAVQVDDQ-VYYRAVRDIHP
GEEMLLY--AREALYPEMELDAMAM-----HKMEEEDRTYSCPECGEVFRSKVALRRHQT
YVCGRSAA-LYQ-AMTR-----
>Mizuhopecten_yessoensis_XP_021356562.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SRADSP-ADRSSDDADHPPVYIPEDI-PIPKQFELKESKK-F-EG----LGVWAKVDIPP
--G-QKF--GPFTGILKN-S--LENTSCAWE------------------IVDEEHNVKG-
---------WIDASEPGTG-NWMKYIRSTED--CES-RNLMAIQIDKQ-VYYRTVRTVQS
SEEMLLY--TSDALYPEKDIDHHTSLAAFHAKLDQGDLNYKCSDCEEVFSSLVTLKHHQA
LSCPKPNL-QMH-ETNS-----
>Pecten_maximus_XP_033763693.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
SPTASL-VNTAADDTDHPPVYIPEDI-PIPKQFELKESKK-F-QG----LGVWAKVDIPA
--G-QKF--GPFTGILKN-D--LENLSCAWE------------------IVDEEHNVKG-
---------WIDASEPGTG-NWMKYIRSTED--RES-RNLMAIQIDKQ-VFYRTVRSIHA
AEEMLLY--TTDALYPEKGIDHHTSLAAFHAKLDQGDLSYKCSECNEVFSNAVTLKRHQA
MACTKLAQ-QIH-DNNS-----
>Biomphalaria_glabrata_XP_055864071.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
----------------------MKLTSSD-P--HRP-RDRMAVQVDEQ-VFYKTTRELHP
REEMLLY--AREASFPDLELETLA------RQSLSGDQTYPCPNCGEVFRSKVAVRRHQT
YSCSSALS-PYS-SLKE-QM--
>Owenia_fusiformis_CAH1775145.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
----------------------MKYVRSAPD--PAQ-QNIMAVQVDDQ-VFYKTVKDIEP
GEEMLLY--ARDAVYPENDLHTMKG-----AT-LDEERVHPCQQCGEVFRSKVALRRHET
YVCNNSNA-IFS-SINK-EF--
>Lingula_anatina_XP_013393556.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
TDEDTFSESPSDL-SHHPPVYIPEDI-PIPDDFELRESKV-F-SG----LGVWTRVAVEQ
--G-EKF--GPFEGILKT-S--VSDPSSAWE------------------IVDKFGKVQG-
---------WVDASDPGTG-NWMKYVRSALS--RQE-QNLMAVQADDQ-VYYKAIKDISP
GEEMLLY--ARDAVYAENEVDSIQK-----SIDAEDEVRYSCGECGEAFRSKVALRRHET
YVCNNANN-IYS-KINS-EFRE
>Anneissia_japonica_XP_033113588.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
----------------------MKYIRSAPD--LEDQQNMMAVQMDHK-VFYKVVRPIST
GDELLVT--K-DTVFSEKSEHQLP---------EIEEKVHTCGDCDESFTSKTALRDHEQ
YSCPRKEY-SDN-ESEK-HS--
>Patiria_miniata_XP_038061538.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
----------------------MKYVRSAPT--LEE-QNMVPVNIENK-VYYKVIHPIAP
GKELLVL--K-EAAFPDQEGIPIQ---------LIEEKRFPCSDCEEVFRSKVALRRHQK
YACRNSNN-IFT-GLNQ-QF--
>Acanthaster_planci_XP_022106093.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
--------------------YVPEDV-VLPPEFELRESCI-QEAG----LGVFSLVDIPV
--G-ERF--GPFAGVERS-L--VQDMLCAWE------------------IVDADGRVRC-
---------WIDASEPGTG-NWMKYVRSAAT--FED-QNMVPVQIENK-VYFKVIRPIGP
GKELLVL--K-EAAFPDQEGIPIQ---------LVEEKRFPCSDCQEVFRSKVALRRHQK
YACQNSSA-IFT-AQQF-----
>Lytechinus_pictus_XP_063965417.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
---------------------------------------------------------MQQ
--E-RRF-----RLDLME-I--LCSMDTDES------------------IVDEFGKVKC-
---------WVDASEPGTG-NWMKYVRSAPK--LEN-QNMVPVQVDGK-VFYKAIHNIGT
GEELLVL--K-DAAFPDQEGNPIQ---------IIEEKQYECEECQNTFRSKVALRRHQK
YACNNANA-IFS-TLNQ-EF--
>Lytechinus_variegatus_XP_041479711.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------M------------------IVDEFGKVKC-
---------WVDASEPGTG-NWMKYVRSAPK--LEN-QNMVPVQVDGK-VFYKAIHNIGT
GEELLVL--K-DAAFPDQEGNPIQ---------IIEEKQYECEECQNTFRSKVALRRHQK
YACNNANA-IFS-TLNQ-EF--
>Strongylocentrotus_purpuratus_XP_003730421.2_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------M------------------IVDEFGKVKC-
---------WVDASEPGTG-NWMKYVRSAPK--LEN-QNMVPVQVDGK-VYYKAIHNIGT
GEELLVL--K-DAAFPDQEGNPIQ---------IIEEKQYECDKCECTFRSKVALRRHQK
YACNNANA-IFS-TLNQ-EF--
>Asterias_rubens_XP_033642492.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
---------------MRV-W--ERISDHRLV------------------IVDEVGKVRC-
---------WIDASEPGTG-NWMKYVRSAPT--FEE-QNMVAVQIENK-VYYKVIHPIPP
GEELLVL--K-EAAFPDQEGIPIQ---------LIEEKRFQCGDCDELFRSKVALRRHQK
YACKNSNA-IFT-TLNQ-QF--
>Saccoglossus_kowalevskii_XP_006819761.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
----------EMMEKSQPPVYIPEDV-VLPEKFELRESRI-AGAG----LGVFTKVRLDV
--G-EKF--GPFAGLQRV-S--VKDTQYAWE------------------IVDEFGKVKC-
---------WIDASEPGTG-NWMKYVRSAPV--LEE-QNMIAVQINEQ-VHYKVLKSIEP
GEELMVI--K-DAAFPDQEGLPLH---------MIEERRFKCGECDEVFRSKVALRRHQK
YVCKNDQA-IFS-TINE-DFKQ
>Branchiostoma_belcheri_XP_019637628.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------SDSAYEAPVYIADDI-HIPPEFELRESKA-AGVG----LGVWTKVAVQA
--G-EKM--GPFTGLQKT-E--VKDMTYAWE------------------IVDEFGKVKF-
---------IVDASEPGTG-NWMKYIRSARN--YNE-QNMVALQINDQ-MYYKVVKDVEM
GEELMVY--MKDAMYPDGTMPPNFE----------EEKRFRCGECDDLFKSKVALRRHQK
YACNNSLA-IFN-SINE-DF--
>Branchiostoma_floridae_XP_035696883.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------SDSAYEAPVYIADDI-HIPPEFELRESKA-AGVG----LGVWTKVAVQA
--G-EKM--GPFTGIQKA-E--VKDMTYAWE------------------IVDEFGKVKF-
---------IVDASEPGTG-NWMKYIRSARN--YNE-QNMVALQINDQ-MYYKVVKDVEM
GEELMVY--MKDAMYPDGTMPPNFE----------EEKRFRCGECDDLFKSKVALRRHQK
YACNNSLA-IFN-SINE-DF--
>Petromyzon_marinus_XP_032818110.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------EGGDAGPPAYGSSVYVPDDV-SLPGELELREARSPPGAG----LGVWARSGLRA
--G-DKY--GPYTAGEGG-SPRSKDGDHAWE------------------LLDGPSGVCGK
DGSAAGEPCRGSAGDSEER-SWLKYVRLAAS--TRR-PNLAAVEIDQK-VYYKAIRDIEA
GEELLLC--MQEEGVEHQAMAPSTE-PLSQGGISDDERQLRCGNCKELCPSDTVLKQHQQ
FG--------------------
>Drosophila_pandora_KAH8326030.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------AAGSAASMENLQLLQEWARRREPVCDLDIRE------------SGVYAKTPLPR
--G-TRY--GPFPVNLCH-Q--PNDMQLAWK------------------AQA--GHYNG-
---------WLEPT-SEVS-AWLKKIRVVQDEGLSK-ANLQSYIDHGC-LWYETNCHVSA
GVEMVVDGRPRSPVQINESFVAGGGVLAA-----AAAAAA--------AA----------
----------------------
>Hermetia_illucens_XP_037902415.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
----------------LEHVVPEISRLREPSEIDIR--------E----NGVFAKVPIHS
--E-TRY--GPFSVKCTS-E--PADKDFAWE------------------VL-AGPDLRS-
---------WLEPM-SDAA-KWLKKIRSTHN--SNE-VNIRHYVLGGN-LWYAVCRDIPA
NGELITE--PKVHLQISDIFGNALT----------EDRSDR--E---SGSQHSGTTGEDD
F---NTSN-DLDNNIIS-ES--
>Bradysia_coprophila_XP_037042457.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------------QLLSEIAKMQGPPPELEVKD------------GSVFTHKFLHR
--G-TKY--GPYTVKYTD-Q--PVDRQFAWE------------------VV-AGSTIRG-
---------WLEPI-PESA-MWLKHIRTVYS--NIE-ANIYSFIVAGY-IWYEVTRDIPA
GTELVAA--PKVPLQLRDIFSNGPQ----------DDRSDR--ET---GSQHSGTNEEDF
-----TSN-DLENS--------
>Aedes_aegypti_XP_011493491.2_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------QTAEQFLRQMARLQRPPPPDLDIRN------------GSVVACKLIPK
--G-TQY--GPFLGKFFR-D--SLNRLEFM-----------------------DMNLRG-
---------WLDAT-LESA-NWSRNIRSTGS--LGD-VNVQQYFKDGY-QWFEVICDISP
GQELLLR--PRVPPAPSHRDQAGAD------------------DSRGSASQHSEVFEDE-
Y---NTST-EYDSSLVH-LN--
>Zerene_cesonia_XP_038222455.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------DDESKEDNVSESTDINLPSELLFKS------------GGIFARLNITN
--G-TKY--GPFNGKWET-Q--PLDRRYAWE------------------VL-GKNGVRG-
---------WLDGT-TDKT-NWLKFVRSTNY--SHD-VNVQHLLLAGQ-IWYKVTRDIPS
GQELLLG--PRTPLPLQDVLAAGGR---------E---------G---SSVNSSSG----
----------------------
>Vanessa_atalanta_XP_047535428.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-------------DE-DYKDELDKFDCNMPSELVVKS------------GGIFARVNIPC
--G-TKY--GPFNGKWDT-Q--PLERRYAWE------------------VL-GKNGVRG-
---------WLDGT-TEKT-NWLKFVRSTTY--SHD-INVQHFLLAGQ-IWYKVTRDIAS
GQELLLG--PRTSLQLQDVVSGIGR---------E---------G---SSVNSSSS----
----------------------
>Tenebrio_molitor_XP_068914254.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------FNGLKLDLSYTKCKEVVAASGAVPCEVELKE-------------GVVAKSLIPK
--G-TRY--GPFQGKWAG-V--PQDARFAWE------------------VV-AGNGVRG-
---------WLDGS-SEHH-NWLKLIRSAET--KSS-ANMRYYLQGGQ-LWYETCVDIPH
GTELVLG--PREPLNLQDMFGDSTS---------ADEKSDR--ET---ASQHSGTVD---
----------------------
>Brassicogethes_aeneus_CAH0564476.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------FNQNNLITIYSKAIEVVLASGAVPPEIELRE------------SGVFAKSTILK
--G-TRY--GPFQGVWAT-K--PEEAMFAWE------------------VV-ADKGVKG-
---------WLDGT-VYEQ-NWLKLIRFNE----PK-INVRYFLQGGE-LWYETCSNISL
GTELILA---KEPLNLQDMYGEAIS---------A----ER--ET---ASQHSEKAD---
----------------------
>Leptinotarsa_decemlineata_XP_023027169.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------QQNARVDIYYLRAREVILASGSLPSELELRE------------TGVFAKVTIPK
--G-TKY--GPFQGKWAS-V--PQDTRFAWE------------------VV-AGSGVRG-
---------WLDGS-VEHQ-NWLKLIQSAPD--KSE-ANLRYNLQGGQ-LWYETFQEIPP
GAELMLA--QREPLNLQDMFGDS-----------ADERSDR--ET---ASQHSGTLD---
----------------------
>Anoplophora_glabripennis_XP_018561524.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------QTNGKVDIFYLRAREVILASGTLPGELELRE------------NGVFAKTTINK
--G-ARY--GPFQGKWAS-I--PQDARFAWE------------------VV-AGSGVRG-
---------WLDGS-SEHQ-NWLKLIQSTPN--KNQ-ANVRHFLQNGQ-LWYETFQDIPS
GTELTLS--PREPLNLQDMFADSTS---------ADERSDR--ET---ASQHSGTLD---
----------------------
>Bombus_terrestris_XP_012176108.2_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------QDATKQE---QKEQSNREWVSPVP-EVEVGGSAP--G-G----PQVRARKDIPR
--G-ARF--GPFLGKWAS-E--PFNPRYAWE------------------VRTAGSGVRG-
---------WLDAS-HETN-NWLKYVRSTSS--PHT-VNMRHVLIGGQ-MVYEAVRDIAA
GEELLLG--VREPLQLQDMLGENTT----------EDRSDR--ET---ASQHSGTVD---
----------------------
>Apis_mellifera_XP_026295431.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------QDATKQE---QKEHANREWVSPVP-EVEVGGSAP--G-G----PQVRARKDIPR
--G-ARF--GPFLGKWAS-E--PFNPRYAWE------------------VRTAGSGVRG-
---------WLDAS-HETN-NWLKYVRSTSS--PHA-VNMRHVLIGGQ-MVYEAVRDIAA
GEELLLG--VREPLQLQDMLGENTT----------EDRSDR--ET---ASQHSGTVD---
----------------------
>Cotesia_glomerata_XP_044595349.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-------QPIKQEP-KDQKDQPREWFPLIPSEVEVGKSSS--G-S----ALVRARKEIPR
--G-TRF--GPFLGKWAS-E--PHNPRYAWE------------------VRVPGNGVRG-
---------WLDAS-HEPS-NWLKYIRSTAS--PHA-VNMRHVLVAGQ-MVYETLREISS
GEELLMG--LREPLQLQDMLGENTT----------EDRTDR--ET---ASQHSGTVD---
----------------------
>Chelonus_insularis_XP_034939426.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------QET-IKDEPKDGDWLSPVP-EIEVEYSSY--G-N----PLVRAKIKIPK
--G-ARF--GPFLGKWVS-E--PHNLRYAWE------------------VRASGNGVRG-
---------WLDAS-DEAS-NWLKYIRSTSK--LHT-INMRHVLIREQ-ICYEALRDIAA
KEELLIA---KVPIQLQDISDEHLT----------EDRIDR--EAGESASQHSETVD---
----------------------
>Atta_colombica_XP_018056888.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------MRHVLIGGQ-MVYEAVRDIAT
GEELLLG--LREPLQLQDMLGENTT----------EDRSDR--ET---ASQHSGTVD---
----------------------
>Frankliniella_occidentalis_XP_052121737.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
---------------RDDVAPAAQLSQLLPAELELR------G-D----AGIWARQPLTK
--G-ARY--GPFLGKWTL-E--PADLRYAWD------------------VRVAGSAIRC-
---------YNDAS-AERS-NWLKLIRSTYR--PEA-RNVRAFLCGGQ-ILYETTQDVPA
GTELLLG--PREPLLLDMLTADN----AA------EDRSDR-----ESASQHSGTGGDDR
E---------------------
>Thrips_palmi_XP_034253686.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
---------------------------------------------------MAGLSIRC-
---------YCDAT-AERA-NWLKFVRSSSR--PEA-RNARAFLHGST-ILYETTQDVPA
GAELLLG--PREPLLVDMLSDSAVE--DR------SDRSDR-----ESASQHSGTGGDDR
D---------------------
>Halyomorpha_halys_XP_014289532.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------------MRGSSEDDRSRPPAEVELR------G-S----AGIYARELIPQ
--G-VRY--GPFMGKWVP-K--PLDPSFAWE------------------VRVGG--NRG-
---------FLDGT-LEFG-NWLKYIRSTDN--PDE-ITVRPVLSAGQ-VFYETVTDVQP
GRELMLP--PKEPLRPEQEES-------------------------HSASQQSSTGE---
----------------------
>Zootermopsis_nevadensis_XP_021923864.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------------PPSRDPLLATRVPPELELRD-----P-G----SGVWTRQLVSR
--G-TRL--GTFIGLWVS-E--PEDPRYALE------------------VRVRGTGNRG-
---------FLDAT-TEDS-NWLKYVRCTNQ--TEA-QNVCILLLDDQ-VFFDTSSDVGA
GEELLVG--PRVPLYLERYGDSPNT---------SEDHSDR--ET---ESQHSGTVDEER
D---------------------
>Nilaparvata_lugens_XP_039278934.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
----------------ADEQDRERARVLLPKELELRS------------DGVWTRSPLAD
--R-SRY--GPFQGKWLN-K--PIDQRFAWT------------------VRVGA--NRG-
---------YLDAT-LECS-NWLKFVRSTSH--GAA-QNVRAFLVAGQ-VYYETISAVRA
GEELLLG--PKEPLVLQDPLQEFTT--TS------EDRSDR-----ESASQHSGTVDEDR
D---------------------
>Aphis_glycines_KAE9539587.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
-------------------------------------------------VRIA--GYSG-
---------YLDGT-IEIC-NWMKFVRSTND--CSR-QNVRAFLLAGQ-IFYELTQTIRG
SEELLLG--KREPLNLDAAFGELMT--AS-----AEDRSER--DS-VVASQN--------
----------------------
>Penaeus_vannamei_XP_027235911.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
--------------SAAAERFITQQLSAVPLELEVRPSSV--GVG----VGVWAKQPIVR
--G-TRY--GPFLGKWTA-N--AKDPGLAWE------------------VVSIRSGLRG-
---------WLDAG--EMG-NWLRHIRVAAA--PVY-GNLRHLLLAGQ-IFYEAIRDISQ
SEELLLI--RKSVIDLDTSAIDDQVQVGS-----PEEKSE--------------------
----------------------
>Penaeus_chinensis_XP_047476722.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
------------------------------------------------------------
------------------------------------------------------------
-----------------MG-NWLRHIRVAAA--PVY-GNLRHLLLAGQ-IFYEAIRDISQ
TEELLLI--RKSVIDLDTSAIDEQVQVGS-----PEEKSE--------------------
----------------------
>Oppia_nitens_XP_054165181.1_PRD16_HUMAN_1276_residues (PRD16_HUMAN_1276_residues)
-----------------HRSGGQLLLPELPDELELRSATP--HTDGQPFMAVCARQTLKM
--G-TIF--GPYLGKIHK-D--RISTSLSWK------------------VTDRTGTFTA-
---------WLELLDLNAI-QWITCIRKAEL--ATN-RNAILLLFRGQ-LYIELTREVNK
GCELQLL--S-TDVLLKHEDPTNDT----------EKRAEK--ATD--YLRLPERVDHQQ
SLQQPPHH-HLHHQLQQ-QQ--
