>Acanthaster_planci_XP_022111953.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCIECNHY-----------------NPTTCTTHGP-PTFIPDAEIPCRAKLTLPNMLKL
SESLTN---R----------KNIRCGVIAVE--NIQQRCQFGPLVGKVINKSDDILE-A-
--DSNRIWKIFRNGI----------VSHFIDVSDENQSNWMRYVRLASRTQEQNVVVHQS
GGNIYFTTNKQITMGEELRAWYSQDYARWFG-----VPDKPGS-----SFHCTQCPMQFL
QRRQLSQHLGFKHPD-
>Patiria_miniata_XP_038073736.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCVECNHY-----------------NPTTCATHGP-PTYIPDTEIPCRAKLTLPAMLRL
SESLTN---R----------KNLRCGVIAVE--NIQARSQFGPLIGKVISKSDDILE-A-
--DSIRIWKIFRNGI----------ASHFIDVSDENQSNWMRYVRLAARSQEQNVVIHQS
GGNIYFTTNKQITMGEELRAWYSQEYARWNG-----VPEKPGS-----SFQCTQCPMQFL
QRRQLSQHLGFKHPD-
>Asterias_rubens_XP_033629625.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCIDCNHY-----------------NPTTCTTHDP-PTTITDSEIPCKAKLTLPSMLKL
SETLVN---S----------HGNRNGVIAVQ--SIEARCQFGPLIGKIISKDDSVVE-T-
--HSNRLWKIYRNGM----------VSHCIDVSDDENCNWMIYVKLANRTSEQNLVAHQS
GGQIYFITNKLIKEGEELKIWYSKDYAQWQG-----VPETPES-----SFHCTQCPMHFF
QRKQLIHHLGCKHPD-
>Holothuria_leucospilota_KAJ8032106.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
FWCVQCDET-----------------MPQVCPQHGA-PTIISDTPIQKRAKMTLPQLLFC
KKSNVS---S----------D--FLGVWAKD--PIKVGCRFGPLEGIILKRLTTEAD-S-
--LSPLLWKVFQNGK----------VRHFIDAKDEDTSNWMMYVKRARKLEEQNLSAHQT
NGQIYFTTKREIKSGEELLFWYSKDYATMSG-----ATLLPED-----SFKCHLCGRQFS
YRQELDGHMRYRHPS-
>Lytechinus_pictus_XP_063971032.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SWCISCRAI------------------VK-CCPHQKPAVVVADKAVETRARQSLPDLLML
KPSIAI---------------PGETGVYAKR--EILPNTRFGPVVGKLADVNSSTDL---
DAIGHKTWRIFSDRK----------LCQLLFTNDESCSNWMMFIKMSK---DHNLMAFQS
GAHIYFTSLTKIQPGEELVVWYSKEYARLRG-----IRDYKG------TMKCQKCHESFP
GNTHLQCHMAEAHPS-
>Lytechinus_variegatus_XP_041452727.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SWCISCRSI------------------VK-CCPHQKPAVVVTDKAVETRARQSLPDLLML
KPSIAI---------------PGETGVYAKQ--EILPNTRFGPVVGKLADVNSSTDL---
DAIGQKAWRIFSDRK----------LCQLLFTNDESCSNWMMFIKMSK---DHNLMAFQS
GAHIYFTSLTKIQPGEELVVWYSKEYARLRG-----IRDFKG------TTKCQKCHQSFP
GKTHLQCHMAEAHPS-
>Strongylocentrotus_purpuratus_XP_030843705.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SWCSSCKSI------------------VK-CCPHQKPSVMVLDKVVETRARQSLPDLLMF
KPSSVI---------------PGETGVFAKH--EIQMNTRFGPVVGKLADINSSTDL---
DAIGQKAWRIFSDGK----------LCQLLFTNDESCSNWMMFIKIAK---KHNLMAFQS
GAHIYFTSFQNILPGEELIVWYSKEYGRLRG-----IKDRKG------TLDCQKCDRSFL
DKTQLRHHLKEAHPS-
>Saccostrea_cucullata_XP_062580416.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
DYCVTCDSS------------------KCTCL-SPVQYTHITDKVIPSRARLSMPGCLEI
RLSKSSMSS------------QTPEGVYALK--CLGAHTKFGPLIGKDITTLE-------
TEGLFPEWRVMADND-----------CHYITTDDEEQSNWLRFIRPAQNIVEQNLVVHQV
GRSLFFFAKRDIREGEELLYWFSKEYSVICG-----FSLIPKPGS---VNECPVCAKMFR
KKQGLRQHLTDVHKE-
>Saccostrea_echinata_XP_061193585.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
DYCVTCDSS------------------KCTCL-SPVQYTHITDKVIPSRARLSMPSCLEI
RLSKSSMSS------------QTPEGVYALK--GLGAHTKFGPLIGKDITTLE-------
TEGSFPEWRVMAEND-----------CHYITTEDEELSNWLRFIRPAQNIVEQNLIVHQV
GRSLFFFAKRDIREGEELLYWFSKEYAVICG-----FSLIPKPGS---VNECPVCARMFR
KKQGLRQHLADIHKE-
>Crassostrea_virginica_XP_022290936.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
DYCVLCDGS------------------KCSCP-APIECSHVPDKIIPSRARLSMPSCLEI
RLSKSSLSS------------QVPESVYALK--SFMTHTKFGPLIGEEVKTLE-------
TEGLFPEWRVMEDNG-----------CHYISTGNEDLSNWLRFVRPAQNIVEQNLVVHQV
GQSLYFYVKRDIKQGEELLFWFSKEYAVICG-----YSVIPKPSS---VNECPVCAVMFR
KRQVLRNHLAEVHRD-
>Ostrea_edulis_XP_056014388.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
DYCVTCDSS------------------KCTCL-SPLEYTHITDKVIPSRARLSMPSCLEI
RLSKSSLSS------------QIPEGVYALK--CLGTQSKFGPLIGKEMKTLE-------
TEGLFPEWKIIEDNG-----------CHYISTTDEEMCNWLMFIRPAQNIVEQNLVVHQV
GKSLYFYAKREIKEGEELLFWFSKEYAALCG-----LSLIPKPGS---VNECPVCAKMFR
KRQVLRQHLADIHKD-
>Biomphalaria_glabrata_XP_055890213.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCVDCNIM-----------------YKLQCKFHPSEYSYICDTPILSHARLTLPSCLRL
GSSSVV---G----------HTNNTGVFAKE--VIAARTKFGPLIGSPVSCDQ--LG---
STRSFSLWQTFSESS-----------TKVVDTSDENSSNWLMFIKPACVSAEQNLVAFQH
GSNVYFVTRMDINPGQELRYWFAKDYARLLG-----ITPNPKSVYYQLCPHCTVCKQIFP
DRKQVRSHTRLQHPK-
>Bulinus_truncatus_KAH9489155.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCVECNTT-----------------YKSQCEFHPNEYSYIIDTPILTHARLTLPTCLKL
KTSNIV---G----------HTNNTGVFAKE--NIAVRTKFGPLIGSSVSCDQ--LG---
STRSFSLWQTFSEKS-----------TKVVDTSDENSSNWMMFVKPARLSSEHNLVAFQN
GSSVYFVTRVDINPGEELLYWFSKDYARLLG-----ITPNPKNVYYQLCPHCTVCKQIFP
DRKQVRSHTRLQHPR-
>Physella_acuta_XP_059149197.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCVECNMM-----------------YKAQCKFHPCDYTYISDTPILSHARLTLPNCLRL
ATSDIA---G----------HTNNTGVFAKE--SIAVRTKFGPLIGSPVSCDK--LG---
STRSFSLWQTFIGTN-----------AKVVDTSDENSSNWLMFVKPARLSSEQNLVAFQH
GSSVYFVTRVNIEPGQELLYWFAKDYARMLG-----ISAKPKNAHHQLCPHCTVCKQVFP
DRKQVRNHIRLQHPK-
>Aplysia_californica_XP_005107014.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SFCVECNTT-----------------YKTQCKFHPSNYTYVADSPILSHARLTLPTCLKL
NISSVV---G----------HSNNTGVFAKE--KIGVRTKFGPLIGSSVSCDK--LG---
STRCFSLWQTFVGNN-----------IKVVDTSDENSANWLMFVKPARLSLEQNLIAFQH
GNSVFFVTRLDIEPGQELRYWFSKDYARMLG-----ITAKPRNARHQLCPHCTVCNTVFA
DRQQVRSHMRLQHPK-
>Elysia_crispata_KAK3776406.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCVECNTM-----------------YKTQCKFHSCDYTYVTDTPILSHARLTLPSCLTL
GESSVM---G----------HTNNTGVFAKE--KVAVRTKFGPLTGSPVSCDK--LG---
STRSFSLWQTFMGGS-----------VKVVDSSDENSSNWLMFVKPARVSMEQNLVAFQH
GHSVYFVTRQEIQPHQELLYWFAKDYARILG-----IADKSKSGQHMLCPHCSICKHIFP
DRKELRSHLRLQHPR-
>Elysia_marginata_GFS15838.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCVECNTM-----------------YKSQCKFHSCEYTYVTDTPILSHARLTLPSCLTL
GESSVI---G----------HTNSTGVFAKE--LIAMRTKFGPLTGSPVSCDQ--LG---
STRSFSLWQTFTGGN-----------VKVVDSSDENSSNWLMFVKPARNSMEQNLVAFQH
GHSVYFVTRQEIQPHQELLYWFAKDYARILG-----ITDKSKNAQHMLCPHCSICKHIFP
DKKELRSHLRLQHPR-
>Gigantopelta_aegis_XP_041352286.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
HYCVECNNT-----------------YKEPCKFHITDYMHLTDTPLLSRARASLPLTLNL
QKSSLN---G----------HFSDVGVFCNE--TVKLRTLLGPLVGKPVPCDM--WQ---
SGKKFVFWKIFFEDY-----------FSVLDISDEDESNWLMFVKPARNALEQNLVAFQK
DEEIYFVTCKDIEPGQELLFWYAKDYAKLLG-----LSPKPRRNGTSYCPYCCVCEKVFP
DRKSLKLHKKEEHPN-
>Haliotis_rufescens_XP_046333562.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
LYCVECNNS-----------------YKNGCTYHKMNYTYVADRPVLPRAKLTLPTCLIL
QTSRIKITAD----------NVNNLGVFTNE--KILKKTEFGPLVGKIVSEDT--YT---
YTSSF-TWKIFYCDH-----------HSVVDVSDEAECNWLMYVKPAPTLQDQNVVVYQR
GAELFFITNKDMEAGSELLFWFAKDYAKLLG-----LPAKPSQLWPSNCPYCHVCSKVFS
DWKSLSRHMKTDHPN-
>Haliotis_rubra_XP_046581380.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
LYCVECNNS-----------------YKNGCTYHKMNYTFVADQPVLPRARLTLPTCLIL
QTSHVKITAD----------NVNNLGVFANE--KILKKTEFGPLVGKIVSEDT--YT---
YTSSF-TWKIFYSDH-----------HSVVDVSDEAECNWLMYVKPAPTLQDQNVVVYQR
GAELYFVTNKDIEAGSEMLFWFAKDYAKLLG-----LPAKPSQLWPSNCPFCHVCSKVFS
DWKSLSRHMKTDHPN-
>Octopus_sinensis_XP_036368015.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
NFCLECNYNSNNNNTSSNGSSSSSGSSNAPCQIHNTNYCDIPDTPIPSRARLSIPSLLYL
KTTSAH---G----------YTDTLGVWAKE--TVPCRSRFGPFVAKVKGKCPVDSQ---
KTSDFPIWMIFSKDG---------QTADALDVSDENECNWMMFVKPARSPEEQNLVAYQQ
QYSIYFMTCCDVQPHQELLVWYSNDYASTLG-----VPLKAN-----VTLSCCVCRKPFA
SHKLLAQHVRSMHPD-
>Mya_arenaria_XP_052808281.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VFCVDCNKL-----------------LPTGCKVHNTEYLYQADTPVLSRARTSLPPCFTL
QHTGSS---E----------HPDLMGVWCKE--CLSERTIFGPMVGQQLKLTNTEFA--E
QAYGFQPFLLSKGEH----------ETKLLHMVDENICNWMMFVRYAPSLLEQNCTVYRD
GDHFYFVTKTEIK-EEELLVWFSAEMCLILG-----ITQNPGNHH---FHQCEDCGLNFL
IKRLLNAHLKSKHPE-
>Dreissena_polymorpha_XP_052239787.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VFCVDCNKV-----------------FASGCRVHRTDYVYQSDTPVLSRARASLPQCFML
QKTGTT---Q----------VVDLLGVWCKG--CLSERTIFGPMVGEKVELTNKNFA--D
QELGFHPFLIRQSES----------SKLVLHLVDEAVCNWTMFIQFAPTLLEQNCTVYRD
NGNFFIVTKTEIK-DEELLLWFSAELCLELG-----ITQNPGNHP---FYQCPECSLNFL
VKRFLNAHQKTKHPE-
>Mercenaria_mercenaria_XP_045197714.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IFCVDCNKL-----------------MKEPCSVHNTDYVDMPDTPYLSRARASLPPCFTL
QQTATS---E----------FKPFLGVWCKG--CLSERTRFGPVVGQIVTMTTPEYE--E
QMHGFQPFLLSKAETGDDLQDKGDNQVEVIQMTDESVCNWTMFIRFAPSLLEQNCTVYRD
QNEFYIVTKTEIK-EEELLMWFSAEICYQLG-----ISQNPGNVK---FSQCEECGLYFL
VKRLLHTHLKSVHPE-
>Potamilus_streckersoni_KAK3577473.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
TFCIECNML-----------------LSERCLLHNTNFTHLDDSPLLSRARASLPSCLYL
RQSCRS---Q----------FPNYLGVWAKQ--TICARTRFGPLRGLHKPFPLPPHEEKN
GDLGFCSWKVFDEN----------GKAEMIDVNNEDNCNWMMFLRLASSLVDQNIIAYQQ
NSDIFVITSKEIDPDQELLVWYSTNYAKNMG-----VSQDPSVQK---ILQCQFCGKLFS
GKMKLKEHIRKQHPD-
>Pecten_maximus_XP_033740939.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SFCVGCDSAS----------------ETTPCLVHDTEYSAIVDSPIPSKARASLPTCLCL
KSSETI--------------LQNVTGVWAKV--KLKAKSKFGPLVGKISSSAPGESK---
LGSL-PEFKVIYSNK-----------VDQYDLEDEQECNWLKFVQMARTEAAQNMVVTQL
GSEIFFFTTKEVYPGEELFFWYSKDYARFLG-----VPVSPETKK---IKTCYVCGKVFV
GRLNLRAHQKLLHAD-
>Ylistrum_balloti_XP_060070452.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SFCVGCNSAS----------------EANPCLIHDTEYTAIADSPIPTRARASLPTCFYL
KPSETI--------------LQNVIGVWSKV--ALKAKSKFGPLVGKVSSSAPGESK---
LGSL-PEFKVIYSDK-----------VDQYDLEDEQECNWLKFVQMARTEASQNMVVTQL
GSEIYFFTTKQVYPGEELLFWYSKDYARFLG-----VPVSPETKK---IKMCYVCGKVFV
GRLNLRAHQKLLHAD-
>Mizuhopecten_yessoensis_XP_021354850.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
SFCVGCNAAS----------------ETSPCLIHDTEYTAIADSPIPSKARASLPTCLYL
KSSETI--------------LQNVMGVWSKV--PIKAKSKFGPLVGKVSSSAPGESK---
LGSL-PEFKVIYSDK-----------VDQYDLDDEEECNWLKFVQMARTEESQNMVVTQM
GSDIYFFTTKDVYPGEELLFWYSKDYARFLG-----IPVSPETKK---IKMCYVCGKVFV
GRLNLRAHQKLLHAD-
>Paralvinella_palmiformis_KAK2140884.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VYCVECNDT-----------------YIGDCNQHSTQYTHIQDSVIESRARASLPKCLYL
MDVNRPHKSSS--------AGITATGVFCGE--DIPAKTLFGPLEGVMSSES--------
AENKANIWQLFQNGT----------TAMYLDCTSEDRSNWLMFMRRASNNAEQTVVVYQQ
GLELYYVTSKPVLKGQELLYWYSATYAQLLA-----LPRRPDL-----LLYCNICHEQFI
SLDAIAGHKKKMHPN-
>Ridgeia_piscesae_KAK2188743.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
RYCVDCNKMYR---------------GESGCPTHATNYAVIADGHIPSRARLSIPPQLTL
RAINNQ---T----------APNFMGVIALE--TVASHTLFGPLLGNKTTKEQLERP---
TETA-YVWELFDD-G---------RQSQVLDCRNEELSNWLMFVKRARTSAEQNVMVYQE
QDDIYFVTCKDIDPGTELLYWYARDYAKMLG-----VAWRPED-----FFKCPTCSKQFP
DMNSVKQHVRYAHPD-
>Capitella_teleta_ELU04920.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
AYCIECNRV-----------------WKSGCPQHIHTYTHVPDSPVYSRAITTLPSILQL
QRSNDP---------------TAPYIVMANV--DIEARTVFGPLEGKRLTGVT--DH---
HGDDPHHWQIYQSQG-----------TQVIDCTDEAVSNWLMFLQRATRNSDQNIVAYQH
GSDVYFVCRQKISAGETLQYWFSSDYAQLLG-----VGQSPEP-----TYSCSQCQREFD
SIKLLNNHVARVHQE-
>Lingula_anatina_XP_013387176.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
FYCVECNCT-----------------YESSCSKHGGEYIHVLDTPVLSRARASLPAQLSL
QSSRIQFDQNS--------RIHFDLGVWSSE--LIPKKTKFGPVVGNLAPLSNFSED-A-
DLSPPFFWKIH-CAE----------ECNILMCTDEDVSNWTMFLKRAKTNSDQNLTAYQE
GESIFFVTCKDIQPGSELAFWYSREYCKELG-----VTLSPEG-----AFLCDICNKQLV
DSKALAQHIKYIHAD-
>Owenia_fusiformis_CAH1799467.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
HYCVDCNDT-----------------YHSVCAQHGNFYVEVKDAPISSRARMSLPEQLKL
TVSDTSLSD-----------IK-FTGIFAKE--KISKGTKFGPLIGAVLMMSQTIQE-L-
EKSSN-IWKICNEDH----------KYHYIHCTNEDTSNWMMFVRKARATREQNIVAYQE
GLNIFFITCKDIEPGAELLYWYSRPYSKYLG-----VPSAPNE-----YYSCSICKKDFV
EFHHLKQHMIFRHAD-
>Balaenoptera_acutorostrata_XP_057413043.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAD----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHSGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHNH
>Erinaceus_europaeus_XP_060050338.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGTE----------------VGVWTEE--TIPVRTCFGPLVGQQSHSMEVAEW--T
DKTVNHIWKIYHSGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHNH
>Rattus_norvegicus_XP_063119009.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGTD----------------VGVWTAE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVSHVWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYSEFKAHLTSHIHNH
>Bos_taurus_XP_059742971.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAD----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLSSHIHNH
>Muntiacus_reevesi_XP_065794571.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSMVGAD----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLSSHIHNH
>Equus_caballus_XP_023487613.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHNH
>XP_025866725.1 (best hit for PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSVVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----APEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHTH
>Vulpes_vulpes_XP_025866725.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSVVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----APEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHTH
>Saccopteryx_leptura_XP_066214328.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFIPDTPVESRARLSLPKQLVL
RQSIVGAE----------------VGVWTAD--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIVTTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECS
SYTEFKAHLTSHIHNH
>Sturnira_hondurensis_XP_036923875.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAE----------------VGVWAGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Galemys_pyrenaicus_KAG8514045.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPVESRARLSLPKQLVL
RQSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKMYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Homo_sapiens_NP_036538.3_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPEHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIFFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Myotis_daubentonii_XP_059537715.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPEHGP-VTFVPDTPIESRARLSLPKQLIL
RQSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIVTTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFYTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHSH
>Mirounga_leonina_XP_034843534.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSVVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Lynx_pardinus_VFV21225.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSVVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVAEW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Loxodonta_africana_XP_003405363.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVADW--T
DKAVNHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Dasypus_novemcinctus_XP_012376015.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RPSIVGAE----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVADW--T
DKAVNHIWKIYHSGV----------LEFCVITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------LCNCGKECN
SYTEFKAHLTSHIHNH
>Antechinus_flavipes_XP_051817483.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDSPIESRARLSLPKQLVL
RQSLLVPD----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVADW--T
DKAANHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQMG-----VPEHPDVH-------VCTCGKECN
SYAEFKAHLSSHIQQH
>Vombatus_ursinus_XP_027729574.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDSPIESRARLSLPKQLVL
RQSLMVAD----------------VGVWTGE--TIPVRTCFGPLIGQQSHSMEVADW--T
DKAANHIWKMYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------VCNCGKECN
SYTEFKAHLSSHIHHH
>Tachyglossus_aculeatus_XP_038612678.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSLMGAD----------------VGVWTGE--TIPVRTCFGPLLGQQSHSMEVADW--T
DKAANHIWKMYHNGV----------LEFYIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSQDIPPENELLFYYSRDYAQQIG-----VPEHPDVH-------ICNCGKECN
SYTEFKAHLNSHIHNH
>Python_bivittatus_XP_007427934.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVSDTPIESRARLSVPKQLNI
RHAVMGPEVGGQYCQLSTCLGSPSLGVWARE--TIPVRTCFGPLIGQQSHSVEVADW--T
DKAANHIWKMYHNNV----------LEFYIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSRDIPPDHELLFYYSRDYARQIG-----VPEHPDVH-------TCHCGKECA
SYAEFKVHLSSHLNSH
>Varanus_komodoensis_XP_044297056.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVSDTPIESRARLSLPKQLVV
RQSIMGAE----------------VGVWAQE--TIPVRTCFGPLIGQQSHSMEVADW--T
DKTANHIWKMYHNNV----------LEFYIITTDEHECNWMMFVRKARTQEEQNLVAYPH
DGKIYFCTSRDIPPDHELLFYYSRDYARQIG-----VPEHPDMH-------TCHCGKECA
SYTEFKAHLNSHIH--
>Apus_apus_XP_051492272.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIMGAE----------------AGVWTRE--TIPVRTCFGPLIGQQSHSLEVADW--T
DKAASHIWKIYHSGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSRDIPPEHELLFYYSRDYARQLG-----VPEHPDVH-------ICHCGKECA
SYADFKAHLSSHIHNH
>Apteryx_rowi_XP_025919207.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIMGAE----------------VGVWTRE--TIPVKTCFGPLIGQQSHSLEVADW--T
DKAASHIWKIYHSGV----------LEFCIIMTDENECNWMMFVHKARNREEQNLVAYPH
DGKIYFCTSRDIPPEHELLFYYSRDYARQLG-----VPEHPDVH-------ICHCGKECA
SYADFKAHLSSHIHNH
>Tyto_alba_XP_042648424.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVPDTPIESRARLSLPKQLVL
RQSIMGAE----------------AGVWTRE--TIPVRTCFGPLIGQQSHSLEVADW--T
DKAASHIWKIYHSGV----------LEFCIITADENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSRDIPPEHELLFYYSRDYARQLG-----VPEHPDVH-------VCHCGKECA
SYADFKAHLSSHIHTH
>Corvus_cornix_XP_039426696.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVPDSPIESRARLSLPKQLLL
RQSIMGAE----------------AGVWTRE--TIPVRTCFGPLIGQQSHSLEVADW--T
DKAASHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSRDIPPEHELLFYYSRDYARQLG-----VPEHPDVH-------ICHCGKECA
SYADFKAHLSSHIHNH
>Taeniopygia_guttata_XP_030118985.3_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFVPDSPIESRARLSLPKQLLL
RQSIMAAE----------------AGVWTRE--TIPVRTCFGPLIGQQSHSLEVADW--T
DKAASHIWKIYHNGV----------LEFCIITTDENECNWMMFVRKARNREEQNLVAYPH
DGKIYFCTSRDIPPEHELLFYYSRDYARQLG-----VPEHPDVH-------ICHCGKECA
SYADFKAHLSSHIHNH
>Chelonoidis_abingdonii_XP_032654613.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFIPDTPIESRARLSLPKQLVL
RQSVMGPE----------------VGVWTQE--TVPVRTCFGPLIGQQSHSLEVADW--T
DKATNHIWKMYHNGV----------LEFYIITADENECNWMMFVRRARNREEQNLVAYPH
DGKMYFCTSRDIPPEQELLFYYSRDYARQIA-----VPEHPDVH-------ICHCGKECT
SYTEFKAHLSSHIHNH
>Chelonia_mydas_XP_043398301.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDKA-----------------YPSDCPDHGP-VTFIPDTPIESRARLSLPKQLVL
RQSITAPE----------------VGVWTRE--TIPVRTCFGPLIGQQSHSLEVADW--T
DKTTNHIWKMYHNGV----------LEFYIITTDENECNWMMFVRRARNREEQNLVAYPH
DGKMYFCTSRDIPPEQELLFYYSRDYARQIG-----VPEHPDVH-------VCHCGKECT
SYTEFKAHLSSHIHNH
>Bufo_bufo_XP_040294076.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCNRA-----------------YPSDCPEHGP-VTFIPDNPIESRARLSLPKQLVL
GQSVTEAE----------------VGVWTQE--SISVRTCFGPLIGQESQSLEVAGW--T
DKSANHIWKIYSNNV----------MEFCIITTDEHECNWMMFVQKARNLDEQNLVAYPH
NGKIYFYTTRDIPAQEELLFYYSRDYAQQMG-----LPEQPEML-------LCHCGEECL
SYAEFKSHLSCHVNSH
>Pseudophryne_corroboree_XP_063785135.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCNQA-----------------YPSDCPEHGP-VTFIPDRPIESRARLSLPKQLAL
RQSVTGAD----------------VGVCAQE--DIAVRTCFGPLIGQESQTLEVAGW--T
DKSANHIWKIYNNNV----------MEFCIITTDENECNWMMFVRKARNPEEQNLVAYPH
DGKIYFYTTQDIPAQEELLFYYSRDYAVQMG-----LPEQPELL-------LCHCGKECS
SYVEFKSHLSSHVNSH
>Pelobates_cultripes_CAH2276657.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPEHGP-VTFIADSPIESRARLSLPKQLSL
RDSVTGAD----------------IGVWTQE--TILVRTCFGPLIGQESQSLEVADW--N
DKSASHIWKMYQGGV----------MDFCIITNDENECNWMMFVRKARKPEEQNLVAYPH
DGKIYFCTSKDIQPQEELLFYYSRDYACQLG-----LPEQPELL-------VCHCGKEYL
SYADFKSHLNSHLNSH
>Geotrypetes_seraphini_XP_033806591.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFIPDTPIESRARLSLPKQLLL
RQSIVSSD----------------IGVWAQE--TIPVRTCFGPLIGEEHSSVDVPEW--T
DKTACHIWKMYHDGI----------LQFCITTSDESTCNWMMFVRKARSVAEQNLVAYPH
NGKIFFCTSRNIAPEEELLFYYSRDYARQLA-----VPEEPELQ----VWWVCHCGKECM
TCSDFKSHLSSHIHNN
>Microcaecilia_unicolor_XP_030070012.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFIADTPIESRARLSLPKQLLL
RQSVVSSD----------------LGVWAQE--TIPDRTCFGPLIGEERSSVDVPEW--T
DKTASHIWKMYHGGM----------LEFCIITSDESACNWMMFVRKARNVAEQNLVAYPH
NGQIFFCTSRNIAPDQELLFYYSRDYARQLA-----VPEEPELQ----VWWVCHCGKECM
TCSDFKSHLNSHIHNN
>Rhinatrema_bivittatum_XP_029453140.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPDHGP-VTFIPDSPLESRARLSLPKQLLL
RQSTVGSE----------------IGVWAQE--TIPVRTCFGPLIGEESPTVDVPGW--T
DKAPSHVWKMYHGGM----------LEFCIITSDENACNWMMFVRKARNVAEQNLVAYPH
NGKIFFCSSRNIAPEQELLFYYSRDYARQLA-----VPEEPEVQ----VWQVCHCGKECM
SYSDFKSHLSCHTHNH
>Latimeria_chalumnae_XP_014351412.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPSDCPEHGP-VTFIPDSPIESRARLSLPRQLSL
RQSITGAE----------------IGVWTRE--TIPVRTCFGPLIGRQSHSVEVADW--P
DKMANHIWKMYHNSA----------LEFCIITTDENECNWMTFVRKARTREEQNLVAYPH
EGKIYFCTSQELHPDQELLFYYSKDYARQIG-----APEQPDMH-------VCHCGKECS
SYTEYKSHESTHSQTH
>Protopterus_annectens_XP_043944511.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCILCDRA-----------------YPSDCPEHGP-VTIIPDSPIESRARLSLPKVLII
KHSVTGAE----------------TGVRARE--PIPPRTCFGPLIGEQVRVADSAEW--S
DISQNHLWKVYNNGE----------LEFVIVTTDENECNWMMFVHKARHVEEQNLVAYPQ
NGKIFFCTSKEIPVDQELLFYYSRDYARQLG-----VLDNPGMR-------ICDHGKECS
SFTEFKSHVSSHAQNQ
>Chiloscyllium_plagiosum_XP_043565328.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTVCDRA-----------------YPADCPEHGA-VTFIPDTPVSSRARLSIPKQLSL
RQSITGED----------------IGVWSQE--TIPIRTCFGPLIGEEINLLEVADW--T
NKNNTNIWKIFCNYV----------LEFLIVTADENICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSKEIPPNHELLFYYTRDYARQLG-----VPEHPNVH-------MCHCGKAYG
TYSELKSHLSSH----
>Rhincodon_typus_XP_048463408.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPADCPEHGA-VTFILDTPVSSRARLSIPKQLSL
RQSITGED----------------VGVWSQE--TIPVRTCFGPLIGEEINLLQVADW--T
NKSNTNIWKIFCNYV----------LEFLIVTADENICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSKEIPPNHELLFYYTRDYARQLG-----VPEHPDVH-------MCHCGKAYS
TYSELKSHLSSH----
>Carcharodon_carcharias_XP_041072193.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPEDCPEHGA-VTFILDTPVSSRARLSVPRQLSL
RQSITGED----------------VGVWSQE--TIPVRTCFGPLIGEEINLLEVADW--S
NKSNTNIWKIFHNYV----------LEFLIVTADENICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSREVPPDHELLFYYTRDYARQLG-----VPEHPDVH-------MCHCGKAYG
TYNELQSHLSSH----
>Scyliorhinus_canicula_XP_038636354.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPADCPEHGA-VTFIPDTPVSSRARLSIPRQLSL
RQSITGED----------------VGVWSQD--TIPVRTCFGPLIGEEINLLEVADW--S
NKSNTNIWKIFHNYV----------LEFLIVTADENICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSREVPPDHELLFYYTRDYARQLG-----VPEHPDVH-------MCHCGKAYG
TYSELKSHLSSH----
>Hypanus_sabinus_XP_059834105.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPADCPEHGA-MTFIPDTPVNSRARLSIPRQLTL
RQSITGED----------------VGVWSQE--AIPVRTCFGPLIGQQINLMEITDW--S
SKSSTNIWKIFRNYV----------LEFQIVTADESICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSREIPPDHELLFYYSRDYSRQLG-----VPEHPDVH-------MCHCGKAYG
TYSELKLHLSSH----
>Mobula_hypostoma_XP_062914058.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPADCPEHGA-VTFIPDTPVNSRARLSIPRQLTL
RQSITGED----------------VGVWSQE--AIPVRTCFGPLIGQQINLMEITDW--S
SKSSTNIWKIFRNYV----------LEFQIVTADENICNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSREIPPDHELLFYYSRDYARQLG-----VPEHPDVH-------MCHCGKAYG
TYSELKLHLSSH----
>Amblyraja_radiata_XP_032893368.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRA-----------------YPEDCPEHGA-VTFIPDTPVNSRARLSIPRQLCL
RQSITGGD----------------VGVWSQD--AIPVRTCFGPLVGQQINLMEITDW--T
SKTSTNIWKIFRNYV----------LEFQIVTVDEDLCNWMMFVHRARTREEQNLVAYPH
NGKIYFCTSREVPPDHELLYYYTRDYARQLG-----VPEQPDVR-------MCHCGKAYG
TYGELKLHLNSH----
>Danio_rerio_NP_001116215.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVTDEP----------------IGVFSRE--SIPSRTCFGPMVGQHCSSVELTDW--S
DKDTPQIWKMFHNDI----------QEFCIVTTDEHECNWMMFVRKARTTGEQNLVAYID
NGKLYFCTTREILPDQELLFYFSRDYSRQLG-----VPRVPEGQ-------ICHCGKECA
SFTEFKSHLGSHA---
>Tachysurus_fulvidraco_XP_047660242.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YSSDCPEHGP-ATFIPDTPIQSRARLSLPHPLCL
RVSVADEP----------------NGVFARE--TIPSRTCFGPMVGQHCSSVELSGW--T
DKDTPQLWKIFHNDI----------LEFCIVTTDENECSWMMFVRKARTTEEQNLVAYID
NGKLFFCTSREILPEQELFFYYSREYSRLLG-----VPHVPEGQ-------ICHCGKECT
SFSEFKAHLSSHA---
>Oncorhynchus_kisutch_XP_020326876.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------FGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--P
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------VCQCGKECQ
SFAELKSHLSSHNNHG
>Oncorhynchus_keta_XP_035604593.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------FGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--P
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
TGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------VCQCGKECQ
SFAELKSHLSSHNNHG
>Salmo_trutta_XP_029616768.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------LGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--S
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------MCQCGKECQ
SFAELKSHLSSHND--
>Salmo_salar_XP_014063244.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------LGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--S
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------MCQCGKECQ
SFAELKSHLSSHNDHD
>Oncorhynchus_gorbuscha_XP_046153491.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------FGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--S
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------VCQCGKECQ
SFAELKSHLSSHNNHG
>Oncorhynchus_mykiss_XP_021419189.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------FGVFARD--IIPPRTCFGPMVGQHCSNVDLQDW--P
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMG-----VPQVPEGQ-------VCQCGKECQ
SFAELKSHLSSHNNHG
>Esox_lucius_XP_034146109.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVADEP----------------LGVFARD--VIPPRTCFGPMVGQHCSNVDLQDW--P
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTQEEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTIDYCGQLG-----LPRVPEGQ-------VCQCGKECQ
SYAELKSHLSSHDN--
>Osmerus_eperlanus_XP_062339332.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVAGEP----------------LGVFARD--IIPPRTCFGPMVGQHCSNVDLSDW--P
DKDTPQIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTSEEQNLVAYPD
NGKLFFCTSTEILPDQELLFYYTRDYCRQMV-----VSQVPEGQ-------VCQCGKECS
SFAELKSHLNSHNSHS
>Solea_solea_XP_058482148.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDAPIQSRARLSLPRPLCL
RISVADEP----------------LGVFARD--VIAQRTCFGPMVGQHCSNVDLSNW--P
EKDTPQIWKMYHNNV----------LEFYIVTTDENECNWMMFVRRARTREEQNLVAYPA
NGKLFFCTTTEIHPDQELLFYYSRDYCRVMG-----VPQVPEGQ-------ICQCGEECS
TFTELKSHLGSHNSNH
>Sebastes_umbrosus_XP_037617073.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDAPIQSRARLSLPRPLCL
RISVADEP----------------LGVFARD--VIPPRTCFGPMVGQHCSNVDLCDW--P
EKETPQIWKMYHNNV----------LEFYIVTTDENECNWMMFVRKARTREEQNLVAYPA
NGKLFFCTTTELHPDQELLFYYSRDYCRLIG-----VPQVPEGQ-------ICQCGKECS
SFSELKSHLGSHNSNH
>Thunnus_albacares_XP_044199578.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCI
RISVADEP----------------LGVFARD--VIPPRTCFGPMVGQHCSNVDLSDW--P
EKETPQLWKMYHNNV----------LEFYIVTTDENECNWMMFVRKARTRDEQNLVAYPA
NGKLFFCTTTEIHPDQELLFYYSRDYCRLMG-----IPQVPEGQ-------ICHCGKECS
SFSEFKSHLNSHNSNH
>Lucifuga_dentata_KAF7658473.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSD------------------------------
---LADQP----------------LGVFARE--VIPPRTCFGPMVGQHCSNVDLSDW--P
EKDTPQIWKMYHNNV----------VEFCIVTTDENECNWMMFVRKARTGEEQNLVAYPA
NGKLFFCTTTEIHPDQELFFYYSRDYCRLMG-----IPQA------------LICHKDCT
PYPELKSHLSSHNGNH
>Gadus_morhua_XP_030197630.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDTPIQSRARLSLPHPLCL
RISVADEP----------------LGVFARDTHIIPQRTCFGPLVGQHCSNMDLSDW--P
EKDTPQIWKMYHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPA
NGKLFFCTTTEIHPDQELLFYYSRDYCRLLG-----APRVPEGQ-------ICQCGKECS
SFTELKSHVSDHNPHP
>Gadus_macrocephalus_XP_059894978.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDTPIQSRARLSLPHPLCL
RISVADEP----------------LGVFARDTHIIPQRTCFGPLVGQHCSNMDLSDW--P
EKDTPQIWKMYHNNV----------LEFCIVTTDENECNWMMFVRKARTREEQNLVAYPA
NGKLFFCTTTEIHPDQELLFYYSRDYCRLLG-----APRVPEGQ-------ICQCGKECS
SFTELKSHVSDHNPHP
>Takifugu_rubripes_XP_011611791.2_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YTSDCPEHGP-VTFIPDTPIQSRARLSLPRPLCL
RISVANEP----------------LGVFARD--IIPQRTCFGPMVGQHCSNVDLSDW--P
EKDTPQIWKVYHNNV----------LEFSIVTTDENECNWMMFVRKARTHEEQNLVAYPA
NGKLFFCTTTEIHLDQELLFYYSRDYCRLLG-----VPQVPEGQ-------LCQCGKECS
SFSDLKSHISSVNSNH
>Brienomyrus_brachyistius_XP_048864791.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRS-----------------YPSDCPEHGP-VTFVPDTPIESRARLSLPRPLCL
RVSVADEP----------------LGVFARE--VIPIRTCFGPLVGQHCSTMELTDW--S
DKNNPQVWKMFHNNV----------LEFYILTTDENVCNWMMFVRKASSEEEQNLVAYPD
NGKLYFFSSREVLPDQELVYYYSRDYCRHLG-----VSEVPGGQ-------LCHCDKDCG
SFGELKSHLGDHAHDQ
>Gymnothorax_javanicus_KAJ8262033.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIESRARLSLPRPLCL
RVTVADEP----------------LGVFARE--VIPVRTCFGPMVGQHCSSVDLTDW--S
DKNTPHIWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTGEEQNLVAYPD
NGKLYFCSSQEILPDQELLFYYSRDYSRQMG-----VPELPEGQ-------VCHCGKECT
SFAELKSHLNSHAHGH
>Megalops_cyprinoides_XP_036373583.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCERS-----------------YPSDCPEHGP-VTFIPDTPIESRARLSLPRPLCL
RVSVADEP----------------LGVFARE--TIPVRTCFGPMVGQHCSTVDLTDW--S
DKNTPHVWKMFHNNV----------LEFCIVTTDENECNWMMFVRKARTGEEQNLVAYPD
NGKLYFCSSREILPDQELLFYYSRDYSRQMG-----VPEVPDGQ-------VCHCGKECA
SFAELKSHLSSHTHSH
>Amia_calva_XP_066561016.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
IWCTLCDRS-----------------YPSDCPQHGP-VTFIPDSPIESRARLSVPRQLAL
RASVIGED----------------AGVFARE--PIPVRTCFGPMVGQHCSSLDVSDW--S
NKTPHNIWKMFHDNV----------LEFYIITADENECNWMMFVRKARSGEEQNLVAYPH
NGKLYFCSSREILPDHELLYYYSRDYARQMG-----VPEVPNAH-------VCHCGKECA
SYTDLKSHLGSHSQA-
>Polyodon_spathula_XP_041113111.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VWCTLCGQA-----------------YPSDCPQHGP-VTFIPDTPIESRARLSLPRQLIL
RQSGTGAE----------------LGVFSRE--PILVRTCFGPLVGQQCGSLDVSDW--S
DKASLHIWKVIHNNV----------LEFCVVTTDENECNWMMFVRKARTGREQNLVAYPH
NGKIYFCTSREILPDHELLFYYSRDYARHIG-----VPENPEAQ-------ICHRGKECA
SYSELKSSLNSHTNSH
>Huso_huso_KAK6482798.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
VWCTLCGQA-----------------YPSDCPQHGP-VTFIPDTPIESRARLSLPGQLTL
RQSGTGAE----------------LGVFSRE--PIPVRTCFGPLVGQQCSSLDVSDW--S
DKASLHIWKVIHNNV----------LEFCVVTTDENECNWMMFVCKARTGREQNLVAYPH
NGKIYFCTSREILPDHELLFYYSRDYARHIG-----VPEIPEAQ-------ICHRGKECA
SYTELKSSLNSHTHSH
>Branchiostoma_floridae_XP_035662480.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
FWCVSCEKA-----------------YPTVCTLHGV-PNMVQDTPIESHARMTLPRDLAL
QPSNIT---T----------S--GTGVFTRT--AIQARTQFGPLQGKIVKKSDVESE-S-
--DWTNMWEIFRDER----------SSHFIDARDENEANWMMFVKRARTSLEQNLVAHQC
GGDIFFTSCKDIAEGDELLMWFAGNYAKLTGRKTECVTSKPEQ-----SYKCCSCERQFA
DLGALGRHTKYAHPD-
>Saccoglossus_kowalevskii_XP_006821599.1_PRDM4_HUMAN_801_residues (PRDM4_HUMAN_801_residues)
LWCVDCECS-----------------HCGDCPQHGP-LNLIEDTPIESKARMSLPKLLRF
QKSMIS---N----------H--SVGVWTYE--SLGSRCQFGPLNGKIIKKNDETIP-QE
VLNSPMVWEIFIDGK----------SSHYIDGRDESESNWMIFVKRARRQSEQNLVAYQY
GNSIYFTTKHSIEPGKELLLWYNREYAKLIG-----VTEKPEE-----SYKCSKCEKQFA
DLSQLGRHMKYSHPD-
