>Asterias_rubens_XP_033642609.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
QQQHPVYI------------PEDVVLPPEFELRESCIVEAGLGVFSLVDIPVGERFGPFA
GVERL---AVKDTQCAWEVSSNSFSVFW-LSED----
>Owenia_fusiformis_CAH1775144.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
TEHPPVYI------------PEDIPIPDQFELRESTV-IFSLGVWTKFPISAGQKFGPFQ
GQFKA---KVDDPSAAWECGYQWHLVSVLVSKDNDAL
>Anneissia_japonica_XP_033113631.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
DNLSQEYI------------PEKITVPPRFELRESSLGNTGLGVFSLADVPIGEKFGPFK
GVERR---TITNSEFACKISGVFVSNQH-LLISSY--
>Styela_clava_XP_039265876.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
LRTRTCYL------------PEDCPITPSFEENSIETEN------KVCNTEMCEVWGPWI
GHDDCDAEC---KSFGNSTRF----RLCEKFAYT---
>Lucifuga_dentata_KAF7656484.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
IQYSNIYI-----------PQEDLTIPLDFELRESMAPGGGLGIWSCRKVNTGERFGPYM
GEHRP---CLRDPNQGWEVGIQ---------------
>Nezara_viridula_CAH1400110.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-WKMPRYLLIAN----RSSEDDRARPPAEVELRG------SAGIYARELIPQGARYGPFM
GKWVP---KPLDPSFAWEDSGIIISKMCIKKLENH--
>Tachyglossus_aculeatus_XP_038600482.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDDIPIPPEFELRESNIPGAGLGIWTKRKIEAGEKFGPYV
GEQRA---NLKDPSCGWERTSVTPQVFDSW-------
>Galemys_pyrenaicus_KAG8511486.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDDIPIPAEFELRESNMPGAGLGIWTKRKIEAGEKFGPYV
GEQRT---NLKDPSYGWEGPVIRTELLIEIF------
>XP_025863512.1 (best hit for PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDDIPIPAEFELRESNMPGAGLGIWTKRKIEAGEKFGPYV
GEQRS---NLKDPSYGWEILD----EFCNVKF-----
>Elysia_crispata_KAK3734610.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
LANHFLTL------------LEDLPVPDEFLLRPSQV-YPGMGVWSKAHIPAGQKFGPFQ
GILKP---SVEDPSCAWEVLSRST----LVNRLTQGI
>Lynx_pardinus_VFV27832.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDDIPIPAEFELRESNMPGAGLGIWTKRKIEAGEKFGPYV
GEQRS---NLKDPSYGWEILVVGIQQVCNASIESL--
>Gryllus_longicercus_KAK7790062.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
RLRAPRELLAAAAAAAAAAAGAAGAMPSELELR-----GAGGGVWARQRLARGARFGPYP
AGWGADA-ASADARYSWEVSSAPGEGRCREVS-----
>Lytechinus_pictus_XP_054768541.2_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
HTSPPVYI------------PEDVILPPEFELQESCIQEAGLGVFSLVDIPQGRKFGPFT
GVEKS---SVKDTQYAWEVRFESISLFD-AFVF----
>Chelonoidis_abingdonii_XP_032639551.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDNIPVPSEFELRESNVPGAGLGIWTKRKIEVGEKFGPYV
GEQQS---NLKDPIYGWEQVFFL--------------
>Rhincodon_typus_XP_048460432.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKAPIYI------------PDDIPIPPEFELRESSIPGAGLGIWTKRKLEAGEKLGPYV
GEELS---NLKDPSHGWEVSTYFNFSVFQMPIHVW--
>Elysia_marginata_GFS03378.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
LTNHFFTL------------LEDLPVPEVFLLRPSQV-YPGMGVWSKGHISAGQKFGPFQ
GVLKP---SVEDTSCAWEVSRTSRDE--WVNNVNKI-
>Python_bivittatus_XP_007434826.2_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
-YKVPIYI------------PDDIPIPSEFELRESNIPGAGLGIWTKRKIEVGERFGPYV
GEHQR---SLKNTNNGWETQETGLLLLLKLGKL----
>Ridgeia_piscesae_KAK2184004.1_PRDM3_HUMAN_169_residues (PRDM3_HUMAN_169_residues)
MSLNHLRL------------PAQMKIPSRVDLRKSTVDESILGVWSKRPFKKGEVFGPFM
GKKVMDATEDMDPSYVWEVSCPD--------------
