>Haliotis_rubra_XP_046577401.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SVSGGSMEEPWELTSLREEELEEFCVYIVHDRPCDSV------------------VGPNR
AQASLPRNLTLKPSAINPN--------------ELGVWSVDFIPRGTRFGPLVGQLFEKE
SKMNI-------------------------------------KKHCKHLWKV--------
---------FQ-HNEVKQFVVTSDPVFSNWMHYVQQTIPET-AGQHNSLACQLDSNIYFY
TVKSIPANSEIVVTYSREYAERITTPPVKDDMVS-
>Haliotis_rufescens_XP_048240122.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
------MEEPWELTSLREEELEEFCVYIVHDRPCESV------------------VGPNR
AQASLPRNLTLKPSAINPN--------------ELGVWSVDYIPRGTRFGPLVGQLFEKE
SKINI-------------------------------------KKHCKHLWKV--------
---------FQ-HNEVKQFVVTSDPVFSNWMHYVQQTVAET-AGQHNSLACQLDSNIYFY
TVKSIPANSEIVVTYSREYAERITTPPVKDDVMLS
>Saccostrea_echinata_XP_061195723.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
PRRFRNLEECWDSSNLKEDEFEEFCVYIVHDRACERV-------------------CPNR
AQASLPRNLTLKPSQNQVN-------------NGLGVWSLDYIPRGTRFGPLVGEVFSRE
PFSRK-------------------------------------DSDRISLWKV--------
---------FK-NNNVYQFLDNSDVTRSNWMHYTNFA--YT-AAQQNLIACQIDFNIYFY
TTKPIPPNTELMVWYCREYADRLNCPLTGEEMLQN
>Pecten_maximus_XP_033740387.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SEEPTNMEEGWDASNLKEDEFEEFCVYIVHDRACERV-------------------CQNR
AQASLPRNLTLKPSQSQSN-------------NALGVWSVDYIPRGTRFGPLVGDVYSKE
PFLRK-------------------------------------ESDRVSIWKI--------
---------FS-NNTVYQYIDNSDVTKSSWMHYINFA--YS-SVQQNLIACQIDFNIYFY
TIKPIPPNTELMVWYCREYADRINCPVTGEEMLHS
>Ylistrum_balloti_XP_060085595.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SEEPTNMEEGWDSSNLKEDEFEEFCVYIVHDRACERV-------------------CQNR
AQASLPRNLTLKPSQSQSN-------------NALGVWSVDYIPRGTRFGPLVGDVYSKE
PFLRK-------------------------------------ESDRVSIWKI--------
---------FS-NNTVYQYIDNSDVTKSSWMHYINFA--YS-SVQQNLIACQIDFNIYFY
TIKPIPPNTELMVWYCREYADRINCPITGEEMLQS
>Potamilus_streckersoni_KAK3578850.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
RILADGMDENWDMTNLKEEEFEEFCVYIVHDRVCDRV-------------------CPNR
AQASLPRNLTLKLSQAQPN-------------NGQGVWSVDYIPRGTRFGPLVGEVFTKE
PLRRN-------------------------------------DTERIVLWKI--------
---------FK-NNHVCQFIDNSDTDRSNWMHYVHFA--YS-SSQQNVIACQIDFNIYFY
TIKPILPNTEILIWYCREYAERLNFPHTGEEMLQS
>Mya_arenaria_XP_052811933.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
QMLLDSLEDGWDMTQLKEDEFEEFCVYIVHDRACEKV-------------------CRNR
AQASLPRNLTLKPSLTQPD-------------NAQGVWSVDYIPRGTRFGPLNGIITPEE
PVRRG-------------------------------------DTNRICLWKI--------
---------FK-DNRTCKYMDVGDTSRSNWMHYVNFS--YN-SNQQNLIACQIDFNIYFY
TIKPIPPNTELLVWYCREYAERLNVPKTGEEMLQA
>Dreissena_polymorpha_XP_052237091.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
QMLLDSLEDGWDMTQLKEEEFEEFCVYIVHDRACEKV-------------------CRNR
AQASLPRNLTLKPSLTQPD-------------QAQGVWSVDYIPRGTRFGPLNGEISLEE
PPRHA-------------------------------------DSSRICLWKI--------
---------FK-DNTTCKYMDVGDTSRSNWMHYVNFS--YN-SSQQNLIACQIDFNIYFY
TIKPIPPNTELLVWYCREYAERLNVPKTGEEMLQA
>Mercenaria_mercenaria_XP_045195577.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
DDSQYSLEDGWDMTQLKEEEFEEFCVYIVHDRACEKV-------------------CRNR
AQASLPRNLTLKPSLTQPD-------------HAQGVWSVDYIPRGTRFGPLNGEITKEE
PLRRG-------------------------------------DTNRICLWKI--------
---------FK-DNKVCEFMDVGDTSHSNWMHYVNFS--YN-SGQQNVIACQIDYNIYFY
TIKPIPPNTELLVWYCREYAERLNVPRTGEEMLQA
>Ruditapes_philippinarum_XP_060556527.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
------------MTQLKEEEFEEFCVYIVHDRACEKV-------------------CRNR
AQASLPRNLTLKPSLTQPD-------------HAQGVWSVDYIPRGTRFGPLNGEITKEE
PLRRG-------------------------------------DTNRICLWKI--------
---------FK-DNKVCEFMDVGDTSRSNWMHYVNFS--YN-SGQQNVIACQIDYNIYFY
TIKPIPPNTELLVWYCREYAERLNVPRTGEEMLQA
>Physella_acuta_XP_059175025.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SLPKHAMEGGWEFAKLNDEEFEEFCVYIVQDRSCDP-------------------VCHNR
AQASLPRNLTLRPSTICPN--------------TVGVWSSDHIPRGTRFGPLVGEKVGPS
VQVDK--------------------------------------FHPKFHWQI--------
---------YK-DGALDHVVQITDPDRCSWQHFMNLA--PS-EQEQNVIACQHGAHIYFY
TVRPIQPNTELLFWFSLEYSDRLKSSPSVAEKYLP
>Biomphalaria_pfeifferi_KAK0040563.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----AMEEGWDFRQLNDEEFEEFCVYIVQDRPCEP-------------------VCHNR
AQASLPRNLTFRPSIICQN--------------SVGVWSSEHIPRGTRFGPLFGEKLDRR
STTEQ--------------------------------------FHPKYIWQV--------
---------YK-EGVLDYMIQITDPDRSSWQLFMNLA--PS-DREQNVVACQHGTHIYFY
TVKPIEANTELLFWFSQEYSERVKCPSSVGENRRA
>Aplysia_californica_XP_012935412.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EAVADVMESGWDFTQLSDEDFEEFCVYIVHDRPCEP-------------------LSHNR
AQASLPRNLTLRPSLICPN--------------NIGVWSSDHIPRGTRFGPLTGELFPSN
STPDH--------------------------------------FHPKFHWKV--------
---------YK-DGRLDHVIQTTDPERSSWQHFLNVS--PS-QQHQNLVACQHGEHIYFY
TVRPVEAHSELLFWFSREYADRVACPCRPVDLSRY
>Octopus_sinensis_XP_029640101.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
KGMATDIDDAWDISNLKEQDFEEFCVCIVHDRQFEEE-------------------HPNR
AQASLPRNLTLKESYTMPE--------------ELGVWSVDYIPRGTRFGPLIGDIIGSS
EYVYD-------------------------------------IRDLKKIWRI--------
---------YK-HG-VQQSVDVSRESHSNWMRYVNFA--FS-TRQQNLVACQIGTDIYFY
TIKTVPPDTELLVWFCEDYGERIHRSMCSSLMIRG
>Caenorhabditis_elegans_NP_001251371.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
VSASGARNVETDWKQSGDENLAELCIFHVPDKSVSLP------------------NPK-R
AECTLPMNLILKSSSKNRK--------------KSSIWSSDHIPRGVRFGPLVGEIRLVD
VDTALVCPAEASMAGGG------------------PAQEDVPFDEAPEEWKIYS------
---------PS-GGRLNKTICVKDDARSNWMKYVAAA--EE-EDFQNLVAAQIGNDIYFY
TVKKIEANTELSFWFSRDYARKLNYSTRPYVRVRR
>Aphelenchoides_besseyi_KAI6208230.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
NSNAISSTNEWERKELSDRTLDNLCVFHVPDKPLKLQ------------------DPENC
ATSSIPLNLALKPSGVYHG--------------ETGVWTVSFIPAYSRFGPISGKSYPPT
VNESMLTPAEALTPTNGNMIVGGALDVPINSTQSNAIRDRRQTTVNPQRWRIFS------
---------KS-GARVEKIIDTSNPKKSNWMCFVKLA--QK-QESQNLIACQIDGEMYFY
SIKSINPNTELLVWYSRDYAQRIQMPANCEFWRQN
>Toxocara_canis_KHN72632.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-RSGMHGMSEWDWTSMSEHNFAELCVFHVPDKPIEHQ------------------DPNNR
SATSLPLNLTIRSSQEIPK--------------TMGVWSMDYIPRGVRFGPLVGEYRKPD
ITEATVCPAEASGAGAPS---GGHAH----LSGAGHAQSGPGTFKWDHIWKVFS------
---------SS-GSILVKMIDAKNDKKSNWMKFVNPA--KS-KDTQNLVACQVENEIYFY
SVKPIKPNTELLYWYSRDYAQRINCPASCEYWAAL
>Lingula_anatina_XP_023933713.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
------MGEDLDLLSLPEEEYEKRCVYIVPDQPCDR-------------------DLPNR
AEASLPRNLVLKPSQIFTD--------------VVGVWSTDYIPKGTRFGPLVGEIFTKD
SIPRT--------------------------------------AEKKFLWQV--------
---------HH-NHDLYLYVNIFDPKKSNWLRYVNSA--PS-KQAQNIVVCQVDHAIYFY
TVRPIPPDSELLFWYCQEFAERLNIPPAEEIYKY-
>Stegodyphus_dumicola_XP_035220762.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MEDAGSWDLSTIREEDFDQLAVYLVRDQPCEE-------------------DCLNR
AEASLPRNLILKASPSL-------------GGDVQGIWSTDYIPRGTRFGPLVGHVYRQD
EVPPE--------------------------------------ANRKFFWRV--------
---------YS-SPDDFYYIDCLDVKKSNWMRYVNPA--YS-TEGQTLVACQIKQQIYFY
TCRPVLPNEELTVWYCKEFAQRLGYPLTGELMLLR
>Nephila_pilipes_GFT22779.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MEDAGSWDLSAIREETFDELAVYLVRDQPCEE-------------------DCLNR
AEASLPRNLVLKASPSL-------------GGDVQGIWSTDYIPRGTRFGPLVGEIYRQD
EVPPE--------------------------------------ANRKFFWRV--------
---------YS-STEDFYYIDCLDVKKSNWMRYVNPA--YS-TKGQTLVACQIKRQIYFY
TCRPVLPDEELTVWYCKEFAQRLGYPLTGELMLKR
>Caerostris_extrusa_GIX89230.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MEDAGSWDLSAIPEEKFDELAVYLVRDQPCED-------------------DCPNR
AEASLPRNLVLKDSLPWMAIIGDLCEAFDKTCHVQGIWSTDFIPRGTRFGPLVGEIYRQD
EVPPE--------------------------------------ANRKFFWRV--------
---------YC-SEEDFYYIDCLDVKKSNWMRYVNPA--YS-TKAQTLVACQIKRQIYFY
TCRTVLPDEELTVWYCKSSLSVWDIR---------
>Caerostris_darwini_GIY29164.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MEDAGSWDLSAIPEEKFDELAVYLVRDQPCDD-------------------DCPNR
AEASLPRNLVLKDSPSL-------------GGNVQGIWSTDFIPRGTRFGPLVGEIYRQD
EVPPE--------------------------------------ANRKFFWRV--------
---------YC-SEEDFYYIDCLDVKKSNWMRYVNPA--YS-TKAQTLVACQIKRQIYFY
TCRTVLPDEELTVWYCKEFAQRLGYPLTGELMLKR
>Oppia_nitens_XP_054164083.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----MEDVVWDLSSIAEEDFDQLAVYLVPDQPCDDTTHK---------------SATNR
SEASLPRNLILKPSQTLND--------------VLGVWSTDYIPRGTRFGPLVGEIYDKD
EVPKD--------------------------------------ANRKYFWRV--------
---------YT-GADSYHYIDGFDASKANWMRYVNPA--YS-NQSQNLVACQVKQNIYFY
TIKPVLPNQELLVWYCKEFAERLNYPLTGEQMLIK
>Varroa_destructor_XP_022647630.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MEAPLTESGAMDLSKIREEDFEQLAVYLVPDRPVDEQDGDHNST--G--RQDREQTAKNR
AVSSLPRNLVLKPSQTLPG--------------VLGVWSTDYIPRGTRFGPLIGERYERD
AVPPD--------------------------------------ANRKYFWRVYSSASAED
G---------S-HCSDYHYIDGFDVTKANWMRYVSPA--YS-SAKQNLVACQLRGKIYFY
TLRAVMPGQELLVWYCREFAQRLNYPETGELMLQR
>Ixodes_persulcatus_KAG0421776.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--VHMMEDGSVDLSSLREEDFEQLAVYQVRDQPCEEG-------------------QTNR
AEASLPRNLLLKPSQTLSD--------------VLGVWSTDYIPRGTRFGPLTGEIYQKD
AVPAN--------------------------------------ANRKYFWRV--------
---------YD-GSESFYYVDGFDVSKANWMRYVNPA--YS-SENQNLVACQVKQDIYFY
TIKPIYPNQELLVWYCREFAERLSYPVTGELMLQR
>Dermacentor_andersoni_XP_054922558.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MMEDGSLDLSSLRESDFEQLAVYQVRDQACEEG-------------------LSNR
AEASLPRNLLLKPSQTLSD--------------VLGVWSTDYIPRGTRFGPLMGDVYRKD
EVPAN--------------------------------------ANRKYFWRV--------
---------YD-GPDSFHYVDGFDVSKANWMRYVNPA--YS-SENQNLVACQVKQDIYFY
TVKPIYPNQELLVWYCREFAERLSYPVTGELMLQR
>Dermacentor_silvarum_XP_037579901.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MMEDGSLDLSSLRESDFEQLAVYQVRDQACEEG-------------------LSNR
AEASLPRNLLLKPSQTLSD--------------VLGVWSTDYIPRGTRFGPLMGEVYRKD
EVPAN--------------------------------------ANRKYFWRV--------
---------YD-GPDSFHYVDGFDVSKANWMRYVNPA--YS-SENQNLVACQVKQDIYFY
TVKPIYPNQELLVWYCREFAERLSYPVTGELMLQR
>Rhipicephalus_microplus_XP_037281403.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MMEDGSLDLSSLRESDFEQLAVYQVRDQVCEEG-------------------LSNR
AEASLPRNLLLKPSQTLSD--------------VLGVWSTDYIPRGTRFGPLMGDVYRKD
EVPAN--------------------------------------ANRKYFWRV--------
---------YD-GPDSFHYVDGFDVSKANWMRYVNPA--YS-SENQNLVACQVKQDIYFY
TIKPIYPNQELLVWYCREFAERLSYPVTGELMLQR
>Rhipicephalus_sanguineus_XP_037519439.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MMEDGSLDLSSLRESDFEQLAVYQVRDQTCEEG-------------------LSNR
AEASLPRNLLLKPSQTLSD--------------VLGVWSTDYIPRGTRFGPLMGDVYRKD
EVPAN--------------------------------------ANRKYFWRV--------
---------YD-GPDSFHYVDGFDVSKANWMRYVNPA--YS-SENQNLVACQVKQDIYFY
TIKPIYPNQELLVWYCREFAERLSYPITGELMLQR
>Chelonus_insularis_XP_034950616.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----MEPSEWDHATLREEEFEQHAVYFVRDVAASA-------------------NESNR
AEASLPRNLVLKQSQALND--------------VLGVWSTGYIPKGTRFGPLVGQVYKKD
SVPVD--------------------------------------ANRKYFWRI--------
---------YK-NNELFYYIDGYDIQKSNWMRYVNPA--YS-SESQNLIACQYDMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Atta_colombica_XP_018054150.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----MEASEWDHATLREEEFEQHAVYLVPDVSASP-------------------GDTNR
AESSLPRNLVLKPSQALNDVCSFAKQNSSRNLSVLGVWSTSYIPKGTRFGPLVGQVYTKD
SVPAD--------------------------------------ANRKYFWRV--------
---------YK-NNELFYYIDGYDVQKSNWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPHQELLVWYCREFAERLNYPLTGELMLQR
>Bombus_terrestris_XP_048265206.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----MEASEWDHATLREEEFEQHAVYLVPDVAASP-------------------GDTNR
AEASLPRNLVLKPSQALNDVRSSAKESFLETSSVLGVWSTSYIPKGTRFGPLVGQVYTKD
SVPAD--------------------------------------ANRKYFWRV--------
---------YK-NNELFYYIDGYDVQKSNWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Cotesia_glomerata_XP_044576638.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-----MEASEWDHATLREEEFELHAVYLVPDVSTSA-------------------NESNR
AEASLPRNLVLKQSQALND--------------VLGVWSTSYIPKGTRFGPLVGQQYTKD
SVPVD--------------------------------------ANRKYFWRV--------
---------YK-NNELFYYIDGYDIQKSNWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPFTGELMLQR
>Ladona_fulva_KAG8233359.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
LGVSAMEESPWDVWSIREEEFEEHVVYIVPDQPVPSSSTKRVEAEEGGKDEEDDGGVPSR
AEASLPRNLVLRPSQALSDQK----VTQSECFQIQGVWSTSYIPKGTRFGPLVGEIYTTD
NVPKT--------------------------------------ANRKYFWRV--------
---------YK-DNELFYYIDGYDVRKSNWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIRPILPNQELLVWYCKEFAQRLNYPLTGELMLQR
>Halyomorpha_halys_XP_066909050.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
------EEEDWDPATTREEEFEKHAVYLVLDQAPPP-------------------GAPNR
AEASLPRNLVLRPSQALSD--------------VMGVWSTSYIPRGTRFGPLVGEVYAKN
EVPST--------------------------------------ANRKYFWRVQIKKDVG-
--L--LSKVYK-ENQLFYYIDGYDVSKSNWMRYVNPA--YS-SESQNLIACQYKMSIYFY
TIRPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Nezara_viridula_CAH1388590.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
------EEEEWDPATTREEEFEKHAVYLVLDQAPPP-------------------GAPNR
AEASLPRNLVLRPSQALSD--------------VMGVWSTSYIPRGTRFGPLVGEVYAKN
EVPST--------------------------------------ANRKYFWR---------
--------VYK-ENQLFYYIDGYDICKSNWMRYVNPA--YS-SESQNLIACQYKMSIYFY
TIRPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Nilaparvata_lugens_XP_039293933.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---DDGVGVIWDLSSIKEEEFEKHVVYIVPDLPSPQ-------------------DCPNK
AETSLPRNLVLKPSQALSD--------------VLGVWSTSYIPRGTRFGPLVGEVYAKD
AVPNT--------------------------------------ANRKYFWRV--------
---------YK-DNQLFYYIDGYDVAKSNWMRYVNPA--YS-SESQNLIACQYKMDIYFY
TIRPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Thrips_palmi_XP_034238123.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
HGGGRPSSPEWDPALLREEDFEDQAVYQVPDQPCEGL--------------------QPR
AQASLPRNLVLKPSQALSD--------------VLGVWSTGYIPRGTRFGPLVGDIYAKD
AVPAT--------------------------------------ANRKYFWRVQLKEERKT
G-R--IRKIYK-EDELFYYIDGYDVNKSNWMRFVNPA--YS-SVSQNLIACQYKMNIYFY
TIRPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Frankliniella_occidentalis_XP_052133338.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-GGGRAGTPDWDPATLREEDFEEQVVYHVPDQPCDAQPCD-------------GPAALPR
AQASLPRNLVLKPSQALSD--------------VLGVWSTGYIPRGTRFGPLVGDIYAKD
AVPAT--------------------------------------ANRKYFWR---------
--------IYK-EDELFYYIDGYDVNKSNWMRFVNPA--YS-SASQNLIACQYKMNIYFY
TIRPILPNQELLVWYCREFAQRLNYPLTGELMLQR
>Frankliniella_fusca_KAK3926785.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-GGGRAGTPDWDPATLREEDFEEQVVYHVPDQPCDAQSCD-------------GPAALPR
AHASLPRNLVLKPSQALSD--------------VLGVWSTGYIPRGTRFGPLVGDIYAKD
AVPAT--------------------------------------ANRKYFWRVQIKEEPRN
R-R--IRKIYK-EDELFYYIDGYDVNKSNWMRFVNPA--YS-SASQNLIACQYKMNIYFY
TIRPILPNQELLVWYCREFAQRLNYPLTGELMLQR
>Daphnia_magna_XP_045027579.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
NQGTKMEEGAWDLAELAEEDFEQLAVYIVPDAVVEPSSSNA-------------SERVNR
AETSLPRNLTLKPSQALSD--------------VLGVWSSDYIPRGTRFGPLVGDIYAKD
HVPKH--------------------------------------ANRKYFWRV--------
---------YN-NSEVFYYIDGYDTAKANWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TTKPILPNQELLVWYCKEFAERLNYPVTGDLMLQR
>Penaeus_vannamei_XP_027228170.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--MPATMSGDWDIEAIKEEEWEERAVYLVPDTPTEE-------------------TCENH
ATLSLPRNLVLKPSQTLSD--------------VMGIWSTDYIPRGTRFGPLVGKCYAKD
EVPKT--------------------------------------ANRKYFWRV--------
---------YK-ENELYYYIDGYDTTRANWMRYVNPA--YS-SEAQNLIACQYKTNIYFY
TIKPILPNQELLVWYCKEFATRLNYPLTGELMLQK
>Penaeus_chinensis_XP_047491141.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--MPATMSGDWDIEAIKEEEWEERAVYLVPDTPTEE-------------------ACENH
ATLSLPRNLVLKPSQTLSD--------------VMGIWSTDYIPRGTRFGPLVGKCYAKD
EVPKT--------------------------------------ANRKYFWRV--------
---------YK-ENELYYYIDGYDTTRANWMRYVNPA--YS-SEAQNLIACQYKTNIYFY
TIKPILPNQELLVWYCKEFATRLNYPLTGELMLQK
>Leptinotarsa_decemlineata_XP_023026060.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VVPSRGVDLLNIREEEFQHHVSYIALDCHVEP-------------------GTPNR
AERTLPRNLVLRTSQVLPH--------------SKGVWSTDFIPQGTRYGPLVGEIYAKD
AIPAS--------------------------------------SSRNYFWRVQLREGFYK
N-RCNDHEIYK-DNELYYYIDGFDTSKANWMRYVSPP--SS-IDSQNLIAYQHEMNIYFY
TIKPIEPNQELLVWYCKEFAERLNYPVSSEQMLQR
>Gonioctena_quinquepunctata_KAG5883139.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VTSASEFDLTNIHEEEFELHSTYIVPDLPVDP-------------------GTPNR
AEATLPRNLVLKSSQVLLN--------------TQGVWSTGYIPRGTRFGPLVGEIYAKD
AIPNS--------------------------------------ANRNYFWRVQLREGFYK
N-RCIDNKIYK-DNELYYYIDGFDTSKANWMRYVSPA--YS-TESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGEQMLQR
>Tenebrio_molitor_XP_068903717.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VTSASEYDLANIHEEEFELHTTYIVPDLPVEP-------------------GTPNR
AEATLPRNLVLKTSQALSD--------------AQGVWSTGYIPRGTRFGPLVGEIYAKD
AVPSS--------------------------------------ANRKYFWR---------
--------IYK-DNELYYYIDGYDTSKANWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGEQMLQR
>Anoplophora_glabripennis_XP_018563212.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VTSASEFDLANIREEEFELHTTYIVPDLPVEP-------------------GTPNR
AEATLPRNLVLKSSQALSD--------------AQGVWSTGYIPRGTRFGPLVGEIYAKD
AVPSS--------------------------------------ANRKYFWRVQLREGFYR
N-SCLDNKIYK-DNELYYYIDGFDTSKANWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGEQMLQR
>Aromia_moschata_KAJ8948399.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VSSATEFDLANIAEEEFELHTTYIVPDLPVEP-------------------GTPNR
AEATLPRNLVLKSSQALSD--------------AQGVWSTGYIPRGTRFGPLVGEIYAKD
AVPSS--------------------------------------ANRKYFWRVQLREGFYR
N-SGVDNKIYK-DNELYYYIDGFDTSKANWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGEQMLQR
>Brassicogethes_aeneus_CAH0556950.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----VSSASEFDPANLLEEQFECHTTYIVPDLPVEP-------------------GTPNR
AEATLPRNLVLKPSEALSD--------------AQGVWSTGYIPRGTRFGPLVGEIYAKD
AVPST--------------------------------------ANRKYFWRVQLREGFYR
N-NM-PDKIYK-DNELYYYIDGFDTSKANWMRYVNPA--YS-SESQNLIACQYKMNIYFY
TIKPILPNQELLVWYCKEFAERLNYPLTGEQMLQR
>Zootermopsis_nevadensis_XP_021933986.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--PPTDTDGGWDLSAMREDDFEQHVVYIVPDLPTEA-------------------GCPNR
AESSLPRNLVLKPSQALSD--------------VQGVWSTGYIPTGTRFGPLVGEVYAKD
SVPDT--------------------------------------ANRKYFWRVQIKEEPR-
--Q--WPKVYK-DNELFYYMDGYDTSKSNWMRYVNPA--YS-SASQNLIACQYKMNIYFY
TIKPILPNQELLVWYCREFAERLNYPLTGELMLQR
>Aphis_glycines_KAE9532581.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ETPPMESDLPFDFNSIKEEEFDKFVDYIVLDQPADP-------------------NNPNR
AESSLPRNLKLKKIGK----------------KITGVKSAIYIPLGTRFGPLVGEVCVKE
HAPN---------------------------------------GKRKYFWRVQLMLAQDN
FWRKMRQQIYK-ENKPFYYINTYDETKSNWMRYVSAP--YS-PQSQNLIACQCGTDIFFY
TIRPIFPNEELLVWYCREFAERLNYPSSVEQMIQR
>Owenia_fusiformis_CAH1799814.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
TKVKGDALEDWDEKKICEKDFDKVCTYIVPDRPCQD-------------------GRSDR
AEASLPRNLLLKPSKTLPN--------------VMGVYSSEHIPRGTRFGPLVGEIFTKD
NVPTH--------------------------------------TSRQYFWRV--------
---------YN-NDELYFYIDGASCSKSNWMRYVNPA--HS-QGEQNLIACQVNFDIYFY
TIKAVAPGAELLVWYCDEFSARLGKSLSPVQLNIP
>Asterias_rubens_XP_033635571.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--KMGCEDDNTEWVDLDEAEYQMKCIYVVGDKPCEDDA------------------EESR
AAASLPGNLNYIQRD--EQ--------------IVGVGAIGYIPKGTRFGPLVGQIYREE
EVPRD--------------------------------------ANRKYFWRI--------
---------YK-NQKFIHYIDGFDPQKSNWMRHVNPA--NS-ACDQNLVACQFDTDIYFY
TVKPIRQGTELLVWYCTEFQRRLEQPVIMQAVTE-
>Patiria_miniata_XP_038077827.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MGCDDDTNSWLDLEEAEYQTKCIYVVNDKPCQGEP------------------DECR
AAASLPANLKYVERD--GQ--------------IVGVVARDYIPQGTRFGPLIGQIYREE
EVPRE--------------------------------------ANRKYFWRI--------
---------YK-AQKFIHYIDGFDPHKSNWMRHVNPA--NS-ACDQNLVACQYDTDIYFY
TVKPIRQGTELLVWYCKEFQRRLEQPVAMETAAGD
>Acanthaster_planci_XP_022108986.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MGCEDDSNGWLDLEEAEYQSKCIYVVNDKPCEGDP------------------DGCR
AAASLPANLKYIERD--GQ--------------IVGVIAGDYIPRGTRFGPLVGQIYREE
EVPRE--------------------------------------ANRKYFWRI--------
---------YK-AQKFIHYIDGFDPHKSNWMRHVNPA--NS-ACDQNLVACQYDTDIYFY
TVKPIREGTELLVWYCKEFQRRLEQPVVMEMGTAE
>Anneissia_japonica_XP_033117979.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MGAAEGES-SSCLAEEDYQKMCVYMVKDRTTEIGV------------------GEDL
SIASLPPNLVLKANDS-EE--------------TIGVFSREYIPVGTRFGPLTGQIYRPE
EVPHD--------------------------------------AEIAYFWRI--------
---------YN-RNTLVHFIDGFDPVKSNWMRHVQPA--PNMSPLQNVVACQHGTEIFFY
TTRSIPEGEQLFVWYCQEFSERLKWKIPSPPKSSS
>Holothuria_leucospilota_KAJ8026498.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MGYEQSETPWNDLEESEYEKRTIYVVPDRRPESAQ---------------KGETTPT
SISSLPRNLKFRSREGDDL--------------ITGVVAAEHIPRGCKFGPLTGKIYRPE
EVPLD--------------------------------------AEMKYFWRI--------
---------YK-ADKFIHYIDGFDCEMSNWMRHIRPA--HG-QMEQNLVACQSGTDIFFY
TIRPITRGEELLVWYCREFAKRLELPITDELHGRE
>Strongylocentrotus_purpuratus_NP_999739.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MGCNDNAV-PSDMTEVDYQKKCIYEVKDPERDPAS------------------TEPR
SVTSLPGNLRFKRRN--EQ--------------VVGVLADEYIPKGTRFGPLAGKIYREE
EVPED--------------------------------------ANKKYFWRI--------
---------YN-GQKFVHYIDGFNKKRSNWMQYVSPA--GA-SAEQNIVACQYKTDIFFY
TTKAVEPGQELFVWYCTEFAKRLEKPVVASR-ASP
>Lytechinus_variegatus_XP_041463104.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--VMGCNDNAV-STGMSEVDYQKKCIYEVKDQDSDPAS------------------KEPR
SVTSLPGNLKFKYRN--EQ--------------VVGVLADQYIPKGTRFGPLAGKIYREE
EVPSD--------------------------------------ANKKYFWRI--------
---------YN-VQKFVHYIDGFDKKRSNWMQYVSPA--GA-SAEQNLVACQYKTDIFYY
TTKAVEPGQELFVWYCTEFAQRLEKPVASALRASP
>Lytechinus_pictus_XP_054753258.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--VMGCNDNAV-STDMSEVDYQKKCIYEVKDQDADPAS------------------REPR
SVTSLPGNLKFKYRN--EQ--------------VVGVLADQYIPKGTRFGPLAGKIYREE
EVPGD--------------------------------------ANKKYFWRI--------
---------YN-VQKFVHYIDGFDKKRSNWMQYVSPA--GA-SAEQNLVACQYKTDIFFY
TTKAVEPGQELFVWYCTEFAQRLEKPVASSLRTSP
>Branchiostoma_floridae_XP_035687581.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MRG---TTMTEDVLRWNEEDFVKNSTYLVVDQEWEE-----------------EGSQQPR
AEGTLPRNLYLKYNDQ---------------NEVLGVCSKEYIPQGTRFGPLVGQVYCRD
EVPKG--------------------------------------ANRKYFWRV--------
---------YD-GEEFQFYVDGYDITKSNWMRYVNPA--HS-GEEQNLVACQHDMKIYFF
TIKPVLPDTELLVWYCREFAERLNYPPSGELMMQR
>Branchiostoma_belcheri_XP_019639161.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MRG---TTMTEDVLRWNEEDFVKNSTYLVVDQEWEE-----------------EGSQQPR
AEGTLPRNLYLKYNEQ---------------NEVLGVCSKEYIPQGTRFGPLVGQVYRRD
EVPKG--------------------------------------ANRKYFWRV--------
---------YD-GEEFQFYVDGYDTTKSNWMRYVNPA--HS-GEEQNLVACQHDMKIYFF
TIKPVLPDTELLVWYCREFAERLNYPPSGELMMQR
>Saccoglossus_kowalevskii_XP_006811492.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
NKAK--MAREINWKDLAEDEYKSKSIYIVYDQPFDEKTE----------------ERNSR
AEESLPQNLHFNKTDDQSE--------------IIGVYSNDFIPQGTRFGPLIGKKYNKD
EVKNG--------------------------------------ANRKYFWRI--------
---------YK-DKEFEFYIDGLDVNESNWMRYVNPA--HT-SDQQNLVACQNGMEVYFY
TIKPIEKNAELLVWYCKEFAERLNYPPTGELMMQK
>Petromyzon_marinus_XP_032828624.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
LEGEEEEEEDGAAAGRSEQELQDTCTYIVQDQPWPGPL----------------PGAAPR
AEATLPRNLRFHVSHT---------------GQIIGVLSSEYIPEGTRFGPLVGDIYTED
AVPKE--------------------------------------ANRQYFWRI--------
---------YR-HGELQHFVDGWDVSRSNWMRFVNPA--RS-RREQNLVACQHGADVFFY
TLRGVSPGRELLVWYSPEYTRRMGQAHHRLQDLLD
>Oncorhynchus_gorbuscha_XP_046183570.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
----MKLETAPDMSEWQEDDFALNCTYIVPDQMSAPS------------------IGLPK
AMMSIPRNLTFEYNTE---------------NEVTGVFSKEYIPQGTRFGPLQGDIYNKD
NVPKQ--------------------------------------ANRKYFWRI--------
---------YN-RGRLYHFIDGYDVRSSNWMRYVNPA--RS-LSEQNLVACQNGRDVYFY
TIRPVEANQELLVWYSQEFAGRLCSQPGDELKQKH
>Amblyraja_radiata_XP_032900950.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MRMKAEVSDMSQWREVDLEEKCTYVVHDQARDLSKST----------------EIPW
ARASIPRNLTFKYAN-ANE-------------QVIGVLSKEYIPQGTRFGPLVGDIYTKD
NVPKN--------------------------------------ISRKYFWRV--------
---------YS-SGRLHHFLDGYSECKSNWMRYVNPA--HS-AAEQNLAACQNGTDIYFY
TVKPIPSSDELLVWYSREFAERLNYPPTGDMVMLK
>Scyliorhinus_canicula_XP_038655179.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDVEDVDMTQWTEAEFEENRTYIVNDQFWEPTTDR----------------EPTQ
AQASLPRNLKFKYAR-DSN-------------EVLGVMSAEYIPKGTRFGPLVGEIYTND
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGDLHHFIDGFDESKSNWMRYVNPA--HS-KQEQCLAACQNEMDIYFY
TVKPIPANEELLVWYSREFAERLHYPTSGDLMMIK
>Hypanus_sabinus_XP_059839010.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEDVDMTQWTEAEFEENCTYIVNDQTWDPTADD----------------CLTH
AQATLPRNLKFKFAH-GGS-------------EVIGVLSAEYIPKGTRFGPLVGEIYTSE
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGDLHHFVDGFDESKSNWMRYVNPT--RS-KQEQCLAACQNGMDIYFY
TVKPILANEELLVWYSSEFAERLHYPGSDDLMMIK
>Mobula_hypostoma_XP_062929182.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MKVMKMDMEDVDMTKWTEAEFEENCTYIVNDQTWDPTTDD----------------CLSH
AQATLPRNLKFKYAH-GSS-------------EVIGVLSAEYIPKGTRFGPLVGEVYTNE
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGDLHHFVDGFDESKSNWMRYVNPT--RS-KQEQCLAACQNGMDIYFY
TVKPILANEELLVWYSSEFAERLHYPGSDDLMMIK
>Rhincodon_typus_XP_020389389.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDVEDVDMTQWTEAEFEENCTYIVNDQSWEPTTDS----------------DLTH
AQASLPRNLKFKYAC-HSN-------------EVLGVMSAEYIPKGTRFGPLVGEIYTIE
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGNLHHFVDGFDESKSNWMRYVNPA--HW-KQEQCLAACQNGMDIYFY
TVKPIPANEELLVWYSSEFAERLKIPASRDLQMTK
>Chiloscyllium_plagiosum_XP_043542974.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDVEDVDMTQWTEAEFEENCTYIVNDQSWEPMVNS----------------DLTH
AQASLPRNLKFKYAS-HSN-------------EVLGVMSAEYIPKGTRFGPLVGEIYTNE
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGDLHHFVDGFDESKSNWMRYVNPA--HS-KQEQCLAACQNGMDIYFY
TVKPIPANEELLVWYSSEFAERLHYPASGDLQMTK
>Carcharodon_carcharias_XP_041044769.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDVEDVDMTQWTEAEFEENCTYIVNDQSWEPTTDH----------------DPTH
AQASLPRNLKFKNAR-NSE-------------EVLGVMSAEYIPKGTRFGPLVGEIYTND
TVPKN--------------------------------------ANRKYFWRV--------
---------YS-NGDLHHFIDGFDESKSNWMRYVNPA--HS-KQEQCLAACQNGMDIYFY
TVKAIPANEELLVWYSSEFAERLHYPASGDLMMIK
>Huso_huso_KAK6489378.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ESTMKLNMEGADMTKWTEAEFEEKCTYIVNDYTWEPSTDG-----------G----NCVK
AEASLPRNLMFKHAP-NPK-------------EVIGVLSREYIPKGTRFGPLVGEAYTVD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGEFHHFIDGFNEEKSNWMRYVNPA--HS-QQEQNLAACQNGTNIYFY
TVKPIPANQELLVWYCPEFAERLHYPPSGELMMMK
>Polyodon_spathula_XP_041107188.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ESTMKLNMEGADMTKWTEAEFEEKCTYIVNDYTWEPSTDG-----------G----NCVK
AEASLPRNLTFKHAP-NSK-------------EVIGVLSREYIPKGTRFGPLVGEAYTAD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGEFHHFIDGFNEEKSNWMRYVNPA--HS-QQEQNLAACQNGTNIYFY
TVKPIPANQELLVWYCPEFAERLHYPPSGELMMMK
>Amia_calva_XP_066558000.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EFTMKMDMEDADMTKWTEAEFEEKCTYIVKDHLWEASPDS-----------G----DLTQ
AEASLPRNLLFKHVP-NTK-------------EVIGVASKEYIPKGTRFGPLVGEMYTTE
TVPKN--------------------------------------ANRKYFWRI--------
---------YSSNGEFHHFVDGFNEEKSNWMRYVNPA--HS-QQEQNLAACQNGKNIYFY
TVKPIPANQELLVWYCPEFAERLHYPPSGELMMLK
>Gymnothorax_javanicus_KAJ8290880.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
HIEVKMDVEEADMTKWTEAEFEEKCTYIVKDHPLEGCSEN-----------S----ELTR
AEASLPRNLAFKHPP-GSK-------------EVIGVVSREYIPKGTRFGPLVGENYTAG
TVPKD--------------------------------------ANKKYFWRI--------
---------YS-EGKFHHFVDGINEQKSNWMRYVNPA--HS-QQEQNLAACQNGMNIYFY
TVKPIPANQELLVWYCPEFAERLDYPPSGELMMQR
>Brienomyrus_brachyistius_XP_048882800.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
RVTTAADVQDADMTTWTEAEFEEKCTYIVYDSSMEGSPDS-----------T----TLTR
AEASLPRNLLFRHPA-GST-------------EVIGVESKEYIPKGTRFGPLVGQCYTAE
TVPKD--------------------------------------ANRKYFWRI--------
---------YS-KGEFHHFVDGLDEDKSNWMRYVNPA--HT-QQEQNLAACQSGMNIYFY
TIKPILPHEELLVWYCPEFAQRLNYPPSGELMMQK
>Megalops_cyprinoides_XP_036394994.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
HIAVKMDVQDADMTKWTEAEFEEKCTYIVKDHPWEGGPEN-----------G----ELTR
AEASLPRNLVFKHNP-NSK-------------EVIGVASREYIPKGTRFGPLVGEIYTAE
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-EGEFHHFVDGFDEEKSNWMRYVNPA--HS-QQEQNLAACQNGMSIYFY
TVKPIPADQELLVWYCPEFAERLHYPPSGELMMQK
>Tachysurus_fulvidraco_XP_026998650.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
QVDPKMIVEDADMSKWTEAEFEEKCTYIVKDHTWEGAD-K-----------P----DLPR
AQTSLPRNLAFRYAP-DSK-------------EVIGVVSREYIPKGTRFGPLVGESYTAE
DVHKD--------------------------------------ANRKYFWRI--------
---------YA-EGKFHHFVDGLDEEKSNWMRYVNPA--HS-QQEQNLAACQNGMNIFFY
TVKAIPADQELLVWYCTDFAHRLHYPPSGDLMMEK
>Danio_rerio_NP_955809.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
NEELKMDVEDVDMTKWTEDEFEEKCTYIVKDHTWEGPLEN-----------T----DLTR
AEASLPRNLAFKHPA-DSK-------------EVIGVVSREYIPKGTRFGPLVGESYTAE
NVPKD--------------------------------------ANRKYFWRI--------
---------YS-DGEFHHFVDGLDEEKSNWMRYVNPA--HS-QQEQNLAACQNGMNIYFY
TVKAIPADQELLVWYCPEFARRLNYPASGEIMMQK
>Takifugu_rubripes_XP_029694031.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
DVDMELDVEEADMTRWTEAEFEGKCTYIVKDTEAGQ---T-----------HGDGVTATR
AELSLPRNLAFKSSF-DSK-------------EVVGVCSREYIPKGTRFGPLVGEIYTAE
SVPKD--------------------------------------ANRKYFWRL--------
---------YT-NGEFHHFIDGLDETRSNWMRYVNPA--HS-VAEQNLAACQNGMEIYFY
TVKPIPAGAELLVWYCHDFAQRLHYPPSGELMMQK
>Lucifuga_dentata_KAF7644247.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
DTDVEVDMEEADMMNWTEAEFEEKCTYIVKDTAWEAGPDT-----------DAMT---TR
AETSLPRNLVFKQPA-DSK-------------EVTGVCSREYIPKGTRFGPLVGEIYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YV-DGEFHHFVDGLDETRSNWMRYVNPA--HS-AAEQNLAACQNGVEIYFY
TVKPVPAGAELLVWYCHDFARRLHYPPSGELMMQK
>Thunnus_albacares_XP_044215860.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--DMEMEMEEADMTRWTEADFEEKCTYIVKDTAWEAGPDG-----------DTMMMTTTR
AEASLPRNLAFKHPA-ESK-------------EVVGVCSREYIPKGTRFGPLVGEIYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YA-DGEFHHFVDGLDETRSNWMRYVNPA--HS-EAEQNLAACQNGMEIYFY
TVKPVPAGAELLVWYCHDFARRLHYPPSGELMMQK
>Sebastes_umbrosus_XP_037641826.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
DMEVEVEMEEADLTRWTEAEFEEKCTYIVKDTAWEAGPDS-----------EAMTTTATR
AEASLPRNLAFKHPA-DSK-------------EVVGVCSREYIPKGTRFGPLVGEIYTAD
SVPKD--------------------------------------INRKYFWRI--------
---------YE-DREFHHFVDGLDETRSNWMRYVNPA--HS-AAEQNIAACQNGMEIYFY
TVKPVLAGAELLVWYCHDFARRLHYPPSGELMMQK
>Solea_solea_XP_058504536.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--DMDMDVEEADMTRWTETEFEEKCTYIVKDTAWEAGPEG-----------DGAVTPLTR
AEASLPRNLAFKHPA-DGK-------------EVVGVCSSEYIPKGTRFGPLVGEIYTAD
SVPRE--------------------------------------ANRKYFWRI--------
---------YA-DKEFHHFVDGLDETRSNWMRYVNPA--HS-AAEQNLAACQNGMEIYFY
TVKPVPAGAELLVWYCHDFARRLHYPPSGELMMQK
>Osmerus_eperlanus_XP_062320947.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-AAADPTMEEADMMRWTEAEFEEKCTYIVKDTPQEPSPDS-----------EG----LTR
AEASLPRNLVFKHPA-SST-------------EVIGVCSREYIPKGTRFGPLVGQCYTAD
SVCKD--------------------------------------ANRKYFWRI--------
---------YS-EGEFHHFVDGLEEEQSNWMRYVNPA--HS-ASEQNLAACQNGMEVYFY
TVRPVAPGAELLVWYCPEFAQRLHYPPSGELMMQK
>Gadus_macrocephalus_XP_059920415.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MVSSSSEVEQADMTRWSEAEFEEKCTYIVKDTPRELGQES-----------EG----LTR
AEASLPRNLSFKHPS-ESK-------------EVIGVISREYIPKGTRFGPLVGEIHTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YA-EGEFQHFVDGLDESRSNWMRYVNPA--HS-AAEQNLAACQNGKEIHFY
TVRAVQAGAELLVWYCPDFAHRLHYPPSGELMMQK
>Gadus_morhua_XP_030226788.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MVSSSSEVEQADMTRWSEAEFEEKCTYIVKDTPRELGPES-----------EG----LTR
AEASLPRNLSFKHPS-ESK-------------EVIGVISREYIPKGTRFGPLVGEIHTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YA-EGEFQHFVDGLDESRSNWMRYVNPA--HS-AAEQNLAACQNGKEIYFY
TVRAVQAGAELLVWYCPDFAHRLHYPPSGELMMQK
>Esox_lucius_XP_010883607.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATNRDPNMEEADMMRWTEAEFEEKCTYIVKDTPREAGTES-----------EG----LTR
AEASLPRNLTFKHPA-GST-------------EVIGVASREYIPKGTRFGPLVGQNYTTD
SVPRD--------------------------------------ANRKYFWRI--------
---------YS-EGNFHHFVDGLDEDRSNWMRYVNPA--HS-AGEQNLAACQNGMNIYFY
TVRAILPGTELLVWYCPEFAHRLHYPSYGDLMMQK
>Oncorhynchus_mykiss_XP_036801629.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATDTDSKMEEADMMKWTEAEFEEKCTYIVKDTPREAGTES-----------EG----LTR
AEASLPRNLAFKQLA-ESK-------------EVIGVASREYIPKGTRFGPLVGQIYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-EGDFHHFVDGLDEERSNWMRYVNPA--HS-AEEQNLAACQNGTNIYFY
TVRAIPPGTELLVWYCPEFAHRLHYPPSGELMMQK
>Salmo_salar_XP_014056343.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATDTDSKMEEADMMMWTEAEFEEKCTYIVKDTPREAGTES-----------EG----LTR
AEASLPRNLAFKQLA-DSK-------------EVIGVASREYIPKGTRFGPLVGQVYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-EGDFHHFVDGLDEERSNWMRYVNPA--HS-AGEQNLAACQNGTNIYFY
TVRAIPPGTELLVWYCPEFAHRLHYPPSGELMMQK
>Salmo_trutta_XP_029596518.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATDTDSKMEEADMMKWTEAEFE-KCTYIVKDTLREAGTES-----------EG----LTR
AEASLPRNLAFKQLA-DSK-------------EVIGVASREYIPKGTRFGPLVGQVYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-EGDFHHFVDGLDEERSNWMRYVNPA--HS-AGEQNLAACQNGTNIYFY
TVRAIPPGTELLVWYCPEFAHRLHYPPSGELMMQK
>Oncorhynchus_kisutch_XP_031642677.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATDTDSKMEEADMMKWTEAEFEEKCTYIVKDTPREAGTES-----------EG----LTR
AEASLPRNLAFKQLA-ESK-------------EVIGVASREYIPKGTRFGPLVGQIYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-EGDFHHFVDGLDEEWSNWMRYVNPA--HS-AGEQNLAACQNGTNIYFY
TVRAIPPGNELLVWYCPEFAHRLHYPPSGELMMQK
>Oncorhynchus_keta_XP_052345569.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
ATDTDSKMDEADMMKWTEAEFEEKCTYIVKDTLREAGTES-----------EG----LTR
AEASLPRNLAFKQLA-ESK-------------EVIGVASREYIPKGTRFGPLVGQIYTAD
SVPKD--------------------------------------ANRKYFWRI--------
---------YS-QGDFHHFVDGLDEERSNWMRYVNPA--HS-AGEQNLAACQNGTNIYFY
TVRAIPPGTELLVWYCPEFADRLHYPPSGELMMQK
>Rhinatrema_bivittatum_XP_029451196.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
GRTMRMAMDEADLTLWAEADFEARCTYIVKDHAWDAGAER-----------G----ALTQ
AEASLPRNLSFKYGP-DGK-------------EVIGVLSNEYIPKGTRFGPLVGEIYTEE
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-GGEFHHFIDGFDEDRSNWMRYVNPA--RS-AQEQNLAACQNGPSIYFY
TIQPIPAKQELLVWYCRDFAERLHCPSTGELPLMS
>Microcaecilia_unicolor_XP_030051522.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
GGTMRMAMDDADLTQWAEADFEERCTYIVKDHAWEGSAER-----------G----SLTQ
AEASLPRNLSFRYGP-DRK-------------EVIGVLSNEYIPKGTRFGPLVGEIYTPD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGEFDHFVDGFDEERSNWMRYVNPA--HS-TQAQNLAACQNGSNIYFY
TIQPIPAKQELLVWYCRDFAERLHCPSTGELSLIS
>Geotrypetes_seraphini_XP_033791283.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
GGTMRMAMDDADLTLWAEADFEERCTYVVKDHAWEGGAER-----------G----ALTQ
AEASLPRNLSFKYAP-DCK-------------EVIGVLSNEYIPKGTRFGPLVGEIYTLD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGEFDHFIDGFDEERSNWMRYVNPA--RS-AQEQNLAACQNGSNIYFY
TVQPIPAKQELLVWYCRDFAERLHCPSTGELPLIN
>Protopterus_annectens_XP_043921132.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SQRMKMDMDDADMTLWREQEFEENCTYIVNDHPWDPSMDG-----------S----CITQ
AEASLPRNLIFKYTD-DRK-------------EITGVMSKEYIPKGTRFGPLVGEEYTTD
SVPKN--------------------------------------ANRKYFWRI--------
---------YS-QGEFHHFIDGFNEEKSNWMRYVNPA--WS-VQEQNLAACQNGMNIYFY
TVKAIPANEELLVWYCRDFADRLHYPATGELMMLR
>Latimeria_chalumnae_XP_005997943.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMGTEDADMTQWSEMEFEENCTYIVNDNPWDPCADG-----------G----NWTQ
AEASLPRNLIFKYAP-SCK-------------EIIGILSKEYIPKGTRFGPLVGEVYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGKFHHFIDGFNEEKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCREFADRLDYPSSGDLMSLK
>Varanus_komodoensis_XP_044283115.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMKDADMTQWTEAEFEDKCTYIVNDHLTEPST-E-----------GS---TVTQ
AESSLPRNLIFKYAA-NCK-------------EVIGVISKDIIPKGTRFGPLVGEIYTND
TVPKD--------------------------------------ASRKYFWRI--------
---------YS-GGELLHFIDGFNEEKSNWMRYVNPA--RS-VQEQNLAACQNGMGIYFY
TIKPIPPGQELLVWYCRDFAERLHYPSTGDLRMMN
>Python_bivittatus_XP_007433539.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMKDADMTLWTEAEFEDKCTYIVNDHPTEPSSGE-----------GC---TITQ
AESSLPRNLIFKYAG-NCK-------------EVIGVISKDIIPKGTRFGPLVGEIYTSD
TVPKD--------------------------------------ANRKYFWRI--------
---------YS-GGELLHFIDGFNEEKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPPGQELLVWYCQDFADRLHYPSTGDLLMLN
>Tachyglossus_aculeatus_XP_038617122.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGSTKMGMEDVDMTLWTEADFEEKCTYIVNDHPWDSGADG-----------TG---SAPQ
AELSLPRNLVFKYSP-NCK-------------EVTGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------VNRQYFWRI--------
---------YS-GGELHHFIDGFNEDKSNWMRYVNPA--HS-GQEQNLSACQNGMNIYFY
TIKPIPASQELLVWYSQDFAERLHYPSSGELLRMN
>Corvus_cornix_XP_010401715.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EWTMKMDMEDADMTLWTEADFEEKCTYIVNDHPLDPSADG-----------G----TLTQ
AEASLPRNLTFKYAS-NCK-------------EVTGVISKEYIPKGTRFGPLVGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGELHHFIDGFNEDKSNWMRYVNPG--YS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPSSRELTMMN
>Apus_apus_XP_051469068.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EWTMKMDMEDADMTLWTEADFEEKCTYIVNDHPLDPSADG-----------S----TLTQ
AEASLPRNLTFKYAS-NCK-------------EVTGVISKEYIPKGTRFGPLVGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGELHHFIDGFNEDKSNWMRYVNPG--YS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPSSRDLTMMN
>Taeniopygia_guttata_XP_012428162.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EWTMKMDMEDADMTLWTEADFEEKCTYIVNDHPLDPSADG-----------G----TLTQ
AEASLPRNLTFKYAS-NCK-------------EVTGVISKEYIPKGTRFGPLVGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGELHHFIDGFNEDKSNWMRYVNPG--YS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPPSRELTMMN
>Tyto_alba_XP_032864370.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EWTMKMDMEDADMTLWTEADFEEKCTYIVNDHPLDPSADG-----------G----TLTQ
AEASLPRNLTFKYAS-NCK-------------EVTGVISKEYIPKGTRFGPLVGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGELHHFIDGFNEDKSNWMRYVNPG--YS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPSSRELTMMN
>Apteryx_rowi_XP_025921504.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EWTMKMDMEDADMTLWTEGDFEEKCTYIVNDHPWDPSADG-----------D----TLTQ
AEASLPRNLTFKYAS-NCK-------------EVTGVISKEYIPKGTRFGPLVGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGELHHFIDGFNEDKSNWMRYVNPG--YS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPSSRELTMMN
>Chelonia_mydas_XP_043398660.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEDADMTLWTEADFEEKCTYIVNDHPWDPSDDG-----------S----TITQ
AEASLPRNLTFKYTL-NCK-------------EVTGVVSKEYIPKGTRFGPLVGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEDKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCPDFAERLHYPSSRELMMN-
>Chelonoidis_abingdonii_XP_032639474.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEDADMTLWTEADFEEKCTYIVNDHPWDPSDDG-----------S----TITQ
AEASLPRNLTFKYTS-NCK-------------EVTGVVSKEYIPKGTRFGPLVGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-SGELHHFIDGFNEDKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCPDFAERLHYPSSRELMMN-
>Vombatus_ursinus_XP_027711110.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEADFEEKCTYIVNDHPWDSGADG-----------G----TAIQ
AEASLPRNLVFKYAP-NCK-------------EVIGVISKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRQYFWRI--------
---------YS-NGELHHFIDGFNEEKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPPSGELMRMD
>Antechinus_flavipes_XP_051853422.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEADFEEKCTYIVNDHPWDSGADG-----------G----ASIQ
AEASLPRNLVFKFAT-NCK-------------EVIGVISKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRQYFWRI--------
---------YS-NGELHHFIDGFNEEKSNWMRYVNPA--HS-VQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPSSGELMKMN
>Pseudophryne_corroboree_XP_063773125.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEGVDMTLWPEAEFEAKCTYIVKDHPWDSSSDG-----------S----NVVQ
AQASLPRNLLFKYAS-SSK-------------EVIGVVSKEYIPKGTRFGPFVGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-NGEFNHFIDGFNEEKSNWMRFVNPA--HS-IQEQNLAACQNGLNIYFY
TIKPIPASQELLVWYCRDFADRLDYPSSEELVMN-
>Bufo_bufo_XP_040284754.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDVEGADMTLWTESEFEAKCTYIVKDHPWDSSSDG-----------S----NLVQ
AQASLPRNLLFKHVP-GSK-------------EVIGVLSKEYIPKGTRFGPFVGEVYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YL-NGEFNHFIDGYNEEKSNWMRYVNPA--HS-IQEQNLAACQNGMSIYFY
TIKPIPANQELLVWYCRDFADRLDYPSSRELVMN-
>Pelobates_cultripes_CAH2252429.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEGADMTLWTEAEFEEKCTYIVKDHQWDSSLDG-----------T----QLKQ
AQASLPRNLLFKYDS-VSK-------------KVIGVFSKEYIPKGTRFGPYIGESYTID
TVPEK--------------------------------------ADRNYFWRI--------
---------YS-NGEFHHYIDGYNEDKSNWMRYVNPA--HS-LHKQNLAACQNGMDIYFY
TIMPIPADHELRVWYSRDFAKRLNYPLCNDVLTN-
>Myotis_daubentonii_XP_059556806.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAAFEENCTYIVNDHPWDSGADG-----------G----TSVQ
AEASLPRNLLFKYTT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-GGELHHFIDGFNEEKSNWMRYVNPA--HS-AQEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Equus_caballus_XP_001501874.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGADG-----------G----TSVQ
AEASLPRNLLFKHSA-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYNND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFKEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Loxodonta_africana_XP_003404365.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-GTMKMDMEDVDMTLWTEAEFEEKCTYIVNDHSWDSGIDG-----------G----TSVQ
AEASLPRNLLFKYAT-NSN-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNVYFY
TVKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Dasypus_novemcinctus_XP_058163190.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDVDMTLWTEAEFEEKCTYIVNDHPWDSSADG-----------G----TSVQ
AEASLPRNLLFKSAT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNVYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Galemys_pyrenaicus_KAG8522108.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
KGTMKMDMEDVDMTLWTEAEFEEKCTYIVNDHPWDSGADG-----------G----TSVQ
AEASLPRNLLFKYIT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTSD
TVPKN--------------------------------------ASRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Erinaceus_europaeus_XP_007523988.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSCTDG-----------G----TSVQ
AEASLPRNLLFKYVS-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTSD
TVPKN--------------------------------------ASRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPVPASQELLVWYCRDFAERLHYPYPGELTTMS
>Homo_sapiens_NP_001189.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
KGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGADG-----------G----TSVQ
AEASLPRNLLFKYAT-NSE-------------EVIGVMSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-PREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Vulpes_vulpes_XP_025861549.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
---MKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDCGADG-----------A----ASLQ
AEASLPRNLLFKYGP-SSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELLHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMS
>XP_025861549.1 (best hit for PRDM1_HUMAN_825_residues)
---MKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDCGADG-----------A----ASLQ
AEASLPRNLLFKYGP-SSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELLHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMS
>Mirounga_leonina_XP_034847585.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-GTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDCSADG-----------G----TSVQ
AEASLPRNLLFKYAT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELLHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPDNQELLVWYCRDFAERLHYPYPGELTMMN
>Saccopteryx_leptura_XP_066229666.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGVDG-----------G----TSVQ
AEASLPRNLLFKYAT-DSK-------------EVIGVLSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELLHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYSGELTVMN
>Balaenoptera_acutorostrata_XP_057383471.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGTEG-----------G----ASVQ
AEASLPRNLLFKYAA-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWLRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Bos_taurus_NP_001179865.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGVEG-----------G----TSVQ
AEASLPRNLLFKYAT-NSK-------------EITGVVSKEYIPKGTRFGPLIGEIYTSD
AVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWLRYVNPA--HT-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYSGELTMMN
>Muntiacus_reevesi_XP_065767652.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSGVEG-----------G----TSVQ
AEASLPRNLLFKYAT-NSK-------------EVTGVVSKEYIPKGTRFGPLIGEIYTSD
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWLRYVNPA--YS-PWEQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHSPYPGELTMMN
>Sturnira_hondurensis_XP_036920853.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
EGTMKMDMEDVDMTLWTEAEFEEKCTYIVNDHPWDSGADG-----------G----TSVQ
AEASLPRNLLFKYAT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQSLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Rattus_norvegicus_NP_001101109.2_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
SGIMKMDMEDADMTLWTEAEFEEKCTYIVNDHPWDSSADG-----------G----TSVQ
AEASLPRNLLFKYAANNSK-------------EVIGVVSKEYIPKGTRFGPLIGEVYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-REEFHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTVMN
>Lynx_pardinus_VFV21741.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
-GTMKMDMEDADMTLWTEADFEEKCTYIVNDHPWDCGADG-----------G----TSVQ
AEASLPRNLLFKYAT-NSK-------------EVIGVVSKEYIPKGTRFGPLIGEIYTND
TVPKN--------------------------------------ANRKYFWRI--------
---------YS-RGELHHFIDGFNEEKSNWMRYVNPA--HS-AREQNLAACQNGMNIYFY
TIKPIPANQELLVWYCRDFAERLHYPYPGELTMMN
>Paralvinella_palmiformis_KAK2154697.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
MHICESQDDSWDSSQLGEDDFDRQATYFVPDRPCQQ-------------------DVSNH
AEASLPRNLALRPSHVFKD--------------SQSVWSTEFIPKGTRFGPLQGEIFTSD
TVRKN--------------------------------------GNPKNIWEI--------
---------YH-KEEPFYYIDTSDTSKSNWMRYVSPA--NG-LRHQNLVACQVKFDIYFY
TIKPVPAGTELYVWYCHEFAERIRHSLPSADRFLS
>Ridgeia_piscesae_KAK2161996.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
GKVTEGEEVSWDVERMNEDDYERKATYFVPDLPCPP-------------------QMPNR
AQATLPRNLTLKASQTLGG-------------KVLGVWSREFIPKGTRFGPLDGDIFQKD
VIPQN--------------------------------------ANRNYLWRV--------
---------YH-DEDLYHYVDGCDVDKSNWMRHVNPA--NS-LKQQNLVACQVKLSIFFY
TIKSIPPNTELLVWYCREFAQRLNYPLATSDRQLG
>Bradysia_coprophila_XP_037046779.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
RCPTPGDQEEYDVTRMREDDFERLAVYMVPDVPCER-------------------GTPSR
ADKTLPRSLTLKPSLVLST----------PN--TEGVWSTGVIPRGTRFGPFEGVAVKTP
NCPSD-------------------------------------KINWRYFWR---------
--------IFK-D-NEYYYLDGSDTTQANWMRYVASA--YS-LRVMNLVACQHQENIYFY
TTRDIMPNEELMVWYCRDFAKRLGYDVDPERATYT
>Aedes_aegypti_XP_021697776.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--VTPTVQQDYDVTRMREEDFERLAVYIVPDVPCEK-------------------GIPSR
ADKTLPRSLTLKPSLVLST----------PTATTEGVWSTGVIPRGTRFGPFEGVR--TP
SHPSD-------------------------------------KQLWRYFWRVQE-LRHVS
Y---GNIKIFK-D-SDFYYLDGSDPAQSNWMRYVASA--YS-FSVMNLVACQHQEHIYFY
TIRDIMPNEELMVWYCRDFAKRLGYDIDPERATYS
>Hermetia_illucens_XP_037905981.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
PTPDNGGQQDYDVTVMREEDFERLAVYIVPDVPCER-------------------GVANR
AEKTLPRSLTLKPSLVLST----------PNIKTEGVWSTGVIPRGTRFGPFEGIA--TT
NYPND-------------------------------------KTSARYFWR---------
--------IFK-D-DDYYYLDGSDRSQANWMRYVASA--YS-LSVMNLVACQHQDNIYFY
TTRDIMPNEELMVWYCKDFARRLGYDVDPERTTYS
>Drosophila_pandora_KAH8345284.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
RSPTPDGNQDYDVTRMREEDFQRLAVYLVPDVQAER-------------------GLPNR
ADKTLPRSLTLKSSMVYST----------PNVKTEGVWSSGVIPRGTRFGPFEGIP--TS
NYPND-------------------------------------KNKARYFWRVQG-TRHIT
Y---GNIKIFK-D-DDYYYLDGSDRSQSNWMRYVASA--YS-LSVMNLVACQHQENIYFY
TTRDILPNEELMVWYCKDFASRLGYDVDPERTIFG
>Vanessa_atalanta_XP_047526865.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
AVNAVGGSDAYDVTRMREEEFERLTVYIVPDVPCER-------------------GLPNR
AERTLPRSLALRPSAVLST----------PNTPTEGVWSTGVIPRGTRFGPFEGTR--TP
NKPND-------------------------------------KVSWRYYWRVQETVRHHT
Y---GNIKIFK-D-SDYYYLDGSDTSVANWMRYVASA--YS-LSVMNLVACQHQEHIYFY
TIRDIMPNEELMVWYCKDFATRLGYDIDPERATYS
>Zerene_cesonia_XP_038210237.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
--GAVANNDAYDVTRMREEEFERLTVYIVPDVPCER-------------------GVLNR
AERTLPRSLALRPSAVLST----------PNTPTEGVWSTGVIPRGTRFGPFEGTR--TP
NKPND-------------------------------------KVSWRYYWR---------
--------IFK-D-SDYYYLDGSDTSVANWMRYVASA--YS-LSVMNLVACQHQEHIYFY
TIRDIMPNEELMVWYCKDFATRLGYDIDPERATYS
>Capitella_teleta_ELT95396.1_PRDM1_HUMAN_825_residues (PRDM1_HUMAN_825_residues)
IEMEPRTTHAWREVIMKKEREEKKATYFVPDRAVPE-------------------GSPSR
ALDSLPRNLTIKQSGVGTQ--------------ILGVWSSEFIPNGTRFGPLRAQR--SN
ERPSG--------------------------------------TDMSQVWRI--------
---------QA-EGNKASYLNASDPSLSNWMRYVNTA--PS-LGAHNVVADVIEREVFFF
TTRPLQPNDELLVL-CSESVSRMDQEKEC--MPRS
