>Caerostris_darwini_GIY01204.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------IVIYSTDIIRNVPGEVFLDASSLPSKKIGVFANTTIEERTVIGPLPGRLVDSSN
FTE--KDLEHSWEVVDE-NG----QIKNLLHLEIHG---KDSWMCFIQPARHALEQNLET
FD--AGS-AIYYRAIKDINVGEELLVWYGLHIEQCFG-LPCFETQNIR---
>Nephila_pilipes_GFS69956.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SVLNSPDVTKSVPEEVFLDVSTLPFQGIGVFAGITIEERTIIGPLPGRIVDPST
TPD--EGLDNAWEVSDE-KG----QIKHILQMEHHGTAARDLWISRIQSARCIQEQNLET
FE--AGG-AIYYRATKEIAAGEELLVWYGLHIEQCFG-LPCFEPKKTQ---
>Dermacentor_andersoni_XP_054919798.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------VTDTDSRVIAGTPRQLRLGVSSVPGCQVGVFAADHIPKDTQMGPYPGAPKPALA
LCRD---PALVWEAIDGASG----RVRFFVDGA-D--AVMPSWMTYVQCARHEQEQNLDM
LLLLPEG-GLYYRVTKAIHPDEELLVWYDGELPHYMG-IPDALLPSDTPVK
>Limulus_polyphemus_XP_013794286.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------EAELPEGLLTRTPVQLKLGVSTIPILHNGVFAAEWITKGTEMGPYPGVIRSKGD
LWIT-SDTDKVWEIFDCSNG----EVEEYVDSR-T--HVMCSWMTHVKCARNEQEQNLET
FQ--VET-SVYYRAMKDIAPEEELLVWYNSAIPQYMG-IPVKLFSDDNKIE
>Oopsacas_minuta_KAI6654623.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
NTMLEYQELISKELQNCQQDLIECRQSSAQLNSIGLFCKGDILQGSKIGPYIGQDYSVCD
IGAD---KGDYWEIYDVDENGQPDKLSCLLVGS----PSYENWMQFVRYARNKREQNLEV
VP--VDG-KIYFRAVRDIKSNEELLVWFSDFYELKFG-IPSVYSVEDNEVN
>Mytilus_californianus_XP_052092480.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
--------SIDDFPSLPLPHQVKIGLSALPGCKYGVFARTVIRTGTEMGPFVGHVKRPCD
IQNV-SHNPSLWEVFDT-TG----HLLHFIDGG-H--YNPASWLSLIQCARSEREQNLEV
TQ--IGA-NLFFKASKDILCGQELLVWYGMSHCLFMG-LPLQNKTERK---
>Potamilus_streckersoni_KAK3610838.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------------MPSQARVGQSTVPGCIQGIFALERIKVGTEMGPFVGHMLALTQ
LNIT-HINSSVWELYDE-YG----RLAGYVDGGGV--QRPASWLSLIQCARMEKEQNLEL
LQ--VGS-QIYYRATRDIHPGEELLVWYGASYSLYMG-LPSYYSDVTCNYQ
>Mizuhopecten_yessoensis_XP_021380257.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
--------EITDPTYLPLPHQVVIARSTLPGAGHGVFATSKIKPGTEMGPYVGTILHHGD
LNSD-TDNTKTWEVFDK-DG----RVLYFLDGG-T--RNPASWLTFVQCARSELEQNLEV
VQ--AGM-DIYYRALRDIEPEEELLVWYGRSQNLYMG-IPDPDLDDP----
>Ylistrum_balloti_XP_060070829.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
--------DIVYPSYLPLPHQVVIARSTLPGAGLGVFATSKIKPGTEMGPFVGTILHHRD
LNSS-MDNSKTWEVFDK-DG----RVLYFLDGG-T--RNPASWLTFVQCARSELEQNLEV
VQ--AGK-DIYYRALRDIEQEEELLVWYGRSQNLYMG-IPDPDLDDL----
>Pecten_maximus_XP_033729894.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
--------DVLYPPYLPLPHQVAIARSTLPGAGFGVFATSQIKPGTEMGPYVGTILHHGD
LDGL-GDNTKTWEVFDK-DG----RVLYFLDGG-T--RNPASWLTFVQCARSELEQNLEV
VQ--AGK-DIYYRALRDIEPEEELLVWYGRSQNLYMG-IPDPDMEEI----
>Crassostrea_virginica_XP_022335571.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
--------INPVLPSPFVPRQVCIRRSTIPGALHGVFSKVWIRRGTEMGPFAGRTCGTID
TNVN---NKNTWEVFDE-RG----EVLFYVDGGSD--IHPASWLTCVQCARNTREQNLEV
VQ--INT-QIFYRAVQDIAPGEEFLVWYGQTSIYHLG-LPMMAQNRIEVEN
>Dreissena_polymorpha_XP_052224369.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------MDTNASLPPELIIFPSTIPGSNLGVFCATSIKHGTKMGPYPGRIVTSCD
CR-N-KPMDKCWEILLP-NN----ALLAYLNAD----SCHDNWLANVQCARAETEQNLEL
VQ--VGS-QIYYRATKDIQRGDELLVWYGASYTLYMG-LPVTSGHTTKPLA
>Mya_arenaria_XP_052788654.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------NKQNNTGEVIPTPPEVAILPSTVPGADVGVYSTGIIKRGTEMGPFPGVYVSPWG
GGGR-ETYTEAWEILNS-DG----SVLAYLTAV----GCPANWLTHMQCARGEHEQNVEA
VQ--VGV-SIFYRATKDIPRGKELLVWYGRTYKLYMG-LPVTRNPDQMAA-
>Gigantopelta_aegis_XP_041369780.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------DIQQDGCFVPTPKQVRLFQSQLPGGSLGVFSTTWIKRGTVMGPFTGRKLNVDQ
IDHI-NHNANAWEVFGE-DG----EVLFYVDGGRD--LSQCSWLSYVNCARSEQEQNLET
FQ--VEH-NIFYRAIKDIPPKQELLVWYGASFNMYMG-LPCSAQHTKD---
>Haliotis_rufescens_XP_046362317.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NNIQEITSVQTPKQVRVGPSSLPGASLGVFSTTWIKTGTEMGPFIGRVVNREN
MDCS---SENAWEIFDD-QG----NILLYLDGGTE--HPRASWLSYVNCARNEQEQNLET
FQ--VGR-NIFYRAIKDIPPQQELLVWYGASFNLYMG-IPSLGHPVPEVK-
>Lottia_gigantea_XP_009063444.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------------ITNVTKPKQVEISRSTIPGCMLGVTSTTWISTGTQMGPFVGRIVKLED
IQNQPDITDNIWEIFDD-KG----VILYFIDGGTS--FPRASWLSYVNCARNPQEQNLEL
VQ--IGH-NIFYRAIKDIAPQKELLVWYGSSTKLYLG-LPTPDLTIEKSS-
>Mirounga_leonina_XP_034872470.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFVDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Bos_taurus_NP_001193224.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Galemys_pyrenaicus_KAG8509476.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAQVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNAHNTFLG-IPGVPGLEEEQKK
>Balaenoptera_acutorostrata_XP_007194839.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Myotis_daubentonii_XP_059514798.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRLIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>XP_025865013.1 (best hit for PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Dasypus_novemcinctus_XP_004463125.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Loxodonta_africana_XP_003407612.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Vulpes_vulpes_XP_025865013.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Muntiacus_reevesi_XP_065783182.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Sturnira_hondurensis_XP_036892927.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGAEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEDQKK
>Homo_sapiens_NP_067632.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEDQKK
>Saccopteryx_leptura_XP_066221664.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Rattus_norvegicus_NP_001414290.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPVEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Equus_caballus_XP_023485351.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPAEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Erinaceus_europaeus_XP_007539125.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPTEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVITPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGT-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Antechinus_flavipes_XP_051829874.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Vombatus_ursinus_XP_027725110.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Tachyglossus_aculeatus_XP_038601955.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDIC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Taeniopygia_guttata_XP_030142460.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Tyto_alba_XP_042642758.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Chelonoidis_abingdonii_XP_032653647.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
IQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Apteryx_rowi_XP_025918089.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
IQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Chelonia_mydas_XP_037735806.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
IQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Apus_apus_XP_051492695.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Varanus_komodoensis_XP_044296084.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRIISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVLGLEEEQKK
>Corvus_cornix_XP_039417738.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIFYKAIEMIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Protopterus_annectens_XP_043914774.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISSEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Rhinatrema_bivittatum_XP_029468728.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DS----SVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Microcaecilia_unicolor_XP_030063087.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DS----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Geotrypetes_seraphini_XP_033817680.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DS----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSHNTFLG-IPGVPGLEEEQKK
>Lucifuga_dentata_KAF7650028.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSVPGEGLGIFSKTWIKAETEMGPFTGRLVSPEH
VDLY-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGGDDEHSK
>Osmerus_eperlanus_XP_062310569.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSVPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----SVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
MQ--LGG-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGTEEDQSK
>Sebastes_umbrosus_XP_037609106.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------VGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLL-KNNNLMWEVFNE-DG----SVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPGIDTEEHL
>Thunnus_albacares_XP_044189490.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLL-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPGTDEEHL-
>Takifugu_rubripes_XP_003965427.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLL-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPGTDEEQQ-
>Solea_solea_XP_058473522.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------AGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPGVDEEQQ-
>Gadus_morhua_XP_030211433.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------AGEVQKLSSLVLPSEVVIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLL-KNNNLMWEVFNE-DG----SVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPTIEEEQQK
>Gadus_macrocephalus_XP_059906589.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------AGEVQKLSSLVLPSEVVIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVLSPEH
VDLL-KNNNLMWEVFNE-DG----SVRYFIDAS-Q--EDQRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNTHNTFLG-IPGVPTIEEEQQK
>Danio_rerio_NP_001007458.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGTEEEQQK
>Esox_lucius_XP_010902213.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
LDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGMEEDQQK
>Oncorhynchus_keta_XP_035643378.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Oncorhynchus_kisutch_XP_020327892.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Oncorhynchus_gorbuscha_XP_046201121.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Salmo_trutta_XP_029578187.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Salmo_salar_XP_014030272.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Oncorhynchus_mykiss_XP_021462358.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVHKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAMETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDDQQK
>Brienomyrus_brachyistius_XP_048851598.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVITPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGIEDEQQK
>Gymnothorax_javanicus_KAJ8285660.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGTEEEHQK
>Amia_calva_XP_066568593.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLL-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAVETIPPDQELLVWYSNSHNTFLG-IPGVPGTEEEHQK
>Megalops_cyprinoides_XP_036383899.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGTEEEHQK
>Tachysurus_fulvidraco_XP_027001519.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGS-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPGMDEEHQK
>Polyodon_spathula_XP_041098747.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVMSPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKTCEVIPPDQELLVWYGNSHNTFLG-IPGVPGMEEDHQK
>Huso_huso_KAK6470913.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVMSPEH
VDLF-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKTCEVIPPDQELLVWYGNSHNTFLG-IPGVPGMEEDHQK
>Rhincodon_typus_XP_048469347.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPYTGRVISPEH
VDLF-KNNNLMWEVFND-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIYYKTTETIPPDQELLVWYGNTQNTFLG-IPGVPGLEEEHRK
>Scyliorhinus_canicula_XP_038638298.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFND-DS----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIYYKATETIPPDQELLVWYGNTQNTFLG-IPGVPGIEEEHRK
>Amblyraja_radiata_XP_032905111.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFND-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIFYKATETIPPDQELLVWYGNTQNTFLG-IPGVPGIEEEHRK
>Carcharodon_carcharias_XP_041050246.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPFTGRVISPEH
VDLF-KNNNLMWEVFND-DG----TVRYFIDAS-Q--EDRRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIFYKATGTIPPDQELLVWYGNTQNTFLG-IPGVPGIEEEHRK
>Mobula_hypostoma_XP_062929186.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPFTGRMISPEH
VDLF-KNNNLMWEVFND-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIFYKATETVPPDQELLVWYGNTQNTFLG-IPGVPGMEEEHRK
>Hypanus_sabinus_XP_059799745.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------TGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKPGTEMGPFTGRMISPEH
VDLF-KNNNLMWEVFND-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-NIFYKATETIPPDQELLVWYGNTQNTFLG-IPGVPGMEEEHRK
>Latimeria_chalumnae_XP_005992184.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVIAPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFVDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAVETIPPDQELLVWYGNSHNTFLG-IPGVPSSDEEQKK
>Pelobates_cultripes_CAH2316015.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DS----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSQSSFLG-IPGVPGMEEEQKK
>Pseudophryne_corroboree_XP_063792782.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSQNSFLG-IPGVPGMEEEQKK
>Bufo_bufo_XP_040262012.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SGEVQKLSSLVLPSEVIIAQSSIPGEGLGIFSKTWIKAGTEMGPFTGRVISPEH
VDLC-KNNNLMWEVFNE-DG----TVRYFIDAS-Q--EDHRSWMTYIKCARNEQEQNLEV
VQ--IGN-SIFYKAIETIPPDQELLVWYGNSQNTFLG-IPGVPGIEEEQKK
>Petromyzon_marinus_XP_032828847.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------LAKLDKMSSLALPAELTVAPSSVPGEDLGIYTRTWIKQGTEMGPFTGKMIPPDG
VDIF-KNNNLMWEVFNE-DG----TVRHFVDAS-Q--DNHRSWMTYIRCARNEQEQNLEV
VQ--IGN-SIYYKALEPIPPDQELLVWYSFSHNTFLG-IPGVPGIEDEQRK
>Ridgeia_piscesae_KAK2191851.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------------MPGIPTPMEVRITWSSLPNETCGVCATAWIKHGTEMGPFWGERVPPMH
IDFS-RSNDLAWEVLTK-DG----NVSHLVDAS-R--IRHRNWITYINCARNVHEQNLEI
FQ--IGL-DIFYRVTKDIAPDQELLVWYAPTSDSFLG-IPGAWAGDREAGD
>Branchiostoma_belcheri_XP_019619668.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------DQEFPSLPGLVLPPQLEARRSQIPCRRWGVFARAWIKPGTEMGPYSGRRVSPAE
VDPV-GENEFMWEVFTP-YG----DLSHYVDAS-R--QEDRSWMAYVNCARSEQEQNLEL
FQ--KGE-HIYYRAMKAIPPDEELLVWYRFSPSTFLG-IPGVPQPDEFTAK
>Branchiostoma_floridae_XP_035687801.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------SPELPSLTGLVLPPQLEARSSQIPCRRWGVFARTWIKQGTEMGPYTGRRVNPTD
VDPC-VENEFMWEVFTP-YG----DLSHYVDAS-R--QEDRSWMAYVNCARSEQEQNLEL
FQ--KGE-HIYYRAMKAIPPDEELLVWYRFSPSTFLG-IPGVPQPEEFTTK
>Patiria_miniata_XP_038063989.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------RKKGMPMPPQVSLCPSSLPGSAIGVFSTDWIKEGTEMGPYTGRIVRPHE
VATD-RDNQFMWEVFDD-QG----RVSHFVDAS-D--ETLQTWMCYVNCARNDQEQNLEV
FQ--TGS-DIYYRAVKTIPPDQELFVYYGAAYDLFMNSIPIGLTSPEHKGS
>Acanthaster_planci_XP_022106272.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------RKKGMPMPPQVSLCPSSLPGSAIGVFSTDWIKEGTEMGPYTGRIVRPHE
VPTD-RDNQFMWEVFDD-QG----RVSHFVDAS-D--ETLQTWMCYVNCARNEQEQNLEV
FQ--TGS-DIYYRAVKTIPPDQELFVYYGAAYDLFMNSIPMGLSSPDHKGN
>Asterias_rubens_XP_033643527.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------RKKGMPMPPQVSLCPSSLPGSAIGVFSTDWIKEGTEMGPYTGRIVRPHE
VATD-RDNQFMWEVFDE-QG----RLSHFVDAS-D--ETLQTWMCYVNCARNDQEQNLEV
FQ--TGS-DIYYRAVKTIPPDQELFVYYGSAYDLFMNSIPIGLASPEHKNN
>Holothuria_leucospilota_KAJ8038575.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------SKKGMPMPSQVTLCPSSIPGATIGVFTRDWIKEGTEMGPYTGRVVLPNE
VNPS-HNNNFMWEVYDD-HG----ILSHFVDAS-D--EALQTWMCFVNSARNDQEQNLEV
IQ--MGK-EIYYKAIKTIPPDQELLVYYGNTYEMFLG-IPIGLASTEQKIK
>Lytechinus_pictus_XP_054769325.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------KKKGLPMPPQVTLCPSSLPGVVLGVFSTDWIKEGTEMGPYSGRIVRPQD
IPTD-RDNRFMWEVFDD-EG----RLIHFVDAS-E--EATQTWMSHVNCARNDQEQNLEV
FQ--MGS-EIYYRAIKTIPPDQELLVYYGSSFDLFLG-IPCGPVIQEQRT-
>Strongylocentrotus_purpuratus_XP_011660599.2_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------KKKGLPMPPQVTLCPSSLPGVVLGVFSTDWIKEGTEMGPYSGRIVRPQE
IPTD-RDNRFMWEVFDD-EG----RLIHFVDAS-E--ESTQTWMSHVNCARNDQEQNLEV
FQ--MGS-EIYYRATKTIPPDQELLVYYGSSFDLFLG-IPCGPVIQEQRT-
>Lytechinus_variegatus_XP_041482276.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------KKKGLPMPPQVTLCPSSLPGVILGVFSTDWIKEGTEMGPYSGRIVRPQD
IPTD-RDNRFMWEVFDD-EG----RLVHFVDAS-E--EATQTWMSHVNCARNDQEQNLEV
FQ--MGS-EIYYRAIKTIPPDQELLVYYGSSFDLFLG-IPCGPVIQEQRT-
>Anneissia_japonica_XP_033103390.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-----------KKKELPVPNQLSLMPSSLPGCDIGIFSTTWIKEGTEMGPFTGKIVSAED
IDWT-QDNRFAWEVFDS-DG----NFAHFLDAS-E--EAYETWMCHVNCARNESEQNLEV
FQ--LGT-EIYYRALKAIPPNQELLVYYGNFYHTFLG-IPVSPTSAEEHKE
>Saccoglossus_kowalevskii_XP_006813906.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
------LLTRGIPVGVSTPEQVVLSQSSVPGAHVGVFSSTWIKEGTEMGPYTGKIIKQRD
VNPD-KDNPLMWEVFNS-NG----DLKHLVDAS-CIPEEHRSWMSYVNCARNEEEQNLEV
YQ--LGD-DIYYRVTKSIPPDQELLVYYGSSYSMFMG-IPNRHNADTMQKR
>Hydractinia_symbiolongicarpus_XP_057293100.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------KCVLNPLTVNLPNQLRIEPSSIPCQPLGVFTSAWVKKGTKMGPYTGKLFTPDV
RNRF-EDSSYMWEIFDR-NG----EVNHFIDGK-D--ELDRNWMCYVQCARSDQEQNLEI
VQ--HGNEKIFYYALKDIPPNQELLVWYGSNVDMFLG-IPQHRLHFPSK--
>Orbicella_faveolata_XP_020626981.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSFFMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKVEE
LSSD-VDNSLMWEVLNE-DG----TVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFTRR
>Desmophyllum_pertusum_KAJ7339592.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSFIMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEATQMGPYTGRIVKVEE
LSSD-VDNSLMWEVLNE-DG----TVSHFLDAK-G--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYIQFLG-IPGIAPVNDFVRR
>Pocillopora_damicornis_XP_027057588.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSYYMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKVEE
LSSD-VDNSLMWEVLNE-DG----TVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Pocillopora_meandrina_CAH3038087.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSYYMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKVEE
LSSD-VDNSLMWEVLNE-DG----TVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Pocillopora_verrucosa_XP_066021722.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSYYMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKVEE
LSSD-VDNSLMWEVLNE-DG----TVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Porites_evermanni_CAH3178321.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSFFMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKIEE
LSSD-VDNSLMWEVLNE-DG----SVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Porites_lobata_CAH3041123.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSFFMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKIEE
LNSD-VDNSLMWEVLNE-DG----SVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Acropora_digitifera_XP_015773828.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------NDSFFMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKDGTQMGPYTGRIVKIEE
LNSE-VDNSLMWEVLNE-DG----SVSHFLDAK-D--ENPRNWMGFVNCARNEQEQNLDV
FQ--YGG-NIYYRAVKDIPPDQELLVWYGGTYVQFLG-IPGIAPVNDFVRR
>Nematostella_vectensis_XP_032232606.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------ADSYYMAFVSLPEQVTIAPSSIPGVQLGVFSTCWIKEGTQMGPYTGRIVKPDQ
VNYE-IDNNLMWEVLNE-DG----SVSHFLDAK-E--ENPRNWMGFVNCARNEQEQNLEV
FQ--YGG-NIYYRAIKDVPPDQELLVWYGGTYMQFLG-IPGIPPVNDYRRR
>Dendronephthya_gigantea_XP_028407787.1_PRD12_HUMAN_367_residues (PRD12_HUMAN_367_residues)
-------ESLQYMTFVSLPEQVCIGSSSVPGNKHGVFTNCWIKEGTHMGPFTGHVLRKDE
IDLK-MDNNLMWEVLSE-DG----EVSHFIDGK-N--ETPRNWMCFVNCARNEQEQNLEV
FQ--YGN-SIYYRAIKDIPPEQELLVWYGPSYVQFLG-IPGIPPIAERPRR
