>Gymnothorax_javanicus_KAJ8285322.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLS-PGRGQGK
>Megalops_cyprinoides_XP_036383612.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLS-SGRPQGK
>Danio_rerio_NP_001098575.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESCSQRLAWDGDA-KAMQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NNSSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLSSSRNQV-K
>Tachysurus_fulvidraco_XP_026994144.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLAWDGDA-KAMQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-GSTAEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLSSSRNIK--
>Gadus_morhua_XP_030213736.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
PGESGGEERVWTGGDSKA-VQCLTDIFTS--------V-----FTTCDVPENA------L
---FGPCVLSHTT--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-SSSAEGVMWLR
LVQSARDPEEQNLEAYVKN-GQLFYRSLRRVHKDEELLVWYGRELLDLLGLRETTDPPIR
>Gadus_macrocephalus_XP_059921791.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
PGESGGEERVWTGGDSKA-VQCLTDIFTS--------V-----FTTCDVPENA------L
---FGPCVLSTTT--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-SSSAEGVMWLR
LVQSARDPEEQNLEAYVKN-GQLFYRSLRRVHKDEELLVWYGRELLDLLGLRETTDPPIR
>Solea_solea_XP_058492083.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLLWDGDA-KAVQQCLTDIFTS--------V-----FTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKATDKRTA--PYVFRVDTSA--T-NSTSEGLMWLR
LVQSARDREEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLVDLLLLS-PSRAPAK
>Sebastes_umbrosus_XP_037635037.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----FTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLLYRSLRRIEKDEELLVWYGKDLIDLLLLSS-SRAPAK
>Takifugu_rubripes_XP_029686070.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIDLLLLSS-SRAPVK
>Lucifuga_dentata_KAF7650425.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIDLLLLSS-SRATK-
>Thunnus_albacares_XP_044188236.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIDLLLLSS-SRAPAK
>Oncorhynchus_kisutch_XP_020329995.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLLSAGKAPVK
>Salmo_salar_XP_014028143.2_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLL-LSAGKEPVK
>Oncorhynchus_keta_XP_035621526.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLLSAGKAPVK
>Oncorhynchus_mykiss_XP_036835142.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLLSAGKAPVK
>Oncorhynchus_gorbuscha_XP_046207426.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLLSAGKAPVK
>Salmo_trutta_XP_029602390.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQRLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLL-LSAGKAPVK
>Esox_lucius_XP_010863725.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--T-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLL-LSAGKAPAK
>Osmerus_eperlanus_XP_062308023.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKLVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NSTSEGLMWLR
LVQSARDRDEQNLEAYVKN-GQLFYRSLRRIEKDEELLVWYGKDLIELLVLSS-SKAPAK
>Brienomyrus_brachyistius_XP_048860795.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESTTQKLVWDGDA-KVVQQCLTDILTS--------V-----YTTCDVPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTST--A-SCPSDGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLKRIEKDEELLVWYGKDLINLLLLSFSRAQAK-
>Polyodon_spathula_XP_041109340.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKVVWDGDA-KAMQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKCTDKRTA--PYIFRVDTSA--A-NGTSEGLMWLR
LVQSSRDKEEQNLEAYVKN-KQLFYRSLRRIEKDEELLVWYGKDLLELLLLSSSKAK---
>Huso_huso_KAK6492528.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSQKVVWSGEA-KAMQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTA--PYIFRVDTSA--A-NGTSEGLMWLR
LVQSSRDKEEQNLEAYVKN-KQLFYRSLRRIEKDEELLVWYGKDLLELLLLSSSKAK---
>Amia_calva_XP_066568194.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESSSHKVLWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTA--PYIFRVDTSA--A-SGSSEGLAWLR
LVQSARDAEEQNLEAYVKS-GQLFYRSLRRIEKDEELLVWYGKDLIELLLLTSSRAQGK-
>Mobula_hypostoma_XP_062898278.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPNAHKGFWESDASRAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSADKRTV--PYIFRVDTSS--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNVRAPAK-
>Hypanus_sabinus_XP_059844477.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPNAHKGFWESDASRAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSADKRTV--PYIFRVDTSS--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLCNVRAPAK-
>Amblyraja_radiata_XP_032879866.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPHAHR---ESDASRAVQQCLTDIFTS--------V-----YTTCDIPENS------I
---FGPCVLSHTS--LYDSIAFIALKAADKRTV--PYIFRVDTSS--A-NSSSEGSMWLR
LVQPARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNGRPQAK-
>Carcharodon_carcharias_XP_041058288.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPNVHKGFWESDASRAVQQCLTNIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSADKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNVRAQAK-
>Scyliorhinus_canicula_XP_038647716.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPNIHKGFWESDASRAVQQCLSNIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSADKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNVRAQAK-
>Rhincodon_typus_XP_048457166.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPNAHKGFWESDASRAVQQCLTNIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNVRAQAK-
>Chiloscyllium_plagiosum_XP_043552201.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPSAHKGFWESDASRAVQQCLTNIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSADKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYVKN-GQLFYRSLRRIDKDEELLVWYGKELLELLLLSNVRAQAK-
>Latimeria_chalumnae_XP_006002810.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDWSAHKGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSAEKRTV--PYIFRVDTSV--A-NGSSEGLMWLR
LVQSARDTEEQNLEAYVKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLSRSQSK---
>Sturnira_hondurensis_XP_036906929.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRPHSK-
>Myotis_daubentonii_XP_059523466.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRPHSK-
>Dasypus_novemcinctus_XP_058152506.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDLGIQRGILDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Mirounga_leonina_XP_034861450.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Vulpes_vulpes_XP_025853820.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>XP_025853820.1 (best hit for PRDM8_HUMAN_689_residues)
MEDSGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Balaenoptera_acutorostrata_XP_057402211.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Rattus_norvegicus_NP_001358896.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWEGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHK--
>Muntiacus_reevesi_XP_065770096.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWEGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Bos_taurus_XP_005208206.2_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGIQRGIWEGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Loxodonta_africana_XP_064141735.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHNK-
>Homo_sapiens_NP_064611.3_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDTGIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHNK-
>Equus_caballus_XP_023493632.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSSIQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Antechinus_flavipes_XP_051820722.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDTGVQRGVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKDLTDLLLLCSSRSHSK-
>Vombatus_ursinus_XP_027710392.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDTGVQRGVWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NSSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKDLTDLLLLCSSRPHSK-
>Saccopteryx_leptura_XP_066242246.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDSGVQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLCPSRSHSK-
>Chelonia_mydas_XP_037752675.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQKGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLNTARSHSK-
>Varanus_komodoensis_XP_044285315.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDPGVHRGLWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLNTARSHSK-
>Chelonoidis_abingdonii_XP_032652745.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MAETGVQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELTELLLLSTARSHSK-
>Taeniopygia_guttata_XP_030128114.3_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQRGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREREEQNLEAYIKS-GQLFYRSLRRIAKDEELLVWYGKELTELLLLGPARAPAR-
>Corvus_cornix_XP_039407550.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQRGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREREEQNLEAYIKS-GQLFYRSLRRIAKDEELLVWYGKELTELLLLGPARAPAR-
>Tyto_alba_XP_042653114.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQRGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREREEQNLEAYIKS-GQLFYRSLRRIAKDEELLVWYGKELTELLLLSPARAPAR-
>Apteryx_rowi_XP_025937406.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQRGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREREEQNLEAYIKS-GQLFYRSLRRIAKDEELLVWYGKELTELLLLSPARAPAR-
>Apus_apus_XP_051473817.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQRGIWDGDA-KTVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSAREREEQNLEAYIKS-GQLFYRSLRRIAKDEELLVWYGKELTELLLLSPARAPAR-
>Geotrypetes_seraphini_XP_033819609.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDIGAQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPANA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIVKDEELLVWYGKELTDLLLLSPARTHSK-
>Microcaecilia_unicolor_XP_030048340.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDIGAQRGIWDGDA-KVVQQCLTDIFTS--------V-----YTTCDIPANA------I
---FGPCILSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIVKDEELLVWYGKELTDLLLLSPTRTQNK-
>Rhinatrema_bivittatum_XP_029456077.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDVGAQRGIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSDGLMWLR
LVQSARDNEEQNLEAYIKN-GQLFYRSLRRIVKDEELLVWYGKELTDLLLLNPARTHSK-
>Bufo_bufo_XP_040276381.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDAGVQKTIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDVPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARNKEEQNLEAYIKN-GQLFYRSLRRIVKDEELLVWYGKELTDLLLLHPARAQGK-
>Tachyglossus_aculeatus_XP_038615311.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDGGVQGSVWDGDA-RAMQQCLTDIFTS--------V-----YTTCDVPDSA------I
---FGPCVLSHTS--LYDSIAFIALKATDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARGREEQNLEAYIKN-GQLFYRSLRRISKDEELLVWYGKDLTDLLLLSPARAAGT-
>Pseudophryne_corroboree_XP_063776030.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEDTGVQKTIWDGDG-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARNKEEQNLEAYIKN-GQLFYRSLRRIVKDEELLVWYGKELTDLLLLNPTRSQGK-
>Pelobates_cultripes_CAH2301758.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEEAGVQKTIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFIALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARNKEEQNLEAYIKN-GQLFYRSLRRIAKDEELLVWYGKELIDLLLLSQVRTSGK-
>Python_bivittatus_XP_007443972.2_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEESGVPRSIWDGDA-KAVQQCLTDIFTS--------V-----YTTCDIPENA------I
---FGPCVLSHTS--LYDSIAFVALKSTDKRTV--PYIFRVDTSA--A-NGSSEGLMWLR
LVQSARDKEEQNLEAYIKN-GQLFYRSLRRIGKDEELLVWYGKELTELLLLSPVRSQSK-
>Protopterus_annectens_XP_043912684.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MEIASLSKTLWTSDP-KLLHQHFTDVLTS--------V-----HTTQDIPEGT------V
---LGPFILQNTIF---DTIAFIALKCTERRSI--PYVFRVDTAM--LNNPSYAGLPWLR
LVQAAVDKKEQNLEAYLKN-GQLYYRATRKIVKEEELFVWYDEELSALLGFQEIKA----
>Petromyzon_marinus_XP_032805860.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------VKGQWDDDV-RAVQQRLTDIFTS--------V-----FTTCDVPEHA------I
---LGPCLLSSAS--FIDTIAFIALKAADKRTA--PYIFRVDSTA--S-QGAADGVAWLR
LVQPARDRAEQNLEAYLKN-GQLFYRSLRKISRDEELLVWYGRELAALLRLDDTVPHKAA
>Caerostris_darwini_GIY75992.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
-------------------------------NAPNYSLYRLLKHERALYICGD-RGLDHV
RHSSGSLAPFFRVPDSLA---VLTWRCVDKLATS-KQVLKVTLKDQFNSNGLPKIPSWLA
HILPARNPNEQTLEIIVKG-GQLYFRTLRELSPGEELRAWFGQDLADILKLPVIPPN---
>Caerostris_extrusa_GIX95003.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
-----------------------------KIKNVYLKIFRLLKHERALYICGD-RGLDHV
WHPSGSPAPFFRVPRLLG---GAHLEMCDKLATS-KQVLKVTLKDQFNSNGLPKIPSWLA
HILPARNPNEQTLEIIVKG-AALLSNPS-RALPGEELRAWFGQDLADILKLPVIPPN---
>Araneus_ventricosus_GBN08172.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------------------------------MSEPYISV-----VTEDVITCGT-L-----
---LGPLPLSSGSPDSLA---VLTWRCVDKLVTS-KQVLKVSMKDQFNNNGLPKAPSWLA
HILPARNPDEQTLEIIVKG-GQLYFRTIRELSSGEEFRAWFGQDLADILKLPVIPPN---
>Nephila_pilipes_GFS63716.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
----------------AYVGWRTPFIASGMMSEPYISV-----VTEDVITCGT-L-----
---LGPLPLSSGSPDSLA---VLTWRCVDKLSTS-KQVLKVSLKDQFNGSGLPKTPNWLA
HILPARNPDEQTLEIIVKG-GQLYFRSLRELSSGEELRAWFGQDLADILKLPVIPPN---
>Parasteatoda_tepidariorum_XP_042905665.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------------------------------MSESYISV-----VTEEPITCGT-L-----
---LGPLPLTSGSPDSLA---VLTWRCVDKLPPS-KQALKINIRDQANVRGIIKTPSWLA
HILPARNPEEQTLEIVVKG-GQLYFRSLRDITEGQELRAWFGQDLADILKLPMIPPN---
>Stegodyphus_dumicola_XP_035216227.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------------------------------MTESYISV-----VTQELITCGT-L-----
---LGPLPLTSGSPDSLA---VLTWRCIDKLPIS-KQVLKVSLREQNNSRSLPKTPPWLA
HILPARNPEEQNLEVIVKG-GQLYFRALRDIIASEELRAWFGQDLVDILKLPMIPPS---
>Varroa_destructor_XP_022664687.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
-----------------------------MDPNGPLDV-------HGRVVCDRALAKGTP
LGPLGPLVSKGSSPGGLDALAAIAAKAKDNYPDV-DKSTTL----PLSTCLLSGDHLWLQ
GVRTARFAEEQNVEVSIID-GQIQFRTIRDIPPGEELRVWFGVEFGQILRLPAFASLV--
>Branchiostoma_floridae_XP_035670746.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
MGQTMDEGREIRGQT-MTDERDSTELLTG--------V-----WTTTDIPPRT------V
---FGPYVSGTDDV---DPAVLIGIRTKDKRMV--SYAYKVDPGC--C-REAGETLKWLR
LIQPARDRREQNMEAFQRA-GKVYFRSVCHIRRDEELLVWYSDDWAVNIGIPDILPSF--
>Nematostella_vectensis_XP_048577370.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---MFLV---------HWSQLEGLQKNAG--------V-----FTTNHIPANL------V
---FGPYNGPIN----------MALKTRDEKHL--DYILEVTYKCGELRWVTDRHLSWAA
FMSFARCDKEKNLELFWHD-GEFFFRSLRGIKKGEELIVWPTALLCKKIGIPDAVERV--
>Potamilus_streckersoni_KAK3602457.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITEYDIDYGR------I
---FGPFPTIE-NI---DSAHFIGLMTKDTLND--SHRITIDVR-----GERNAILEWLP
YIQPARTEEEQNMEAYTKNDGKIYYRTLRIIRAKETIFVWYSKDFAQILGIPTLKRSNA-
>Ruditapes_philippinarum_XP_060592778.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----IAETDVDYGR------I
---YGPFPAVG-HI---PISHFIGYLTADDRHD--TGSVKINLND--S----VLGNTWLP
YVHPARTVDEQNMEAYMKD-GNIFYRTLRIIRAGEELLVWYSKDFAQILDIPLSHIVQ--
>Mercenaria_mercenaria_XP_053379449.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----TAETDVDYGR------I
---YGPFPAVG-HI---PQSHFIGYLTADDRHD--TGGVKINLND--T----VLGNTWLP
YVHPARTVDEQNMEAYMKD-GNIFYRTLRIIRAGEELLVWYSKDFAQILEIPLSNIVQ--
>Dreissena_polymorpha_XP_052218165.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----IVETDVDYGR------I
---FGPFPAVG-HI---SPTHFIGYLTSDEKRV--TGDFKVDLNE--G----NLDNTWMA
YAQPARTVDEQNTEAYMKD-GNIFYRTLRIIRAKEEILVWYSRDFALILGMNFNVH----
>Mya_arenaria_XP_052776452.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VAETDVDYGA------I
---YGPFPAVG-NI---PSAHFIGYLTSDSVRE--TASVRVDVHD--S----QLGTAWLP
YVRAARSMDEQNMEAYTKD-GHIYYRTLQIIRSGKELLVWYSKDFAQILGIHVSLTP---
>Octopus_sinensis_XP_029635647.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITLSDIDYGQ------I
---FGPFPISQTKA---DPATFIGLLTKDKQVD--TILLKVDLMV--D---KDRTVEWLP
YIQPARDEDEQNIEAYMKD-GYVYYRALRIIRKNEDLFVWYSKDFSQILAIPEVQR----
>Mizuhopecten_yessoensis_XP_021346600.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITVCDIDYGR------I
---FGPFPVQVALM---DPTYVIGMLTQDTRHD--SPAIEVDPDA--S-NGVARADGWLA
YIQPAREEEEQNVEAYMKN-GQVFYRTLRIIKEREELLVWYSKDFCQLIGIPDVRRS---
>Pecten_maximus_XP_033735855.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITVCDIDYGR------I
---FGPFPVQVALM---DPTYVIGMLTQDTRHD--SPSIEVDPDA--S-SGLARADGWLA
YIQPAREEEEQNVEAYMKN-GQVFYRTLRIIKAREELLVWYSKDFCQLIGIPDVRRS---
>Ylistrum_balloti_XP_060081399.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITICDIDYGR------I
---FGPFPVQVALM---DPTYVIGMLTQDTRHD--SPAIEVDPDA--N-VGVARADGWLA
YIQPAREEEEQNVEAYMKN-GQVFYRTLRIIKAGEELLVWYSKDFCQLIGIPDVRRS---
>Mytilus_californianus_XP_052071097.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITVVDIDYGH------I
---FGPFPISSTAM---DPTYAIGMLTQDTQHQ--GPMLEIDPSI--N-NGLARGMEWLA
YINPARNEDEQNMEAYVKN-KEVFYRALRIIKSREELLVWYSKDFCQLIDVPEVKRI---
>Saccostrea_cucullata_XP_062603480.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MT--------V-----STNTDIDYGI------I
---FGPVNVESSAL---NPTSLIGLMTRDGRTEKDDTNLSLDPFE--M-SKRTHALEWLI
CIPPARNEEEQNMEAYSKG-GKMYYRTLRIIKAGEPLFVWYSKDFCQTLQIQIIKRH---
>Saccostrea_echinata_XP_061169068.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MA--------V-----STNTDIDYGV------I
---FGPVNVESSAL---NPTSLIGLMTGDGRTEKDDINLSLDPFE--M-SKRTHALEWLI
CIPSARNEEEQNMEAYSKG-GKVYYRTLRIIKAGEPLFVWYSKDFCQALQIQIIKRH---
>Ostrea_edulis_XP_056018607.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MA--------I-----LTSSDIDYGV------I
---FGPVNVESPAM---NPTRLIGLMTEDTRCEKDDRCLSVDLVE--M-SKRTRALEWLI
CIPSARNEEEQNMEAYTKG-GKVYYRTLRIIKAGEPLFVWYSKDFCHVLHIKDIKRQ---
>Crassostrea_virginica_XP_022319170.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------ML--------V-----YTSTDLDYGV------I
---FGPIVVQSSLL---NPRNLIGLLTEEKRNKANDAYISLDLLE--M-SGRNPTLDWLV
CIPSAQNETEQNMEAYSKD-GEVFYRTLRIIRSGEPLFVWYSKDFCQLLHIHSPKRY---
>Candidula_unifasciata_CAG5114640.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------------------------QANMG--------V-----VTVNDIDYGQ------I
---FGPFPTHFTVT---DPAYIIGMLTNDKQPD--GIVVRVDAEE--R-SDGIRVVDWLP
YVSPARDEEEQNMEAYLKE-GGIYYRTLRIVKAGEELLVWYSKDFTKILGIPELQTN---
>Physella_acuta_XP_059158658.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTITDIDYGQ------I
---FGPFPAHI--T---DPAYVIGMLTNDKPSN--GAVVRVSLT-----SSCLMTVDWLP
YVSVARDGDEQNMEAYPKD-GGVYYRTLRIVKAGEELLVWYSKDFTQLLGVPELQTN---
>Aplysia_californica_XP_035825131.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTVTDIDYGQ------I
---FGPFPSDVTST---DPVYVIGMLTSDKHPG--GMVIRVDTNE--R-RDGQRPLDWLS
YVSPARDEEEQNMEAYLKD-GAVYYRTLRIVKSGEELLVWYSKDFSQILGVPELQTN---
>Biomphalaria_pfeifferi_KAK0049185.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
------------------IILPSIQDAMG--------V-----VTVSDIDYGQ------I
---FGPFPTHVTAT---DPAYVIGMLTCDRQPD--GVLLRVDTEE--R-RGGIRNIDWLP
YVSPARDEEEQNMEAYPKE-GGVYYRTLRIVKAGEELLVWYSKDFTQLLGVPELQSN---
>Biomphalaria_glabrata_XP_013094943.2_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTVSDIDYGQ------I
---FGPFPTHVTAT---DPAYVIGMLTCDRQPD--GVLLRVDTEE--R-RGGIRNIDWLP
YVSPARDEEEQNMEAYPKE-GGVYYRTLRIVKAGEELLVWYSKDFTQLLGVPELQSN---
>Bulinus_truncatus_KAH9504044.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTVSDIDYGQ------I
---FGPFPTHVTAT---DPAYVIGMLTSDRQPD--GVVLRVDTEE--R-RGGVRKLDWLP
YVSPARDEEEQNMEAYPKE-GGVYYRTLRIVKAGEELLVWYSKDFTQILGVPELQSN---
>Elysia_chlorotica_RUS90089.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
--------RFI-----SLRKWAKSWSKMG--------V-----VTVADIDYGQ------I
---FGPFPTHITAT---NPAYIIGMLTRDKQPE--GAVLKER----------KNWLNWNP
AVKSCRHIFLT-----DRT-ARGTSRTLRIVRAGEELLVWYSKDFTHILGIPELATN---
>Elysia_marginata_GFR78409.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTVADIDYGQ------I
---FGPFPTHITAA---NPAYIIGMLTRDKQPE--AAIVKVNTEE--L-RDGPGCLDWLP
YVSMARDEAEQNMEAYLKE-GGVYFRTLRIVRAWEELLVWYSKDFTHLLGIPELASN---
>Elysia_crispata_KAK3761597.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTVADIDYGQ------I
---FGPFPTHITAT---NPAYIIGMLTRDKQPE--GVVLKVNTDE--L-RDGPGYLDWLP
YVSTARDEAEQNMEAYLKE-GGVYFRTLRIVRAGEELLVWYSKDFTQLLGIPELASN---
>Haliotis_rufescens_XP_046359405.2_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VPVSDIDYGQ------I
---FGPFPSHLAMA---DPAYLIAMLTNDKRQD--GVIIKLDLSE--R-KEGIKAVDWLP
YIHPARNEEEQNVEAYMKE-GQVYYRTLRIVKAGEELLVWYSKDFCQLLNIPD-------
>Haliotis_rubra_XP_046574196.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VPVSDIDYGQ------I
---FGPFPSHLAMA---DPAYLIAMLTNDKRQD--GVIIKLDLSE--R-KEGIKAVDWLP
YIHPARNEEEQNVEAYMKE-GQVYYRTLRIVKAGEELLVWYSKDFCQLLNIPD-------
>Gigantopelta_aegis_XP_041364257.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITVTDINYGQ------I
---FGPFPSHLAMA---DPVNLIASLTNDKRQD--GVILKVDPLE--R-KEGIKAVEWLP
YIQPARDEEEQNMEAYLKE-GHVYFRSLSIIRAAEELLVWFSKDLCQLLVIPELPRHIDK
>Ridgeia_piscesae_KAK2189698.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITTGDIAEGT------S
---FGPIPRSLTLV---DLTLLIGHMTCDSRPD--VHTVKLDVNK--Y-SCGSALGEWLP
YVRAARYDNERNVQLSL-DGGHMYYRVTRAIDSGRELFVWYSVEYARSLALPPILPDY--
>Capitella_teleta_ELT97137.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----VTTEEVSEGQ------T
---FGPIPMTLTLA---EPAVLIGHRTCDTPPD--IHAVKLDITA--Y-REGIGLAEWVP
YVQAAREASEQNMEAFLNSSGQLYYKTIKALSPGSELFIWYSNDYAAYLKVPPILP----
>Paralvinella_palmiformis_KAK2149395.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---IFLD-WGLRKNPN-SRSLIRLFWIMG--------V-----LITVRVHEGK------T
---FGPIPANLTLT---DPTLLIGHMTSDNRPD--VHTVKIDIHE--Y-ASGTRLAEWLP
YVQAARDEHEQNLEALI-QNGQLYYRFLKTVPPHGELLVWYSEDLARIIGVPQLNEVH--
>Owenia_fusiformis_CAH1794754.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
----------LKGRHHTRIQIESAYCKMG--------V-----ISLKEIEEGL------T
---FGPFPVSLTYH---DPSYLIGHMTFDKRPD--IPAMEVDICD--E-KVS-KNLEWMP
YVSSARDDNEKNMDAIN-KDGHIYYKTIRHVEKNDELLVWYSTDFANSLRIPDITPFK--
>Lingula_anatina_XP_013421582.1_PRDM8_HUMAN_689_residues (PRDM8_HUMAN_689_residues)
---------------------------MG--------V-----ITSEDIPCGR------E
---FGPYPVGPSIL---DPGVGIAWRTQHFVEE--EHKIKINPD--------LEPETWLP
LVQTAKDIRDQNLEALLRE-GRVYYRVIRHIPALEELLVWYGDEFAAAIGLKDIKDGHN-
