>Tachysurus_fulvidraco_XP_026988833.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-EGLLECVNECVLSVLGLIPRGLTLGPSLAE--DGQMGLWCVGWTLQSGTL---LGLEDL
DKV----AG--------------KE---ETAEV-----S---------RCLERAKGQISD
RTYWMRFACSAPNEDQRNVIVHEV--------DGRLCFKTCKDISQGTELLVWPEVPKIL
NEPVKNY--------
>Danio_rerio_NP_001315204.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
---GSGNKRDSIHSALRSVPLGLTVGPSLAE--DEQLGLWCVGRVLKKDTL---LGLEEP
GETI---SK--------------EK---EEGLQ-----N---------ASQSVYKREISD
EVCWMQFACSAQSAEESNVSVLKV--------DGRLGLKVCRDIQPGTELLLWESHPEAV
TEEETPQVETCEN--
>Oncorhynchus_keta_XP_035591423.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-PSLNQDFLHSVLNAVPRGLTVGPSLAN--DGQLGLWCVGHALQKGML---LGVENQ
SNTFDQRED--------------FT---ESLME-----E---------AYHTIIKGHLWD
RCYWIRFACNARRKDEQNVTVHEV--------DGSLCLRACKDINPGTELLLWSFLADPP
EHDGSQG--G-----
>Oncorhynchus_gorbuscha_XP_046205649.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-PSLNQDFLHSVLNAVPRGLTVGPSLAN--DGQLGLWCVGHALQKGML---LGVENQ
SNTFDQRED--------------FT---ESLME-----E---------AYHTIIKGHLWD
RCYWIRFACNARRKDEQNVTVHEV--------DGSLCLRACKEINPGTELLLWSFLADPP
EHDGSQG--G-----
>Oncorhynchus_mykiss_XP_021441541.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-PSLNQDFLHSVLNAVPRGLTVGPSLAN--DGQLGLWCVGHALQKGML---LGVENQ
SNTFDQSED--------------FT---ESLME-----E---------AYHTIIKGHLWD
RCYWIRFACNARRKDEQNVTVHEV--------DGSLCLRAYKDINPGTELLLWSFLADPP
EHDGSQG--G-----
>Salmo_salar_XP_013981912.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-PSLNQDFLHSVLNAVPRGLTVGPSLAN--DGQLGLWCVGHALQKGML---LGVENQ
SNTFDQSED--------------FT---ESLME-----E---------AYQTIIKGHLWD
RCYWIRFACNARRKDEQNVTVHEV--------DGSLCLRACKDINPGTELLLWSFLADPL
EHDGSQG--G-----
>Salmo_trutta_XP_029622888.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-PSLNQDFLHSVLNAVPRGLTVGPSLAN--DGQLGLWCVGHALQKGML---LGVENQ
SNTFDQSED--------------FT---ESLME-----E---------AYQTIIKGHLWD
RCYWIRFACNARRKDEQNVTVHEV--------DGSLCLRACKDINPGTELLLWSFLADPL
EHDGSQG--G-----
>Esox_lucius_XP_012994496.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--G-SSLTQDPLLNVLKAVPRGLTVGPSLAN--DGQLGLWCVGNALNKGVF---LGLEDQ
NKAIDQSGD--------------FS---ESLVE-----E---------TFRRIIKGHLWD
RCYWIRFACNARRQEEQNVTVHEV--------DGSLCLRAYKDIMPGTELLLWSFLAGPL
DHHGSEG--G-----
>Osmerus_eperlanus_XP_062326591.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-NG-SLDQAFYLYSMLRSVPRGLAVGPSLAN--DGQLGLWCVRCAVPRGAM---LGLESQ
AQAHCHREG--------------KR---EEEMD-----G---------EWQGVVNGPLWD
QFYWVRFACNAKGKEERNVTVHQL--------AEGLFLRACQDISPGTELLLWVGESQTL
PEPLEKS--VGGQTG
>Gymnothorax_javanicus_KAJ8248913.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-QD-SLPGQDSLHRVLKAVPRGLTVGPSLAS--RDRLGLWCVGHALQKGAL---LGLQED
QVK---STD--------------NR---EGGSE-----V---------PCATVFAGPGGG
DSYWIRFACFAKSKEEQNVSVYEV--------GGRLCLRACEYINPGTELLLWMEDQQCP
PQTLGQE--KCLK--
>Megalops_cyprinoides_XP_036391046.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KD-SPPGQESLHSVLNAVPRGLTVGPSLAN--NGRLGLWCVGRALQKGAL---LGLQED
QAK---HPE--------------TQ---ESGLE-----E---------PCTAVASGPCGD
KSYWIRFACIARSKEKQNVSVHEV--------GGRLCLRACEDISPGTELLLWLEDQQCS
TEPLKQD--TSQEV-
>Gadus_morhua_XP_030233350.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-HDTPLGSSPLMALLSSLLPKGFAVGPSRVS--EGRLGLWWVGRCLDVGTV---LGREGD
TEWSWIQSHEPDRDPPNRHPGGHDPAALDACPKGAQIYSTNAREETRGMTAD--EEVLLD
KVFWISFASHTLCKARQNVEV-------CGGVSGGARLRVSQQIQTGSELLLYRCSAAGV
TAAAPQSQSENHC--
>Gadus_macrocephalus_XP_059926913.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-HDTPLGSSPLMALLSSLLPKGFAVGPSRVS--EGRLGLWWVGRCLDVGTV---LGREGD
TEWSWIQSHEPDRDPPNRHPGGHDPVALDACPKGAQTYSTNAREETRGMTAD--EEVLLD
KVFWISFASYTLCKARQNVEV-------CGGVCGGARLRVSQQIQTGSELLLYRCSAAGV
TAAAPQSQSENHC--
>Lucifuga_dentata_KAF7659666.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-------LSPLASLLSSVLPRGFAVGPSQMC--DGRVGLWWVGHSLQAGCL---LGKEGD
TAWTSLRQTVPNCHPASHSRECELTVTSDPESKEGQSNSIEAEKEMMDIVAA--TECVLE
KALWISFACQALCRAQQNVAVQCACGERCVCECVDVCLRVCRDIQPGTELLLYEGTEGKQ
EV-----DTQDNA--
>Takifugu_rubripes_XP_011608116.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--LTPPLPSALTSILSTLLPCGFAVGPSRFC--EGRLGLWWVGCMLKPGSL---LGRDGD
LRSSSVHQSERRKSEATVCC--------DSRT--TQTGCTEETKELMLMAAN--KEAL--
QHMWISFACQVQSREQQNVVMQCACGED---ECVCVRLRVCRDIHPGTELLLCRDTVGKL
QAGDETTVLDTNK--
>Solea_solea_XP_058486206.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--LGPPIPSALTSFLSMLLPPGFAVGPSQLC--EQRLGLWWVGRSLGAGSL---LSREGD
TAWTWK----YHTDQMFHEQGAELSVNSESET--GQSTK-T-EKLMIEIAAN--KEAPLK
KPVWINFACQAQSSAQQNVAVHCACGDKCVAECMDVCLRVCEDVQPGTELLLYKDTVGES
KIM-DKTDPHDNL--
>Sebastes_umbrosus_XP_037615341.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
--LAPLVPSAVASFLSTLLPCGFAVGPSRLC--GGRMGLWWVGRSLEAGAL---LGRDGD
TEWTSDRTAEYHTDPTNHSPDGQLTVST----------E-AEKALMERAANK--EEASLE
RAVWIKFACQARSRAQQNVSVQCACGEVCAGECVDVCLRVCRDIQPGTELLLYGEDTVGT
RQTTDEPDAQDNA--
>Thunnus_albacares_XP_044212864.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
---MAGLPSALASFLSASLPRGFAVGPSLFC--EGRLGLWWVGRSLEAGCL---LGREGD
AGRASKH----RTDPPTHCREDEFTETSQSIT--DQTNS-TEEKALTDLTAD--KEALLQ
KSVWISFACQARSRAQQNVTAQCACGEVCAGECADACLRVCRDIQPGTELLLYGDTVVKS
QTADEPPDTRDNP--
>Amia_calva_XP_066556747.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-SDSDPGPQSPC-RLLHSLPLGLAVGPSLVQ--DRHMGIWCVGQALQKGTI---FRPLEK
QARSNDDQ--------------------VSKEG-----V----GQKAEGAVAS--VPLEE
AGHWMRFTCEARNAEEQNVRVVRA-------RGGELCLNVLKDIRPGMELLLHREEQREE
AAEGDDRQRGMQAV-
>Dasypus_novemcinctus_XP_004457976.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-EDCPLGPAGAI-FALKNLPRGLALGPSLAV--EQRLGIWCVGEPLQPGLL---WGPLEE
ESVSEEKVE--------------GA---KYREE-----E----DLSLGPWQDV--CACER
SSGWTSLVQRGRQENEGNVAPVWI--------SERLHLQVYQVVLPGSELLLWPHPLPES
PNPTQPRLEEEAA--
>Loxodonta_africana_XP_003412301.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-QDFRPEPARAI-LALKNLPRGLALGPSLAK--EQRLGIWCVGEPLQPGLQ---WGPLEE
RLVSEEKGK--------------QV---DTRHK-----E----DLSLGPWQDI--CACEQ
SSGWTSLVQQGRRESEGNVAPVRI--------GKRLHLQVYRVVLPGAELLLWPWPPSDD
PSPTQPRLEEEGA--
>Homo_sapiens_NP_079017.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDVPPEPTRDI-LALKSLPRGLALGPSLAK--EQRLGVWCVGDPLQPGLL---WGPLEE
ESASKEKGE--------------GV---KPRQE-----E----NLSLGPWGDV--CACEQ
SSGWTSLVQRGRLESEGNVAPVRI--------SERLHLQVYQLVLPGSELLLWPQPSSEG
PSLTQPGLDKEAA--
>Rattus_norvegicus_XP_003749580.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
----KGYTSPAI-LALRSLPQGLAMGPSRSR--KQHLGVWCVGAPXQPGLH---WGPLEE
EAVL-EKGE--------------GM---KTSHE-----E----DFSLAPCGAI--CTXKQ
SSSWTSLVQPGRLQSDGNVSLVWV--------SEKLHLQVSQTGLPGVELLLRPQPPPKS
LNVLHPKLEEVAA--
>Muntiacus_reevesi_XP_065801223.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDVPPGQTRAI-LALKNLPRGLALGPSLTA--EQRLGVWCVGEPLQPGLL---WGPLEE
ESVFKQKGN--------------GV---EPKRK-----E----AVSLDSWGDV--CACEQ
SAGWTSLVQRGRLEGEGNVAPVWI--------SERLHLQVSRLVLPGFELRLWPQRPSEG
LSPTQPRLEEVAS--
>Bos_taurus_NP_001180086.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDVPPGPTRAI-LALKSLPRGLALGPSLTA--EQRLGVWCVGEPLQPGLL---WGPLEE
GSVSEQKGN--------------GV---EPKRK-----E----DVSLGSWGDV--CACEQ
SAGWTSFVQLGRLEGEGNVAPVRI--------GERLHLRVSRRVLPGFELRLWPQLPSEG
PSPPQPRLEEASS--
>Balaenoptera_acutorostrata_XP_007181226.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFSPGPTRAI-LALKSLPRGLALGPSLTK--EQRLGVWCVGEPLQPGLL---WGPLEE
ESVSEQKGH--------------GV---KTKQK-----E----DVSLGPWGDV--CACEQ
SSGWTSLVQRGRLEGEGNVAPVRI--------SERLHLQVYRVVLPGFELLIWPQPPSEG
LSPTQPGLEEEAS--
>Saccopteryx_leptura_XP_066218149.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-EDFPPWPTRAA-HALKSLPRGLALGPSLVE--KQRLGVWCVGEPLQPGLL---WGPLQE
ESVSEHKGE--------------GV---TSQQE-----K----DVSLGPWGDV--CACEQ
SSGWTSLVQRGRLEGEGNVAPMWI--------SERLHLHVCRVVLPGCELLLWPQSPSEG
LRPTQPRLEEAA---
>Myotis_daubentonii_XP_059565452.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-RDRPAWPTRAV-HALKTLPQGLALGPSLVE--KQRLGVWCVGKPLQPGLL---WGPLGE
EAASERKDE--------------GV---QPRQE-----E----DVSPGLWGDV--CACER
SSGWTSLVQRGRLEGEGNVTPVWI--------SERLHLQVYRVVLPGFELLLWPRSPSER
VSPTQSRLEEEAA--
>Sturnira_hondurensis_XP_036883864.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDSPPWSIQAV-LALKSLPRGLALGPSLME--KQRLGVWCVGEPLQPGVL---WGPLEE
ESDPEQKGE--------------GV---KPWQK-----T----DVSLGPWGDV--CACEQ
SSGWTSLVQRGRLEGEGNVAPVWI--------SERLHLQVNQVVLPGFELLLRPRSPSEG
LGPTQARPEEEAA--
>Equus_caballus_XP_001490832.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-RDFPPGPTRVL-RALQSLPRGLALGPSLAE--DQRLGVWCVAEPLQPGLL---WGPLEE
ECDSEQKGE--------------AV---KPRQE-----E----DVSLGPWGDA--CACEQ
SSGWASLVQRGRLEGEGNVAPVWI--------SERLHLQVSRVVLPGFELLLWPRPPAED
LSPAQPRLEAAAA--
>Mirounga_leonina_XP_034868609.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFPPGATRAF-LALKSLPRGLALGPSLAE--EQRLGVWCVGEALQPGLL---WGPLEE
ESVSEQKDE--------------GV---KPRQE-----E----DVSLGPWGDV--CACER
SSGWISLVQRGRLEGEGNVALVRV--------SEKLHLQVYQVVLPGSELLLWPQPPSAG
LSPTQPGLEEEAA--
>Lynx_pardinus_VFV18658.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFPPGPTRAF-LALKSLPRGLALGPSLAE--EPCLGVWCVGEPLQPGLL---WGPLEE
ESVSKQKEE--------------GV---KLRLE-----E----DVSLGPWGDV--CACEQ
SSGWISLVQQGRLEGEGNVALVRI--------NEKLHLQVYRVVLPGFELLLWPQPPSDG
LSPTQPRLEEEAA--
>XP_025859853.1 (best hit for PRDM17_HUMAN_720_residues)
-KDFPPEPTRAV-LALQSLPRGLALGPSFAE--EQRLGVWCVGEPLQPGLL---WGPLEE
ESVPEQKDE--------------GV---KPRRK-----E----DVSLGPWGDV--CACEQ
SSGWISLVQRSRLESEGNVAPVRI--------SEKLHLQVYRIILPGFELLLWPQPPSDG
LSHTQPRLEEAA---
>Vulpes_vulpes_XP_025859853.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFPPEPTRAV-LALQSLPRGLALGPSFAE--EQRLGVWCVGEPLQPGLL---WGPLEE
ESVPEQKDE--------------GV---KPRRK-----E----DVSLGPWGDV--CACEQ
SSGWISLVQRSRLESEGNVAPVRI--------SEKLHLQVYRIILPGFELLLWPQPPSDG
LSHTQPRLEEAA---
>Erinaceus_europaeus_XP_007519134.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFPIGPTLTT-FALKSLPRGLALGPSLVE--EQRLGIWCVGEPLQPGLL---WGPLQE
ESVSQSQCE--------------IV---KPQKE-----Q----DISRGPWGDV--HACEQ
SSGWTSLVQHSRQEDEGNVTLVRI--------SDRLHLQVYRVVLPGFELLLGSGPPSEG
LSPAQPRLEEEE---
>Galemys_pyrenaicus_KAG8519552.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDFPPGPTRAT-LALKSLPPGLALGPSLAK--KQRLGVWCVGQPLQPGLL---WGPLEE
ESLS-QQGE--------------GV---SRQQE-----E----DVPLGPWGDV--CACEQ
SSGWTSLVQRGRLEDEGNVAPVRI--------SGRLHLQVCWAVLPGFELLLRPGPPSAG
LSPIQPKLKKEAA--
>Chelonia_mydas_XP_027687667.2_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-RDPPAQPGASC-GALRSLPPGLALGPSLAQ--EPGMGVWCVGRALPPGAL---LGPRPE
E----ELGC--------------AA---ERAPS-----E----AIQSGCCSDE--SICER
SPSWRRLVKRGRGEDEANVALVWI--------SGRLHIRVRRPIAAGTELLYWPTEAQAG
PAQVEGRMLQSAS--
>Apus_apus_XP_051477694.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
GPGPGGLPRAPC-PALRSLPPGLALGPSLSGLSAQAVGVWCVGRALPAGLL---LGPPGG
A----RQAA--------------------------------------------------A
GPGWSGLVQRSPKEAEANVVLGRA--------DGRL--RLRRPVAAGAELLYWPEEARGA
AAEERRSEGEGIA--
>Python_bivittatus_XP_007421831.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-------GSWPF-CPAWHLPRGLAVGPSLSS--EKGLGVWCVGRALQPGMLL-LLGPQGE
E----QKAA--------------T-------SL-----S----AFPLPSWKKA--SACNR
ISNWRSLVKQSRVEDEANVMLEWI--------NGELHIRVCCPIDVGSELLCWLTESQAS
PTCLENDSLAHTS--
>Varanus_komodoensis_XP_044291756.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-------GGWFR-CPAWRLPSGLALGPSHYA--ESGLGVWCVGRALQPGMRLRLIGPREE
E----EKEA--------------A-------TS-----V----TFPSSWGKEP--CVCDR
IPSWRSLVKQSKDETEANVSFIWI--------NGELHIQVCRFLAAGTELLYWLAESQAS
PACLEKKAPARIS--
>Geotrypetes_seraphini_XP_033784040.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-SDPLLQAGFCC-LTLYSLPRGLALGPSLDQ--DSSLGVWCVGEGLQEGAL---FGPIEG
D----LETK--------------DA---RAETE-----K----QTQAGVWKST--STLHK
SFSWVSALKKAKSSKERNVSCVQL--------RGLPFLRVCKSIQPGTEMLLGTMECRAS
TAHEDGRT-------
>Microcaecilia_unicolor_XP_030056725.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-SDSLLQAGCCC-LTLYSLPRGLALGPSLDQ--DSSMGIWCVGEGLQEGAL---FGPIEG
D----PETK--------------GA---RADTG-----E----QTRTVVWKDT--STLHK
SFSWVSAVKKAKSAEEQNVSCLQL--------HGLLYLQVCKSMQPGTQMLLGTVECGER
TAHEDERAWPQAA--
>Pelobates_cultripes_CAH2325946.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-PVPAGCTQDAILQFLSSLPRGLALGPSLSL--KEGLGLWWVGQTLDAGSLLPTPSHKSD
NSLSESEER--------------LS-----------------------------SFLLET
DAAWLRFVRRC--TKRENVRPCQY--------RGQVYLKVVTSLKPGSELLFQQEVQKAC
TINGDDLPGPEKL--
>Bufo_bufo_XP_040265103.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-SPPVDRTQDVIQKVLRELPCGLALGPSLSQ---DGIGLWCVGRTLPSGALIASCGPVPE
DELSLPEEG--------------PT-----------------------------SSLQHG
ECHWLRFVRRS--AGKENVKFYRL--------KGVLQLQVTTSVQPGSELLLPQEEHVVC
DQDDEGTTPPSPN--
>Pseudophryne_corroboree_XP_063800607.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
---PVEDTQDATWQALHSLPRGLALGPSLSQ--EEGLGLWCVGKPLPSGSFLPPYSPGCE
DGLSVSEE-----------------------------------------------LSPET
GLRWLRFVRRS--AQQMNVKLCWL--------GGCLRLQVIVPIQQGSEVLFPLEKHTTL
EDTGEMLQKRAA---
>Polyodon_spathula_XP_041073823.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDSIPEKVSPC-RVLHTLPPGLAAGPSLAQ--GSRIGIWCVGQTLQKGIF---FGPVEE
RLKYSGSV--------------------EAAED-----E----GDKVDGLDNT--KSVEE
AVNWMKFACSARSEEEQNVAVFHF--------HGKLHFRVLKVIEPGTELLLRPEEGRKA
SSEEGQSREDAVA--
>Huso_huso_KAK6472521.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDSIPEKVSPC-RVLHTLPPGLAAGPSLAQ--VSRIGIWCVGQALQKGII---FGPVKK
QLKYSGSV--------------------EAAED-----E----GDKIDGLDNT--PSLVE
AVNWMKFACSARSEEEHNVAAFQS--------HGKLHFRVLKVIEPGMELLLGPEEGRKD
SSEEGPCREDAVA--
>Latimeria_chalumnae_XP_064423091.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-WDSAAYMGLPCWRALGTLPPGLAVGPSRAQ--EKRMGIWCVETALQKGIF---FGPLEG
DLERHDITG--------------RR---TPQEP-----R----ETGSEDLQKV--PGVER
LMNWMSFASLAQSKEERNVAEFTL--------RGKIYFRVCKVIEPGAELLVWPEDATVC
PEEEEDEDEEEEL--
>Amblyraja_radiata_XP_032895125.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDTPVKLGLPC-RAFYTLPAGLAAGPSHAQ--KDRLGIWCVSTVLLRGTF---FGPLEG
KLECDDVVG--------------SA---SIISK-----KVGADSGV--KTGEA--QVSPS
VSNWMRYANKAGTKKDSNAAIFRY--------SGKIYFRVCKNIKMGQELLLWPEKNRVR
TAKKVNRAQEENE--
>Mobula_hypostoma_XP_062919310.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-RDTPVELGLPC-RAFYTLPAGLAAGPSQTQ--ENQLGIWCVSKALPRGIF---FGPLEG
KLECYDVVG--------------RT---SLISK-----ELGDSGEKAGE---T--EVNQS
LSNWMRYANKARTKEESNAVIFQF--------YGKIYYRVCKNIELGQELLLWPEENLVQ
SAQGLSNTQKDND--
>Hypanus_sabinus_XP_059831438.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-RDTPVELGLPC-RAFYTLPTGLAAGPSQTQ--ENQLGIWCVSKALPRGIF---FGPLEG
KLLCYDVVG--------------KT---SLISK-----ELEDSGEKAGE---T--QVNQS
LSNWMRYANKARTKEESNAIIFQF--------YGKIYYRVCKNIELGQELLLWPEENLVQ
SAQGLSNTQKDND--
>Chiloscyllium_plagiosum_XP_043562193.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDTPVDLASPC-RAFYTLPPGLAAGPSQIQ--KQKLGIWCVSKALPRGVF---FGPLEG
KLECDDVNG--------------IA---SFISK-----EFRENGDKVELPELQ--RVNQS
FSNWMRYANKAKTKEESNAVIFQF--------YGKIYYRVSKTIELGQELLLWPEENQVQ
VTCEVKDSHTDKE--
>Rhincodon_typus_XP_020381208.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDTPVEFGWPC-RAFYTLPPGLAAGPSQTQ--KKKLGIWCVSKALPRGVF---FGPLEG
KLECDDVNG--------------IP---CFISK-----EFRENGDKVELPELQ--RVNQS
FSNWMRYANKAKTKAESNAVIFQF--------YGKIYYRVSKTIELGQELLLWPEENQVQ
VTHKIKNAHTDKE--
>Carcharodon_carcharias_XP_041054074.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDTPVELGLPC-RAFYTLPPGLAAGPSQTQ--KNQLGIWCVSKALPRGIF---FGPVEG
KLECDDVNG--------------IA---SFISK-----ELRENNEKAGLPEAQ--RVNQS
FSNWMRYANKAKTKEESNAVIFQF--------YGKIYYRVSKTIELGQELLLWPEENQVQ
VIKDIDNVHEDIE--
>Scyliorhinus_canicula_XP_038663338.1_PRDM17_HUMAN_720_residues (PRDM17_HUMAN_720_residues)
-KDTPVALGLPC-RAFYTLPLGLAAGPSQTR--ENQLGIWCVSKALPRGVF---FGPLEG
KLECDDVNG--------------LA---SSLSK-----ELREKDEK--APETQ--KVNQP
FSNWMRYANKAKTKEESNAVIFQL--------YGKIYYRLSKIIELGQELLLWPEENQIQ
IMQDVNNAHKDSE--
