raalist='/panbanques/acnucdb/pub/banques_raa'
export raalist
raadisable='/panbanques/acnucdb/racnuc.linux/racnucd_disable.fifo'
export raadisable
emglib='/beegfs/banque/acnucdb/emglib /beegfs/banque/acnucdb/emglib'
export emglib
embl='/beegfs/banque/acnucdb/embl/index /beegfs/banque/acnucdb/embl/flat_files'
export embl
genbank='/beegfs/banque/acnucdb/genbank/index /beegfs/banque/acnucdb/genbank/flat_files'
export genbank
genbankseqinr='/ftp/genbank/index /beegfs/banque/acnucdb/genbank/flat_files'
export genbankseqinr
genbankseqinrok='/ftp/genbank/index /ftp/genbank/flat_files'
export genbankseqinrok
emblwgs='/beegfs/banque/acnucdb/embl/wgs/index irods://lbbeZone/home/banques/emblwgs/flat_files'
export emblwgs
hobacnucl='/beegfs/banque/acnucdb/hobacgen/genomic/index /beegfs/banque/acnucdb/hobacgen/genomic/flat_files'
export hobacnucl
hobacprot='/beegfs/banque/acnucdb/hobacgen/protein/index /beegfs/banque/acnucdb/hobacgen/protein/flat_files'
export hobacprot
hobacnucg='/beegfs/banque/acnucdb/hobacgen/cg/genomic/index /beegfs/banque/acnucdb/hobacgen/cg/genomic/flat_files'
export hobacnucg
hobacprcg='/beegfs/banque/acnucdb/hobacgen/cg/protein/index /beegfs/banque/acnucdb/hobacgen/cg/protein/flat_files'
export hobacprcg
nbrf='/beegfs/banque/acnucdb/nbrf/index /beegfs/banque/acnucdb/nbrf/flat_files'
export nbrf
swissprot2019='/beegfs/banque/biomaj/databases/acnuc/uniprot_2019_11/index/ /beegfs/banque/biomaj/databases/acnuc/uniprot_2019_11/flat_files/'
export swissprot2019
swissprotpev='/beegfs/banque/biomaj/databases/acnuc/uniprot_2021_07/index/ /beegfs/banque/biomaj/databases/acnuc/uniprot_2021_07/flat_files/'
export swissprotpev
swissprot='/beegfs/banque/acnucdb/swissprot/index/rel_2023_07_loc/ /beegfs/banque/acnucdb/swissprot/flat_files/rel_2023_07_loc/'
export swissprot
swissprotold='/beegfs/banque/acnucdb/swissprot/index/rel_2023_04_sauvegarde_locale/ /beegfs/banque/acnucdb/swissprot/flat_files/current/'
export swissprotold
swissprotseqinr='/ftp/swissprot/index/ /beegfs/banque/acnucdb/swissprot/flat_files/current/'
export swissprotseqinr
celegans='/panbanques/acnucdb/genomes/celegans/index /panbanques/acnucdb/genomes/celegans/flat_files'
export celegans
ensembl='/beegfs/banque/biomaj/databases/acnuc/ensembl/current/index /beegfs/banque/biomaj/databases/acnuc/ensembl/current/flat_files'
export ensembl
nurebnucl='/banques0/nurebase/genomic/index /banques0/nurebase/genomic/flat_files'
export nurebnucl
nurebprot='/banques0/nurebase/protein/index /banques0/nurebase/protein/flat_files'
export nurebprot
hovergendna='/beegfs/banque/peneldb/hovergen_049/genomic/index /beegfs/banque/peneldb/hovergen_049/genomic/flat_files'
export hovergendna
hovergen='/beegfs/banque/peneldb/hovergen_049/protein/index /beegfs/banques/peneldb/hovergen_049/protein/flat_files'
export hovergen
hovergen48dna='/banques/in2p3/hovergen_048/genomic/index /banques/in2p3/hovergen_048/genomic/flat_files'
export hovergen48dna
hovergen48='/banques/in2p3/hovergen_048/protein/index /banques/in2p3/hovergen_048/protein/flat_files'
export hovergen48
hoppsigen='/panbanques/acnucdb/hoppsigen/genomic/index /panbanques/acnucdb/hoppsigen/genomic/flat_files'
export hoppsigen
trypano='/panbanques/frozen/trypano/index /panbanques/frozen/trypano/flatfiles'
export trypano
polybase='/panbanques/acnucdb/polybase/genomic/index /panbanques/acnucdb/polybase/genomic/flat_files'
export polybase
polymorphix='/panbanques/acnucdb/polybase/genomic/index /panbanques/acnucdb/polybase/genomic/flat_files'
export polymorphix
greviews='/panbanques/biomaj/databases/acnuc/genome_reviews/current/annoted/index/ /panbanques/biomaj/databases/acnuc/genome_reviews/current/annoted/flat_files/'
export greviews
greviews2009='/banques/biomaj/databases/acnuc/genome_reviews/acnuc_genome_reviews_2009-03-03/index/ /banques/biomaj/databases/acnuc/genome_reviews/acnuc_genome_reviews_2009-03-03/flat_files/'
export greviews2009
homolens1prot='/panbanques/acnucdb/homolens/protein/index /panbanques/acnucdb/homolens/protein/flat_files'
export homolens1prot
homolens1nucl='/panbanques/acnucdb/homolens/genomic/index /panbanques/acnucdb/homolens/genomic/flat_files'
export homolens1nucl
homolens5='/banques0/peneldb/homolens_Decembre_2010/protein/index /banques0/peneldb/homolens_Decembre_2010/protein/flat_files'
export homolens5
homolens5dna='/banques0/peneldb/homolens_Decembre_2010/genomic/index /banques0/peneldb/homolens_Decembre_2010/genomic/flat_files'
export homolens5dna
homolens6='/pandata/penel/homolens/homolens_Novembre_2011/protein/index /pandata/penel/homolens/homolens_Novembre_2011/protein/flat_files'
export homolens6
homolens6dna='/pandata/penel/homolens/homolens_Novembre_2011/genomic/db/index /pandata/penel/homolens/homolens_Novembre_2011/genomic/db/flat_files'
export homolens6dna
homolens='/banques0/peneldb/homolens_Decembre_2010/protein/index /banques0/peneldb/homolens_Decembre_2010/protein/flat_files'
export homolens
homolensdna='/banques0/peneldb/homolens_Decembre_2010/genomic/index /banques0/peneldb/homolens_Decembre_2010/genomic/flat_files'
export homolensdna
homolens3='/panbanques/acnucdb/homolens/version3/protein/index /panbanques/acnucdb/homolens/version3/protein/flat_files'
export homolens3
homolens3dna='/panbanques/acnucdb/homolens/version3/genomic/index /panbanques/acnucdb/homolens/version3/genomic/flat_files'
export homolens3dna
homolens2prot='/panbanques/acnucdb/homolens/version2/protein/index /panbanques/acnucdb/homolens/version2/protein/flat_files'
export homolens2prot
homolens2nucl='/panbanques/acnucdb/homolens/version2/genomic/index /panbanques/acnucdb/homolens/version2/genomic/flat_files'
export homolens2nucl
hoinvprot='/panbanques/acnucdb/hovingen/protein/index /panbanques/acnucdb/hovingen/protein/flat_files'
export hoinvprot
hoinvnucl='/panbanques/acnucdb/hovingen/genomic/index /panbanques/acnucdb/hovingen//genomic/flat_files'
export hoinvnucl
hogendprot='/banques0/peneldb/module_hogenom/version5.1/protein/index /banques0/peneldb/module_hogenom/version5.1/protein/flat_files'
export hogendprot
hogendnucl='/banques0/peneldb/module_hogenom/version5/genomic/index /banques0/peneldb/module_hogenom/version5/genomic/flat_files'
export hogendnucl
genomicro1='/panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_1/index /panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_1/flat_files/'
export genomicro1
genomicro2='/panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_2/index /panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_2/flat_files/'
export genomicro2
genomicro3='/panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_3/index /panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_3/flat_files/'
export genomicro3
genomicro4='/panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_4/index /panbanques/acnucdb/genomes/genomicro/acnuc/genomicro_4/flat_files/'
export genomicro4
bacterial='/beegfs/banque/peneldb/bacteria_NCBI/db/index irods://lbbeZone/home/banques/bacterial/flat_files'
export bacterial
hogenombac='/panbanques/peneldb/bacteria_NCBI/selected_genomes_split/db_newids_OSOC_longspec/index /panbanques/peneldb/bacteria_NCBI/selected_genomes_split/db_newids_OSOC_longspec/flat_files'
export hogenombac
archaeal='/panbanques/peneldb/archaea_NCBI/db_newids_OSOC/index /panbanques/peneldb/archaea_NCBI/db_newids_OSOC/flat_files'
export archaeal
ensbacteria='/beegfs/banque/biomaj/databases/acnuc/ensembl/bacterial/current/database/index /beegfs/banque/biomaj/databases/acnuc/ensembl/bacterial/current/database/flat_files'
export ensbacteria
ensprotists='/beegfs/banque/biomaj/databases/acnuc/ensembl/protists/current/database/index /beegfs/banque/biomaj/databases/acnuc/ensembl/protists/current/database/flat_files'
export ensprotists
ensfungi='/beegfs/banque/biomaj/databases/acnuc/ensembl/fungi/current/database/index /beegfs/banque/biomaj/databases/acnuc/ensembl/fungi/current/database/flat_files'
export ensfungi
ensplants='/beegfs/banque/biomaj/databases/acnuc/ensembl/plants/current/database/index /beegfs/banque/biomaj/databases/acnuc/ensembl/plants/current/database/flat_files'
export ensplants
ensmetazoasel='/banques/biomaj/databases/acnuc/ensembl/metazoa_selected/current/database/index /banques/biomaj/databases/acnuc/ensembl/metazoa_selected/current/database/flat_files'
export ensmetazoasel
ensmetazoa='/beegfs/banque/biomaj/databases/acnuc/ensembl/metazoa/current/database/index /beegfs/banque/biomaj/databases/acnuc/ensembl/metazoa/current/database/flat_files'
export ensmetazoa
protozoan='/banques/biomaj/databases/acnuc/protozoan_genomes/current/index /banques/biomaj/databases/acnuc/protozoan_genomes/current/flat_files'
export protozoan
hogenom7dna='/beegfs/banque/acnucdb/hogenom/7/dna/index /beegfs/banque/acnucdb/hogenom/7/dna/flat_files'
export hogenom7dna
hogenom7dnaprev='/panbanques/peneldb/hogenom_7/hogenom_whole/db_hogenom_7_reformated/testhogenom7/index_pbil-banques /panbanques/peneldb/hogenom_7/hogenom_whole/db_hogenom_7_reformated/testhogenom7/modflats'
export hogenom7dnaprev
hogenom7slow='/beegfs/banque/acnucdb/hogenom/7/protein/index /beegfs/banque/acnucdb/hogenom/7/protein/flat_files'
export hogenom7slow
hogenom7='/ftp/ftpdir/pub/hogenom/hogenom7/protein/index /ftp/ftpdir/pub/hogenom/hogenom7/protein/flat_files'
export hogenom7
hogenom7prev3='/beegfs/data/penel/debug-db/index /beegfs/data/penel/debug-db/flat_files'
export hogenom7prev3
hogenom7prev='/panbanques/peneldb/hogenom_7/hogenom_whole/dbprot/acnuc /panbanques/peneldb/hogenom_7/hogenom_whole/dbprot/acnuc'
export hogenom7prev
hogenom7prev2='/panbanques/peneldb/hogenom_7/hogenom_whole/db/index /panbanques/peneldb/hogenom_7/hogenom_whole/db/flat_files'
export hogenom7prev2
hogenom='/panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/protein/index /panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/protein/flat_files'
export hogenom
hogenomdna='/panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/genomic/lastversion/index /panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/genomic/lastversion/flat_files'
export hogenomdna
hogenom4='/banques0/peneldb/hogenom_jan_07/m2protein/index /banques0/peneldb/hogenom_jan_07/m2protein/flat_files'
export hogenom4
hogenom4dna='/banques0/peneldb/hogenom_jan_07/m3genomic/index /banques0/peneldb/hogenom_jan_07/m3genomic/flat_files'
export hogenom4dna
hogenom5='/banques0/peneldb/hogenom_fev_09/annotated_prot/index /banques0/peneldb/hogenom_fev_09/annotated_prot/flat_files'
export hogenom5
hogenom5dna='/banques0/peneldb/hogenom_fev_09/annotated_nucl/db_dna_2011_2/db/index /banques0/peneldb/hogenom_fev_09/annotated_nucl/db_dna_2011_2/db/flat_files'
export hogenom5dna
hogenom5dnaprev='/banques0/peneldb/hogenom_fev_09/annotated_nucl/new_acnuc_with_gc/index /banques0/peneldb/hogenom_fev_09/annotated_nucl/new_acnuc_with_gc/flat_files'
export hogenom5dnaprev
hogenom5dnatest='/banques0/peneldb/hogenom_fev_09/genomic/index /banques0/peneldb/hogenom_fev_09/genomic/flat_files'
export hogenom5dnatest
hovirgen2='/bge/penel/hovirgen/release2/web/protein/index /bge/penel/hovirgen/release2/web/protein/flat_files'
export hovirgen2
hovirgen5='/bge/penel/hovirgen/release5/web/protein/index /bge/penel/hovirgen/release5/web/protein/flat_files'
export hovirgen5
hovirgen2dna='/bge/penel/hovirgen/release2/web/genomic/index /bge/penel/hovirgen/release2/web/genomic/flat_files'
export hovirgen2dna
hovirgen5dna='/bge/penel/hovirgen/release5/web/genomic/index /bge/penel/hovirgen/release5/web/genomic/flat_files'
export hovirgen5dna
phever2='/beegfs/banque/in2p3/phever2.0/bases/web/protein/index /beegfs/banque/in2p3/phever2.0/bases/web/protein/flat_files'
export phever2
phever2dna='/beegfs/banque/in2p3/phever2.0/bases/web/nucleic/index /beegfs/banque/in2p3/phever2.0/bases/web/nucleic/flat_files'
export phever2dna
refseq='/beegfs/banque/biomaj/databases/acnuc/refseq/rna/current/database/index /beegfs/banque/biomaj/databases/acnuc/refseq/rna/current/database/flat_files'
export refseq
refseq16s='/beegfs/banque/biomaj/databases/acnuc/refseq/16srna/current/database/index /beegfs/banque/biomaj/databases/acnuc/refseq/16srna/current/database/flat_files'
export refseq16s
refseqcur='/panbanques/biomaj/databases/refseq-temp/index /panbanques/biomaj/databases/refseq-temp/flat_files'
export refseqcur
refseqold='/panbanques/biomaj/databases/acnuc/refseq/rna/acnuc_refseq_rna_2016-11-03/database/index /panbanques/biomaj/databases/acnuc/refseq/rna/acnuc_refseq_rna_2016-11-03/database/flat_files'
export refseqold
refseqViruses='/beegfs/banque/biomaj/databases/acnuc/refseq/viruses/current/index/ /beegfs/banque/biomaj/databases/acnuc/refseq/viruses/current/flat_files'
export refseqViruses
wannagat='/bge/wannagat/viroscan/acnuc/index /bge/wannagat/viroscan/acnuc/flat_files'
export wannagat
mito='/beegfs/banque/biomaj/databases/acnuc/refseq/mitochondrion_proteins/acnuc_refseq_mitochondrion_proteins_2010-05-16/index /beegfs/banque/biomaj/databases/acnuc/refseq/mitochondrion_proteins/acnuc_refseq_mitochondrion_proteins_2010-05-16/flat_files'
export mito
agrogenom='/panbanques/acnucdb/agrogenom/index /panbanques/acnucdb/agrogenom/flat_files'
export agrogenom
hogenom6old='/pandata/penel/hogenom6prot_newannot/decoupe2/index /pandata/penel/hogenom6prot_newannot/decoupe2/flat_files'
export hogenom6old
hogenom6curr='/panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/protein/index /panbanques/peneldb/hogenom_rel_06_Novembre_2010/database/protein/flat_files'
export hogenom6curr
hogenom6dnacurr='/pandata/penel/tmp_hogenom6/db/index /pandata/penel/tmp_hogenom6/db/flat_files'
export hogenom6dnacurr
hogenom6dnaold='/banques0/peneldb/hogenom_rel_06_Novembre_2010/data/nucleic_new_3/db/index /banques0/peneldb/hogenom_rel_06_Novembre_2010/data/nucleic_new_3/db/flat_files'
export hogenom6dnaold
spermato='/pandata/penel/jos/index /pandata/penel/jos/flat_files'
export spermato
ensemblbacteria='/beegfs/banque/peneldb/ensembl_bacteria/release/Dec2013/index /beegfs/banque/peneldb/ensembl_bacteria/release/Dec2013/flat_files'
export ensemblbacteria
ribodb3='/pandata/penel/RiboDB/RiboDB_V3/index /pandata/penel/RiboDB/RiboDB_V3/flat_files'
export ribodb3
ribodb4='/pandata/penel/RiboDB/RiboDB_V4/index /pandata/penel/RiboDB/RiboDB_V4/flat_files'
export ribodb4
ribodbuser='/pandata/penel/RiboDB/data_Juin_2014_complete/analyse_RiboDB_V4/acnuc/index /pandata/penel/RiboDB/data_Juin_2014_complete/analyse_RiboDB_V4/acnuc/flat_files'
export ribodbuser
proaselle='/panbanques/peneldb/proasellus/db_embl/index /panbanques/peneldb/proasellus/db_embl/flat_files'
export proaselle
proaselleprot='/panbanques/peneldb/proasellus/db_prot/index /panbanques/peneldb/proasellus/db_prot/flat_files'
export proaselleprot
emblTP='/panbanques/frozen/embl/index /panbanques/frozen/embl/flat_files'
export emblTP
ribodb='/beegfs/banque/peneldb/public_ribodb/index /beegfs/banque/peneldb/public_ribodb/flat_files'
export ribodb
taxodb='/panbanques/peneldb/taxodb/dbtaxo /panbanques/peneldb/taxodb/dbtaxo'
export taxodb
lafaydb='/pandata/penel/genomes_lafay/embl_annotated_acnuc/index /pandata/penel/genomes_lafay/embl_annotated_acnuc/flat_files'
export lafaydb
lafaydb2='/pandata/penel/genomes_lafay_2ndset/monhogenom/embl_annotated_acnuc/index /pandata/penel/genomes_lafay_2ndset/monhogenom/embl_annotated_acnuc//flat_files'
export lafaydb2
omar='/pandata/penel/omar/database/index /pandata/penel/omar/database/flat_files'
export omar
plants='/panbanques/peneldb/raquel/hogenom/acnuc_dna/index/ /panbanques/peneldb/raquel/hogenom/acnuc_dna/flat_files/'
export plants
lamarque1='/beegfs/banque/peneldb/lamarque/index /beegfs/banque//peneldb/lamarque/flat_files'
export lamarque1
lamarque='/beegfs/data/penel/pipeline_lamarque/reannotated_db/index /beegfs/data/penel/pipeline_lamarque/reannotated_db/flat_files'
export lamarque
lamarque2='/beegfs/data/penel/paramecium_V2/reannotated_acnuc/index /beegfs/data/penel/paramecium_V2/reannotated_acnuc/flat_files'
export lamarque2
