>Rhipicephalus_microplus_XP_037280637.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----MSTGGEETALVAAQPLPAGCRSRPF--STP-SCNQPLRRMLVDARGSRPVTRPVPV
ACA---------------------GV---------ELL-------------LPATANPLC
--ARLARDCHEQNATVSRL-AC------------G---RLALVTTRALGAGEELRPWLSP
ALLAELGVPAALTPAH--IRGH----R-CYACPDCGAAFEQPNPLKAHLALDACGAKPPR
L
>Rhipicephalus_sanguineus_XP_037520985.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------------------------------------------MLTDACGSRPVTRPVPV
ACA---------------------GV---------ELL-------------LPATANPLC
--ARLARDCHEQNATVSRL-AC------------G---RLSLITTRALCAGEELRPWLSP
SLLTELGVPAALTPAH--IRGH----R-CYACPDCGTAFEQPNPLKAHLALDACGAKPPR
L
>Dermacentor_andersoni_XP_050026229.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----MSASGEETALVAAQPLPAGCRSRPF--SAP-SCSQPLRRMLLDAGGSRPVTRPLPV
ACA-------------------GGGV---------ELL-------------LPASANPLC
--ARLARDCHEQNATVSRL-SC------------G---RLSLTTTRALCAGEELRPWLSP
ALLAELGVPVALTPAH--IRGH----R-CYACPDCGAVFEQPNPLKAHLALDACGGKPPR
L
>Dermacentor_silvarum_XP_037579292.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----MSAGGEETALVAAQPLPAGCRSRPF--SAP-SCSQPLRRMLLDAGGSRPVTRPLPV
ACA-------------------GGGL---------ELL-------------LPASANPLC
--ARLARDCHEQNATVSRL-SC------------G---RLSLITTRALCAGEELRPWLSP
ALLAELGVPVALTPAH--IRGH----R-CYACPDCGAVFEQPNPLKAHLALDACMRQAAQ
A
>Ixodes_persulcatus_KAG0425966.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-PKQGFEPCLESALVAATPIPAGTKSRPS--SG--GCESSLRRLLHQ----RPVQRIVQL
VCNQMA----------RPLCDARSGLQVVVQDGVLSAK-------------EPSVGVSLC
RGVRLARDCHEQNAQLGRG-AD------------G---RLWLQTSKALAAGEELRAWFAV
DLLAELDVPI-LTPAH--IRGH----Q-SYVCLGCGASFPQPNPLKAHLMLEHCSATRAP
S
>Varroa_destructor_XP_022664766.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----MIEHPTSSCVLAGEPLPAGAISMPV--GAE-VLLER--LL----------------
-----------------DRRRPEVEYKVALRHGFLRVISPE-----------CSDSQQLS
TIMRLAADVHEQNVALVKT-----------------VNFYVLQTTRPIPIGEELRFWFNL
EVSCELQIPV-LTPRH--ILGH----Q-RYVCISCDATFPQPNMLKAHLRLNWCTYQRGQ
L
>Limulus_polyphemus_XP_013785958.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-EFTAEYSAMETTVAVDCPIPIGSQSLPL--TVG-LCLHR--------------------
---------------LIHSGLIRRVLQATLNSGTIL-------------LHENPSSRRWV
KLVRVARDCHEQNAQLTRT-SE------------E---HLVLETTRNISAGEELFVWFAT
DMLFEQAIPF-LLPSQ--ILGQ----E-QYSCVVCGTTFSHPNPLKAHIILECSGRFKPA
Q
>Araneus_ventricosus_GBM71193.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------MSSSVAAVCDIPEGTCSLPG--VGD-IDIRR--LL----------------
-----------------EKSEPKKYFHVELRGGYLNLVEK-------------QVCQNWA
CLIAIAKDCHEQNVELTKS-----------------PCGFILRMTRAVKACQELFIWMGA
DLLSQLEFPF-LTPVN--IKGN----Q-AYHCHKCGHIFQNPNPLKVHLFFQCQAPAVHF
-
>Stegodyphus_dumicola_XP_035206768.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------MSSSVVSVCDIPEGTFSLPG--VGC-IDFRQ--TL----------------
-----------------DKSVPKVYLHVDLYGGHLSIVEK-------------EYGQTWA
RFIAIARDCHEQNVELIKN-----------------QQGFLLRVTRAIKISDELFVWIGT
DLLSELEFPF-LKPVN--IKGY----Q-SYHCHKCGFISPNPNPLKIHLFLNCDTSKLFP
P
>Caerostris_darwini_GIY54598.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------MNSSVVAVCDIPEGACSLPG--VGD-IDIKK--LL----------------
-----------------EKSTTKSYFHVELHDGYLSVIEN-------------QIAQNWA
NYIAIAKNCHEQNVELTKS-----------------PTGLILRMTRSVKASEELYVWIGV
DLISKLEFPF-LTPMN--IKGN----Q-AYHCHKCGKIFQNPNPLKVHLSFQCKTSKPEF
-
>Nephila_pilipes_GFU22822.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------MNSSIVAVCDIPKGACSLPG--VGD-IDIRR--LL----------------
-----------------EKSTTKTYFHVDLCGGYLSIVEK-------------QVTQNWA
CFIAIAKNCHEQNVELTKS-----------------YNGLILRMTRSVKASDELFVWIGA
DLLSELEFPF-LTPIN--IKGN----Q-AYHCHKCEKVFKNPNPLKVHLSFECKPSMPPL
-
>Parasteatoda_tepidariorum_XP_042897044.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
------------------------MRKVEVRNGYLSILEK-------------EAGQNWA
CFVDIARNCYEQNVELIKS-----------------HGVLVLRTTRLIKSSEELFVWIGS
DLLSELEYPF-LKPFN--IKGN----Q-DYFCHKCGKKFENPNPLKVHLSLECVSLLQTK
P
>Oppia_nitens_XP_054163735.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-QTNYDINCMEAAIIANTSIPTNVWSQPF--FSK-LCLTR--IFSST----KDITYSLKA
---------------------------FLSPTGMLC----------------VNHSIDWL
PFVRIAKNCFEQNLTAILTQNK------------S---SVVLKTIRNIEKGEELKVWLSD
DLIIALNIPF-LNPIN--IINE----N-CYQCHRCGQSYCQPNPLKIHLTMECKNEEKTN
I
>Daphnia_magna_XP_045026467.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-NRCINESLTGPSVVA------EEFLRPE--SKS-PIIA---------------------
-------------LDPRRFTAHHQQFKVGLRKGELTSSP---------------PSSLWP
MSVEVATECRMQNVECCVVSSTQQSA--ISDV---NNLSLIFTTTRPIEKGQRLYFWFSE
SMLAHLEMPF-LVPKN--IQAG----D-RYVCHRCSSAFVHPNPLKLHLFFHCSSRSVST
S
>Penaeus_chinensis_XP_047484965.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------PVVHVTAGEDLPRAVSTRAC--PAR-DLCLNLTQE--K---------FRQ-
-----------------RRRAHEPTLCIQVNDGTLVAR-------------DNVQLSTWL
PLLPLATDVHAEAATLSFVHSGQ-----------GESATLRVTLTRAVKVGETPPLWFSS
EVAAQLGLPF-LNFSH--IK-E----G-RYVCPECQRQFSAPNPLKLHLAANCDSLDPR-
-
>Atta_colombica_XP_018052070.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----NFFMSRPFVRAAGLLKGNSTTEMI--PVS-TLSEG--NI-------SIIQHN---
------------------------VIEIIDVGGRLHCL------------NGSISPSCWL
KIITLATDFQNYNVLLMIS-ND----------------GLVLKAIKDIAVGEPLLMWFED
CILTMLNIPF-LTPIN--CNIQG---Q-VYTCHNCNSCFDHPNPLKLHLALDCNRMDNS-
-
>Cotesia_glomerata_XP_044580853.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--HNNSSRAPKHHVRAAAHLPINASTGVI--EET-DLQKS--DT-------PVDQY----
-------------------------ISIVHHEDRLICR------------DIPLDASSWF
KLVTIANNIHNYNVILEQV-DR----------------GILLKAKKEIFPGEPLMMWFDT
QLLIKMNIPL-YLEPQ--CIVQSDCTP-NYKCQRCDCLFPDPNPLKIHMALDCNKLDKS-
-
>Apis_mellifera_XP_016769727.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----QACLDRPIVRAAGLLRRESSTEIV--DLN-KLAQK--ST-------SVIQY----
-------------------------VEVIDAEGRLYCV------------DGLVSASCWL
KIVKFANDCQSCNVLLMIN-GN----------------GVVLKTIRNVTPGEPLLMWFTE
NILAMLNIPF-LTPSN--IQGQ----N-RYICHICNKLFEYPNPLKIHLALKCNRLDTN-
-
>Bombus_terrestris_XP_003398139.3_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----QRYLNRPIVIAGGPIGKDSSTETI--DVK-KLSEN--TT-------SGIQY----
-------------------------VEVINVEGRLISA------------DGLVSTSCWL
KIVEIANDCQSCNVLLMIT-AE----------------GVILKTIRDIIPGEPLLMWFTE
AILAMLNIPF-LTPSN--IQDQ----N-RYICHICNNLFEFPNPLKIHLALKCNRLDSD-
-
>Chelonus_insularis_XP_034950564.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----HKYFQKNSVRAATYLERDSTTEVI--DVA-RLTQR--SN-------SVIRR----
-------------------------AKIADEKGHLYCV------------DNAVNASYWI
RIVTIAKDCQSNNVMLTNT-DE----------------GIILKTVRTIMPGEPLLMWFNE
AILAMMNMPF-LSLPN--IQGK----N-KYTCHICNCSFESPNPLKIHLALRCNQLDAS-
-
>Aphis_glycines_KAE9537457.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------SKQTFVAASYLPANCSTTTV--DVT-DMLYN-----------GSLHSFPSG
NDNESS----STGRKTKNLVSVDDAGRLVYANGHLCS---------------TADCSCWI
LSVPLADDCHAYNCRLSLL----------------AVGTVGLHTTTAVMAGQPLKMWFSP
DLQLMLHVPF-LTPVN--IKDE----R-KYVCHKCGYACENPNPLKIHMALDCGKQSRA-
-
>Drosophila_pandora_KAH8318473.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
AKKMRSNPRPG--VYTSQYTPKDTCSIAV--PTA-ALLSA--------------------
--------------PATPTDSGRSHCQL-SNGELI-------------------LSASLL
RQIKLSEDVYSFNAIFELH-G-------------G---QVRVRLVRDVARDDEIVAWFGE
ELVLLMGIPF-LTPLN--IQGN----N-RYTCHLCHLTFETPHPLKIHLALGCGRSAMD-
-
>Hermetia_illucens_XP_037906305.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--RVLKVPSPSDSVSAYEFLEKDTLSSGI--STA-ELVTH--------------------
------------------TSCGRIGIRK-SSNGIIKP---------------AQKVTTWI
RSIRLSPDVYSHNAIIELN-EE------------K---QVRVRVTKNIAPGEEVIAWLSE
EISLFMNIPF-LTPSN--IIDN----K-CYTCHLCKTSFETPNPLKIHLAIACGQQNID-
-
>Bradysia_coprophila_XP_037044718.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--SVKISDSATGGCYASECIPKDTKTKSI--GAL-DSYSM--------------------
------------------GDRFR-KFYLSIRGGYLQTI-------------DKTPEHTWI
KHLKLSTDTHSNNVILELF-N-------------N---ELCVRTIRNVNVNEEVMLWFSE
EILAAMHIPF-LTPAN--IRGK----N-TYTCHVCEKTFENPNPLKIHIATNCERISEH-
-
>Aedes_aegypti_XP_001660252.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--GEPTSASALASVCALSYLPVDSVSKSY--PVE-EICQK--------------------
--------------TALPGGR-RITIRKSSSTGLLTPN----------EADSVMKSCNWI
RSIKLASDVRSYNSVLELT-TN------------Q---MIRLRLTQDLSEDEELKLWFSE
DVAAHMQIPF-LTPAN--IQRQ----N-CYVCHICGKSYEYPNPLKIHIATDCGQQSMT-
-
>Vanessa_atalanta_XP_047527258.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
---------------------MDACGQLTARGGPARAA------RLARLAPAPPHASA--
------LLCLERGPTPASP-DD------------L---RLCLRLTTDAPPLHELLLWFDE
HTLAHLNMPF-LTLRN--ITGK----K-NYACHNCDAEFEQPNPLKIHMFLSCRPFEPD-
-
>Halyomorpha_halys_XP_014291760.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----------MAVVAAENIPPGATSAHL--PLP-RVV-------------------SSG
L--------------SSDK-------ISLRMGDNGLLVSS------------DDRL--LL
QSLPLSEDFHSCSAVLERG---------------LREDTVFLQMTRAVKKGERISLWFST
SLQAAIGIPF-LTPSN--ILGE----K-NYVCHHCRECFEYPNPLKIHLALDCGRLSLN-
-
>Macrosteles_quadrilineatus_XP_054260588.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------AKTLVVAAQGVPAYTASPPI--PLE-DVV-------------------TGK
L--------------DRNK-------IELVVNKNGELTME------------DTPCWSWL
RHVRVSPDCHSYNTLVHRVQNVSTSVASRTDSFPSATNYVTLQTVRELQLGEELCIWFDE
EVLAAAGIPF-LTPMN--IQGE----K-NYTCHRCRKYFEFPNPLKIHLALECGTMRRV-
-
>Coptotermes_formosanus_GFG30244.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------STMSVTAVTDIPRGTCSEDI--NVA-DLTEE-----------K-----TSL
S--------------QSIA-------VCVSEDGKLRTV---------------GCDSRWL
LEARLADDCHSYNVLLQKG---------------GAGNTVVLYVVTSIRNGEELQLWFSE
QMLVLLAVPF-LTPLN--IQGE----K-RYVCDRCGRHFEIPNPLKIHLTLDCDRLNRS-
-
>Diploptera_punctata_KAJ9584407.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--------------------PKQKL------T----LR-P-----------K-----SGL
M--------------SS---------RSLYSELTYGLL---------------EVLSRWI
LEARISNDCHSYNVIVKKG---------------RGINKVKCQTVKTIRNGEELRIWFSE
ELLVSLTIPF-LSPIN--IQGE----K-KYVCHSCKEQFEYPNPLKIHLALNCDQLKKQ-
-
>Nilaparvata_lugens_XP_022185561.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------------------MRNCGGDD--NQ--------------------------N
K--------------TTTT-------VSLHKDGHLRQDTE------------DKDCYKWI
QSMALADDCQSYNVQLRKC---------------CGSESVRLVVTQPLKKGEKLLMWFSD
EILSLLMMPF-LTPVN--IQGE----K-NYRCHLCRKTFEYPNPLKIHIMLGCFSNGN--
-
>Frankliniella_fusca_KAK3914928.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-RRHAAATPTPSTVVVAEDIPLHAASKTF--QPG-ALLGA-----------AGDPDLLVG
D--------------DSLQ-------LRLSAEGHLDVD--------------ADPTPGWV
RRVRLADDCHSVNVQLQVERHSRA-A--RAGAAGPAGVRCMVRAVRPLSRGQDLLMWFAD
DLLACLRLPF-LAPHN--IQGE----K-RYVCHHCGRTFEFPNPLKLHLALDCGREDVA-
-
>Thrips_palmi_XP_034237756.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------MTTANG
D--------------DVLQ-------LRLCADGYLDAD--------------VEATPRWV
RRLRLADDCHSANVQLQAEAAGRS----------SPPTRCRVRAVRPLSRGQSVQLWFAD
DLLPCLRLPF-LAPHN--IQGE----K-RYVCHHCGRSFEFPNPLKLHLALDCGREDVS-
-
>Aromia_moschata_KAJ8943376.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------LLVPGRVTATTSIPQGSMSTAI--EPT-LLLGQ-----------PDVQQISVG
I--------------N--------------SHGTIELDEKC--------KSVWYNNTHWI
RALRLSDDCHSYNIQLRLQPSYQRPS--TSLNKISQIPKLILQAVRPVEAGQELLLWFSE
DILAMLQIVF-LTPAN--IQGA----R-PS--------TSPPNPLKLHITLGCGKQSVA-
-
>Anoplophora_glabripennis_XP_023310486.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------LLVPGRVTAATGIPQGALSDAI--EPA-LLLGQ-----------PDIQQISVG
I--------------N--------------SNGTIELDEKC--------KDVWDNNTHWV
RALRLSDDCHSYNMQLRLQPAYQRPT--TSLAKLTQIPKLMLQAVRPIEAGQELLLWFSE
DILAMLQIVF-LTPAN--IQGQ----K-KYVCTRCSALYESPNPLKLHITLSCGKQTVT-
-
>Gonioctena_quinquepunctata_KAG5872534.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------LLVPGRVTAVSSIPQGSMTVPI--EPA-MLLGQ-----------PDVQQISVK
T--------------T--------------PKGIIDLEEQF--------QQVWCQTTHWV
RALRLSDDCHSYNVQLKLHPAYQRPR--PNSARSCQLPKLILQAVRPIEQGQELLLWFSE
DILAMLQIVF-LTPAN--IQGQ----K-KYVCTRCSALYESPNPLKLHMTLGCGKLSIS-
-
>Tenebrio_molitor_XP_068905408.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------LLVPGKVTAFTTIPQGAVSAPI--EAA-QLLGQ-----------PDVVQISAQ
P--------------N--------------SLGTIDLEKQS--------KDVWCQDTHWV
RALRLSDDCHSYNIQLRFQPT-QRPG--TSFTKNVPTPKLILQAVRPIEMGQELLLWFSE
DILAMLQIAF-LTPAN--IQGQ----K-KYVCTKCSALYESPNPLKLHISLGCGRYTVT-
-
>Brassicogethes_aeneus_CAH0556841.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------LLVPGRVTAATKIAQGAMTIPV--DPM-HLLGQ-----------PDVQQISVG
T--------------N--------------SYGTIDLEDKS--------KETWSKTTHWI
RALRLSDDCHSYNMQLRLQPS-QRPC--STLNKNLPTPKLILQAVRPIEMGQELLLWFSE
DILAMLQIVF-LTPAN--IQGQ----K-KYVCTRCSSLYESPNPLKLHITLGCGRSDIC-
-
>Mercenaria_mercenaria_XP_045198293.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-MDETRGISRKVHVIAGSVIPYGSWYGPV--QK----IDF--------------------
--------------HKEPERLL-------GETGTAIKIITDM----GMLQAKNPSQNPWY
QYLLPARDIHEQNLNLFRS-RD------------G---HLYLRATRDIDKGEVITCWYDE
ALAWEINVPY-LTPAN--IIGI----G-RYCCTMCQKEFIYPNHLKLHIMRTCSGFEKSK
D
>Dreissena_polymorpha_XP_052251827.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------------------------------------MGK----------------WLKR
DGATFTGAL----KILAPSGA----IGVLSIKGR---------------IQSRDCYGEWL
SFLQPARDMLEQNLQLFRSLDD------------G---EMYIRACEDIPRGETLTGWYED
SLALEMNIPY-LTPLH--IRGI----R-EYICNYCERAFHFPNLLKMHIMFNCYPSKQSS
P
>Mya_arenaria_XP_052809498.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------MDVADIILVAGSAIPAGASCAPL--NSH-FRFARTDEFASL-----D-------
---------------------RKRYIEIVYVNGQMHSN--------------DVSDSQWP
LLLRPARDMFETNVQLCLS-RD------------H---NLHVRACRDIQQGEEIVCWYEA
GLALKLEVPY-LTAAN--IIGC----E-EYCCTVCEKSFRFPNFLKLHLMDGCKKSSSGS
I
>Potamilus_streckersoni_KAK3576991.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-MYEEEVKPDEASVVTVTDISAGIKVGPF--PNC-FSTGH--NVRDF----PEISYILE-
---------------------------VEFRNGF--------------IQPLFSTSKDWI
RYMQPARDRHEQNVSLYKT-DE------------G---NLFICTIRPISRGEQLLIWYSD
GMARECNVPV-LFLNN--IKGS----R-CYACTHCGKEFVYPNTLKSHLMFRCRADHKEK
S
>Elysia_crispata_KAK3766859.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
-------------------MNLDFHFQITWANGHAVVFK-K-----NSLTEMSAQSAGKL
SCIRSASNRHEQNVELCRE-----------------GAALQVVTLRKIFKGETLLIWYGE
ELAREMNIPF-LTPAH--IRGY----N-EYTCTACSSVFVHPNALKAHVFLQCSKGKSSP
D
>Elysia_chlorotica_RUS74799.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------------------------------------TG---------------------
-------------ARPCKEFFWKCNKRIAWANGRVLFYK-K-----DSTAETSRHCHGQL
TYIRSASNRHEQNLELCRE-----------------GGILQVLTLRQIDKGETLLIWYGE
ELARELGVPF-LTPAH--IRGS----N-EYACTACASVFAHPNALKAHIFLQCSGSKSRL
S
>Candidula_unifasciata_CAG5114615.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
---------------------------LCWRNDRLESSD-G-----D------GLPQSWL
QLMRCARDRHEQNLELVRS-----------------DDGLFVCTIREILQGEELLIWYRE
TLAREVGVPI-LTPCH--IRGH----Q-KYVCTGCQAVYTHPNTLKAHMFLQCRKSAVSS
-
>Biomphalaria_pfeifferi_KAK0052862.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-LVDDVHDFKFCGVVAGNDIPELVTVKVQ--ATD-LTLGR--DLIAS---------I---
-----------------DSQIKARCIKVFWKNKQLETNS-E------------YRISACL
AFVRSARDRHEQNVELVQK-----------------DGCFFVRTIRPIKQGEQLLIWYED
GHAREVGVPI-LTLSH--IRGH----Q-NYMCTTCGVTFTHPNILKAHMFLQCNSSTTPL
E
>Biomphalaria_glabrata_XP_013061438.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-LVDDVHDFKFCGVVAGNDIPELVTVKVH--STD-VTLGR--DLIAS---------I---
-----------------DSQIKARCIKVFWKNKQLETNS-E------------YRISACL
AFVRSARDRHEQNVELVQK-----------------DSCFFVRTIRTIKQGEQLLIWYED
GHAREVGVPI-LTLSH--IRGH----Q-NYMCTTCGVTFTHPNILKAHMFLQCSSSTTPL
V
>Bulinus_truncatus_KAH9525086.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
---------------------------VYWKNKQLETTA-N------------STINSCL
SCVRSARDRHEQNVELVHK-----------------EDFYYVRTIRPIRRGEQLLIWYEE
SHAREVGVPI-LTLSH--IRGH----Q-NYMCTSCGVTFTHPNILKAHIFYHCSTCTPTP
-
>Physella_acuta_XP_059154055.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------CTEMPSGVVAGNEIPAGVTVTLD--SID-VTLGR--DLLMK---------T---
-------------RLPDDHASPARSLKVYWRNGQLEPCA-E------------LKVSSWV
QSVRSARDRHEQNAELTHG-----------------ERGLYVRTIRQIPRGQALLLWYED
GLARAMGVPI-LTLSH--IRGH----Q-SYVCTGCNTRFTHPNTLKAHMFLQCRHVSLTS
P
>Aplysia_californica_XP_005098240.3_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
----------------------------------MEVMP-G-----G------TTTRGWV
KDMRTARDRHEQNVHLVRD-----------------GDRVLVRTMKHIQAGEALCLWYSD
ELALEVGVPI-LTPSN--IRGY----Q-DYECTHCRAVFRHPNTLKSHMMHRCLTSTVVL
T
>Mizuhopecten_yessoensis_XP_021380071.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-TRRSTPGDGNSGVAASTDVPAQVTAGPY--PGD-FSLNFTRNIGDY----LKVEFLLE-
---------------------------VRYKNDTICLDIESTNE----RLQKIESSNQWL
SHVQPARDRHEQNCEFYRN-EN------------G---EILLRTLKKVESGEQLLAWYSE
QLAREFAIPF-LGLHN--ILGN----Q-QYVCDRCGQTYTHPNPLKLHLVTRCNKGLTTP
T
>Pecten_maximus_XP_033741892.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-IRRNTPGDGNTGVAASSDVPAQVTAGPY--PGD-FNLNFMRNIDDD----FKVEFLLES
S----------------KIACVTFYRQVRYKNGTICLEIESSNH----ILQKIEPSNQWL
IYVQPARDRHEQNCEFYRH-EN------------G---EILLRTLKKVGSGEQLLAWYSE
QLSRDFSIPF-LGLHN--ILGN----Q-QYVCDRCGQTYTHPNPLKLHLRTCRNKGVTSP
N
>Mytilus_californianus_XP_052089268.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-HTNGNPSDYNTGVIAATDIPENCIAGPH--PGE-FKLGQ--NSLDE----PNIDYIIE-
---------------------------VKHKDGRITLD--------------FESSNQWI
KYVQPARDRHEQNIEFYKD-RT------------G---TIYLRTTRKLKMGEQLYAWFSE
PLARESGVPF-LSLQN--IIGN----Q-QYQCDKCQLSYRYPNPLKSHMMFRCRTQEAEI
Q
>Saccostrea_echinata_XP_061177091.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
-----------------------------------------------------------M
KGIRPARDRHEQNTEFFRS-DD------------G---GIYLRSLRRVRGGEEILVWYSD
DLARRCGVPF-LSLVN--IQGK----E-CYACDSCGKTFKYPNPLKAHLRYRCNDTMTQ-
-
>Saccostrea_cucullata_XP_062566735.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-SYHAPVNPPRARVVAGSVIPPLCVAGPY--PGE-FLFGR--ET-EE----LNAEALIK-
---------------------------VKFQD--------------DTIVPELKATRDWM
KGIRPARDRHEQNAEFFRS-DD------------G---GIYIRSLRRVRGGEEVLVWYSD
DLARRCGVPF-LSLVN--IQGK----E-RYVCDSCGKAFKYPNPLKVHLRYRCNKNDTMT
Q
>Ostrea_edulis_XP_048768549.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-LSHAPVDPQRVRVVAGSNIPPLCIAGPY--PGE-FQFGR--NSSDD----LPTDVTIK-
---------------------------VKFQD--------------DTIVPELKAASDWL
RGVRPARDRHEQNTEFFRS-DD------------G---VVYLRTLRRLRGGEEVLAWYGD
DLARQCGVPF-LSLVN--IQGK----E-CYVCDSCGKTFKYPNPLKAHILFKCTKDAMTQ
-
>Crassostrea_virginica_XP_022294659.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
-----------------------------------------------------------M
KGVRAARDRHEQNAEFFRSADD------------R---GVYLRTLRKLRGGEELLAWYSE
DLAIKCGVPF-LSLVN--IRGK----E-CYVCDSCGKVFRFPNPLKAHIQYRCTQDAMSQ
-
>Gigantopelta_aegis_XP_041354496.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----------HVGVIAGTDLPTLASTGPY--PAY-VPIGV--NTRDE----HDVKYTLEL
NVNIFDFALTRYAIHTSPNGLKEASFAVHYEDGRLLIKHDVTGQWPRPLQPAVDVTQHWP
QFIQPARDRHEQNVEAYRD-ER------------D---NVHLRVQRPIRRREELLVWYSD
DLARCVGIPF-LTPDN--IRGN----Q-EYMCSKCRKTYKYPNTLKAHIRFRCVMNQADK
-
>Haliotis_rufescens_XP_046334416.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--------------------------------MD-TLI----------------------
------------GLHTMDSQTIGHVLEVVYKGGRVMLP--------------DNVTDTWL
LHVQPARDRHEQNVETYRD-VK------------G---RLFLRFLRHVNKGEQLLVWYSD
DLARQSGIPI-LSPDN--IRGN----Q-QYMCTECQKIFKYPNSLKAHIRFRCSEKKPDV
T
>Haliotis_rubra_XP_046555716.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
----------------MDSQTIGHVLEVVYKDGRVMLP--------------DHVTDTWL
LHVQPARDRHEQNVETYRD-VK------------G---HLFLRFLRHINKGEQLLVWYSD
DLARQSGIPI-LSPDN--IRGN----Q-QYMCTECQKIFKYPNSLKAHIRFRCSDKKPDV
T
>Lottia_gigantea_XP_009063507.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
------------------------------------MD--------------GDHSNQWM
IYIQPARDRHEQNVEAFMD-EK------------E---EVCLRFIRGVKCGEQLLVWFHD
TLARYRDIPI-LKPEN--IRGY----Q-EYTCTVCQKVFKFPNSLKAHIRYWCRKEEVVT
S
>Octopus_sinensis_XP_029658336.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-SSGSTSADGHGTVVASCEVPAFTIVGTY--TLD-FQIGY--NTEDE----PNITRVVE-
---------------------------VKYVNGKLIT---------------SDGSSNWL
RHVQPARDRHEQNVEVFCDNET------------SGCKRVTVRTLRSVQKGEQLFVWYSD
QLARSTGIPI-LTPDN--IKGK----Q-RYTCTKCQKSYLYPNTLKAHMRFRCPQSRAQI
L
>Capitella_teleta_ELT99123.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
------------------------------------------------------------
-----------------------------------------------------------M
PYIRAARDRHEQNVEVSKD----------------SRGQMVFRCLREITRGEELFVWYCD
ELARQCGIPV-LSPAN--IRGD----S-DYTCNRCLKTFRFPNTLKSHMHYHCSSASRIS
P
>Ridgeia_piscesae_KAK2170786.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-----SSVTAPVAVRTLSHIPAGFSLGHI--DGE-LALGT--TVS---------------
-----------------ETRTFGHEIEVVLRDGTVQNAVRH-----HRHAVNGRNARDWV
LHIAAARDRHEQNVEAVSQHG----------L---SGSDVSYRTTRDIARGEHLFVWYGE
ELARHIGVPI-LTPGN--IRGN----Q-EYVCTRCLMCFQHPNTLKSHILWHCRQVSPSA
A
>Paralvinella_palmiformis_KAK2160426.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-SRPASSGSGTWRVRAGVTIPAGIVIGPY--PSE-MLLGI--NTV---------------
-----------------DHPKGDKYIEVKMKENTLVA------------CPDVDTPRHWL
LHVRPARDRHEQNVEAMRD----------------SRGLITFRIIKVILRGQELLVWYSA
ELALECNIPI-LTPAN--IRSD----Q-EYTCTSCDATFRYPNTLKAHVRFHCSRSSMTS
W
>Owenia_fusiformis_CAH1784349.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---GLHPQMDNIAVRAACTIPKGSTTAPY--PGP-CTIGL--RTSDL----RVVHYVIE-
---------------------------ARSVNGEILAD--------------AERTRDWM
LYVLPARDNLEQNLEAVKH-IS------------G---HILFRAIREVKTGELLSVWYSE
ELAQEMAIPN-LQKQH--STDN----R-KFNCLSCDKTYDYPNSLRAHIRYRCIAHSQIP
K
>Apus_apus_XP_051469553.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTSRA-PAISVSAESCIPAGLRLGPV--PGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------SSALEWI
GLIRAARNSQEQTLEAVAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
PLAQWFDIPVTATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCALSHSRP
-
>Taeniopygia_guttata_XP_030125213.3_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTSRA-PAISVSAESCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRKEPGPKKKVRMVRGELVDEAG-------------SSALEWI
GLIRAARNSQEQTLEAVAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
PLAQWFDIPVTATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCALSHGRP
-
>Corvus_cornix_XP_039424530.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTSRA-PAISVNAESCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRKEPGPKKKVRMVRGELVDEAG-------------SSALEWI
GLIRAARNSQEQTLEAVAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
PLAQWFDIPVTATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCALSHGRP
-
>Tyto_alba_XP_042659603.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTSRA-PATSVSAESCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------SSALEWI
GLIRAARNSQEQTLEAVAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
PLAQWFDIPVTATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCALSHGRP
-
>Python_bivittatus_XP_025022753.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MLSSRPPPALGITAESSIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------ASAVEWI
GLIRAARHAQEQTLEAMAD---------------LPGGQIFYRALRDVQPGEELTVWYSS
ALAEWFDIPATATPTHD-EKGE----E-RYICWYCLRTYKYPNSLKAHVHFHCVLNHGRG
-
>Varanus_komodoensis_XP_044286221.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQPSRAPPAPNVTAESSIPAGLRLGPV--SGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------GSAVEWI
GLIRAARHSQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCVLNHGRG
-
>Muntiacus_reevesi_XP_065767480.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARSPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPIIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGGG
-
>Saccopteryx_leptura_XP_066217412.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARTAATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARSPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPIIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGAG
-
>Bos_taurus_NP_001179939.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPIIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGGG
-
>Mirounga_leonina_XP_034847329.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHATARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGGG
-
>Lynx_pardinus_VFV23601.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMHGTARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGGG
-
>Galemys_pyrenaicus_KAG8522119.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGGS
-
>XP_025858651.1 (best hit for PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCGLSSGGG
A
>Vulpes_vulpes_XP_025858651.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCGLSSGGG
A
>Sturnira_hondurensis_XP_036915605.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MNGASRAPATSVSADCCIPAGLRLGPV--PGT-FRLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSGAG
-
>Myotis_daubentonii_XP_059555746.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTIATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSSSAG
-
>Rattus_norvegicus_NP_001178027.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGTSRTSATSVNADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNPQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSGGGG
-
>Erinaceus_europaeus_XP_060046850.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MYAAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNSQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPMTATPTHD-EKGE----E-RYICWYCWRAFRYPNSLKAHLRFHCALSGRAA
P
>Dasypus_novemcinctus_XP_058163652.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MYGNARAPAASVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPRKKVRLVRGELVDESG-------------GSPLEWI
GLIRAARNAQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWFCWRTFKYPNSLKAHLRFHCGLSDGGG
-
>Homo_sapiens_NP_067633.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAPATSVSADCCIPAGLRLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNSQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVFSGGGG
-
>Loxodonta_africana_XP_064123249.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MHGAARAAATSVSADCCIPAGLLLGPV--PGT-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNSQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLRFHCVLSGGGG
-
>Antechinus_flavipes_XP_051852681.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MHTNRAAAISVSAESCIPAGLRLGPV--PGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNTQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLHFHCVLSGGGG
-
>Vombatus_ursinus_XP_027709687.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MHTNRTAAISVSAESCIPAGLRLGPV--PGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDESG-------------GSPLEWI
GLIRAARNTQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFRYPNSLKAHLHFHCVLRGGGG
-
>Tachyglossus_aculeatus_XP_038616820.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MQASRAPDISVSAENCIPAGLRLGPV--PGV-FKLGK--YL----------------
----------------ADRREPGPKKKVRMVRGELVDEAG-------------VPPLEWI
GLIRAARNTQEQTLEAVAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWFCWRMFRYPNSLKAHLHFHCVLGGGGG
G
>Chelonoidis_abingdonii_XP_032636353.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTNRA-LAISVNAESCIPAGLRLGPV--PGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------GSALEWI
GLIRAARSTQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPITATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCVLNNGRG
-
>Chelonia_mydas_XP_037749413.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTSRA-PAISVNAESCIPAGLRLGPV--PGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRMVRGELVDEAG-------------GSALEWI
GLIRAARNTQEQTLEAIAD---------------LPGGQIFYRALRDVQPGEELTVWYSN
SLAQWFDIPITATPTHD-EKGE----E-RYICWYCWRTFKYPNSLKAHVHFHCVLNNGRG
-
>Latimeria_chalumnae_XP_006000293.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MQTARSPNITVCTESSIPAGMRLGPV--PGM-FKLGK--YM----------------
----------------SDRKDPGIKKKVRLVKGDLVDEAG-------------APVLEWI
GLIRAARNNQEQNLEAIAD---------------LPGAQVFYRALRDVQPGEELTVWYSN
ALAQWFDISVTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLKAHIHFHCIVSNGRG
-
>Protopterus_annectens_XP_043921078.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MQTSRASTTAVCADSTIPSGMRLGPI--PGI-FKLGK--YM----------------
----------------ADRKESGIKKKVRMVRGDLVDEAG-------------CPAVEWI
GLIRAARNNQEQNLEAVAD---------------LPGGQIFYRALRDVPPGEELTVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWFCWRTFKYPNTLKAHIHFHCVLSNGRG
-
>Salmo_trutta_XP_029591174.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTISVFADCSIPAGLRIGPV--QGI-FKLGK--YF----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CPVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Salmo_salar_XP_014055726.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTISVFADCSIPAGLRIGPV--QGI-FKLGK--YF----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CPVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Oncorhynchus_mykiss_XP_021418688.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-APTISVFADCSIPAGLRIGPV--QGI-FKLGK--YV----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CHVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Oncorhynchus_kisutch_XP_020353092.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTISVFADCSIPAGLRIGPV--QGI-FKLGK--YV----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CHVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Oncorhynchus_gorbuscha_XP_046157817.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTISVFADCSIPAGLRIGPV--QGI-FKLGK--YV----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CHVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Oncorhynchus_keta_XP_035601234.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTISVFADCSIPAGLRIGPV--QGI-FKLGK--YV----------------
----------------TDRKEVVTKKKIRLLRGEIVDESG-------------CHVPDWI
GCIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLTEIPAGEELSVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Esox_lucius_XP_010900360.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQATR-ASTLSVFADCSIPAGLRIGPV--PGI-FKLGK--YL----------------
----------------TDRKEVGSKKKIRLLRGEIVDESG-------------CPVSDWI
GFIRAARNNQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELNVWYSN
TLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRS
-
>Osmerus_eperlanus_XP_062322279.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQASR-ASTLSVFADCSIPAGLRIGPV--PGV-FKLGK--YV----------------
----------------SDRKEVGSKKKIRLQRGEFLDETG-------------CPVSDWI
GFIRAARNSQEQNLEAVAD---------------LPGGQIFYRVLREISAGEELSVWYSN
PLAQWYDIPTSATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Gadus_morhua_XP_030227129.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQASR-ASPISVFADCCIPAGLRIGPV--PGI-FKLGK--YL----------------
----------------SDRKEVGPKKKIRIIRGEFVEESG-------------CTGPEWI
GFIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELSVWYSN
PLAQCYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Gadus_macrocephalus_XP_059921386.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQASR-ASPISVFADCCIPAGLRIGPV--PGI-FKLGK--YL----------------
----------------SDRKEVGPKKKIRIIRGEFVEESG-------------CTGPEWI
GFIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELSVWYSN
PLAQCYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Takifugu_rubripes_XP_003965954.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---ATRA-STTISVYTDCSIPAGLRIGPV--PGI-FKLGK--YL----------------
----------------SDRKEAGPKKKIHLVRGEFVDEAG-------------SPVPDWI
GLIRAARNSQEQNLEAVSD---------------LPGGQIFYRVMREIPAGEELTVWYSS
ALAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Solea_solea_XP_058503990.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---ATRA-STTVSVFADCSIPAGLRIGPV--PGV-FKLGK--YV----------------
----------------TDRKEVGPKKKIRLVRGEFVDESG-------------CPVPDWI
GLIRAARSSQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELSVWYSN
ALAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Sebastes_umbrosus_XP_037641889.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---ASRA-STTVSVFADCSIPAGLRVGPV--PGV-FRLGK--YV----------------
----------------SDRKEVGPKKKIRLVRGEFVDESG-------------CPVSDWI
GLIRSARNSQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELSVWYST
SLAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRG
-
>Thunnus_albacares_XP_044215344.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---ATRA-PTTVSVFADCSIPAGLQIGPV--PGI-FKLGK--YV----------------
----------------SDRKEVGPKKKIRLVRGEFVDESG-------------CPVPDWI
GFIRAARNSQEQNLEAVSD---------------LPGGQIFYRVLREIPAGEELSVWYSN
ALAQWYDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHIHFHCALSNGRG
-
>Tachysurus_fulvidraco_XP_047662649.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQASRTSSSIGVFADCSIPAGARLGPV--PGI-FRLGK--CV----------------
----------------SDRKEVGIKKKVRMVRGEFVDECG-------------SAVTDWI
LLIRAARNSEEQNLEAVSD---------------LPGGQIFYRALREIPVGEELSVWYSE
GLAQWFHIPTTATPTHD-ERGE----E-RYICWYCWRIFRYPNTLKAHVHFHCALSYART
P
>Danio_rerio_NP_001313383.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTTR-TPTISVYADCSIPAGLRIGPV--PGI-FKLGK--YV----------------
----------------SDRKELGVKKKIRLVRGEFVDESG-------------SAVPDWI
GLIRAARNGQEQNLEAVSD---------------LPGGQIFYRVVREIQAGEELSVWYSN
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCALSNGRS
-
>Brienomyrus_brachyistius_XP_048881475.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-AMQAT---RVSSVFADCSIPAGLRIGPV--PGA-FKLGK--HM----------------
----------------SDRKDQGHKKKIRLLRGDFVDESG-------------CAVADWI
GLIRAARNVQEQNLEAVSD---------------LPGGQIFYRVLRDVHPGEELTVWYSN
SLAQWFDMPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFHCAVSNGRG
-
>Megalops_cyprinoides_XP_036395457.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQATR-APTISVSADCSIPAGLRMGPL--PGT-CTLGK--YM----------------
----------------SDRREPGLKKKIRLLRGDFVDETG-------------SPVSDWI
GLIRAARNGQEQNLEAVSD---------------LPGGQIFYRVLRDVQPGEELSVWYSN
TLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHVHFQCALSNGRG
-
>Amia_calva_XP_066558521.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQGSR-TPAISVCADSSIPAGLRIGPV--PGI-FKLGK--YM----------------
----------------SDRKEPGLKKKIRLLRGDFVDEAG-------------SQVPEWI
GLIRAARNGQEQNLEAIAD---------------LPGGQIFYRALRDIQLGEELAVWYSH
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKAHIHFQCALSNGRG
-
>Polyodon_spathula_XP_041105303.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQATR-TPTISVCADNLIPAGLRLGPA--PAI-LKLGK--YM----------------
----------------TDRKEPGIKKKIRLLRGYLVDEDG-------------SPVLEWI
GLIRAARNSQEQNLEAVAD---------------LPGGQIFYRALRDIQPGEELTVWYSF
SLAQWFNIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKSHIHFQCALSNGGG
-
>Huso_huso_KAK6488644.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQAAR-TPAISICAESIIPVGLRLGPA--PGI-FKLGK--YM----------------
----------------TDRKEPGLKKKIRLLRGDLVDEDG-------------SPVLEWI
GLIRAARNSQEQTLEAIAD---------------LPGGQIFYRALRDIQSGEELTVWYSF
SLAQWFNIPTTATPTHD-EKGE----E-RYICWYCWRIFKYPNTLKSHIHFQCALINGRG
-
>Pelobates_cultripes_CAH2252510.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MHSNRPTAISVSADTSIPAGLRLGPL--VGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRYVRGEILDEAG-------------SPAQEWI
GLIRAARNGQEQNLEAISD---------------LPGGQIYYRTLREVQAGEELTAWYSN
SLAQWFDISTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLKAHIHFHCTLNNGRG
-
>Pseudophryne_corroboree_XP_063775749.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MHTSRAPAISVSAETSIPASLRLGPI--LGI-FKLGK--YL----------------
----------------SDRREPGPKKKVRFLRGELVDEAG-------------GPVTEWI
GLIRAARNSQEQNLEAISD---------------LPGGQIYYRTMREVQAGEELSAWYSN
SLAQCFEISTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLKAHVHFHCALNSSRG
-
>Bufo_bufo_XP_040286000.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---------MHPSVSADTRIPTGLRLGPV--LGS-FKLGK--YL----------------
----------------TDRREPGPKKKVRFIRGELVDESG-------------GPASEWI
GLIRAARNSQEQNLEAFSD---------------LPGGQIYYRTMREVQAGEELTAWYSN
SLAHSFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKFPNSLKAHIHFHCALNNGRG
-
>Microcaecilia_unicolor_XP_030051046.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MQSSRAPAISVNADSRIPEGLRLGPV--PGV-LKLGK--YL----------------
----------------TDRREVASKKKVRMVRGELVDEVG-------------DSSPEWI
GLIRPARNSQEQNLEATAD---------------LPGGQIFYRVLRDVQPGEELTVWYSS
SLAQWFDIPTTATPVHD-EKGE----E-RYICWYCWRAFKYTNTLKSHIHFHCVLNNGRS
-
>Rhinatrema_bivittatum_XP_029452707.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---MQTSRAPAGGVSAESAVPAGLRLGPVPVPGV-PRLGK--HL----------------
----------------TDRRDGACKRKVRMVRGELVDEAG-------------GSSPEWI
GLIRPARNSQEQNLEAIAD---------------LPGGQIFYRVLRDVQPGEELTVWYSS
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWKTFKYPNTLKAHLHFHCALNSGRG
-
>Carcharodon_carcharias_XP_041044803.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTPR-SSAITVTAESIIPAGLRLGPL--QGI-FRLGK--YM----------------
----------------SDRKEQCNKKKVRFVRGDLIDEAG-------------DSVPEWI
ELIRAARHVQEQNLEAITD---------------LPGGQIFYRTLRDIQPGEELAAWYSR
ALAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLIAHIHFHCSLSNGRG
-
>Scyliorhinus_canicula_XP_038655449.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTPR-SSALTVTAESIIPAGLRLGPV--QGI-FRLGK--YM----------------
----------------SDRREHNNKKKVRFVRGDLVDEAG-------------DSVSEWI
ELIRAARHVQEQNLEAITD---------------LPGGQIFYRALRDIQPGEELAAWYSS
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLIAHIHFHCALSNGRG
-
>Chiloscyllium_plagiosum_XP_043541584.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTPR-SSAITVTADSTIPAGLRLGPV--QGI-FRLGK--YM----------------
----------------SDRKEHFNRKKVRFVRGHLVDEAG-------------DSVPEWI
ELIRAARHIQEQNLEAITD---------------LPGGQIFYRTLRDIQPGEELAAWYSS
TLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLIAHIHFHCALSNGRG
-
>Rhincodon_typus_XP_020372088.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQNPR-SSAITVTADSTIPAGLRLGPV--QGI-FRLGK--YM----------------
----------------SDRKEHFNRKKVRFVRGHLVDEAG-------------DSVPEWI
ELIRAARHIQEQNLEAITD---------------LPGGQIFYRTLRDIQPGEELAAWYSS
TLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLIAHIHFHCALSNGRG
-
>Mobula_hypostoma_XP_062896945.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTPR-SSAITVTAGSIIPAGLRLGPV--QGI-FKLGK--YM----------------
----------------SDRKEHCNKKKVRFVRGDLVDEAG-------------DSVPEWT
ELIRPARHIQEQNLEAITD---------------LPGGQIFYRTLREIQPGEELAAWYSS
SLAQWLDIPTTATPTHD-EKGE----E-RYICWYCWRAFKYPNTLKAHIHFHCTLSNGRG
-
>Hypanus_sabinus_XP_059837292.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQTPR-SSAITVTAGSIIPAGLRLGPV--QGI-FKLGK--YM----------------
----------------SDRKEHCNKKKVRFVRGDLVDEAG-------------DSVPEWT
ELIRPARHIQEQNLEAITD---------------LPGGQIFYRTLREIQPGEELAAWYSS
SLAQWLDIPTTATPTHD-EKGE----E-RYICWYCWRAFKYPNTLKAHIHFHCTLSNGRG
-
>Amblyraja_radiata_XP_032876918.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
--MQNPR-SSAITVTAGSIIPAGLRLGPV--QGI-FRLGK--YM----------------
----------------SDRKEHCNKKKVRFVRGDLVDEAG-------------ETDPEWT
ELIRPARHIQEQNLEAITD---------------LPGGQIFYRTLRDIQPGEELTAWYSS
SLAQWFDIPTTATPTHD-EKGE----E-RYICWYCWRTFKYPNTLKAHIHFHCSLSNGRG
-
>Holothuria_leucospilota_KAJ8026910.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---ARRDDPELRGVRTSTDIPAGVTCGYV--EGE-YFLSE--KIQ---------------
-----------------DNMTAKKFVEVRFEHGRLTSKHG-------------DTFNLWM
QMVRPARCDSEQNLVASRK----------------SSSLLVFRSLRPISAGEELLAWYDP
DVCAELGLAQ-NVQP---LKGD----D-GYSCTVCSASFSYPNPLRVHLRFACKQISVEK
N
>Acanthaster_planci_XP_022107599.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
---SAKGSDIETSVWTSTEIPADVSFGPF--DGE-FRLGA--AMK---------------
-----------------DCRDSPYMLEVKYSEGRLVSGPD-------------SHPTRWM
RFVAAAHDDHEQNLSAVRS----------------PEGRVMFRTNRSILRGEELLVWYTN
AFAEYLGMPL-AVNH---YRGK----D-GFSCPKCPKIYRYPNTLKSHLHFRCTGASAVC
E
>Patiria_miniata_XP_038077099.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-SVTTKSSDIETSVWTSTEIPADVSFGPF--DGE-FRLGA--AMK---------------
-----------------DSRDSPYMLEVKYSEGRLVSGPD-------------SHPTRWM
RFVAAAHDEHEQNLSAVRS----------------PEGRVMFRTTRSILRGEELLVWYTS
AFAEYLGMPT-TVNQ---YRGK----K-HCIVLVN--L----------------------
-
>Asterias_rubens_XP_033635807.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------------------------------------------MK---------------
-----------------DSRDSPYMLEVKFSEGRLVSGPD-------------SHPTRWM
RFVAAAHDDHEQNLSAVRS----------------PEGRVMFRTTRSILRGEELLVWYSS
GFAEYLGMPT-TINR---YRGK----D-GYRCPRCPKTFRYPNTLKSHLRFRCTITARGE
-
>Lytechinus_pictus_XP_054753679.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------HRGAPRVWTSSEIPADVVIGPF--DDSLLNFGE--RIS---------------
-----------------EDSSDATMIEVKVSFGRVVSACG-------------NDSTKWA
WHIAAARNDHEQNLSAERT----------------SDGMVIFKTTRRILKGEELRVWHSP
DLAKNMGVPA-HVGT---YQAE----DRSFVCPVCSKKFRYPNTLKAHLMSCGASSKRTS
-
>Lytechinus_variegatus_XP_041462865.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-------HRGAPRVWTSSEIPADVVIGPF--DDSLLNFGE--RIS---------------
-----------------EDSSDATMIEVKVSFGRVVSACG-------------NDSTKWA
WHIAAARNDHEQNLSAERT----------------SDGMVIFKTTRRILKGEELRVWHTP
DLAKNMGVPA-HVGT---YQAE----DRSFVCPVCSKKFRYPNTLKAHLMRCGASSKRT-
-
>Strongylocentrotus_purpuratus_XP_011683401.2_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----HHHQPASSRVWTSSEIPADIVLGPY--DDSVLSFGD--RIT---------------
-----------------EDSSNPTMIEVKVSFGRVVSARE-------------SDSSSWA
WHIAGARNDHEQNLSAERA----------------SDGMIVFKTTRRVLKGEELKVWLSS
DLAKHMGVPA-HVGT---FQAE----DRSFVCPVCSTKFRYPNTLKSHLRSCGTSAKRTS
-
>Anneissia_japonica_XP_033118215.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-ECCLDGEGVDTGVWCASEIPNDLVLGSF--EGA-LRLGD--GMK---------------
-----------------DERHRPYMLQIRYVDGKITTN----------------DDVPWI
RFISAARNDVEQNTEATTD----------------TNGQVILRTTRRISVGEELLVWYSD
KLQQLMNIPQ-VLPSRD-HTGQ----I-NYVCQYCCKRYQHPNTLKSHLRFTCVRASVSA
A
>Trichoplax_adhaerens_XP_002112854.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
----MDLSKIKTGVWTSTSIPHNLKFGPY--KDE-LKFFE--KAS---------------
-----------------DNRETAFMLEVQIKNGNIICTSN------------IVNGLEWV
ACMSCARNKDEQNIEVQFNGH---------------TKEIHFKTTRDITRHEELLVWFSQ
EMEKKWDIPQ-PKKEN--IIGP----N-YFWCTLCHATYRYLHPFIAHLMCKCPVLYSKS
P
>Pocillopora_meandrina_CAH3121559.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEMEKVQ--RYSGVFAASPIPPSLTFGPY--KGT-LNIFL--KTN---------------
-----------------DHKHLDYILEVTYKCGQLIWVFD--------------RHLSWV
PFMNFARCPEEQNVEVFLS-----------------EGSFFFRTIDRVSPGEELLLWPTE
RLCRSLRMPN-FVYHGD-RERE----Y-QYICHHCSQVFAFPNTLKTHIAFECASNRGKS
-
>Pocillopora_verrucosa_XP_058952471.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEMEKVQ--RYSGVFAASPIPPSLTFGPY--KGT-LNIFL--KTN---------------
-----------------DHKHLDYILEVTYKCGQLIWVFD--------------RHLSWV
PFMNFARCPEEQNVEVFLS-----------------EGSFFFRTIDRVSPGEELLLWPTE
RLCRSLRMPN-FVHHGD-RERE----Y-QYICHHCSQVFAFPNTLKTHIAFECASNRGKS
-
>Desmophyllum_pertusum_KAJ7385663.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEIEKVQ--RYSGVFAVSSIPPSLTFGPY--EGP-LNILL--KTN---------------
-----------------DHKHLDYILES--------------------------------
------------------------------------------------GPGEELLIWPTE
GLCRSLRIPN-HVIPSK-DERE----Y-QYICHHCSQVFAFPNTLKTHIAFECASNRGKS
-
>Orbicella_faveolata_XP_020622892.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEIEKVQ--RYSGVFAASSIPSSLTFGPY--EGP-LNILL--KTN---------------
-----------------EHKHLDYILEVTYRCGQLIWVVD--------------RHLSWV
PFMNFARCPEEQNVEVFLS-----------------AGSFFFRTIDRVARGEELLIWPTE
GLCRSLRIPN-LVTPRV-NEGE----Y-QYICHHCSQVFAFPNTLKTHIAFECASNRGKS
-
>Acropora_digitifera_XP_015759988.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEFENVQ--RYSGVFATSSIPASLTFGPY--QGP-LNILL--KTK---------------
-----------------DHKRVEYVLEVSYKGGHLIWVVD--------------RHLSWV
PFMNFARCPEEQNLEVFLC-----------------DGSFYFHTICKVEPGEELLIWPSE
RLSTNLMIPE-RVTPRSKHIGE----Y-QYICHHCSQVFAFPNTLKTHIAFECASKRGNC
-
>Porites_lobata_CAH3126332.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEMENVQ--RYSGVFATCSIPALLTFGPY--QGP-LNMLL--KTT---------------
-----------------DHKHLDFVLEISYRYGQLIWVMD--------------RHLSWV
PFMNFARCPEEQNVEVFLK-----------------EDSFYFRTIRRVAPGEELLIWPTE
GLSRRLKIPK-LVIPKT-EQRE----Y-QYICHHCSQVFAFPNTLKTHIAFECATNRTKS
-
>Porites_evermanni_CAH3171587.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
SEMENVQ--RYSGVFATCSIPALLTFGPY--QGP-LNMLL--KTT---------------
-----------------DHKHLDFVLEISYRYGQLIWVMD--------------RHLSWV
PFMNFARCPEEQNVEVFLK-----------------EGSFYFRTIRRVAPGEELLIWPTE
GLGRRLKIPK-LVIPKT-EQRE----Y-QYICHHCSQVFAFPNTLKTHIAFECATNRTKS
-
>Dendronephthya_gigantea_XP_028414813.1_PRD13_HUMAN_707_residues (PRD13_HUMAN_707_residues)
-RFWDMQPLSDIGVIAVSNIPAGSKIGPS--HEI-PNILM--KAK---------------
-----------------EERKMSYALKVSWKNGKVRCGDS--------------DYIWWV
RFMNYARNEEETNVEIYRD-----------------AGVFYCQIVRDIMKGQELLVWFEE
KLAQELGLAK-C---EKLEEGE----Q-GYRCFQCSQLFRYSHSFRVHISLTCGNYKLAY
N
