>Halyomorpha_halys_XP_066904483.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----EEEAVQ-IICDKPVICRAVASLPAKFLYFGKEA----------GPSKGVFAKKEIP
KRAQFGPMEGIIQRTPCINKHH----------IEL--------------TIENNGGIEWL
DVSNENISNWMKYVRQAESGEEQNLSLHQIG--------K-NLYFRALSRI-APQEELKV
WYSMAYAKTRNLPLLSFTKTRK
>Nezara_viridula_CAH1402717.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----EEEAVQ-IICDKPVICRAVASLPAKFLYFGKET----------GSSKGVFAKKEIP
KRAQFGPMEGILQRTPSVTKHH----------LVL--------------TIENNGEVEWL
DVSNENISNWMKYVRQAESADEQNLSLHQIG--------K-NLYFRALNRI-GPHEELKV
WYSMAYAKPRNLPLLSFAKNRK
>Gryllus_longicercus_KAK7788748.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
-----SLNIS-SIQDKPVLAIALPSFPSAFLAIRKLPPKKT-----EKIVYGVFARKILS
KRMQFGPIEGIFVKDKDHLGSC-QKQYDNSKDLVLS-------------IEMESGDLQKL
YVNPGDSWCWMKYIRTAPSFKERNLVLNQNG--------Q-SLFFMTTKVI-HPKEELRV
WYSLPYAIKRNLPLLNPDVLIR
>Ladona_fulva_KAG8226515.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSKHKIQ-TISDKPVPSRAWATLPAAYLMITKVASES------GGKDYGVFARKTIP
KRTQFGPVEGVATPKEAA--------ANIHHKIELL-------------LENEQGEFLKL
DVSEENTSNWMRFVRPAKSFKEINLILSQQG--------H-SLYFTTTRLI-HPREELLV
WYSLPYAQR-------------
>Macrosteles_quadrilineatus_XP_054261369.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----AEHQINRKISDKAVPSRARATLPASYLAINRVSD--------EVEEYGVFARKTIP
KRTQFGPIEGVLAKSGEVV------VLQEAPTLKLT-------------IESDSGEFRIL
DVSNEHMSNWMRFVRRATTDRPPNLLLSQLG--------N-SLYFTTTQMI-HQKEELLV
WYSPSYAVRRGLPANPPP----
>Nilaparvata_lugens_XP_039284450.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSLHRVNSIICDKPVPSRARATLPASYLAINLVK----------PNVYGIFARKTIP
NRTQFGPIEGILLKCEDVW---------TDSPLELL-------------VETETGEMHRL
DVSNEDTSNWMRFVQPASSAKEQNLVLSQQG--------H-SLYFTSTRPI-HPRQQLLV
WYSAAYAAKRHLPQLLEPPQ--
>Diploptera_punctata_KAJ9585314.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPQHRVQ-TICDKPVPSRAWATLPASYLAINKVGTSS-S----GCPVYGVFARKTIP
KRTQFGPIEGVLVKADDSQHDIHVISCGQETQLELL-------------VESETGSMLKL
DTTCENSSNWMRFVRSAETLKEQNLILSQQG--------H-SLYFTTTRVI-HPRQELQV
WYSLPYANKRGLSLLQSDTTEK
>Coptotermes_formosanus_GFG30499.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPQHRVQ-TICDKPVPSRAWATLPVSYLAINKVGTTS-T----GSPVYGVFARKTIP
KRTQFGPIEGVLVKTDDPH---MILADREEPQLELL-------------VESETGAMLKL
DTGCENSSNWMRFVRAAESFKDQNLILSQQG--------H-SLYFTTTRVI-HPRQELQV
WYSFPYANKRGLSLLQPEKEK-
>Zootermopsis_nevadensis_XP_021917414.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPRHRVQ-TICDKPVPSRAWATLPASYLAINKVGTTS-D----GSPVYGVFARKRIP
KRTQFGPIEGVLVKADEPH---VILAGGEEPQLELL-------------VESETGAMLKL
DIESENSSNWMRFVQGAESFKDQNLILSQQX--------S-FFIFTTTRVI-HPRQELQV
WYSLPYANKRGLPLLQPDPGK-
>Chelonus_insularis_XP_034940802.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTCENVQ-TIADEPVPSRARATLPVLYLAINKLSAINTINNG-TTALYGVFAKRSIK
RRTQFGPIEGILCDYNSGILEN---------ELPLI-------------YETDDGKLLRV
DISNENTSNWMRFVRPALNYEEQNLVICQQN--------D-GIVFLTTREI-LPKEELKA
GPSLQYAIRRNLTVFQADVVKE
>Atta_colombica_XP_018058479.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---SNLTDVC-TIADQPVPSRAVATLPGSYLLLNKLSTSHGSA---NNVTYGVFAKRNIR
RRTQFGPIEGVLCTYDGSPFRN---------ALPLL-------------YETQDGEFLKV
DVSNENTSNWMRFVRPALTYKEQNLIICQQK--------D-GIVFLTNRNI-SPKEELKA
GPSSDYASRRNLSILKPDIK--
>Cotesia_glomerata_XP_044599219.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTCRNVR-TISDQPVPSRAVATLPGSYLAINKLPSTPGIGEPIGYCNYGVFAKRNIR
QRTQFGPIEGVLYPYNGQSFKN--------DQLPLL-------------YETNDGHLLKV
DVSDENTSNWMRFVRPALTYDEQNLVICQQS--------D-GIFFLTTRNI-LSKEELKA
GPSSQYASRRGLTILESDSSLK
>Bombus_terrestris_XP_048261504.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTSHNVC-TIADQPVPSRAIATLPGSYLSINKLSNSEIIS---GGSDYGVFAKRYIQ
KRTQFGPIEGVLYPYDGTPFRD---------ELPLL-------------YETENKEFLKV
DVSNENASNWMRFVRPALTYKDQNLVICQQR--------D-GIVFLTTRSI-LPKEELKA
GPSIDYAIRRNLIPLKSTQETK
>Apis_mellifera_XP_006569371.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTSHNVC-TIADQPVPSRAIATLPGSYLSINKLCNSDIVL---GGSDYGVFAKRYIQ
KRTQFGPIEGILYPYDGTPFKN---------ELPLL-------------YETENKEFLKV
DVSNENASNWMRFVRPALTYKDQNLVICQQR--------D-GIVFLTTRSI-LPKEELKA
GPSTDYAIRRNLIPLKSMQEIN
>Penaeus_vannamei_XP_027209209.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPQHRIQ-AISDKPVRTRAWASLPAQHLIIRKIAD---------TEEYGVFVRKAIP
KRTQFGPIEGVLKEDSDGSVSP---------HGLIY-------------TIKQGDQTLHL
DTSDEATSNWMRFVRQATTYLEQNCVVMQVD--------E-NLVFLTTTDI-APRTELRV
GYSKQYGDKRGLHILQPTAEEI
>Penaeus_chinensis_XP_047496828.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPQHRIQ-AISDKPVRTRAWASLPAQHLVIRKHAD---------TEEYGVYVRKAIP
KRTQFGPIEGVLKEDSNGSVSP---------HGLIY-------------TINQGDQTLHL
DTSDEATSNWMRFVRQATTYLEQNCVVMQVD--------E-NLVFLTTTDI-APRTELRV
GYSKQYGDKRGLHILQPTAEEI
>Limulus_polyphemus_XP_022248654.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CARHVVQ-LIVDKPVLSRAWASLPATYLYLHRIADA--N----NESEYGVFAKKTIP
KRTQFGPIEGVLVETEKRPNNR----------FLLI-------------VEHDEDHTVYL
DTSEESRSNWMRFVRPAESYWQQNLVLVQQG--------Q-SLYFNTTRAI-NPRTELRV
WYSSSYAESWSLSLLEMPEEET
>Dermacentor_andersoni_XP_050034082.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPRHKVQ-LIVDKPVLTRAWASLPASYLYVHKVAEDS-D----GEPIYGVFAKKNIP
KRTQFGPMEGVLQRRTDRPQQF----------PLFV-------------REDENGSVFCL
DTSDETQSNWMRFVRPAQTPLEQNIIVIQQG--------T-SLYFNTTRAL-SSRTELRV
WYSTAYAQRWGLPLLHQQQQ--
>Dermacentor_silvarum_XP_037572904.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPRHKVQ-LIVDKPVLTRAWASLPASYLYVHKVAEDS-D----GEPIYGVFAKKNIP
KRTQFGPMEGILQRRTDRPQQF----------PLFI-------------REDENGSVFCL
DTSDETQSNWMRFVRPAQTPLEQNIIVIQQG--------T-SLYFNTTRAL-SSRTELRV
WYSTAYAQRWGLPLLHHQQQQQ
>Rhipicephalus_microplus_XP_037279419.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPRHRVQ-LIVDKPVLTRAWASLPASYLYVHKVAEDS-D----GEPIYGVFAKKNIP
KRTQFGPMEGVLQRSTDRPHSF----------PLYI-------------KKDESGTVFCL
DTSDETQSNWMRFVRPAQTPLEQNIIVVQQG--------Q-SLYFNTTRAL-ATRTELRV
WYSSAYAQRWCLPLLHQQ----
>Rhipicephalus_sanguineus_XP_049271985.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPRHRVQ-LIVDKPVLTRAWASLPASYLYVHKVAEDS-D----GEPIYGVFAKKNIP
KRTQFGPMEGVLQRSTDRPQPF----------PLYV-------------KKDESGTVFCL
DTSDETQSNWMRFVRPAQTPLEQNIIVIQQG--------Q-SLYFNTTRAL-ATRTELRV
WYSSAYAQRWCLPLLHQQ----
>Parasteatoda_tepidariorum_XP_015925355.2_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPQHRIQ-LIFDKPVLSRAWASLPATYLYVNKIAMN--------EEVYGVFAKKTIP
KRTQFGPIEGVLVKREELPTNN----------FLLL-------------IEHEEGMALLL
DTSDESMSNWMRFVRPAETHKEQNLVLVQHG--------H-SLYFNTTRAI-NPKAELKV
WYSQTYAEKWGLPILEPNEDEK
>Nephila_pilipes_GFU29900.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--------------------------------------------------YGVFAKKTIP
KRTQFGPIEGVLIKREDLPSDS----------FILV-------------LEHEENVALYV
DTSDESVSNWMRFVRPADTHKEQNLVLVQQG--------R-SLYFNTTRSI-NPKTELRV
WYSTAYAEKWGLPVLEPNEEEK
>Caerostris_extrusa_GIX76686.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSRHRVQ-LIFDKPVLSRAWASLPAQYLYVNKISVNNET----GETVYGVFAKKTIP
KRTQFGPIEGVLVKREDPPSDH----------FILV-------------LEHEENIVLYL
DTSDESASNWMRFVRPAHSHKEQNLVLVQQG--------Q-SLFFNTTRVI-NPKTELRV
WYSTAYAEKWGLPVLEPNEEEK
>Caerostris_darwini_GIX76994.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSRHRVQ-LIFDKPVLSRAWASLPAQYLYVNKISINNET----GETVYGVFAKKTIP
KRTQFGPIEGVLVKREDPPSDH----------FILV-------------LEHEENIVLYL
DTSDESASNWMRFVRPAHSHKEQNLVLVQQG--------Q-SLFFNTTRVI-NPKTELRV
WYSTAYAEKWGLPVLEPNEEEK
>Stegodyphus_dumicola_XP_035227688.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSQHRIQ-LIFDKPVLSRAWASLPATYLYVNKIGIDD-D----GDPVYGVFAKKTIP
KRTQFGPIEGVLVKREDPPSDN----------FILL-------------VEHEDGVALYL
DTSDESMSNWMRFVRPADTHKEQNLVLVQQG--------Q-SLFFNTTRSI-NPKTELRV
WYSATYAEKWGLPVLEPNEEEK
>Araneus_ventricosus_GBM48422.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSLHKIQ-LIFDKPVLSRAWASLPAQYLYVNKISVDN-E----GEPVYGVFAKKTIP
RRTQFGPIEGVLVKREDPPSDN----------FILV-------------IEHEDNVALYL
DTSDESMSNWMRFVRPAETHKEQNLVLVQQN--------H-SLFFNTTRSI-NPKTELRV
WYSAAYAEKWGLPVLEPNEEER
>Varroa_destructor_XP_022665256.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSQHRVL-MIKDERIQSRAFATLPSNHLVIQNVASNV-N----GPPVYAVFSRNVIP
LRTMFGPMEGVPIKTTQKPNVP----------FPIF-------------LSEDVSGCVIL
DTRDEERSNWMSFVRTAASPSEQNMAIVQQG--------G-QIFFKVVTQI-LPKTELKV
WYSDAYIQRYRL----------
>Tenebrio_molitor_XP_068898694.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----SVPKVY-SIVDKPVLSRARATLPESYLVLNKVDE-----------GLGVFAKKTIP
KRTQFGPLTGIVKPVSPEELKN------SPPGLQFL-------------IEDENHVVSQL
DVSDENSSNWMRFIRQATTYNEQNLLITQED--------N-SLYFTTMKNI-LPKQELKV
GYGWPYAIRHELSVLVPEE---
>Gonioctena_quinquepunctata_KAG5897474.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----LLSCVY-SITDKPILTRAQASLPETYLVINKINE----------EECGVFAKKTIP
KRTQFGPLEGVLMLNNESNSTE----TEEGDFLSFL-------------IKSE-GVLYKI
DVSDENTSNWMRFVRKAQTFEEQNLVLTQEN--------N-AIYFTSTTYI-LPKQELKV
GYNSGYGEFYNLPVLKPRE---
>Anoplophora_glabripennis_XP_018572563.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----LLSCVY-SITDKPILTRARASLPESYLFINKIND-----------ENAVFAKKAIP
KRSQFGPLEGILTLRTEKVKNE-------LASLVFF-------------IESE-GATYEM
DVADENSSNWMCFVRKALTYEEQNLVITQEN--------N-AIYFTTTANI-LPKQELKV
GYSASYAHYFDLPLLEPRE---
>Aromia_moschata_KAJ8941230.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----LLSCVY-SITDKPILSRARASLPESYLVINRVNE----------LENGVFAKKAIP
KRTQFGPLEGVLLLNNENIKNE--------SSLVYL-------------IEIE-GSVYKM
DVSDEISSNWMSFVRKANTYEEQNLVITQEN--------G-TIYFTTTTNI-LPKQELKV
GYSTAYAQYFGLPMLQPQE---
>Brassicogethes_aeneus_CAH0554572.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----LLSCVY-SISDKPILSRARASLPASFLVISIINE-----------ENAVFAKKVIP
KSSQFGPLEGLYVHVKSDEVV-----KVDNNILQLF-------------VKLD-DGVYKV
DFSDENSSNWMGFVRKAQNFEEQNLLVSEDN--------G-SLYFITTKPI-LPKQELKV
GYSNAYAQQFNLPILEPKQ---
>Oppia_nitens_XP_054154487.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
----LEVPQEHVISDLPVLSRARASLPSEYLYIEETDN--------SIGVIGVFAKKTIP
KRTQFGPVEGVIVGHNHSNVHN------FNHNLMI-----------------FITETLIL
DQSDENQSNWMKFVRSANTYEEQNLALITKENITGNEIEI-KFFFHTTRAI-YAREELKV
WYSREYAEKFNLKVLEPRPPIP
>Blomia_tropicalis_KAJ6217930.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---SINHENV-IINDLPVLTRARASMPIDYLCLQDTAS----------GGVGTFARKPIP
KRSQFGPIEGMLYHFSENELSIPELVQTSKNNLMIF-------------V----SDSTLL
SQSDENNSNWTRFVRPATNVMEQNLELIQREYAHIN--EI-KFFYYTTRDI-MPNEELKV
WYSKEYRQKFKIPNLLLDQDGM
>Hermetia_illucens_XP_037902856.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---NDEEDFL-LVTDKPVESRARASLPTNYLYFGNSPDNS-------NGDISVFAKREIP
ARTKFGPFEGELRLSSDVISDVLLIQA--SNTYPLL-------------LI---NDTHIL
DVSNENTCNWMRFVRLAKNYTEQNLLLFEES--------G-KLYFRSCQVI-HAKQEIKV
GYSESYAKHYDLKTISPTESEL
>Bradysia_coprophila_XP_037049154.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---VKKDEEL-VICDKQVPYRSLCSLPTAYLYINGN---G-------DNDVKVFAKKEIP
LRTKFGPVEGDMQHII----DPDHLKK--HSTLPLY-------------LI---DESTYI
DTSNELTSNWMRFVKLAVKISEQNCLLYECD--------G-RLYFRTCKFI-HPKQELKV
GYSKEYADRFGLNFLVPDDNE-
>Styela_clava_XP_039272547.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---MSGQKVI-RIYNKTSKSKARSSLPDILAI-KKVGEH-----------CSVFAKCSLS
LLSQFGPLEAPLVTR-NEMDGS---------GFVIKLDINKCK-----RLENVDASYIYY
DMSDENMCNWMMFVQPAKSYTEQNLCAHQEE--------D-FIYFTTTRQV-LPDEELKV
WYSPTYAKFLSVPLLTSTSGCI
>Ciona_intestinalis_XP_002128357.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
FSEDEELEVF-AIKDKKFQSKARSTLPDILSVVQTET-----------YSCGVVAKTRIR
ARTQFGPLDAPLVSEQVSSFVL----KPGPTRLNEV-------------NTADDKTDLYY
DTREENSCNWMCLVRVAQNSDEQNLVAQLVK--------Q-DVYFTTIRKI-EAKEELKV
WYAPKYAKFLGKPLLQPNINQH
>Anneissia_japonica_XP_033126033.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLKQGVFH-TIADKPVTSRARASLPAMLQI-FKV-ED---------GQIGVFARKNVP
KRTQFGPLEGKLRNTEDEVANA---------VIKWKVQ-------------KADQSTLFM
DCSDESECNWMMFIRPAKRYSEQNLVAFQHE--------G-NIYFATMKNI-DPKTELKV
WYTKSYAEFVGVGVLEATAEE-
>Asterias_rubens_XP_033641495.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLKQGALQ-TISDNPVISRARASLPSQLQI-FKV-EN---------NEVGVFAKRVIP
KRTQFGPMEGKILRQ-EFLHKG---------TLKWLVK-------------RD-GQDAYL
DCSDEQESNWMGFIRPAKRYSEQNLIAFQLE--------N-SIYFATIKSV-EPKTELKV
WYAKSYAELIGEKVLEITAEE-
>Patiria_miniata_XP_038065260.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLKQGALQ-TISDNPVISRARASLPSQLQI-FKV-DN---------NQVGVFAKRSIP
KRTQFGPLEGKHIRA-EFLPKG---------SMKWLVK-------------QD-GMDAYL
DCSDEQESNWMGFIRPAKRYSEQNLIAFQME--------N-AMYFATIKTV-EAKSELKV
WYAKSYAELIGEKVLEITAEEA
>Acanthaster_planci_XP_022098457.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
------------------------------------------------ESLGVFAKRSIP
KRTQFGPLEGKVVRP-ESLHKG---------AFKWLVK-------------RD-GKDIHL
DCSDEQESNWMGFIRPAKRYSEQNLIAFQME--------N-AIYFATIKMV-EAKTELKV
WYAKSYAELIGEKVLEITPEE-
>Holothuria_leucospilota_KAJ8035274.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLKQGALQ-RIVDRPITSRARATLPSMLQV-FKI-SS---------SEVGVFAKRALP
KRTQFGPLEGFIVHE---PPAT---------SLKWPVE-------------RN-GERVFI
DCSDEFRSNWMGFIRPARSYSEQNLMAFCNQ--------N-EIYFATIKTI-EPRQELKV
WYAKSFAESLGERILEITPEE-
>Strongylocentrotus_purpuratus_XP_030833423.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLRQGAIQ-TIADKPIISRARASLPPMLQI-FKV-ED---------DEIGVFAKRTIS
KRTQFGPLEGRIVTR-DEVPKD---------HMTWNVK-------------RN-GEDMYI
DCADEYESNWMSFIRPASCYSEQNLIAFQLG--------GTEIYFATIKNI-PPRTELRI
WYAKAYAETIGENILEITAEE-
>Lytechinus_variegatus_XP_041470407.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLRQGAIQ-TIADKPIISRARASLPPMLQI-FKV-EN---------DQIGVFAKRTIS
KRTQFGPLEGRIVTR-AEVPQD---------HMTWKVK-------------RN-GQDMYI
DCADEYESNWMSFIRPASCYSEQNLIAFQLN--------GTEIYFATIKNI-APRTELRV
WYAKAYAETIGENILEITAEE-
>Lytechinus_pictus_XP_063959971.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--FLRQGAIQ-TIADKPIISRARASLPPMLQI-FKV-EN---------DQIGVFAKRTIS
KRTQFGPLEGRIITR-AEVPKD---------HMTWKVK-------------RN-GQDMYI
DCADEYESNWMSFIRPASCYSEQNLIAFQLS--------GSEIYFATIKNI-APRTELRV
WYAKAYAETIGENILEITAEE-
>Saccoglossus_kowalevskii_XP_006812318.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
------GALQ-TICDKPVLTRARASLPNLLQI-FKV-DD---------DKVGVFAKRAIP
KKTQFGPIEGKLVSE---MPAE---------GMVWKLQ-------------QEDGSIAYF
DLMDENECNWMMFVRPASCHSEQNLIAYQNG--------G-NLFFATIRTV-DPKQELRI
WYAASYAEFVGADVFEITAEEL
>Paralvinella_palmiformis_KAK2153604.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CMKHKQQ-PIYDKVLLSRAWATLPSPLQI-LRLGET---------SELGVFARKTVQ
KRTKFGPFYAPLVESLEHVTNK---------RFLLK-------------IENEDGSQYFF
EANDENSCNWMMFVRPANNYSEQNVVAFQYK--------M-DIFYMTTKNI-EPKQELKV
WYAAPYANRMGVEPYRPTEEEL
>Capitella_teleta_ELU00380.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVEHKLK-AVYDRVVLSRAWASLPSHLQI-FRLGEA-------SSTELGVFAKKAFP
KRIQFGPFVAEHVLNRDQLTNP---------KFFLQ-------------VEQEDGQVAYL
EASDENKCNWMMFVRPAVTYEEQNLVAYQYG--------N-GIFFTTIKPI-EPRQELKV
WYAASYAEHIGVSVHELTDEDL
>Ridgeia_piscesae_KAK2180456.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPHHQQQ-PVYDKLVVSRAWASLPPQLQI-FRFGEP---------LELGVFAKKTIP
KRIQFGPYVADLVDDTGKLSST---------DFVLK-------------LERENGT-FYL
ETSDENKCNWMMFVRPAKTYAEQNLVAYQYG--------A-DICFTTIRDI-EPKQELKV
WYAAHYAEHVGVKTHQVSEADQ
>Physella_acuta_XP_059172951.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHRVT-CIQDKVVMTRAWASLPNQVHI-FRITESQ--MGP-EDPEFGVQAKRQIP
KFTQFGPFVADLVPSPELVTRK---------SFPLMVEQ-------------EDGGCMYF
ETADEDKCNWMMFVRPARTFAEQNLVAYQYK--------E-HVYFTVTKLI-ESKQELKV
WYAAHYAERIGVKTLELTEEDM
>Biomphalaria_glabrata_XP_013066851.2_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKVA-IIQDRVVLTRAYASLPNQLQI-IKINDSQ--PGDTEPADHGVQAKRQIA
KYTQFGPLVADLVDSIDQVTRK---------SFPLKLEL-------------PDGSFKYL
DCVDEDKCNWMMFVRPAKTFAEQNLVAYQYK--------D-GIYFSVTKQI-ESKQELKV
WYAAHYAGHLGVKTLELTEEDM
>Biomphalaria_pfeifferi_KAK0042406.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKVA-IIQDRVVLTRAYASLPNQLQI-IKINDSQ--LGDTEPADHGVQAKRQIA
KYTQFGPLVADLVDSIDQVTRK---------SFPLMLEL-------------PDGSFKYL
DCVDEDKCNWMIFVRPAKTFAEQNLVAYQYK--------D-GIYFSVTKQI-ESKQELKV
WYAAHYAGHLGVKTLELTEEDM
>Bulinus_truncatus_KAH9504326.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVIHKVS-AIQDKLVLTRAYASLPSQLQI-IKTDSQL----ENGEPDHGIQAKRQIA
KYTQFGPFVAELVDSLDQVTRK---------SFPLMLEL-------------PDGSFKYF
ETRDENKCNWMMFVRPAKTFAEQNLVAYQYK--------D-GIFFSVSKLI-ESKQELKV
WYAAHYAGHLGVKTLELTEEDM
>Elysia_chlorotica_RUS77561.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPAHRLT-AVPDKIVLSRAWASCPNQVQI-CRLHEAQ--VEP-GDSAMGVFAKRQIP
KFTQFGPLLGVLVDSLDKVTRQ---------FFPLMVSFCSFCCVFDLGSLNLNLPREYF
ETADENECNWMMFIRPAKTFAEQNLVAYQHR--------R-NVFFSSTRTI-EPKQELKV
WYAAPYAEQMGVKTLELTEDDI
>Elysia_crispata_KAK3722828.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPVHRLT-AVPDKIVLSRAWASCPNQVQI-CRLPEAQ--LAP-GESSVGVSAKRQIP
KFTQFGPFLGVLVNALDKVTRQ---------FFPLMLDL-------------PNKPRQYF
ETADENECNWLMFVRPARTFAEQNLVAYQHK--------R-NVFFSSTKII-EPKQELKV
WYAAPYAEQMGVKTLELTEDDI
>Aplysia_californica_XP_012943372.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHMLH-VVPDKVVLSRAWASSPPHIQI-FKVPQSQ---LVDGESSLGVYAKRPIQ
KYTQFGPFSGHLVDSLDQLERS---------YFPLM-------------LEHADGERSYF
ETSDENRCNWMMFVRPAKTFSEQNLVAYQYK--------Q-DVFFTVTKLV-ENKQELKV
WYAAHYAERMGLKALELTEADV
>Owenia_fusiformis_CAH1797479.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHSLQ-LVYDKVVLSRAWSSLPPMLLI-FRLAST---------AELGVFAKRDIA
KRTQFGPFCSDIVPSKEQLTNP---------NNLLL------------MVDREDGSSVFY
DAVDENKCNWMMFVRPAKTYAEQNVVAYQHG--------T-DIYFSAIKHI-PSREELKV
WYAPHYAERLGIKTHEITEADR
>Lingula_anatina_XP_023930001.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTAHRLL-PVYDKVVLSRAWSSLPGMLQI-FRIADDP--------NAIGVFAKKMVP
KRTQFGPFVGELVPDMDSVTNK---------EFPLQ-------------LIKADSQEMYF
NTSDENKCNWMMFVRAAQNFKEQNCVVYQHG--------E-DIFFSVTREI-EPREELKV
WYAAHYAEKLGKPVFKADLEDQ
>Octopus_sinensis_XP_036359248.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPEHRLQ-IVPDKVVLSRAWSSLPPILQI-FRLGES---------TELGVFAKRPIA
KSTQFGPFIGEPVANQNQLTNC---------RFVLM-------------LERENNECFYI
EMSDENKCNWMMFVRPAENFAEQNLVAYQHC--------Q-DIYFTVSKNI-EPRQELKV
WYAAHYAERIGAHVLDITDEDI
>Sepia_pharaonis_CAE1329123.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPEHRLQ-IVPDKVVLSRAWSSLPSILQI-FRLGES---------TELGVFAKRYIS
KSTQFGPFIGEPVASQNMLEDS---------KFILM-------------LEKENNEYYYF
KTSDENKCNWMMFVRPAENFAEQNLVAYQHG--------Q-DIFFTVSKNI-EPKQELKV
WYACNYAERIGVQVLDITDEDI
>Gigantopelta_aegis_XP_041372835.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPYHRLQ-MVLDKVVLSRAWSSLPAHLQI-FRLSES-------GGTELGVFAKRPIS
KYTQFGPFVGELVDSQDKLIVR---------KFLLM-------------LEKSGGGVEFF
ETSDENKCNWMMFVRPAANFSEQNLVAYQHK--------Q-DIYFTVTKNI-EPKHELKV
WYASHYADRMGLSTLEITEQDI
>Lottia_gigantea_XP_009055474.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPVHRAI-VVSDKIVLSRAWSSLPQMLQI-YRFN------------KIGVFAKKPVS
KMTQFGPFVADMVSSQDDLTNT---------RFLLMVLMNFFLY---FQLEKNDGTLGYF
ETSDENKCNWMMFVRPARNFAEQNVVAYQYG--------Q-DIYFTVMKNI-EARQELKV
WYSAHYGARIGIPIHEITERDK
>Haliotis_rubra_XP_046577359.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPVHRLS-IVLDKVVLSRAWSSLPPQLQI-YRLSET-------GGADLGVFAKKPIP
KYTQFGPFVGDLVDSQEKVTVH---------KFPLM-------------LDRSDNTLAYF
ETSDENKCNWMMFVRPAENFMEQNLVAYQHG--------Q-DIFFTVTKAI-DTRQELKV
WYAAHYATRMGLKTHDMTQEDR
>Haliotis_rufescens_XP_048254271.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPVHRLS-IVLDKVVLSRAWSSLPPQLQI-YRLSET-------GGAELGVFAKKPIP
KYTQFGPFVGDLVDSQEKVTVH---------KFPLM-------------LDRSDSTLAYF
ETSDENKCNWMMFVRPAENFMEQNLVAYQHG--------Q-DIFFTVAKPI-DTRQELKV
WYAAHYATRMGLKTHDMTQEDR
>Pecten_maximus_XP_033757805.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPVHRLQ-VIPDKVVLSRAWASLPPMLQI-FRLSEVS--QYPPDPPHVGVFAKRPLT
KLTQFGPYIGDLVSNRENVGSA---------RFLLL-------------LEKSSGDIMYF
ETSDENKCNWMMFVRPAESYAEQNMVAYQYG--------Q-DIYFSVTKNI-EARGELKV
WYASHYAERFGLQTLEITDQDL
>Mizuhopecten_yessoensis_XP_021355186.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPIHRLQ-VIPDKVVLSRAWASLPPMLQI-FRLSEDN--QYPPDPPHVGVFAKRPLT
KLTQFGPYIGDLVPNRESAGTT---------RFLLL-------------LEKVGGDIMYF
ETSDENKCNWMMFVRPAETYAEQNMVAYQYG--------Q-DIYFSVTKNI-ETRGELKV
WYASHYAERFGLQTLEITDQDL
>Ylistrum_balloti_XP_060063772.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPMHRLQ-IIPDKVVLSRAWASLPPMLQI-FRLSEVN--QYPADPPHVGVFAKRPLS
KQTQFGPYIGDLVSNRESVGSA---------RFLLL-------------LEKTGGDMMYF
ETSDENKCNWMMFVRPAESYAEQNMVAYQYG--------Q-DIYFTVTKHI-EARGELKV
WYASHYAERFGLQTLEITDQDL
>Mytilus_californianus_XP_052061545.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHRLT-LFPDKVVLSRAWASLPQMLQI-FRLEDAS--SQYGGEAHVGVFAKRTIP
RCTQFGPFIGELVQSKEDIQST---------KFLLM-------------LERQEGDVLYF
DTSDENKCNWMMFVRPAENFAEQNMVAYQHG--------F-DIYFSVTKNI-DIRTELKV
WYATHYARRHALHTLEITQQDI
>Crassostrea_virginica_XP_022322765.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKLT-LVPDKVVLSRAWSSLPPLLQI-FRIHDPN---VPLSETSVGVFAKRTIQ
KNVQFGPFVGELVTK-DNVMNT---------RFPLA-------------IERGEGDVSYF
DTSDENKCNWMMFVRPADSYADQNCVAYQYG--------L-DIYFTVTRNI-EARAEIKV
WYAPHYAQRFGFPQLEITDQDI
>Ostrea_edulis_XP_056013494.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKLT-LVPDKVVLSRAWSSLPPLLQI-FRIGDPS---LHPAETNVGVFAKKTIQ
KNVQFGPFVGELVTK-DCGINS---------KFPLA-------------IERGEGDINYF
DTSDENKCNWMMFVRPAGSYADQNCVAYQYG--------L-DIYFTVTRNV-EARAEIKV
WYAPHYAERFGFPQLEITDQDI
>Saccostrea_echinata_XP_061165396.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKLT-LVPDKVVLSRAWSSLPPLLQI-FRIGDPN---LHPIETSVGVFAKRTIQ
KNVQFGPFVGELVTD-ENAING---------KFPLA-------------IERGEGDVSYF
DTSDENKCNWMMFVRPAESYAEQNCVAYQYG--------L-DIYFTVTRNI-EAKAEIKV
WYAPHYAERFGFPKLEITDQDI
>Saccostrea_cucullata_XP_062572035.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKLT-LVPDKVVLSRAWSSLPPLLQI-FRIGDPN---LHPIETSVGVFAKRTIQ
KNVQFGPFVGELVTD-ENIINS---------KFPLA-------------IERGEGDISYF
DTSDENKCNWMMFVRPAESYAEQNCVAYQYG--------L-DIYFTVTRNI-EAKAEIKV
WYAPHYAERFGFPKLEITDQDI
>Mya_arenaria_XP_052805102.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CSAHTLI-PLPDKIVFSRAWASLPSQLQI-FRMEQTN-----GGETELGVFTKKRIN
KQTQFGPFVAELVGSRDHLTRH---------TFPLM-------------VEQPSGEVAYY
EACDENKCNWMMFVRPAASFAEQNLVAYQHG--------Q-DIFFTTSKDV-DSREELKV
WYAAHYADRWNQPYYTATEQDI
>Dreissena_polymorpha_XP_052253518.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPTHKLV-PLSDKIVFSRAWASLPSPLSI-FRIDKKG-----GNETMLGVFAKRPIA
KQMQFGPFVGDPVSSKEEVANQ---------EFVLM-------------VEQATGEAIFF
DTSDENCCNWMIFVRPAADFSEQNLVAYQHG--------A-DIFFTTTKAI-EPREELKV
WYAAHYATRWNLPYHMPTEKDI
>Potamilus_streckersoni_KAK3611352.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTTHPLT-FCPDKIVFSRAWASLPSMLQI-FRLGTE---------GDLGVFSKRMIP
KFTQFGPFVAEVVDSQAKVTNA---------KFPLM-------------VERQTGEFIYY
ETSDENKCNWMMFVRPADTFAEQNLVAYQHG--------S-DIFFSVTKTI-EAKQELKV
WYAAHYAERLGKKRLEVTQEDI
>Mercenaria_mercenaria_XP_053372828.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CTQHRLI-PIQDKVVFSRAWASLPQSLQI-FRIEDDN--------NELGIFNKRPIV
KLTQFGPFVAELVDSEDKVTNR---------KFPLM-------------VER-DGVTMHY
ETSDENACNWMMFVRPAQNFSEQNMVAYQHG--------N-EIYFTVSKDINEPKTELKV
WYAAHYAERWNKPIHEATEQDL
>Ruditapes_philippinarum_XP_060601126.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CEQHRLI-PILDKVVLSRAWASLPQSLNI-FRIEDDN--------NELGIFNKRPIV
KFTQFGPFVAELLDSEDKVTNR---------KFPLM-------------VER-DGHTLYF
EACDENVCNWMMFIRPAQNFAEQNMVAYQHG--------N-EIFYTVTKDINEPKTELKV
WYAASYAERWNKTIYEATEQDI
>Branchiostoma_floridae_XP_035670510.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
------GPVQ-RIPSKPVLSKARASLPNQLFL-AKSGET---------TEHGVFTKRALP
KRTQFGPVEAKLLKK-EEIPEG---------TFLLK--HKTEG-----EEQPDDQPELYY
DLTNEDECDWMMFVKPAANHMEQNLVAYQHG--------N-EIFYTTIKPV-EPRQELKV
WYSTSYASFMGVSVHEVTEEEK
>Branchiostoma_belcheri_XP_019618675.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
--CKKHGPMQ-RIPSKPVLSKARASLPNQLFL-AKSGET---------TEHGVFTKXALP
KRTQFGPVEAKLLHK-EEIPEG---------TFLLKLQHKTEG-----DEQPADQPELYY
DLTNEDECNWMMFVKPAANHMEQNLVAYQHG--------N-EIFYTTIKSV-EPRQELKV
WYSTTYASFMGASVHEITEEEK
>Protopterus_annectens_XP_043937018.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHAIPNRPVFSRARASLPLILYI-DR-------------FLGGVYSKRRIP
KRTQFGPVEGPVVKQSELKDNY----------IHLKICSE------EENKIGRPQEDLWY
ELSDENICNWMMFVRPAKNHLEQNLVAYQHG--------S-SIYFTTIKNI-EPRQELRV
WYAASYAQFVSQKIYAISEEER
>Latimeria_chalumnae_XP_064424748.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLSRARASLPLILYV-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPFVKESDLKDDY----------IHLKVCIE------EGAKEEEKQADLWY
DLSDENQCNWMMFVRPAQNHLEQNLVAYQYG--------K-DIYYTTIKNI-EAKQELKV
WYAASYAEFLNQKIHDISEEER
>Scyliorhinus_canicula_XP_038634489.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPLVRQSELTDDY----------IHLKISMG---VGWEDCKDEDKPGDLWF
DLSDENFCNWMMFVRQAQNHLEQNLVVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVEQKTHDISEEER
>Hypanus_sabinus_XP_059813140.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGTLHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPLVKRSELSDDY----------IHLKVAMG---VGRDESKDGEKSGDLWF
DLSDENMCNWMMFVRRAQNHLEQNLVVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVEQKIHDISEEER
>Mobula_hypostoma_XP_062894510.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGTLHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPLVKRSELSDDY----------IHLKVAMG---VGRDESKDGEKSGDLWF
DLSDENMCNWMMFVRRAQNHLEQNLVVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVEQKIHDISEEER
>Amblyraja_radiata_XP_032905714.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGALHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPFVKQSELCDDY----------IHLKIAMG---VVREGLKEGEKPGDLWF
DLSDENLCNWMMFVRQAQNHLEQNLVVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVEQKIHDISEEER
>Chiloscyllium_plagiosum_XP_043532887.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGALHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPLVKQSELKDNY----------FHLKIAMG---VGREDCKDEEKPADLWF
DLSDENLCNWMMFVRQAQNHLEQNLIVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVERKIHDISEEER
>Carcharodon_carcharias_XP_041030141.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGTLHCIPNRPVLSRARASLPLILYI-NR-------------FAGGIFSKRRIP
KRTQFGPVEGPLVKQSELTDDY----------IHLKVAMG---VGREDCKDGEKPGDLWF
DLSDENLCNWMMFVRQAQNHLEQNLVVYQYG--------K-NLYFTTIKHI-EPKQELKV
WYAASYADFVERKIHDISEEER
>Amia_calva_XP_066567036.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIANRQVLSKARASLPLVLYI-DR-------------YLGGVYSKRRIP
KRTQFGPVEGPLVAQSQLMDGY----------IHLKVCLL------DGGKEVEKGDGLWV
ELSDEERCNWMMFVRPAQNHLEQNLVAYQYG--------K-DLYYTTIKNI-EPKQELKV
WYAASYADFVHQKIHDVTEEER
>Huso_huso_KAK6469133.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGTLHPIPNRPVLSKARASLPLVLHV-DR-------------FAGGVFSKRRIP
KRTQFGPVEGPLVRQSELKDHY----------IHLKVSAQ------DSVKEGEKGEDLWV
ELSDEERCNWAMFVRPAQNHLEQNLVAYQYG--------R-DIYYTTIKNI-EPKQELKV
WYAASYAEFVNQKVHNVTEEER
>Polyodon_spathula_XP_041098465.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGTLHPIPNRPVLSKARASLPLVLHV-DR-------------FVGGVFSKRRIP
KRTQFGPVEGPLVRQSELKDHY----------IHLKVSTQ------DSVKEGEKGEDLWV
ELSDEERCNWAMFVRPAQNHLEQNLVAYQYG--------R-DIYYTTIKNI-EPKQELKV
WYAASYAEFVNQKVHEVTEEER
>Megalops_cyprinoides_XP_036393098.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIPNRPVLSKARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQSELQDNY----------IHLKVCMQ------DSAKEGEKAEDMWV
DLSDEERCNWMMFVRPAQNHLEQNLVAYQYG--------A-DIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Brienomyrus_brachyistius_XP_048836937.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIANRPVLSKARASLPLVLYV-DR-------------FQGGVYSKRRIP
KRTQFGPVEAPLVRQSELQDGY----------IHLKVCML------DLAKDGEKKEDLWL
DLSDEELCNWLMFVRPAQNHLEQNLVAYQYG--------P-DIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIYNVTDEER
>Gymnothorax_javanicus_KAJ8266613.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIPNRPVLPKARASLPLALYL-DR-------------FAAGVYSKRRIP
KRTQFGPVEGPLVRQGELRDNY----------IHLKVCML------DTPKD-EQREDTWV
DLSDEERCNWMMFVRPAQNHLEQNLVAYQYG--------A-HIYYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDITDEER
>Tachysurus_fulvidraco_XP_026988416.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVKHGPLYPIVNRPVMSKARASLPLILYI-DH-------------FQGGVYSKRRIP
KRTQFGPVEGPLMPQSELQDTQ----------FQLKLCMT------GPQKDSNSSEDIWI
NLSDEDRCNWMMFVRPAENHLEQNLVAYQYG--------S-EIFYTSIKNI-PPKQELKV
WYAASYAEFVNKKVHEITEEER
>Danio_rerio_NP_001334616.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CIKHGPLHPILNRPVMSKARASLPLVLYI-DR-------------FLGGVFTKRRIP
KRTQFGPLEGPLVRQSELLDTH----------IHLKLYML------DPEKEGERAQDLWF
DLSDEERCNWMMFVRPAQNHLEQNLVAYQYG--------S-DIFYTSIKNI-QPKQELKV
WYAASYAEFVNQKVHDVTEEER
>Takifugu_rubripes_XP_029699745.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPILNRPVMTKARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVPQSELQEHY----------IHLKLCEL------DVEKDIEKSNDLWL
ELSDEERCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKEELKV
WYAASYAEFVNQKIHDVTEEER
>Lucifuga_dentata_KAF7656993.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIPNRPVVSRARASLPLILYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVPQNELQDHY----------IHLKLCML------DGEKVGEKSDDTWL
DLSDEDGCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTEEER
>Thunnus_albacares_XP_044210184.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGPLHPIPNRPVMSKARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVPQSELQDHY----------IHLKLCML------DAEKDGEKSDDTWL
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTEEER
>Sebastes_umbrosus_XP_037630174.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVMSKARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVSQTELQDHY----------IHLKLCML------DAEKDAEKSDDMWL
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTSIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTEEER
>Gadus_macrocephalus_XP_059930714.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGALHPLPNRPVVSKARASLPLLLYM-DR-------------FMGGVFSKRRIP
KRTQFGPLEGPLVPESQLQDHN----------IHLKLCML------DSDKDGEKTDESWV
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAQFVNQKIHTVTEEER
>Gadus_morhua_XP_030236202.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGALHPLPNRPVVSKARASLPLLLYM-DR-------------FMGGVFSKRRIP
KRTQFGPLEGPLVPESQLQDHN----------IHLKLCML------DSDKDGEKTDESWV
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAQFVNQKIHTVTEEER
>Solea_solea_XP_058490479.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CLKHGALHPIPNRPVVSKARASLPLVLYT-DR-------------FLGGVFSKRRIP
KRTQFGPLEGPLVPQGELQDHY----------IHLKLCLL------DAEKDAEKPSDMWF
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELRV
WYAASYAEFVNHKIYNVTDEER
>Osmerus_eperlanus_XP_062328506.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CQKHGPLHPIPNRPVVSKARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQNELQDHY----------IQLKLCML------DAEKDEQKPEDMWV
DLSDEDSCNWLMFVRPAENHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKVHDVTEEER
>Esox_lucius_XP_034150060.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CEKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELQDHY----------IHLKLCML------DADKDVEKSDDMWL
DLSDEDSCNWMMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVSQKVHDVTEEER
>Salmo_salar_XP_045580886.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CMKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DADKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Salmo_trutta_XP_029629775.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CMKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DADKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Oncorhynchus_kisutch_XP_031651345.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DVDKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Oncorhynchus_mykiss_XP_036817577.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DADKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKVHDVTDEER
>Oncorhynchus_gorbuscha_XP_046171058.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DADKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Oncorhynchus_keta_XP_052320943.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CVKHGALHPIPNRPVVSRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQGQLHDHY----------IHLKLCML------DADKDMEKSDDMWV
DLSDEDICNWLMFVRPAQNHLEQNLVAYQYG--------S-EIFYTTIKNI-QPKQELKV
WYAASYAEFVNQKIHDVTDEER
>Rhinatrema_bivittatum_XP_029428847.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVYSKRRIP
KRTQFGPVEGPLVKQSELKDSY----------IHLKVSLE---S--GNSSGRDFHEDLWF
ELSEESLCNWMMFVRPAQNHLEQNLVAYQYG--------Q-HIYYTTIKNV-EPKQELKV
WYAASYAEHVNQKIHDISEEER
>Microcaecilia_unicolor_XP_030077018.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYV-DR-------------FLGGVYSKRRIP
KRTQFGPVEGPLVKKSELKDSY----------IHLKVSLE---S--GNSSGRDFREDLWF
ELSEESLCNWMMFVRPXQNHLEQNLVAYQYG--------Q-HIYYTTIKNV-EPKQELKV
WYAASYAEHVNKKIHDISEEER
>Geotrypetes_seraphini_XP_033774339.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYV-DR-------------FLGGVYSKRRIP
KRTQFGPVEGPLVKKSELKDSY----------IHLKVSLE---S--SNSSGRDFHEGLWF
ELSEESLCNWMMFVRPAQNHLEQNLVAYQYG--------Q-HIYYTTIKNV-EPKQELKV
WYAASYAEHVNKKVHDISEEEK
>Pseudophryne_corroboree_XP_063799714.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGALHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVYSKRRIP
KRTQFGPLEGPLVKKSELKDCY----------IHLQVLLN---N--TLESQDTFQEDLWF
DLSEESLCNWMMFVRPAQNHLEQNLVAYQYG--------Q-HIYYTTIKNI-EPKQELRV
WYAASYAEFVNQKIHDISQEER
>Bufo_bufo_XP_040287950.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGALHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVYSKRRIP
KRTQFGPLEGPLVKKSELKDTY----------IHLKVLLN------SLETQEPYQEDLWF
DLSEESLCNWMMFVRPAQNHLEQNLVAYQYG--------Q-HIYYTTIKNI-EPKQELRV
WYAASYAEFVNQKIHDISQEER
>Pelobates_cultripes_CAH2320456.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGALHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVYSKRRIP
KRTQFGPLEGPLVKKSELKDGY----------IHLKVSLN---S--T-NSDGNLHEDLWF
ELSEESLCNWMMFVRPAKNHLEQNLVAYQYG--------Q-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNEKIHDISQEER
>Tachyglossus_aculeatus_XP_038609570.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVYSKRRIP
KRTQFGPVEGPLVRQAELKDCY----------IHLKVALE---K--GERKDRSQHEDLWF
ELSDEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYFTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Vombatus_ursinus_XP_027690907.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVTQSELKDCY----------IHLKVSLE---K--GDRKDRDMHEDLWF
ELSDEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Antechinus_flavipes_XP_051842637.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVTQSELKDCY----------IHLKVSLE---K--GERKDRDIHEDLWF
ELSDEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Apus_apus_XP_051494441.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Corvus_cornix_XP_039420711.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDITEEER
>Taeniopygia_guttata_XP_030146936.3_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYADFVNQKIHDITEEER
>Tyto_alba_XP_032838122.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Apteryx_rowi_XP_025927478.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Chelonia_mydas_XP_037738028.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLE---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Chelonoidis_abingdonii_XP_032658215.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQTELKDCY----------IHLKVSLE---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Varanus_komodoensis_XP_044295500.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRQSELKDCY----------IHLKVSLD---K--GDRKDRDLKEDLWF
ELSSESLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDVSEEER
>Python_bivittatus_XP_025028699.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRLSELKDCY----------IHLKVSLD---K--GDRKDRDLQEDLWF
ELSSEALCNWMMFVRPAQNHLEQNLVAYQYG--------H-HIYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDVSEEER
>Lynx_pardinus_VFV31663.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLE---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Homo_sapiens_NP_001354822.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRGSELKDCY----------IHLKVSLD---K--GDRKERDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Rattus_norvegicus_NP_001414701.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRGSELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Saccopteryx_leptura_XP_066221332.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDPHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Galemys_pyrenaicus_KAG8523163.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Mirounga_leonina_XP_034865195.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Vulpes_vulpes_XP_025854699.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Myotis_daubentonii_XP_059532914.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Erinaceus_europaeus_XP_060035868.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKEFY----------IHLKVSLD---K--GDRKDRELHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------Q-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Dasypus_novemcinctus_XP_058145403.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Loxodonta_africana_XP_064124930.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>XP_025854699.1 (best hit for PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Equus_caballus_XP_023500904.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
>Balaenoptera_acutorostrata_XP_007183415.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNRKIHDISEEER
>Bos_taurus_NP_001178097.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNRKIHDISEEER
>Muntiacus_reevesi_XP_065793480.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNRKIHDISEEER
>Sturnira_hondurensis_XP_036894069.1_PRD10_HUMAN_1147_residues (PRD10_HUMAN_1147_residues)
---CPKHGPLHPIPNRPVLTRARASLPLVLYI-DR-------------FLGGVFSKRRIP
KRTQFGPVEGPLVRESELKDCY----------IHLKVSLD---K--GDRKDRDLHEDLWF
ELSDETLCNWMMFVRPAQNHLEQNLVAYQYG--------H-HVYYTTIKNV-EPKQELKV
WYAASYAEFVNQKIHDISEEER
