>Amphimedon_queenslandica_[PORIFERA] XP_019853365.1 PREDICTED: histone-lysine N-methyltransferase PRDM9-like 
CEDCQKIHHGDCPVHGPLATLDPSSGYN----TASLQYTSVPVPRE-LTVKESKIPKAGL
GVFAT-ELIPNGVKFGPYKGQKVYYED--IDEDD--DTSYMWEIKKP--NESYYIDGQVE
SESNWMRYINCARNEEEQNLVAFQYHGEIYYRTFKDICPGTELFVWYGDQYAKDLGI---
ETTVN-----------
>Oopsacas_minuta_[PORIFERA] KAI6661891.1 60 kDa SS-A/Ro ribonucleoprotein-like 
CEECDDLHLGDCPVFGELCPLDESAMII-------SPLSSIPIPKQ-LILKNSSIPKAGL
GIFAT-ETIAIRTRMGSYAGTFVRGSV--DNLPN--ESEYLWQIKRGNGKAVWYIDGEDL
TRANWMRYVNCARHEDEQNLVAFQFKGRIYYRTYKVVNPGDELLVYYGDQYAKHLGI--G
QFDN------------
>Desmophyllum_pertusum_[CNIDARIA] KAJ7369806.1 Histone-lysine N-methyltransferase prdm9 
CEGCQDLHYGDCPVHGPLQIIEDRTEDG----NSNLSSAVASLPTV-LKISNSSIPGAGL
GVFST-SEIPKGVRFGPYKGKKIRWEH--ITDET--NTSYMWEIVKD-GKFSHFLDGGDE
AHSNWMRFVNCSRCEDEQNLVAYQYRGEIYYRTYKSVNPGNELLVWYGESYAKDLGISVN
DSNDE--NKRK-----
>Orbicella_faveolata_[CNIDARIA] XP_020615740.1 zinc finger protein 3 homolog 
CEECQDLHFGDCPVHGPLQVINDKIMEG----YSNLSSAVASLPPV-LKISPSSIPGAGL
GVFST-SEIPKGVRFGPYKGKKRGWEH--ISDET--NTSYMWEIVKD-GKFSHFLDGQDE
SHSNWMRFVNCSRCEDEQNLVAYQYRGEIYYRTYKPVTPGKELLVWYGESYAQDLGIAPC
DNQDH--SISI-----
>Porites_evermanni_[CNIDARIA] CAH3155689.1 unnamed protein product 
CEDCNDLHYGDCPVHGPLQIIEDKPREE----NPDVSAAVASLPAS-LKISDSSIPGAGL
GVFST-SEIPKGVQFGPYKGMKIGWEN--ITEDR--NTSYCWEILKD-GKFSHFLDGRDE
NNSNWMRFVNCCRCEDEQNLVAFQFRGKIYYRTYKPIKAGSELLVWYGESYAKDLGILLD
DNKDR--SKTN-----
>Acropora_digitifera_[CNIDARIA] XP_015772146.1 PREDICTED: histone-lysine N-methyltransferase PRDM9-like 
CEDCHDLYYGDCPKHGPLQVIEDKDAEH----SWGVSAAIASTPDV-LEIDQSSIPGAGL
GVFSA-AFIPERARFGPYKGDKVVWEN--MTDKT--DTSYFWEVMKD-GKFSHFVDGHDK
SNSNWMRFVNCPRSEDEQNLVAFQYRGKIYYRTYKAISPGKELLVWYGEGYARELGIEID
DSQED--SVQSHSNG-
>Pocillopora_meandrina_[CNIDARIA] CAH3133825.1 unnamed protein product 
CEECQDLHYGDCPVHGPLQIIADRNTTE----NSNLSPAVSSLPVV-LKIKSSSIPGAGL
GVFST-TDISKGVRFGPYKGKKIGWEN--ITDET--NTCYMWEIVKS-GKFSHFVDGHEE
SQSNWMRFVNCSRCEDEQNIVAFQFRGEIYYRTYKSINPGEELLVWYGESYARDLGISLV
DDPDR--GSKK-----
>Stylophora_pistillata_[CNIDARIA] XP_022785311.1 histone-lysine N-methyltransferase PRDM9-like 
CEECQDLHYGDCPVHGPLQIIADRITAE----NSNLSIALSSLPAV-LEIKTSSIPGAGL
GVFSI-THIPKQVRFGPYKGKKIKWES--ITDEM--NTCYIWEIVRS-GKLSHFVNGHDE
SQSNWMRFVNCSRCEDEQNMVAFQFRGEIYYRTYKSINPGEELLVWYGESYARDLGISLV
DDQDR--SSTK-----
>Nematostella_vectensis_[CNIDARIA] XP_032234935.2 histone-lysine N-methyltransferase PRDM9 isoform X1 
CEECQDLHYGECPIHGPLQAIADNATTS-----STQTTARATLPHC-LEIKTSSIPNAGL
GVFSK-SRIAKRVMFGPYKGTKVKLSD--EQMEN--DTSYMWEISRD-GNFNHFIDGHDE
EQSNWMRFVNCSRCEKEQNLVTFQYRGQIFYRSYKDVHPGTELLVWYGDKYANDLGIALE
DVEDS--NIIA-----
>Paramuricea_clavata_[CNIDARIA] CAB4028688.1 histone-lysine N-methyltransferase PRDM9-like, partial 
CDQCDDFYYGECPTH-NFNIIEDNDMEA----GKKTPGAIKSLPEN-LCVKPSTIPEAGM
GVSAK-EKLEVNTRFGPYRGDKILKED--LEEGR--NTSYMWEIIQE-GKIQYYIDGKDP
SQSNWMRFVNCARCEDEQNIIAYQYHGEIFYRVYKEIDADAELLVWYGDEYAEQLGILLF
EEEEK--QEEKRFK--
>Dendronephthya_gigantea_[CNIDARIA] XP_028394808.1 histone-lysine N-methyltransferase PRDM9-like 
CDQCDDFYYGECPTH-NFNIIEDNGTDT--EKGMKMPDAMKSLPGN-LYVKDSKIPEAGM
GVFSK-EKLEINTRFGPYRGVKVLKED--LEEGK--DTSYMWEIVHE-GKIQFYIDGKDL
NHSNWMRYINCARCEDEQNIIAYQYHGDIYYRVYKEIHVDDELLVWYGDEYAEQLGISLF
EEDEK--QLEKLFE--
>Hydractinia_symbiolongicarpus_[CNIDARIA] XP_057300026.1 zinc finger protein 431-like 
CEDCGDFYYGDCPVHGALHPLADKYNPV-----NDEKKSIATLPDG-LEINESFIPGAGL
GIITT-QKFESGTRFGPYQGKKVRPDI--PRDDV--DTSYMWEIMRD-GKIVYYVNGKDE
NYGNWMRYINCSRTEQEQNLIAFQYHGEIYYRLYKDVAAGTELLVWYGDDYARDLGIALS
DDKKA--STKI-----
>Hydra_vulgaris_[CNIDARIA] XP_047143556.1 histone-lysine N-methyltransferase PRDM9-like isoform X1 
CESCSEFFYGDCPEHGSLLPLADKTVNY-----DEVQRSVATLPDG-MVIKESLIPHAGL
GVFAI-ENFDVGVRFGPYQGKKIRPDI--PKEDL--DTSYMWEIMKD-GNVLYYIDGKDE
RYSNWMRYINCSRIEAEQNLVAFQYHGEIYYRVYKKVEKGKEFLVWYGDDYAKDLGI---
-------INSKK----
>Magallana_gigas_[BIVALVIA] XP_034333813.1 zinc finger protein 665 
CEECNKEHEGDCPYHGPLKVIKDVEQPR-----GISDRAMKTLPQG-LFVRDSIIPNAGK
GVFAE-MLIPKRTRFGPYEGECTE--N--QEEAH--ETGYAWQIYKQ-GQRSHFVNAFKE
PMSNWMRYVNCARSESEQNMVAFQHRGQIYYRSFKDISPGTELLVWYGHDYGKELGI--F
RGEVE--IIPKVLNGE
>Crassostrea_virginica_[BIVALVIA] XP_022303385.1 putative zinc finger protein 66 
CEECNREHEGDCPYHGPLKIVNDTKQPL-----GVTDRARKTLPQG-LSIRKSSIPNAGE
GVFAE-QFIPKRTQFGPYEGEITD--N--QEEAH--ETGYAWQIYKH-GRPSHFVNAFKE
PISNWMRYVNCARSEFEQNLVAFQHQGQIFYRSFKDIAAGTELLVWYGHDYGKELGI--F
RSDVA--ITPKLVNGE
>Saccostrea_echinata_[BIVALVIA] XP_061170491.1 histone-lysine N-methyltransferase PRDM9-like isoform X2 
CEECNREHEGDCPVHGPLLVVSDTEQPQ-----GIPDRAKKTLPIG-LSVRESNIFNAGQ
GVFAD-KFFLKRTRFGPYEGEVTE--N--QDEAQ--ETGYAWQIYKK-GQPSHFVNAFKE
PCSNWMRYVNCARSEIEQNLVAFQYKGQIYYRSFKDISAGTELLVWYGHDYGKELGI--F
REHID--VTPKIVNGE
>Ostrea_edulis_[BIVALVIA] XP_048750803.2 zinc finger protein 665-like 
CEECNGEHEGDCPVHGPLLVVEDTKQSL-----GIPDRAKKTLPPG-VSVRKSRIPNAGL
GVFTD-KFISKRTKFGPYEGKITE--N--QEEAH--ETGYAWQIYKQ-GQPSHFVNAYEE
TTSNWMRYVNCARSESEQNLVAFQHKGEIYYRSFKDIPPGTELLVWYGHDYGKELGI--H
REDIQ--IISKFINGE
>Ruditapes_philippinarum_[BIVALVIA] XP_060558031.1 zinc finger protein 737-like 
CEDCNKEYDMDCPIHGPLQYIRDTVVNL----EYDEDRALHTLPPG-LVVKPSSIIGAGL
GVFTE-REIPPRVMFGPYGGVEIH--D--EMTAH--DSGYCWQIYAN-GKPSHFVDARDK
VTSNWMRYVNCAPSESEQNLVAFQFKGNIYYRSYKTIFPGTELLCWYGNEYGRELGL-VR
DKNLL--IRPKLVNGQ
>Mercenaria_mercenaria_[BIVALVIA] XP_053387483.1 zinc finger protein 271-like isoform X2 
CEECNKEYDMDCPIHGPLEYIQDTEVLN----SQDPDRALHSLPPD-LVVKNSSIKGAGL
GVFTE-KEIPARVMFGPYGGVIVT--D--PEKAH--KSGYCWQIYKD-GKPSHFVDAQDK
VHSNWMRYVNCATSEEVQNLVAFQFKGGIYYRSYKTIAAGTELLCWYGTEYGRDLGI-VR
DKNLL--FRPKYVNGQ
>Dreissena_polymorpha_[BIVALVIA] XP_052213848.1 histone-lysine N-methyltransferase PRDM9-like isoform X1 
CEECKKDFEGDCPVHGPYHYIQDKEVVS-----GDPLKADNTLPDG-LEIKMSKIVGAGL
GVFSK-MGLESRIMFGPYGGDIIT--D--SQAAH--KSGYCWQIYTE-GKPSHFVDAQNK
STSNWMRYVNCAMKEADQNLVAFQYKGGIYYCTFKPVLPGEELLVWYGDEYARELGL-IR
DKNLL--FRPKYVNGE
>Potamilus_streckersoni_[BIVALVIA] KAK3580334.1 hypothetical protein CHS0354_014807 
CEECNKEYEGACPDHGPLVVVEDSKVPD----TCKKDQDRATLPAG-LTIKESGIPNAGL
GVWAD-VQFASRTRFGPYVGVITK--D--VDKVH--ATGYAWQIYKD-GEASHFIDARDP
AQSNWMRYINCARTEAEQNLTAYQYYGHIYYRAFKTIEPGKELLVWYGNEYGRDLGI-VR
DIKSF--LKPKYVNGE
>Mytilus_californianus_[BIVALVIA] XP_052080008.1 zinc finger protein 665-like 
CEDCEREYEGDCLVH-PCINIFDSQTTT-----KNERRAINTLPDG-LSVKESRIPNAGL
GVFAD-KTFPSRSKFGPYQGEITK--D--AETAH--YTGYAWQIYLD-GAPNYFIDALDK
SKSNWMRYVNCARNEDEQNLIAYQYKGDIYYRCFKDIEPGNELLVWYGQDYGKDLGIERM
NITSI--LKPKYINGE
>Mizuhopecten_yessoensis_[BIVALVIA] XP_021377301.1 histone-lysine N-methyltransferase PRDM9-like 
CEECNKEYEGDCPVHGPLVIVEDTEIKP-----KDKERSLYTLPPG-LCVRKSSIQNAGL
GIWSD-YKISPRTRFGPYKGEKTQ--D--LDKAH--STGYAWQIYEN-GKPSFFIDAFDK
NQANWMRYVNCARNEDEQNMTAYQHRGQIYYRTHKVINPDTELLVWYGEDYSEELGI--R
RWEDSTELKPFTVNGT
>Pecten_maximus_[BIVALVIA] XP_033725916.1 histone-lysine N-methyltransferase PRDM9-like 
CEECNKEYEGDCPEHGPLDIVEDTEIVD--IKPKGKDRSLYTLPPS-LCVRESSIPNAGL
GVWSD-REILPRTRFGPYKGKQTQ--D--LDKAH--STGYAWQIYEN-GKPSYFIDAFDK
IHANWMRYVNCARNEDEQNMTAYQHKGQIYYRTHRVIKAGTELLVWYGDDYSDELGIRRR
AAEDPSQLKPFTVNGT
>Ylistrum_balloti_[BIVALVIA] XP_060080568.1 histone-lysine N-methyltransferase PRDM9-like 
CEECNKEYEGDCPVHGPLIIIEDTKMID--IKPKEKERCLYTLPPG-LSVLESSIPNAGL
GVWSD-HEILPRRRFGPYKGKLTK--D--LDQAH--STGYAWQIFEN-GKPSHFIDAFDK
NHSNWMRYVNCARSEDEQNMTAYQHKGQIYYRTHKIIKPRNELLVWYGDDYSDELGIRRG
AENPSE-CRPFTVNGT
>Biomphalaria_glabrata_[GASTROPODA] XP_013085935.2 histone-lysine N-methyltransferase PRDM9-like isoform X1 
CEECNFEYMGDCPEHGGLNIVRDSVVPSDCKPGLDEDYSKKTLPEG-LIIKQSKIPNAGL
GVFAT-QLFPSRTRFGPYLGKIEK--Y--EEDAH--ESGYSWQVYKD-SNTSHFVNASDP
TNSNWMRYVNCARSEDEQCVTAYQHQGQIYYRSHKDIHPGTEILVYYGDSYAKELGIQLQ
TVGNC--KKLLQVTNN
>Bulinus_truncatus_[GASTROPODA] KAH9500327.1 Histone-lysine N-methyltransferase prdm9 
CEECNFDYMGDCPEHGGLNIVVDATVPADCKMYQEKSYCWKTLPDG-LLIKQSSIPNAGL
GVFTT-KFFPVRSRFGPYVGTIEK--N--ELEAH--ESGYSWQVYKD-GRPSHFVNASNT
SSSNWMRFVNCARCEDEQCVTAYQHKGQIYYRAHKDIQPGTEILVYYGDSYAKDLGIQLQ
VVGLL--KKAKNKLYK
>Elysia_chlorotica_[GASTROPODA] RUS68832.1 hypothetical protein EGW08_023406 
CEECNIEYFGDCPEHGPLKIINDSVVPPTCKMGEDPEYCRKSLPPG-LMIKKSKIPQAGL
GVFAT-TFFPSRSRFGPYKGRKET--D--RIIAY--ESGYCWQVIQE-GKTSHFVDASDP
KESNWMRFVNCARSEEEQCVTAYQHEGEVYYRAHKDIHPGMEILVYYGDSYATDLGIKTQ
QVGGM--KKQVVSDSG
>Physella_acuta_[GASTROPODA] XP_059143957.1 histone-lysine N-methyltransferase PRDM9-like 
CEECNIEYIGDCTKHGPLNILSDSQVPPDCIRGKDKDYCKKTLPPG-LVIKTSNIPDAGL
GVFAL-TSFPARTRFGPYGGKKEK--N--EQMAH--DSGYCWQIFKD-GRPSHFVDASDS
SDSNWMRFVNCARCEDEQCVTAYQHKGEIYYRAHRDISAGTEILVYYGDSYARDLGIQVQ
RVGVV--SKNSLTNME
>Aplysia_californica_[GASTROPODA] XP_035827333.1 histone-lysine N-methyltransferase PRDM9 
CEECNFEYDGDCPEHGPLLIVADAQVPEGINKGTHSQYSSKTLPEG-LIIKRSTIPGAGL
GVFAV-KDFPSRTRFGPYGGKKVK--D--EATAH--LSGYCWQIFED-EKPSHFVDASDP
ACSNWMRFVNCARSEEEQCVTAYQYKGEIYYRSHRPIPAGTEILVYYGDSYARDLGIQVQ
KVGRL--VRAQTEPKE
>Candidula_unifasciata_[GASTROPODA] CAG5119181.1 unnamed protein product, partial 
CEECRQEYDGDCPIHGPLLLVDDAEVQQ--CPGESIEYSKRTLPVG-LVIKRSKIPHAGL
GVFAL-KDFPARTRFGPYKGKKEV--D--ETIAH--ESGYSWQIMKD-GQTSHFVDGKDP
SRSNWMRYVNCARHEDEQCVTAYQYQGDIYYRSHKPICAGTEILVYYGDSYARDLGINST
KPERK--QHRAKKVQE
>Haliotis_rufescens_[GASTROPODA] XP_046375300.2 histone-lysine N-methyltransferase PRDM9-like 
CEECNKEYEGDCPVHGPLLVVMDTQVSS---PSKKGERAEKTLPPG-LEIKPSSIPNAGL
GVFAI-ADFPTRTRFGPYEGDNIK--D--ADVAH--NSGYCWQVCVD-GRGSHFVDAANV
ETANWMRFVNCARTEDEQNVTAYQFEGSIYYRSYKPILPGDELLVWYGQDYARDLGI---
RREVK--VHHSKIP--
>Gigantopelta_aegis_[GASTROPODA] XP_041356286.1 zinc finger protein 724-like isoform X3 
CEDCGKEYDGDCPVHGPLNIVEDTKVPN---TVKNKDKASCTLPAG-LSIRKSGIPNAGL
GVWAD-KFFPSRTQFGPYGGICEK--D--IDKAH--ASGYCWQIYNDTGRLSHFVDARDP
SQSNWMRYVNCARTEEEQNVTAYQFSGQIYYRSFKPIKPGSELLVWYGQEYAKELGISPK
QWTSK--HMKKTNIK-
>Lottia_gigantea_[GASTROPODA] XP_009045324.1 hypothetical protein LOTGIDRAFT_156439, partial 
CEECNMEYGGDCPVHGSYNIIENKQVEE-SVSQKDKNRCYLTAPDC-IEIKESSIPNAGL
GTFAS-ITIPNRSRFGPYGGDIIK--D--TETAH--NSGYCWQIYQE-GKHHHFVDAKNP
ATSNWMRFVNCARTESEQNVTAYQYCGEIYYRTFKEIPPGSEILVWYGNEYGADLGINRP
LWSKSTFVAYHENMKK
>Octopus_sinensis_[CEPHALOPODA] XP_029652860.1 zinc finger protein 420-like 
CEDCNEEYTGDCPNHGPLLVVSDNKVAK-----GSPNRAKLTAPPC-VSITKSKIPGAGL
GAIAL-VTIHARSRFGPYEGKVID--D--QDEAH--ISGYSWQINTY-GKSTYFVDAMNV
TISNWMRYVNCARTEEEQNLNAFQYNGNIYYRTLRNIVPGEELLVWYGEEYAKDLGISHC
EQLKAKTVSTVGAQLS
>Lingula_anatina_[Other_SPIRALIA] XP_013396565.1 histone-lysine N-methyltransferase PRDM9-like 
CDECNMEYAGDCPVHGPLNIVEDVQVPA---DGSDPERARKTLPPY-FNIYTSQIPDAGL
GVWVI-RTLKNRTRFGPYEGEIST--D--TAKAH--ESGYSWQVYKE-GQPSHFVDAQDP
SKANWMRYVNCARTEREQNLVAFQYHGQIYYKTIKPIPEGNELLVWYGDAYAMELGIDKT
KPESN--LDLLRKLN-
>Owenia_fusiformis_[Other_SPIRALIA] CAH1776611.1 unnamed protein product 
CEDCNLEHKGDCPIHGPLIIVEDRKVE------GGKFRAELTAPYD-LVVRLSKIPGAGH
GVWTT-AEIPKGVRFGPYAGRIVEIHR--EHDAH--ESGYAWMIYKN-EKPSHFIDAGDV
GQANWMRYVNCARFEGEQNVTAFQYLGQIYYRTFRPIPPNTEVLVWYGESYAEELGIDVV
KFRNQTAHVNGIGNMN
>Ridgeia_piscesae_[Other_SPIRALIA] KAK2174698.1 hypothetical protein NP493_783g01042 
CDDCNTEYEGDCPVHGPLVIIKDTEVKA-VDLKPGVYRCHLSLPTG-LVIKTSSIPKAGA
GVWAE-APVPKGVRFGPYEGIIVE--H--SEDAH---SGYCWQIYKQ-GKAHHYVDAANK
NESNWMRYVNCACREEDQNLLAFQFHGEIYYRTIENVSAHTELLVWYGDEYGQELGITRQ
EFVSK--KQNDNYRCN
>Limulus_polyphemus_[Other_CHELICERATA] XP_013791986.1 probable histone-lysine N-methyltransferase PRDM7, partial 
CDDCEDEYEGDCPVHGPLLVIEDKKIPA---DGSDPMRADHSIPNN-LSIGTSGIKNAGS
GVWAE-VPFPKGVRFGPYEGIVTY--D--SIEAH--RSGYAWQIYKN-GRPSHFVNAKDT
SKSNWLRYVNCACNEEQQNLVAFQYHGQIFYRTYKPVLQGSELLVWYGDAYAKELGITRG
DKNSV--PKCIMDKD-
>Dermacentor_andersoni_[ARACHNIDA_acari] XP_050048434.1 histone-lysine N-methyltransferase PRDM9-like 
CDDCKMDYPGDCPVHGPLTHVKDTPVPL-----GDPQRANKTVPDG-LCVRRSTIKGAQY
GVFTM-KRLPKRLCFGPYEGVKV-------DSSA--ANGYTWQIRHS-GR-EFLVDGRPL
DRSNWMRYVNCAPEQSQQNLVAFVRQGAVYYRTCKVVNAAEELFVWYGDDFAKQLGLIG-
NSGTQ--SK-------
>Rhipicephalus_microplus_[ARACHNIDA_acari] XP_037273253.1 probable histone-lysine N-methyltransferase PRDM7 
CDDCNMDYPGDCPVHGPLTHVKDTPVPL-----GDPQRANKTVPDG-LLVRRSTIKGAQY
GVFTI-KQLSKRLCFGPYEGVTV-------DSSC--ANGYTWQIRHG-GR-VYLVDGRPL
DRSNWMRYVNCAPQQSQQNLLAFVRQGAVYYRTNRVVYPGEELFVWYGDAFAKQLGLIGK
SATAS--AQNKQGAKE
>Parasteatoda_tepidariorum_[ARACHNIDA] XP_042898984.1 histone-lysine N-methyltransferase PRDM9-like 
CDFCDCDYKGACPKHGPMLWVCDRRVPK-----NSSDRAELTIPSF-LSIGISSIPKAGL
GIWTE-IPLPIGTVFGPYKGKIIR--T--RQEAE--KSGYSWMVWKG-ERVNHYIEGFKK
DISNWLRFVNCADKEEKQNLVAIQYKKQIYYKTYRDVLPFQELLVWYGGKYASDLGISLK
RDIET--NQLNM----
>Stegodyphus_dumicola_[ARACHNIDA] XP_035208194.1 histone-lysine N-methyltransferase PRDM9-like isoform X2 
CEDCNLEHKGACPTHGPMLLVCDQKVAK-----GLQNKALGSTPCF-LSIGKSSLPKAGL
GVWTE-IPLPKGMVFGPYKGTIVR--K--REEAS--KSGYAWQVWKG-GKAHHYIEGFDK
SSSSWLRFVNCADIEERQSLTAFQYKKMIYYKTYKYVLPYTELLVWYGDQFARDLGI---
DTKKG--VLDDVA---
>Caerostris_darwini_[ARACHNIDA] GIX88188.1 histone-lysine N-methyltransferase PRDM9 
CDVCNEEYDGVCPVHGPMLLVCDTKVHK-----DDPQKARKSLPLT-LSIGFSSIKAAGL
GVWTE-MPLVAGVVFSPYKGKVVK--KG-GAGVK--ESGYAWQVRRE-TKTSLYVEGVDK
GSSNWMRYANCADSEEWQNVVAFQYKGAIYYRTYKPVLAYTEILVWYGNEYASHLGIDVR
QKKLL--PLPSKSVCD
>Araneus_ventricosus_[ARACHNIDA] GBN13368.1 Histone-lysine N-methyltransferase PRDM9 
CDVCNEEYRGSCPVHGPLLLVCDTKIPK-----GDSDRAKRTFPYF-FSIGISSIPRAGL
GVWTE-IPLVAGMVFGPYEGNVIK--Q--NEDAK--KSGYAWQVRKQ-SKPHHYVEGADE
DCSNWMRYVNCADHEEWQSVIAFQYLGKIYYRTYKPVLPYTEILVWYGNSYASDLGIEIK
GRKCL--QPP------
>Nephila_pilipes_[ARACHNIDA] GFS79972.1 histone-lysine N-methyltransferase PRDM9 
CDSCDQEYKGACPVHGPMLLVCDTRVFN-----NDSQKAKNTLPYF-LSIGISSLPRAGL
GVWTE-IPLTPGMVFGPYKGSLIK--K--SSEAK--KSGYAWQIRKG-SKISHYVEGKDE
RCSNWMRYVNCADREEWQNVVAFQYQGSIYYRTYKPILPFTEILVWYGDDYASDLGI---
DVQQQ--SHLEAL---
>Penaeus_chinensis_[CRUSTACEA] XP_047492491.1 zinc finger protein 724-like 
CADCEEEKEGECPYH-PLFLILDNPVVR---DGSEKDRARLTAPWP-LTVHDSKVKGAGK
GVWTN-AHLPAHLVFGPYEGRVLR--GH-PEDGK--ESGYGWKIRGV-GTSNTCIDAVDS
AVSNWMRYVNCSRTEAETNLSAFQYKGQIYYKTDSTISRGSELMCWYGDDYGKDLGL--S
REPSK--WKPPKRDVK
>Frankliniella_fusca_[THYSANOPTERA] KAK3908607.1 Histone-lysine N-methyltransferase PRDM9 
CDDCGREWEGDCPEHGPLQIVPDTEVAA-----GVPERARHTVPSS-LAVLQSKIPDAGL
GVWAK-EPIPRRVRFGPYEGDIT--------TKR--DTGYGWEIRRE-GKTVHCVDALDV
THSNWMRYVNCARHAGEENLHPYQHKGRLYYRTVTDIPAHAELLVWYGDSYAKDLGI---
DPKAH--REAAADARP
>Thrips_palmi_[THYSANOPTERA] XP_034237838.1 histone-lysine N-methyltransferase PRDM9-like 
CDDCERSWEGECPVHGPLLVIPDAKVEP-----KDPQRALHTVPPQ-LAVLDSKIEGAGK
GVWTK-QAVPKRARFGPYEGDIT-------EPNR--ESGYGWEIRRD-GKPVHCVDALRE
STSNWMRYVNCPRNVAEANLHPFQFQGHLYYRTVRDVPANTELLVWYGDSYGKELGI---
DPKAF--RAPAANAHV
>Frankliniella_occidentalis_[THYSANOPTERA] XP_026278869.2 histone-lysine N-methyltransferase PRDM9-like, partial 
CDDCQKEWDGDCPVHGALEIIADTEVAV-----GHPERALLTVPPQ-LVIEASKIPGAGR
GVWTR-QAVPRRVRFGPYEGDNV-------PANK--ETGYGWEIHRG-GKATHCVDALDM
AKSNWMRFVNCARHSGEENLYPYQYKGHLYYRVVRDIPPNTELLVWYGDSYGKELGL---
DPKLY--KDPTQDTRA
>Coptotermes_formosanus_[POLYNEOPTERA] GFG28833.1 hypothetical protein Cfor_03048 
CDDCNQEWEGDCPVHGPLTAVEDTKVPP---DPTDPTRADRTVPPQ-LCIAQSGISGAGY
GVWTS-VPLAKGLRFGPYEGVKV-------KSSN--SNGYCWQIRRN-SRPLYCVDAQDC
GVANWMRYVNCARHEEEQNLMAFQYKGEMYYRTFKHVPAHAELLVWYGDDYGRELGI---
DVESF--HKPQQKQSH
>Cryptotermes_secundus_[POLYNEOPTERA] XP_023708049.2 histone-lysine N-methyltransferase PRDM9 
CDDCGQEWEGDCPVHGALTVVEDTKVPA---DPEDSTRADRTVPSQ-LYIAQSGISGAGR
GVWSR-VPLSKGLRFGPYEGAKV-------KSSN--SNGYCWQIRRN-YRALYCVDAKNC
GIANWMRYVNCARHEEEQNLMAFQYKGEMYYRTVRPIPAHVELLVWYGDEYGRELGI---
VIENF--HKPQQKKSL
>Zootermopsis_nevadensis_[POLYNEOPTERA] XP_021927980.1 histone-lysine N-methyltransferase PRDM9-like isoform X1 
CDDCHHEWEGDCPVHGALTVVEDTKVPA---HPGDPTRADRTVPFQ-LCIAQSGISDAGC
GVWTR-VPLRKGLRFGPYEGAKL-------ETSN--SNGYCWQIHHN-SRPLYCVDAKDC
GVANWMRYVNCARHAEELNLMAFQYKGEIYYRTFQHIPAHVELLVWYGDEYGRLLGI---
DVKNF--HKPQQKQCH
>Diploptera_punctata_[POLYNEOPTERA] KAJ9577987.1 hypothetical protein L9F63_025154 
CDDCDHEWEGDCPIHGPLQIVQDTKVPQ---DPEDPTRADRTIPPQ-LCIGQSKIPHAGR
GTWTR-VALSKGIRFGPYEGAIV-------EYNN--TNGYGWQIRRN-RRPSHCVDAKHC
GFANWMRYVNCARHEEEQNLMAFQYKGQMYYRTVMDIPPHMELLVWYGDDYGRELGI---
DVDNF--HNPQNVQSE
>Macrosteles_quadrilineatus_[HEMIPTERA] XP_054282047.1 DNA ligase 1-like 
CDFCDREYEGDCPEHGPHKYYPDKDIPV----TGDRERAVETTPDM-LKIGKSKIPGAGS
GVWTI-LGLPPHVRFGPYQGD-----N--TSEPD--PLGYSWAIVKD-RKVDHYIAAHST
ATSNWMRFVNCARHESEQNLMAFQYKGKMYYRTVKLIPPKAELFVWYGKEYAEMLGISME
SFRSK--DTSHLRSEC
>Nilaparvata_lugens_[HEMIPTERA] XP_039298170.1 uncharacterized protein LOC111057492, partial 
CDVCGREWFKQCNVHGKMMTIPDIPVNR---KKAGYNYAKETTPRI-LGVAQSKIANAGK
GVWTR-DMIKNQIQFGPYQGRTG------KGNPK--DPNYAWQLKEM-AGGLNYIDASDE
RYSNWMRYVNCARNINEMNLMAYQFEGGIYYRTFRLVAPHEELFVFYGEQFGCSLGI---
DVKNF--RNPTLTNEK
>Gonioctena_quinquepunctata_[COLEOPTERA] KAG5867302.1 hypothetical protein JTB14_036690 
CDVCEEDYLDFCPKCGMLVSLEDNPVPI-----GMEDRAKKTVPKGVLEVRQSKIH--GF
GVFAL-RNLKMGIRLGPYQGETTRMDT---------QNGYAWKLRDG-----RLIDASDE
TNSNYLRYVNCARNAKEQNVVAFQYNGGLYYRTCKNVPKDEELLTYYGRSFAKNLGI---
DPKKY--FEPVQEREE
>Anoplophora_glabripennis_[COLEOPTERA] XP_018570320.1 histone-lysine N-methyltransferase PRDM9-like, partial 
CDNCGEEYLDYCSKCGVLKSLLDFPVPL-----GTEDRAKKTAPKGVLEVRPSKVH--GF
GVFAS-RHVRKGIQMGPYQGEITRVDT---------TNGYCWKLRDG-----RLIDGADE
TRSNWLRYVNCAKNVAEQNVIAFQYNGQIYYRTCRDVEKGEELLVYYGKSFAEVLGI---
NTKKY--FEPNSEEVD
>Callosobruchus_analis_[COLEOPTERA] CAI5839466.1 unnamed protein product 
CDNCEEDCVDYCKTCGKLSFLKDYPVRM-----NTADRAKKTCPKGILIVRPSNIH--GF
GVFAL-KWLPKGIQMGPYEGQAVKEET---------KSGYAWKLRNG-----KLIDAADE
RNSNYLRYVNCARNSHEQNLVAFQYDGKLFYRTCKNIGPDEELLVYYGHSFAKTLGI---
DPKKF--YEPNTSKVK
>Patiria_miniata_[ECHINODERMATA] XP_038055654.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCHELFENDCPQH-PLTIIEDSPVPK-----RCRDQAKRSLPEG-LIVKEAGIKNAGL
GVWAE-KFFPKGVRFGPYGGEIV---G--EDVGQ--DSGYAWEVFDH-DGKSYYVDGKNP
NKGNWMRYVNCACSEAEQNLIAYQYCGQIYYRSFKPIQPGQELLVFYGEEYATELGIVMT
TANDV--KNVQ-----
>Acanthaster_planci_[ECHINODERMATA] XP_022086382.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCHELYEKDCPQH-PLTIIGDSLVPK-----GCREHAKQSLPQG-LVVKEAGIENAGL
GVWAE-KSFPKGVRFGPYGGEIV---G--EDVGQ--DSGYAWEVFGH-SGKSHYVDGKNP
NKGNWMRYVNCACSEAEQNLIAYQYCGQIYYRSFKPIHPGQELLVFYGEEYATELGIVMT
TADDV--QNEK-----
>Asterias_rubens_[ECHINODERMATA] XP_033631837.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCHELYENSCPQH-PLTVIENTPVSK-----GCRDHAKRSLPDG-LIVKEAGIKNAGL
GVWAE-KAFPKGVRFGHYGGEIV---G--EEEGR--ESGYAWEIFDH-NGKSHYIDGKNP
SKGNWMRYVNCACNEAEQNLVAYQYCGQIYYRSFKTISPGQELLVFYGEEYASELGIVMT
DNDDK--HFAK-----
>Lytechinus_variegatus_[ECHINODERMATA] XP_041467334.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCHEVFEGECSKH-PLTIIKDNPIAK-----GCKDRAIKTLPDG-LMVKQSSIPGAGQ
GVFAT-KFIPKGYRFGPYEGDIV---D--LETGY--DSGYAWEICTE-SKTHHYVDSNSE
LTGNWMRYINCARNEGEQNLVAFQYLGEIYYRTFKPICPGRELLVYYGEQYAKDLGI-PS
QLNKL--SVET-----
>Strongylocentrotus_purpuratus_[ECHINODERMATA] XP_030849723.1 probable histone-lysine N-methyltransferase PRDM7 
CEDCHEVFEGECSKH-PLTIIKDNPIAK-----GSKDRARKTLPDG-LVVKQSSIPGAGQ
GIFAT-KFIPKGYRFGPYDGDIV---D--LETGY--DSGYAWEICTE-GKPHHYVDSNSE
QTGNWMRYINCARNEGEQNLVAFQYLGQIYYRTFKPICPGRELLVYYGEQYAKDLGI---
-TSQL--NKLNIETGT
>Anneissia_japonica_[ECHINODERMATA] XP_033096562.1 zinc finger protein 3-like 
CEDCCELNEGQCPLH-PLIKVKDKPTSK-----TCNDRARLSLPDG-LQIRPSKIRKAGL
GVWTK-TSFPKGVQFGPYEGEVV---F--GDEGY---SGYAWQIYKE-GKRSHFIDGQKE
NKSNWMRFVNCARNEHEQNLVAFQYHNQIYYRTFKPILAHCELLVFYGQEYAQELKI--T
DFYSG--VLLKNTKKK
>Branchiostoma_floridae_[CEPHALOCHORDATA] XP_035671859.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCNELYEGDCPVHGPLIVVKDKEVPK-----GVENRAVHTLPDY-LSVCPSKIKGAGD
GVWLDGKAMPKNFVFGPYDGKIT---G--PEIGM--TSGYAWQISKN-DKVKYYIDATDI
TKSSWMRYVNCARNEEEQNLVAFQYYRNIYYRTYKPIPPGTELMVWYGNEYAKDLGIFEE
AETKE--EEPKQQNQ-
>Branchiostoma_belcheri_[CEPHALOCHORDATA] XP_019646360.1 PREDICTED: histone-lysine N-methyltransferase PRDM9-like 
CEDCNELYEGDCPVHGPLTVVKDKVVPK-----GEPNRAVHTLPDY-LSVCPSKIKGAGD
GVWLDGQAMPKNLVFGPYDGKIT---G--PEIGL--TSGYAWQISKN-DKVKYYIDATDV
TKSSWMRYVNCARNEEEQNLVAFQYYRNIYYRTYKTIPPGTELLVWYGNEYAKELGISEK
EETEG--EEPNKQKQ-
>Styela_clava_[TUNICATA] XP_039264285.1 histone-lysine N-methyltransferase PRDM9-like 
CDECKALHLDDCPDH-PSMRMKDTLVKI-----GIKDRAKHTCPPG-LSIDPSQIRNGGL
GVWCE-IDIPQNTVFGPYEGDIVKKYDV-KNLVKVSEGGYSWQIYKK-DKLSHYIDGSNI
KTSNWLRYVNCARNEEEQNLIAFQYKGQIYYRTFKQVKRNVELFVWYGSHYASQMGIAS-
--------KPLRDKAF
>Ciona_intestinalis_[TUNICATA] XP_002130308.1 histone-lysine N-methyltransferase PRDM9-like 
CDDCDKLYLGDCEVHGPYKPAPDAVVKK-----GLIDRARKTSPDG-ISIAMSGIRAGGL
GAWCD-KGFSKNTVFGPYEGKAVHRNDV-AKLSRLFEGGYAWEIYKK-GKLSHYIDGEDT
KQSNWMRYINCACFEEQQNVIAYQYQGDIYYRLYRDVTPGTELLVWYGDQYAQSLGIPTE
YKTKC--VQPEKETEA
>Petromyzon_marinus_[Other_VERTEBRATA] XP_032800804.1 histone-lysine N-methyltransferase PRDM9-like 
CELCRDFYLGECSVHGPPEFIADTAVAP-----GVADRARLSLPQG-LTVGASSIAGAGL
GVWSNRKKLPKGVMFGPYQGEV-------SEENP--VSEYCWLIYKN-KKDREYVDAQDE
SKSNWMRFVNCARNEQEQNLVAFQHRGQIYYRTFRAVGPGSELLVWYGEEFAQELGIACE
AGPSRRRSSSSSSELA
>Rhincodon_typus_[CHONDRICHTHYES] XP_048476546.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCETFFVEECPVHGPPVFIKDTVVEF-----NRPERARLTLPEG-LNIAISKIRKAGL
GVWNEGKIIPKGVHFGPYEGVTS---N--EESAA--VSGYSWVISKG-KQDFEYIDAKDE
SKSNWMRFVNCARKEEEQNLVAFQHHGKIYYRTCKPVPPRCELLVWYGDEYAKELGI---
KWTAM--WTMKQNPK-
>Chiloscyllium_plagiosum_[CHONDRICHTHYES] XP_043539261.1 zinc finger protein 271-like 
CEDCETFFVEECPVHGPPVFIKDTVVEF-----NQPDRARLTLPEG-LSIAISKIRKAGL
GVWNEGKAIPKGVHFGPYEGITS---N--EESAA--VSGYSWVISKG-KQDVEYIDAKDE
SKSNWMRFVNCARKEEEQNLVAFQHHGKIYYRTCKRVPPRCELLVWYGDEYAKELGI---
KWTAM--WMMKQNPK-
>Carcharodon_carcharias_[CHONDRICHTHYES] XP_041032610.1 zinc finger protein 271-like 
CEDCETFFIEECPVHGLPVFIKDTVVEF-----SRSDRARLTLPEG-LSIATSKIRKAGL
GIWNEGKIIPKGVHFGPYEGVVS---N--EESAA--VSGYSWMISKG-KQDFEYIDAKDE
SKSNWMRFVNCARKEEEQNLVAFQHCGRIYYRTCKPVPPRCELLVWYGDEYAKELGI---
KWIAM--WMAKQEPK-
>Amblyraja_radiata_[CHONDRICHTHYES] XP_032891443.1 probable histone-lysine N-methyltransferase PRDM7 
CEACENFFTEECPVHGPPVFMKDTVVDS-----NHPDRARLTLPES-LSIATSKIRKAGL
GVWNEGKVIPRGVHFGPYEGEVS---N--EEEAV--VSGYSWMISKA-NNDTEYIDAQDE
SKSNWMRFVNCARNEEEQNLVAFQHRGNIYYRTCKPVPPHCELLVWYGDEYAKELGI---
TWTTM--WMSNQDPK-
>Polyodon_spathula_[CHONDROSTEI] XP_041102665.1 probable histone-lysine N-methyltransferase PRDM7 
CNICHSFFLDKCNIHGPPVFIKNPLVEI-----GVANRARLTLPQG-MKIKVSKIPNAGL
GVWNERRVIPNSIHFGPYEGELT---S--EKEAA--LSGYSWMIRKG-NSDHEYLDAKNE
ANSNWMRYVNCARNDDEQNLVAFQYKGQIFYRSCKPIPPGCELLVWYGDEYGKELGV---
GLDFM--WERSIGKNI
>Clupea_harengus_[CLUPEIDAE] XP_042566439.1 histone-lysine N-methyltransferase PRDM9-like 
CEDCESFYIDECGVHGPPNFIPDTPAPI-----GVPDRARLTLPPG-LVVSESNIPNAGL
GVFNQGQTVPRGAHFGPYEGEVM---D--RDEAI--ESGYSWVTYKS-RHVDEYIDAKRE
THSNWMRYVNCARDGEEQNLVAFQYRGGIVYRCGKTIAPGEELLVWYGEDYARDLGI---
TFDYL--WDIKSSAKG
>Oncorhynchus_mykiss_[SALMONIDAE] XP_036826454.1 histone-lysine N-methyltransferase PRDM9 
CEDCKSFFMEECGVHGPPLFVLDIPAPL-----GTSDRARLTLPSG-LEIRTSSIPEAGL
GVFNHGNTVPAGAHYGPYEGEIT---D--KEQAM--ESGYSWVINKS-RHWDDYIDAGRD
THSNWMRYVNCARREEEQNLVSFQYRGGILYRCCKPIAVGEELLVWYGEEYARDLGI---
VFDYL--WDKKSSAK-
>Salmo_trutta_[SALMONIDAE] XP_029578426.1 histone-lysine N-methyltransferase PRDM9-like isoform X1 
CEDCKSFFMEECELHGPAFFVPDIPVPL-----GAPDRARLTLPSG-LEVRTSSIPEAGL
GVFNQGNTVPAGAHYGPYEGEIT---D--KDQAM--ESGYSWVIYKS-RHWDDYIDAGRD
THSNWMRYVNCARSEEEQNLVAFQYRGGILYRCCKPIAVGEELLVWYGGEYARDLGI---
VFDYL--WDKKSCAK-
>Brienomyrus_brachyistius_[OSTEOGLOSSOCEPHALA] XP_048876133.1 histone-lysine N-methyltransferase PRDM9-like isoform X3 
CEDCQSFFTEQCEVHGPPVFISDSPAVM-----GIPGRALLTLPPG-LEVQTSSIPGAGQ
GVFSQGQTVPRGVHYGPYEGEVM---D--KEQAI--DSGYSWVVYKG-KQCETYIDARRE
THSNWMRYVNCARDEEEQNLVAFQHKGNILYRCCKLIAPGQELLVWYGEDYAKDLGM---
TFDCL--WSNKCSSE-
>Gymnothorax_javanicus_[Other_TELEOSTEI] KAJ8281444.1 hypothetical protein GJAV_G00067780 
CEECQTFFTDECEVHGPPSFVLDAPVPM-----GTPDRARLTLPPH-LEVRTSGIPGAGL
GVFNLDQTVRRGVHYGPYEGELA---E--KDVAM--DSGYSWMIYRS-ERCEEYIDAKRE
THSNWMRYVNCARNEEEQNLVAFQHRGSILYRCFKPILPGQELLVWYGEDYGKELGI---
TFDVL--WSNKCSSK-
>Megalops_cyprinoides_[Other_TELEOSTEI] XP_036372284.1 histone-lysine N-methyltransferase PRDM9-like 
CDECQSFFTDQCEVHGPPSFISDSPAPL-----GTPNRARLTLPPG-LEVRESSIPGAGL
GVFNQGPTVPRGVHYGPYEGELT---D--KDEAV--HSGYSWMIYRR-KLCDEYIDARRE
THSNWMRYVNCARNEEEQNLVAFQHRGRILYRCFRPILPGQELLVWYGEEYARDLDI---
TFDYW--WSNKCSSK-
>Osmerus_eperlanus_[Other_TELEOSTEI] XP_062316828.1 histone-lysine N-methyltransferase PRDM9-like 
CEECNSFFIEECDLHGAPLFVPDTPAAL-----GLTDRARLTLPPG-LEVRRSNIPRAGL
GVFNCGGVVAKGTHYGPYEGEVK---E--EEEAI--ESGYSWVIYKS-RHCDEYIDAKTE
THSNWMRYVNCARNVEEQNLVAFQHRGAILYRCCRPLALGEELLVWYGDEYARDLCI---
SFDYL--WDNKSSTR-
>Latimeria_chalumnae_[Other_EUTELEOSTOMI] XP_005998057.1 PREDICTED: histone-lysine N-methyltransferase PRDM9-like 
CEECQTFFVEECPVHGPPVFVNDTVVAW-----GQEGRAQLTLPEG-MSISPSQIPKAGL
GVWNEAKAILKGVHFGPYEGEIT---E--EEEAA--HSGYSWVITKG-KNYYEYIDAKDE
DKSNWMRYVNCAREEEEQNLVAFQHHGKIFYRSCRQILPGRELLVWYGDDYGKELGI---
KWNSM--WKNRQEPK-
>Geotrypetes_seraphini_[AMPHIBIA] XP_033770316.1 zinc finger protein 850-like isoform X1 
CEECQELFVEQCLIHGPPMFIKDTKIDP-----GSSNRSTLTLPLG-MSIRSSNIPQAGL
GIWNETTTLPKGVHFGPYEGITT---D--EDEAA--NSGYSWVITKG-RNYYEYIDAVNE
SYSNWMRYVNCARNEEEQNLVAFQYHGKIFYRSCKVIPPHCELLVWYGEEYGKELGI---
KWSIM--WKRELTSE-
>Microcaecilia_unicolor_[AMPHIBIA] XP_030069220.1 histone-lysine N-methyltransferase PRDM9 
CEECQELFVEECSVHGPPMFVKDTAVEP-----GSSNRSALTLPLG-MRIRPSNIPQAGL
GVWNEATTLPKGVHFGPYEGIIT---D--EDEAA--NSGYSWVITKG-RNCYEYIDAINE
SYSNWMRFVNCARNEEEQNLVAFQYHGKIYYRSCKLIFPHCELLVWYGEEYGKELGI---
KWGIM--WKRELTAE-
>Chelonia_mydas_[TESTUDINES] XP_007053470.4 LOW QUALITY PROTEIN: histone-lysine N-methyltransferase PRDM9 
CEDCLTFFIDECSVHGPPVFIRDPIVET-----GQERRAALTLPPG-MRIGLSSIPQAGL
GVWNEADTLPVGVHFGPYDGRIT---E--EEEAA--HNGYSWLITKG-RNWYVYIDGKDE
MNANWMRYVNCARDEEEQNLVAFQYRGKIYYRVCRAILPHCELLVWYGDEYGKELGI---
KWGTR--WKSTAPPK-
>Python_bivittatus_[SQUAMATA] XP_025023857.1 LOW QUALITY PROTEIN: histone-lysine N-methyltransferase PRDM9 
CEYCLTFFVEECSVHGPPLFIRDTLAEL-----GLADRATFTLPSG-FRIGLSSIPRAGF
GVWNEREILPPGIHFGPYEGTMT---E--EEEAA--NSGYSWMITRE-QNCYIYVDGKNE
TSSNWMRYVNCARNEEEQNLVAFQYHGEIYYRTCKVIQLHSELLVWYGEEYGKELGI---
KWGSK--WKSLN----
>Tachyglossus_aculeatus_[MONOTREMATA] XP_038598109.1 histone-lysine N-methyltransferase PRDM9-like 
CEECQAFFLEECAVHGAPAFLRDAAVAP-----GTAGRAAGTVPPG-LRVGPSGIPGAGL
GVWTGARALPLGLHLGPYEGRLT---H--DQEAA--DNGYSWMVTRG-RNRCEYVDGKEE
SLANWMRYVNCARNEEEQNLVAFQYRGGIYYRTCRPVPPACELLVWYGDEYGRELGIERA
APPRG--RSP------
>Antechinus_flavipes_[METATHERIA] XP_051846826.1 LOW QUALITY PROTEIN: histone-lysine N-methyltransferase PRDM9-like 
CEECQTFFLEACAVHGPPKFVQDGAMIK-----GYPYCSAITLPPG-LRIGLSGIPNAGL
GVWNEGSNLPLGLHFGPYEGKAT---E--DDEAA--NSGYSWMITKG-RNSYEYVDGKEE
SCSNWMRYVNCAREEEEQNLVAFQYQRQIFYRTCRVIRPGCELLVWYGDEYGQELGI---
KWGSK--WKRPLTGIT
>Vombatus_ursinus_[METATHERIA] XP_027711105.1 LOW QUALITY PROTEIN: histone-lysine N-methyltransferase PRDM9-like 
CEECQTFFLETCAVHGPPKFVQDSTMIK-----GHPYCSAITLPPG-LRIGLSGIPGAGL
GVWNEASNLPLGLHFGPYEGQMT---E--DDEAA--NSGYSWMITKG-RNCYEYVDGKEE
SCSNWMRYVNCARDEEEQNLVAFQYRRQIFYRTCQVIRPGCELLVWYGDEYGQELGI---
KWGNK--WKRPLTAWT
>Loxodonta_africana_[AFROTHERIA] XP_023397543.1 histone-lysine N-methyltransferase PRDM9 
CEKCQNFFIDTCAVHGAPMFVKDSPVDR-----GHPNHSALTLPPG-LRIGPSSIPKAGL
GVWNEASELPLGLHFGPYEGQVT---E--DKEAA--NSGYSWLITKG-KNCYEYVDGKDE
SWANWMRYVNCARDEEEQNLVAFQYHRQIFYRTCRTIQPDCELLVWYGDEYGQELGI---
KWGSR--WKKELTSGT
>Mirounga_leonina_[Other_CANIFORMIA] XP_034880387.1 probable histone-lysine N-methyltransferase PRDM7 
CEKCQNFFIDSCAVHGPPTFVKDSAVDK-----GQPNRSALTLPPG-LRIRPSSIPQAGL
GVWNEASDLPLGLHFGPYEGQIT---E--DEEAA--NSGYSWLITKG-RNCYEYVDGKDN
SWANWMRYVNCARDDEEQNLVAFQYHRQIFYRTCRVIRPGCELLVWYGDEYGQELGI---
KWGSK--WKSELTAGK
>Lynx_pardinus_[Other_CARNIVORA] VFV36104.1 histone-lysine n-methyltransferase 
CEKCQNFFIDSCAVHGPPTFVKDNAVGK-----GHPNRSALTLPPG-LRIRPSSIPEAGL
GVWNEASDLPLGTHFGPYEGQIT---E--DEEAA--NSGYSWLITKG-RNCYEYVDGKDN
SWANWMRYVNCARDDEEQNLVAFQYHRQIFYRTCRVIRPGCELLVWYGDEYGQELGI---
KWGSK--WKSELSTGK
>Bos_taurus_[RUMINANTIA] NP_001306826.2 histone-lysine N-methyltransferase PRDM9 
CEECQSFFIDSCAAHGPPIFVKDCAVEK-----GHANRSALTLPPG-LSIRESSIPEAGL
GVWNEVSDLPLGLHFGPYEGQIT---D--DEEAA--NSGYSWLITKR-RNCYEYVDGKDT
SLANWMRYVNCARDDEEQNLVALQYHGQIFYRTCQVVRPGCELLVWYGDEYGQDLGI---
KRESS--RKSELAGPR
>Erinaceus_europaeus_[EULIPOTYPHLA] XP_060040953.1 histone-lysine N-methyltransferase PRDM7 
CETCQNFFIDSCAVHGSPVFIKDKAVDK-----GHPDRSALTLPPG-LTIRPSGIPEAGL
GIWNEGSDLPVGVHFGPYEGQIT---D--DEEAA--NSGYSWLITKG-RNCYEYVDGENK
SWANWMRYVNCARNDEEQNLVAFQYHRQIFYRTCRVIQPGCELLVWYGDEYGQELGI---
KWGSK--WKKELTAEQ
>Rattus_norvegicus_[GLIRES] NP_001102373.2 histone-lysine N-methyltransferase PRDM9 
CEKCQNFFIDSCPNHGPPVFVKDSVVDR-----GHPNHSVLSLPPG-LRIGPSGIPEAGL
GVWNEASDLPVGLHFGPYKGQIT---E--DEEAA--NSGYSWLITKG-RNCYEYVDGQDE
SQANWMRYVNCARDDEEQNLVAFQYHRKIFYRTCRVIRPGRELLVWYGDEYGQELGI---
KWGSK--MKKGFTAGR
>Homo_sapiens_[PRIMATES] NP_001363829.1 histone-lysine N-methyltransferase PRDM9 isoform PRDM9 B 
CEMCQNFFIDSCAAHGPPTFVKDSAVDK-----GHPNRSALSLPPG-LRIGPSGIPQAGL
GVWNEASDLPLGLHFGPYEGRIT---E--DEEAA--NNGYSWLITKG-RNCYEYVDGKDK
SWANWMRYVNCARDDEEQNLVAFQYHRQIFYRTCRVIRPGCELLVWYGDEYGQELGI---
KWGSK--WKKELMAGR
